### ISSUE TITLE
有转义的账号在openwrt如何拨号？

### ISSUE THREAD

**Issue by liuminghao233** [drcoms/drcom-generic#100]
就是这种\r\n3114003以\r\n开头的账号，windows下用PPPoE-Dialer 可以拨号。

不知道这段有什么用 我路由器的ppp.sh在/lib/network下 改了也没用

#!/bin/sh
cp /lib/netifd/proto/ppp.sh /lib/netifd/proto/ppp.sh_bak
sed -i '/proto_run_command/i username=`echo -e "$username"`' /lib/netifd/proto/ppp.sh
sed -i '/proto_run_command/i password=`echo -e "$password"`' /lib/netifd/proto/ppp.sh

log显示是userid错误

Sep  9 00:20:08 RP-LINK daemon.notice pppd[7635]: Modem hangup
Sep  9 00:20:38 RP-LINK daemon.info pppd[7635]: PPP session is 7781
Sep  9 00:20:38 RP-LINK daemon.warn pppd[7635]: Connected to 60:08:10:29:39:5b via interface eth1
Sep  9 00:20:38 RP-LINK daemon.info pppd[7635]: Using interface pppoe-wan
Sep  9 00:20:38 RP-LINK daemon.notice pppd[7635]: Connect: pppoe-wan <--> eth1
Sep  9 00:20:41 RP-LINK daemon.info pppd[7635]: CHAP authentication failed: userid error1
Sep  9 00:20:41 RP-LINK daemon.err pppd[7635]: CHAP authentication failed
Sep  9 00:20:47 RP-LINK daemon.notice pppd[7635]: Connection terminated.
Sep  9 00:20:47 RP-LINK daemon.notice pppd[7635]: Modem hangup
Sep  9 00:21:17 RP-LINK daemon.info pppd[7635]: PPP session is 7765
Sep  9 00:21:17 RP-LINK daemon.warn pppd[7635]: Connected to 60:08:10:29:39:5b via interface eth1
Sep  9 00:21:17 RP-LINK daemon.info pppd[7635]: Using interface pppoe-wan
Sep  9 00:21:17 RP-LINK daemon.notice pppd[7635]: Connect: pppoe-wan <--> eth1
Sep  9 00:21:20 RP-LINK daemon.info pppd[7635]: CHAP authentication failed: userid error1
Sep  9 00:21:20 RP-LINK daemon.err pppd[7635]: CHAP authentication failed

寻求解决方法

**Comment by 23171580** [comment]
@liuminghao233 路由器型号和路由器固件链接发到该主题下。

**Comment by liuminghao233** [comment]
型号 TP-Link TL-WR741N/ND v4
固件版本	OpenWrt Attitude Adjustment r31296 / LuCI Trunk (trunk+svn8572)

@23171580

**Comment by mchome** [comment]
ppp.sh改了肯定有用的，没用应该是你改错了

**Comment by mchome** [comment]
既然PPPoE-Dialer能拨上号就是你的openwrt的问题了，请自行搜索办法解决吧

**Comment by liuminghao233** [comment]
@mchome Sep  9 00:20:51 RP-LINK daemon.info pppd[15423]: Plugin rp-pppoe.so loaded.
Sep  9 00:20:51 RP-LINK daemon.info pppd[15423]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.5
Sep  9 00:20:51 RP-LINK daemon.notice pppd[15423]: pppd 2.4.5 started by root, uid 0
Sep  9 00:20:51 RP-LINK daemon.info dnsmasq[14532]: exiting on receipt of SIGTERM
Sep  9 00:20:51 RP-LINK kern.info kernel: [ 2225.270000] eth1: link up (100Mbps/Full duplex)
Sep  9 00:20:51 RP-LINK kern.info kernel: [ 2225.270000] ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
Sep  9 00:20:52 RP-LINK user.notice ifup: Enabling Router Solicitations on lan (br-lan)
Sep  9 00:20:53 RP-LINK user.info firewall: adding lan (br-lan) to zone lan
Sep  9 00:20:55 RP-LINK daemon.info dnsmasq[15630]: started, version 2.59 cachesize 150
Sep  9 00:20:55 RP-LINK daemon.info dnsmasq[15630]: compile time options: IPv6 GNU-getopt no-DBus no-i18n DHCP TFTP no-conntrack no-IDN
Sep  9 00:20:55 RP-LINK daemon.info dnsmasq-dhcp[15630]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 12h
Sep  9 00:20:55 RP-LINK daemon.info dnsmasq[15630]: using local addresses only for domain lan
Sep  9 00:20:55 RP-LINK daemon.warn dnsmasq[15630]: failed to access /tmp/resolv.conf.auto: No such file or directory
Sep  9 00:20:55 RP-LINK daemon.info dnsmasq[15630]: read /etc/hosts - 1 addresses
Sep  9 00:20:55 RP-LINK daemon.info dnsmasq-dhcp[15630]: read /etc/ethers - 0 addresses
Sep  9 00:20:56 RP-LINK daemon.info pppd[15423]: PPP session is 15439
Sep  9 00:20:56 RP-LINK daemon.warn pppd[15423]: Connected to 60:08:10:29:39:5b via interface eth1
Sep  9 00:20:56 RP-LINK daemon.info pppd[15423]: Using interface pppoe-wan
Sep  9 00:20:56 RP-LINK daemon.notice pppd[15423]: Connect: pppoe-wan <--> eth1
Sep  9 00:20:59 RP-LINK daemon.notice pppd[15423]: peer from calling number 60:08:10:29:39:5B authorized
Sep  9 00:20:59 RP-LINK daemon.info pppd[15423]: LCP terminated by peer
Sep  9 00:21:00 RP-LINK user.info firewall: adding lan (br-lan) to zone lan
Sep  9 00:21:02 RP-LINK daemon.notice pppd[15423]: Connection terminated.
Sep  9 00:21:02 RP-LINK daemon.notice pppd[15423]: Modem hangup
Sep  9 00:21:02 RP-LINK kern.debug kernel: [ 2235.980000] eth1: no IPv6 routers present





连上了秒断是我设置问题吗 
LCP terminated by peer
