### ISSUE TITLE
5.2.0D PC测试正常，路由器认证失败

### ISSUE THREAD

**Issue by zenyangdeshihuai** [drcoms/drcom-generic#101]
河南工程学院
5.2.0D
斐讯K1
固件  PandoraBox-r2075-lite    5.5M

事故现象
latest-wired.py中IS_TEST = False这一行  

在路由器中 将赋值改为True，可以运行  但是会在跟目录生成登录日志文件drcom_client.log，随着运行时间，文件越来越大，最后路由器会卡死，能上网，但是不能对路由器进行任何设置。比如修改WIFI名等。

改为false的话 就登录不上， 无法上网

**Comment by mchome** [comment]
看清楚wiki怎么写的...
