### ISSUE TITLE
有没有T版本的

### ISSUE THREAD

**Issue by zephyrzoom** [drcoms/drcom-generic#103]

**Comment by mchome** [comment]
没有

**Comment by zephyrzoom** [comment]
能否指条路，如何分析

**Comment by ly0** [comment]
知道这个客户端干了啥么？

**Comment by zephyrzoom** [comment]
联通拨号上网的

**Comment by mchome** [comment]
抓个包上来

**Comment by zephyrzoom** [comment]
[dr.zip](https://github.com/drcoms/drcom-generic/files/492754/dr.zip)

**Comment by mchome** [comment]
那个是p版的

**Comment by zephyrzoom** [comment]
我用的就是这个
![qq 20160926191820](https://cloud.githubusercontent.com/assets/3319755/18832452/0faac320-841e-11e6-8df5-ce7a9d82d0da.jpg)

**Comment by mchome** [comment]
总之你先按照p版的配置

**Comment by zephyrzoom** [comment]
我试试

**Comment by zephyrzoom** [comment]
![screenshot from 2016-09-27 07-36-40](https://cloud.githubusercontent.com/assets/3319755/18840722/1bc5ecc4-8442-11e6-9daa-940d502d9567.png)

大哥 超时了

**Comment by zephyrzoom** [comment]
![screenshot from 2016-09-27 08-47-14](https://cloud.githubusercontent.com/assets/3319755/18843545/0a4c5320-844c-11e6-907f-a6b26723532b.png)
发的包没问题，怎么收不到呢

**Comment by ly0** [comment]
拨号了么

**Comment by zephyrzoom** [comment]
拨号用的哪个账号

**Comment by zephyrzoom** [comment]
给你说一下我正常联网的流程，先开始要通过学校的上网账号拨号过得IP，然后再用drcom账号登陆。

**Comment by zephyrzoom** [comment]
应该是两个PPP拨号

**Comment by ly0** [comment]
那就先拨第一次号，再用脚本试试

**Comment by zephyrzoom** [comment]
什么意思

**Comment by ly0** [comment]
拨号第一次后试试ping一下113.200.81.10看看通不通？

**Comment by zephyrzoom** [comment]
通的

**Comment by ly0** [comment]
然后是用脚本不通是吗

**Comment by zephyrzoom** [comment]
对的

**Comment by ly0** [comment]
脚本里有账号密码的变量 改一下

**Comment by zephyrzoom** [comment]
你是说用latest-wired.py？

**Comment by zephyrzoom** [comment]
![screenshot from 2016-10-13 01-01-33](https://cloud.githubusercontent.com/assets/3319755/19304029/a2c7cce4-909d-11e6-96f8-b95a221d6cff.png)

这是用运行`latest-wired.py`的结果

**Comment by ly0** [comment]
你们这个不是要拨号的么，大概是p版，用latest-pppoe.py试试

**Comment by zephyrzoom** [comment]
这个之前已经试过了，你看前面的聊天记录，有截图

**Comment by ly0** [comment]
回到 latest-wired.py 相关的参数用配置器生成过么

**Comment by zephyrzoom** [comment]
参数都改了

**Comment by ly0** [comment]
可能这就是命吧　２３３

**Comment by zephyrzoom** [comment]
感觉应该还是版本问题，T版本的不能套用其他几种，555

**Comment by MikeMiao** [comment]
T版的本质上是用L2TP替换了PPPoE，然而L2TP可以支持ipsec加密，所以你应该先抓包看一下L2TP的连接有没有加密

**Comment by ly0** [comment]
@MikeMiao 
![image](https://cloud.githubusercontent.com/assets/1551736/19887193/117f1b32-a062-11e6-99c9-f4e14dc4a6cf.png)

**Comment by mchome** [comment]
没看见l2tp，pptp倒是有

**Comment by MikeMiao** [comment]
pptp抓包看一下有没有mppe加密。如果没加密，也许可以像p版那样去找心跳特征。如果加密了就比较麻烦了，要想办法去做中间人攻击了。

**Comment by zephyrzoom** [comment]
![qq 20161102003413](https://cloud.githubusercontent.com/assets/3319755/19897731/35158d24-a094-11e6-9435-bf6fb045ac6c.gif)
