### ISSUE TITLE
p版

### ISSUE THREAD

**Issue by leeehan** [drcoms/drcom-generic#105]
心跳包有问题，试了#82里边的版本都不行

**Comment by ly0** [comment]
发#82脚本的日志出来看一下

**Comment by leeehan** [comment]
auth svr:172.16.1.2
pppoe_flag:24
keep_alive2_flag:d8
auth svr:172.16.1.2
pppoe_flag:24
keep_alive2_flag:d8
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000ec95c205010163f6a8a600000bf2e2a800000000d8020000
pppoe: send heartbeat request
	packet:070260000300000000000000010163f600620024ec95c20560618c5c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000000896c205010163f6a8a600000bf2e2a800000000d8020000
pppoe: send heartbeat request
	packet:070260000300000000000000010163f6006200240896c2059864f74c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000002496c205010163f6a8a600000bf2e2a800000000d8020000
pppoe: send heartbeat request
	packet:070260000300000000000000010163f6006200242496c205d0221f2c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry

**Comment by leeehan** [comment]
5.2.0P版的
![image](https://cloud.githubusercontent.com/assets/22447638/18860658/09b94506-84b2-11e6-9742-deee9a502eb4.png)
![image](https://cloud.githubusercontent.com/assets/22447638/18860665/1700484a-84b2-11e6-9ab7-bdf1489f8bb3.png)

**Comment by leeehan** [comment]
问题已解决 在网上找到可用脚本 我放到路由器试试~同时感谢大大们在github提供技术和解答
