### ISSUE TITLE
drcom版本 5.2.0d，使用路由器登陆，多台设备时掉线

### ISSUE THREAD

**Issue by bigfuji** [drcoms/drcom-generic#106]
一台设备的时候没问题，似乎可以一直联网，第二台设备连上路由器的时候就掉线了。
掉线之后终端就一直显示 send keep_alive2。
请问下是什么问题，drcom服务器端这样也能监测到是多台设备吗？
之前暑假的时候还没问题用过一个星期左右，开学了就出现了这个问题。

**Comment by bigfuji** [comment]
我路由器改成了drcom一开始登陆的那台电脑的mac。现在奇怪的是，路由器也不运行脚本，我电脑直接连这个路由器，就能上网。手机一连路由器，就掉线。

**Comment by ly0** [comment]
新版的drcom似乎有做NAT的检测

**Comment by bigfuji** [comment]
可有什么应对的办法吗？

**Comment by ly0** [comment]
这个我这里没时间分析，临时方案是NAT关掉，然后路由器上开一个代理，大家都走这个代理 应该没问题

**Comment by bigfuji** [comment]
具体操作的话，我把网线从wan口换到lan口接入，然后安装mproxy或者tinyproxy，其他设备走路由器这个代理。是这样吗？

**Comment by ly0** [comment]
我觉得你可以先试一下伪装一下TTL试试

**Comment by bigfuji** [comment]
因为用Drcom的客户端登录上网的情况ping网关得到的回复ttl是255，打了命令：
`iptables -t mangle -A OUTPUT -j TTL --ttl-set 255`
此时电脑ping网关得到的回复ttl是254，路由器ping网关得到的回复是255。
这种情况使用两台电脑（不同系统）连路由器都可以上网，但是手机一连路由器就不行了。
我猜测再多几台电脑连路由器应该都没问题，但是用手机应该就不行，应该是针对有对这方面的检测？
没打第一条命令也是这种情况，估计第一条命令没有什么用？
后来再加了如下一条命令：
`iptables -t nat -A POSTROUTING -o eth0.2 -j MASQUERADE`
情况相同，估计也没有什么效果。

**Comment by bigfuji** [comment]
其实一开始似乎就是这种情况，多台电脑连路由器都行，手机一连就全部掉线

**Comment by bigfuji** [comment]
试着用了tinyproxy在路由器做了透明代理，路由器是newifi mini。这回手机是可以连上路由器上网了，但是速度实在是太慢了，尤其是手机连上路由器上网的速度。
而且在用了一段时间（一次半个小时，一次两个小时）后也会掉线，应该是被检测出来了，因为Login会fail，要等一段时间才能登录。具体为什么被检测出来了原因不明。
准备向恶势力低头了。

**Comment by ly0** [comment]
用代理的话理论上不应该

**Comment by bigfuji** [comment]
我再试试代理的情况。
另外使用tinyproxy代理的时候，为什么我打开youtube,baidu,google载入速度很快(youtube,google在电脑端用了hosts文件，打开youku,taobao,freebuf速度就特别慢？感觉是域名解析的问题，但是pc端路由器端改dns都没有用。很奇怪。
![qq 20161013125355](https://cloud.githubusercontent.com/assets/5062731/19337097/4f4c31f2-9144-11e6-9d62-73aca2079191.png)

**Comment by bigfuji** [comment]
使用ss全局代理后上网速度正常

**Comment by ly0** [comment]
gxgx

**Comment by bigfuji** [comment]
但是我的ss是搬瓦工的，速度堪忧，还是想能够直连。
换了mproxy情况差不多，可能是因为tinyproxy有超时设置，Mproxy下进weibo,youku,freebuf一些网站直接显示'ERR_EMPTY_RESPONSE'。

**Comment by bigfuji** [comment]
好像已经超过drcom的讨论范畴了
