### ISSUE TITLE
5.2.0p版pc测试成功 放入路由后掉线频繁

### ISSUE THREAD

**Issue by leeehan** [drcoms/drcom-generic#107]
账号开头是\r\n版本的
按照wiki步骤放入路由器后
右下角那个小电脑没有显示感叹号 但就是频繁掉线自动重连
看了下系统日志 提示DNS有问题

**Comment by leeehan** [comment]
然后我就把DNS改为用客户端登陆时ipconfig/all得到的DNS仍然不行

**Comment by leeehan** [comment]
可能是python安装到路由器没成功？

**Comment by szlytlyt** [comment]
或许就是你们学校分配的dns有问题，openwrt默认的dhcp分配的dns是转发到学校dhcp分配的dns

**Comment by leeehan** [comment]
好像就是python和路由器固件的问题，又找了几个固件终于适配到能用的，现在过去30分钟了正常联网
