### ISSUE TITLE
看了一个晚上，还是不怎么能理解，dr5.2.1（p）版。

### ISSUE THREAD

**Issue by ouyangyueying** [drcoms/drcom-generic#109]
dr5.2.1（p）的登入IP每次都不一样的，正常吗？5.2.0版也是这样的吗？那个window的拨号器有什么用？

**Comment by leeehan** [comment]
正常
5.2.0p也是这样 pppoe拨号好像都是这样吧。
你说的是哪个拨号器 ？PPPoE-Dialer这个？这个只针对账号开头是\r\n版本的，别的可以直接用系统
自带拨号器

**Comment by mchome** [comment]
...固定的ip叫静态ip，认证服务器的ip是不变的。连wiki都懒得看的，请不要用这个项目了。
