### ISSUE TITLE
关于测试latest-pppoe.py 文件出现socket.timeout: timed out

### ISSUE THREAD

**Issue by coderyaogh** [drcoms/drcom-generic#110]
![image](https://cloud.githubusercontent.com/assets/19632533/18901363/d9233836-857c-11e6-9751-5666f7fb6264.png)对于这种疯狂超时

**Comment by leeehan** [comment]
测试这个文件的时候电脑联网了没？我刚开始电脑联网测试也出现了这种情况
还有可能是本身文件代码的问题吧如果是5.2.1p可以参考#82

**Comment by ly0** [comment]
同学你插网线了吗？

**Comment by homerious** [comment]
我测试这个文件也出现了这个超时的问题，我拨号是成功的，拨号之后ping认证服务器地址也成功，请问大神是什么原因呢？我用的文件是 #82 里面的那个

**Comment by ly0** [comment]
@homerious 参考一下这个 https://github.com/drcoms/drcom-generic/commit/4306fc16c968b8e9fb7347c9372d5b457476278a

**Comment by homerious** [comment]
@ly0 注释了该句子之后还是超时哦。。。需要我提供一下什么信息嘛？。。

**Comment by homerious** [comment]
C:\Users\Homer\Desktop\Programming\IDEA project\PythonTest>python latest-pppoe.py
[*]  auth svr:10.0.3.2
pppoe_flag:6a
keep_alive2_flag:dc
[*]  open local port:61432
[*]  DEBUG MODE:True
[*]  pppoe: send challenge request
        packet:0701080001000000
Traceback (most recent call last):
  File "latest-pppoe.py", line 455, in <module>
    main()
  File "latest-pppoe.py", line 450, in main
    pppoe.send(s)
  File "latest-pppoe.py", line 306, in send
    data, address = s.recv()
  File "latest-pppoe.py", line 194, in recv
    data, address = self.s.recvfrom(1024)

**Comment by homerious** [comment]
@ly0 我的好像又可以了，貌似不用注释那一行代码，我开始由于没有用管理员权限执行会出现10013错误，所以我自己改了端口号，后来才发现61440是drcom的端口，所以改回来了，然后用管理员权限运行，能够正常收到心跳了，给你添麻烦了，不好意思
