### ISSUE TITLE
电脑上测试正常，路由器里登不上

### ISSUE THREAD

**Issue by zhjc1124** [drcoms/drcom-generic#111]
之前一直好好地，一天晚上重启后出错，
路由器用putty来ping学校官网正常，说明网线没断
但是仍然提示'[challenge] timeout, retrying...'
换路由器换账号都仍然如此

**Comment by mchome** [comment]
![qq 20160928153807](https://cloud.githubusercontent.com/assets/7392658/18904615/9c57eb6c-8591-11e6-84fa-2812be4a0426.jpg)

**Comment by ly0** [comment]
![image](https://cloud.githubusercontent.com/assets/1551736/18905163/75944d2e-8594-11e6-84b7-8358a7f3ef3c.png)

**Comment by zhjc1124** [comment]
...
![image](https://cloud.githubusercontent.com/assets/21313564/18908424/1c0b023a-85a2-11e6-903a-58a46773d9d0.png)

**Comment by tdxddt** [comment]
python-light  logging codecs openssl 可能是codecs
