### ISSUE TITLE
5.2.1(p)Windows拨号不成功

### ISSUE THREAD

**Issue by chenhongji12** [drcoms/drcom-generic#113]
广东工业大学最近有h3c改用drcom了，经多次尝试均无法使用python客户端拨号上网。其中发现他不绑定mac，但是wireshark抓取到的帧提取后放入latest-pppoe.py运行不成功，而pppoe-dialer.exe软件拨号显示拨号出现异常。附上截图、抓包和Windows、linux客户端。
[config.txt](https://github.com/drcoms/drcom-generic/files/499180/config.txt)

![qq 20160928200733](https://cloud.githubusercontent.com/assets/22506371/18930835/39cd3572-85fc-11e6-9daa-5e6778b61e52.png)
![qq 20160928201637](https://cloud.githubusercontent.com/assets/22506371/18930834/39c69550-85fc-11e6-9cae-609d8aa03c7d.png)

**Comment by ly0** [comment]
在拨号成功以前不是本项目的讨论范围

**Comment by chenhongji12** [comment]
用他配来的客户端是可以拨号成功和正常上网的。
