### ISSUE TITLE
电脑上能拨号成功，但路由器128错误…

### ISSUE THREAD

**Issue by lweo** [drcoms/drcom-generic#114]
Sep 29 05:48:27 PandoraBox user.info sysinit: Traceback (most recent call last):
Sep 29 05:48:27 PandoraBox user.info sysinit:   File "/usr/bin/drcom", line 385, in <module>
Sep 29 05:48:27 PandoraBox user.info sysinit:     main()
Sep 29 05:48:27 PandoraBox user.info sysinit:   File "/usr/bin/drcom", line 376, in main
Sep 29 05:48:27 PandoraBox user.info sysinit:     package_tail = login(username, password, server)
Sep 29 05:48:27 PandoraBox user.info sysinit:   File "/usr/bin/drcom", line 303, in login
Sep 29 05:48:27 PandoraBox user.info sysinit:     salt = challenge(svr,time.time()+random.randint(0xF,0xFF))
Sep 29 05:48:27 PandoraBox user.info sysinit:   File "/usr/bin/drcom", line 89, in challenge
Sep 29 05:48:27 PandoraBox user.info sysinit:     s.sendto("\x01\x02"+t+"\x09"+"\x00"*15, (svr, 61440))
Sep 29 05:48:27 PandoraBox user.info sysinit: socket.error: [Errno 128] Network is unreachable
Sep 29 05:48:28 PandoraBox user.info sysinit: setting up led wifi
Sep 29 05:48:28 PandoraBox user.info sysinit: setting up led USB

**Comment by lweo** [comment]
路由器是禁止dhcp服务器还是要开启？正常使用校园网能禁用路由器的dhcp

**Comment by mchome** [comment]
你确认执行/usr/bin/drcom之前，ip已经获取到了吗

**Comment by lweo** [comment]
获取到了，跳出网关登陆页面了。。

**Comment by mchome** [comment]
获取到ip后，手动执行一遍

**Comment by mchome** [comment]
如果手动执行没有没有错误的话，可以确定是自启的问题了。

**Comment by lweo** [comment]
你意思是在ssh上执行脚本？

**Comment by lweo** [comment]
确认下：路由器DHCP开吗？

**Comment by mchome** [comment]
怎么不开，不开你手动配置静态ip麽...

**Comment by lweo** [comment]
嗯，开了dhcp，而且校园网的网线要插在wan口，手动运行路由器上的脚本能上网成功。貌似不自动拨号。

**Comment by lweo** [comment]
在exit 0前是这么添加吗？&和exit没空格？

`sleep 10 && python /usr/bin/drcom&exit 0`
