### ISSUE TITLE
如果掉了不能自动重连，已添加hotplug但还是得重启路由器才能连上

### ISSUE THREAD

**Issue by lweo** [drcoms/drcom-generic#115]
怎么破？

**Comment by mchome** [comment]
可以说下掉线出现什么错误吗？

**Comment by lweo** [comment]
没错误提示，
系统日志显示
send……
rev……
数据不一样，但类似，和拨号成功后的日志明显不一样。。

**Comment by ly0** [comment]
发一下脚本的日志

**Comment by lweo** [comment]
`Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.140000] 	ch6 bssid:00:1f:64:e5:83:e4
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.140000] 	ch6 bssid:28:6e:d4:24:b0:f2
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.150000] 	ch6 bssid:28:6e:d4:24:b0:f3
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.150000] 	ch6 bssid:28:6e:d4:25:44:82
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.160000] 	ch6 bssid:28:6e:d4:25:60:32
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.160000] 	ch6 bssid:28:6e:d4:25:60:33
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.160000] 	ch6 bssid:28:6e:d4:25:60:34
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.170000] 	ch6 bssid:28:6e:d4:24:b0:f4
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.170000] 	ch6 bssid:28:6e:d4:25:44:83
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.180000] 	ch6 bssid:28:6e:d4:25:44:84
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.180000] 	ch9 bssid:d4:ee:07:3d:3f:ac
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.180000] 	ch11 bssid:00:25:9e:ec:9c:12
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.190000] 	ch11 bssid:00:1f:64:e5:80:32
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.190000] 	ch11 bssid:8c:f2:28:d9:e7:66
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.200000] 	ch11 bssid:5a:d2:24:25:01:23
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.200000] 	ch11 bssid:4a:ee:65:aa:ad:67
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.200000] 	ch11 bssid:00:25:9e:ec:9c:11
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.210000] 	ch11 bssid:00:1f:64:e3:7a:ec
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.210000] 	ch11 bssid:24:69:68:90:2d:58
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.220000] 	ch11 bssid:00:1f:64:e3:80:32
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.220000] 	ch11 bssid:00:1f:64:e4:7a:ec
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.220000] 	ch11 bssid:00:1f:64:e4:80:32
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.230000] 	ch11 bssid:00:1f:64:e5:7a:ec
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.230000] 	ch11 bssid:3c:46:d8:7b:73:c9
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.240000] 	ch11 bssid:56:db:30:ee:53:cb
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.240000] 	ch11 bssid:00:1f:64:e5:e7:58
Oct  7 00:33:55 PandoraBox kern.alert kernel: [   30.250000] Channel status:
Oct  7 00:33:55 PandoraBox kern.info kernel: [   31.830000] device ra0 entered promiscuous mode
Oct  7 00:33:55 PandoraBox kern.info kernel: [   31.840000] br-lan: port 3(ra0) entered forwarding state
Oct  7 00:33:55 PandoraBox kern.info kernel: [   31.840000] br-lan: port 3(ra0) entered forwarding state
Oct  7 00:33:56 PandoraBox authpriv.info dropbear[1518]: Running in background
Oct  7 00:33:57 PandoraBox kern.info kernel: [   33.840000] br-lan: port 3(ra0) entered forwarding state
Oct  7 00:33:57 PandoraBox user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Oct  7 00:33:57 PandoraBox user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Oct  7 00:34:01 PandoraBox daemon.info dnsmasq[1564]: started, version 2.66 cachesize 150
Oct  7 00:34:01 PandoraBox daemon.info dnsmasq[1564]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP no-conntrack no-ipset no-auth
Oct  7 00:34:01 PandoraBox daemon.info dnsmasq-dhcp[1564]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 12h
Oct  7 00:34:01 PandoraBox daemon.info dnsmasq[1564]: using local addresses only for domain lan
Oct  7 00:34:01 PandoraBox daemon.info dnsmasq[1564]: reading /tmp/resolv.conf.auto
Oct  7 00:34:01 PandoraBox daemon.info dnsmasq[1564]: using nameserver *.*.*.* #53
Oct  7 00:34:01 PandoraBox daemon.info dnsmasq[1564]: using nameserver  *.*.*.*#53
Oct  7 00:34:01 PandoraBox daemon.info dnsmasq[1564]: using local addresses only for domain lan
Oct  7 00:34:01 PandoraBox daemon.info dnsmasq[1564]: read /etc/hosts - 1 addresses
Oct  7 00:34:01 PandoraBox daemon.info dnsmasq-dhcp[1564]: read /etc/ethers - 0 addresses
Oct  7 00:34:15 PandoraBox user.info sysinit: auth svr: *.*.*.*
Oct  7 00:34:15 PandoraBox user.info sysinit: username:*****
Oct  7 00:34:15 PandoraBox user.info sysinit: password:*****
Oct  7 00:34:15 PandoraBox user.info sysinit: mac:*****
Oct  7 00:34:15 PandoraBox user.info sysinit: 0.0.0.0
Oct  7 00:34:15 PandoraBox user.info sysinit: [challenge] recv 020242d56bdd20000a000100f303e8f000000000ac1048fbf000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
Oct  7 00:34:15 PandoraBox user.info sysinit: [DEBUG] challenge:
Oct  7 00:34:15 PandoraBox user.info sysinit: 020242d56bdd20000a000100f303e8f000000000ac1048fbf000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
Oct  7 00:34:15 PandoraBox user.info sysinit: [challenge] challenge packet sent.
Oct  7 00:34:15 PandoraBox user.info sysinit: [mkpkt] 030100215ac9849a6efc588f788f36f2eb78e396323031333330323032303332320000000000000000000000000000000000000000000000200458c5e4e15e0bf82abcc0563cd5dc2969fe8e6197e84501000000000000000000000000000000001c0df694b7d7f85f01000000
Oct  7 00:34:15 PandoraBox user.info sysinit: [login] send 030100215ac9849a6efc588f788f36f2eb78e396323031333330323032303332320000000000000000000000000000000000000000000000200458c5e4e15e0bf82abcc0563cd5dc2969fe8e6197e84501000000000000000000000000000000001c0df694b7d7f85f010
Oct  7 00:34:15 PandoraBox user.info sysinit: Traceback (most recent call last):
Oct  7 00:34:15 PandoraBox user.info sysinit: setting up led wifi
Oct  7 00:34:15 PandoraBox user.info sysinit: setting up led USB
Oct  7 00:48:40 PandoraBox daemon.notice netifd: wan (706): Sending renew...
Oct  7 00:48:40 PandoraBox daemon.notice netifd: wan (706): Lease of  *.*.*.*obtained, lease time 1800
Oct  7 01:03:40 PandoraBox daemon.notice netifd: wan (706): Sending renew...
Oct  7 01:03:40 PandoraBox daemon.notice netifd: wan (706): Lease of  *.*.*.* obtained, lease time 1800
Oct  7 01:18:40 PandoraBox daemon.notice netifd: wan (706): Sending renew...`

**Comment by ly0** [comment]
`drcom_client.log`  有么

**Comment by lweo** [comment]
这个在什么位置？

**Comment by ly0** [comment]
脚本IS_DEBUG设置为True，在工作目录位置会有生成

**Comment by lweo** [comment]
找不到IS_DEBUG，是IS_TEST吧？

**Comment by ly0** [comment]
啊 是的

**Comment by lweo** [comment]
[drcom_client.txt](https://github.com/drcoms/drcom-generic/files/518683/drcom_client.txt)

**Comment by ly0** [comment]
这不挺正常吗

**Comment by lweo** [comment]
看最后面

**Comment by ly0** [comment]
```
[keep_alive2] send 69 074528000b03dc022f120000000000000007e6090000000000000000000000000000000000000000
[keep_alive2] recv 074528000b04dc022f120000000000000007e6090000000000000000000000000000000000000000
[keep_alive1] send ff34fc7932ca80f2797263ce9b3b0049bb0000004472636fdea89032c1dcac1048fb012b3f3100000000
[keep_alive2] send 70 074628000b01dc022f120000000000000007e6090000000000000000000000000000000000000000
[keep_alive2] send 70 074628000b01dc022f120000000000000007e6090000000000000000000000000000000000000000
[keep_alive2] send 70 074628000b01dc022f120000000000000007e6090000000000000000000000000000000000000000
```

这个之间你有做过什么网络操作吗？看上去很像发送失败重新发送的样子
