### ISSUE TITLE
拨号成功之后打开drcom还是无法上网

### ISSUE THREAD

**Issue by sansroman** [drcoms/drcom-generic#120]
这是抓包文件

[dr.zip](https://github.com/drcoms/drcom-generic/files/517420/dr.zip)

**Comment by mchome** [comment]
如果你不能登录，请发Issue的时候附上用哪个脚本文件，脚本的日志输出，正常客户端的抓包，并且附上你的学校的名称，最好可以提供相关的Windows和Linux下的客户端，提高沟通效率。
