### ISSUE TITLE
5.2.1p认证失败

### ISSUE THREAD

**Issue by driver1998** [drcoms/drcom-generic#121]
pppoe能登录，心跳包认证失败
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:0701100002010000954d88020a1e0bcba8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000000a1e0bcb0062006a954d8802bcce7fa90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[*]  pppoe: heartbeat response failed, retry

登录抓包
[drp.zip](https://github.com/drcoms/drcom-generic/files/517454/drp.zip)

**Comment by mchome** [comment]
尝试一下 #116 的

**Comment by driver1998** [comment]
问题解决 非常感谢
