### ISSUE TITLE
5.2.1 (P)    

### ISSUE THREAD

**Issue by dingge** [drcoms/drcom-generic#122]
成功登陆的抓包文件如下！

[drp.zip](https://github.com/drcoms/drcom-generic/files/518153/drp.zip)

win7 下测试连接超时，无数据返回！
如图！
![qq 20161009151210](https://cloud.githubusercontent.com/assets/8029027/19218677/d5c90db4-8e32-11e6-8177-db84e51fd9e2.png)

**Comment by dingge** [comment]
已解决，，登陆账号加上\r\n  。开启latest_pppoe接受心跳包。 可稳定维持！ 感谢！

**Comment by Van1996** [comment]
你好，请问在哪里的“登陆账号加上\r\n”

**Comment by dingge** [comment]
找个拨号器。支持pppoe的都可以。不过win7自带的好像不像。
看这个！
 https://github.com/drcoms/drcom-generic/wiki/%E5%85%B3%E4%BA%8EP%E7%89%88%E7%9A%84PPPoE%E6%8B%A8%E5%8F%B7%E9%97%AE%E9%A2%98
这个拨号器我测试的可以。
