### ISSUE TITLE
PC上拨号测试成功，放入路由却不行···

### ISSUE THREAD

**Issue by gdutjason** [drcoms/drcom-generic#123]
![default](https://cloud.githubusercontent.com/assets/18497116/19228178/368cfbb6-8ef5-11e6-919c-86ecdddcc145.png)
![default](https://cloud.githubusercontent.com/assets/18497116/19228179/36933a26-8ef5-11e6-8236-4699c0147ce3.png)

能看出来是哪一步错了吗，网线插在wan口

**Comment by ly0** [comment]
没拨号成功 网络没通

**Comment by gdutjason** [comment]
@ly0 能看出来是哪一步的问题吗？pc拨号成功的，改了is_test=False  然后放进去路由器，跟着教程弄到最后是不成功的， 然后就进去路由器试了下，这个结果

**Comment by ly0** [comment]
拨号的问题啊，没拨号成功。

**Comment by mavcissac** [comment]
lz也是广工校友吗
我也遇到这种问题了，pc可拨，极路由1s刷pandora死活拨不上，运行drcom万年error 128

**Comment by lossme** [comment]
vi /etc/config/network
看看wan设置是否正确，username是不是\r\n学号，不是的话自己修改，密码也检查一下有没有问题
然后把wan macaddr地址修改成电脑mac（所谓的合法地址，mac不“合法”拨号拨不通）
保存退出
重启，然后再运行python /usr/bin/drcom看看

**Comment by B1anker** [comment]
楼主我pc端播不了号啊，你是直接按照教程说的就可以了吗？

**Comment by dgeibi** [comment]
https://github.com/drcoms/drcom-generic/wiki/关于P版的PPPoE拨号问题

**Comment by qq709631261** [comment]
刷潘多拉的极路由就是拨不了号 刷回官方固件 已解决
