### ISSUE TITLE
5.2.1(P) 心跳失败

### ISSUE THREAD

**Issue by sahrechiiz** [drcoms/drcom-generic#124]
https://yunpan.cn/cvLLNWshu2krd （提取码：a93e）
含log、脚本和抓包

**Comment by eczn** [comment]
看了#82了么 
广工？

**Comment by kyjo2014** [comment]
是的，广工

**Comment by dgeibi** [comment]
试一下 #116 的

**Comment by eczn** [comment]
@dgeibi 你成功了么

**Comment by dgeibi** [comment]
@eczn 可以了

**Comment by mavcissac** [comment]
@dgeibi 你好，同广工，在openwrt 接口-wan-设置了\r\n账号 密码并保存应用，但是之后在python执行drcom时总是报socket.error 128 network is unreachable，请问怎么办
是需要对 /lib/netifd/proto/ppp.sh 打补丁吗？给出的那三行命令怎么执行？直接粘贴到putty然后回车？

**Comment by dgeibi** [comment]
@mavcissac 是的，必须先连上再执行drcom

**Comment by mavcissac** [comment]
@dgeibi 在PC上用dialer可以拨号成功，在pandorabox上却死活连不上。。。现在有点怀疑人生

**Comment by ly0** [comment]
为什么不怀疑一下pandorabox呢 233

**Comment by kyjo2014** [comment]
为什么用dialer 在PC上能够拨号成功，但是大概1-2min后就会自动断线？

**Comment by mavcissac** [comment]
@kyjo2014 latest-pppoe.py有没有在python下运行？

**Comment by eczn** [comment]
@kyjo2014 看#82

**Comment by mavcissac** [comment]
@ly0 _(:з」∠)_hc5661a我就找到两版pandorabox，刷进去各试了几次还是没有拨号成功。。。你们成功的用的什么路由或者固件

**Comment by eczn** [comment]
@mavcissac  我刷的是别的dalao特别制作的针对广工的固件  
http://eczn.website/Vally

**Comment by WinAu** [comment]
@ly0 昨天作死又刷了一遍，结果真作死了，拨号拨不上，还是原来的pandorabox固件，脚本无论是#82的还是最新代码仓库的都是提示socket.timeout: timed out，原来我是用的#82，9天没断。然而pc顺风顺水。。。

**Comment by kyjo2014** [comment]
可以了，非常感谢！

**Comment by ly0** [comment]
@WinAu 让你瞎折腾 23333

**Comment by exview** [comment]
有没有能够让台式电脑开wifi的

**Comment by exview** [comment]
求大神指教

**Comment by ly0** [comment]
@exview 不属于本repo讨论范围，请自行google

**Comment by exview** [comment]
这个讨论的是什么？

**Comment by ly0** [comment]
DrCOM登陆协议相关

**Comment by exview** [comment]
有什么用？
