### ISSUE TITLE
能在PC上拨号，在路由器上不行128错误

### ISSUE THREAD

**Issue by qq709631261** [drcoms/drcom-generic#125]
![image](https://cloud.githubusercontent.com/assets/20498524/19358808/efa28da8-91a9-11e6-9e05-0a04127e28f5.png)

IP也获取不到，就是在路由器上用PPPOE完全拨不上号。。咋办

**Comment by ly0** [comment]
请先确认路由器上是否拨号成功

**Comment by qq709631261** [comment]
一直发送 接受数据都是0 折磨整天了 wan还是连不上

**Comment by qq709631261** [comment]
也已经按openwrt的方法拨号了

**Comment by ly0** [comment]
你先确认一下是否拨号成功，就这个情况来看应该是没拨号成果的结果。

**Comment by LZH0713** [comment]
@ly0 想问下，我用 #116 的latest-pppoe.py，在pc拨号后执行latest-pppoe.py总是提示socket.timeout: timed out，多次执行后才能keep_alive2连接上；在openwrt上也是这个问题，是我哪里操作错了么

**Comment by ly0** [comment]
@LZH0713 发一下drcom_client.log

**Comment by qq709631261** [comment]
@ly0 我已经按照wiki里openwrt的拨号方法了 PC上是能拨号的但 主要是路由器恶心

**Comment by qq709631261** [comment]
@ly0 极路由1S刷了潘多拉的就会连号都拨不上 只要刷回官方固件再ROOT就一切畅通无阻
