### ISSUE TITLE
P版拨号问题

### ISSUE THREAD

**Issue by jkgeekJack** [drcoms/drcom-generic#127]
Ubuntu下如何拨号

**Comment by ly0** [comment]
你说的是pppoe拨号还是？

**Comment by mchome** [comment]
RTFM & STFW

**Comment by MonsterOOF** [comment]
gdut? 刚刚弄好在ubuntu上的dr.com问题。ubuntu上拨号用自带的pppoe拨号程序即可啊，拨号方法见[ADSL（PPPOE）接入指南](http://wiki.ubuntu.org.cn/ADSL%EF%BC%88PPPOE%EF%BC%89%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)

重点是用户名前面加上回车换行符(\r\n)

还有, @mchome 为何拨号成功之后无须执行latest-pppoe.py脚本也是可以上网的呢？(Ubuntu 16.04 LTS)，这样windows 下的Dr.com客户端岂不是多此一举？不过不运行python脚本网络会不太稳定，偶尔掉线，十几秒钟又好了。

然而并没有刷进路由器，只是学校提供的Linux客户端只能运行在centos上，所以想着既然有方法能刷在openwrt上为何不能直接在ubuntu上用呢...

**Comment by mchome** [comment]
@MonsterOOF 
> 为何拨号成功之后无须执行latest-pppoe.py脚本也是可以上网的呢？(Ubuntu 16.04 LTS)，这样windows 下的Dr.com客户端岂不是多此一举？不过不运行python脚本网络会不太稳定，偶尔掉线，十几秒钟又好了。

那是维持心跳用的，如果你没有持续发送心跳，认证服务器就会认为你客户端没开启，而中断连接。

> 然而并没有刷进路由器，只是学校提供的Linux客户端只能运行在centos上，所以想着既然有方法能刷在openwrt上为何不能直接在ubuntu上用呢...

你可以随意在哪个终端拨号，并没有别人限制你。
