### ISSUE TITLE
广工P，用仓库的latest-pppoe.py失败，帮忙看看，谢谢

### ISSUE THREAD

**Issue by LZH0713** [drcoms/drcom-generic#128]
![ieh1uw400 5 6 jg ns30ad](https://cloud.githubusercontent.com/assets/20476715/19386759/a93468ec-9248-11e6-8ab7-220b4c0e7477.png)

**Comment by mchome** [comment]
原版客户端和latest-pppoe.py各抓一个

**Comment by LZH0713** [comment]
latest-pppoe.py的没连接上，抓包http://pan.baidu.com/s/1slnKq7b

**Comment by LZH0713** [comment]
试过执行多次，可能跑起keep_alive2

**Comment by w282200695** [comment]
issue #82 已解决的问题。

**Comment by LZH0713** [comment]
#82的也不行，9月份的时候是可以的，现在不行了
![tyaw c 96 zptk rb1n](https://cloud.githubusercontent.com/assets/20476715/19390918/e45e3c9a-925c-11e6-955b-96f483c82a5d.png)

**Comment by mchome** [comment]
latest-pppoe.py.pcapng 这个包好像连 heartbeat 也没有获取到???

**Comment by LZH0713** [comment]
应该是获取了，日志和第一张图一样的

**Comment by w282200695** [comment]
同为广工，目前issue #82 的依旧可行。当时我解决你日志中的出现的问题方法（代码基于issue #82 ）：

1. 把main中的`s = Socket(server)` 移动到循环外，可避免每趟循环都重新初始化一个s

2. 把181行的注释去掉。使得构建出来的socket可复用。
`self.s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)`

**Comment by LZH0713** [comment]
@w282200695 按照你说的尝试，过1分来钟我的还是会断
![image](https://cloud.githubusercontent.com/assets/20476715/19406272/93a5acc6-92b5-11e6-91d0-d79f5568ddfc.png)

**Comment by ly0** [comment]
你这个发的包不大对

第二个包应该是 0702080001000000

**Comment by LZH0713** [comment]
这是#82按照上楼改了执行的日志

**Comment by LZH0713** [comment]
1.我将pppoe = PPPOEHeartbeat(1)放出循环，解决了同样包问题；
2.在challenge中加了捕获，让它在尝试；
这样心跳是可以维持，可是好像写死了，拨号断了的话，它还会跑，不知会不会影响使用
![image](https://cloud.githubusercontent.com/assets/20476715/19408257/8ee6806c-92eb-11e6-9c09-9f4ddb905335.png)
![image](https://cloud.githubusercontent.com/assets/20476715/19408285/02651242-92ec-11e6-9472-bffc95fb48f6.png)

**Comment by ypingcn** [comment]
issue 116的可以使用。 @LZH0713 
https://github.com/drcoms/drcom-generic/issues/116#issuecomment-250953770

**Comment by LZH0713** [comment]
嗯，好的，之前应该是我校园网的设备故障，网络不通畅问题，维修后应该#116的正常不过我没重试，我现在用楼上稍微改过的#82，正常使用，谢谢各位啦

**Comment by MonsterOOF** [comment]
@w282200695 同为广工， 为何我连拨号都不成功(win自带拨号程序，wiki上的PPPoE-Dialer运行不了)，一直691错误，根据wiki上p版拨号问题也不知该怎么解决
