### ISSUE TITLE
广工p版心跳一直timeout ，显示socket.timeout: timed out

### ISSUE THREAD

**Issue by kman-c** [drcoms/drcom-generic#132]
[*]  auth svr: 172.30.1.80
[*]  pppoe_flag: 2a
[*]  keep_alive2_flag: dc
[*]  open local port:61440
[*]  DEBUG MODE:True
[*]  pppoe: send challenge request
        packet:0701080001000000
Traceback (most recent call last):
  File "drcom", line 451, in <module>
    main()
  File "drcom", line 446, in main
    pppoe.send(s)
  File "drcom", line 298, in send
    data, address = s.recv()
  File "drcom", line 227, in recv
    data, address = self.s.recvfrom(1024)
socket.timeout: timed out

**Comment by mchome** [comment]
拨号了吗，拨通了吗

**Comment by unconsciousness** [comment]
[Dr.Com.zip](https://github.com/drcoms/drcom-generic/files/534036/Dr.Com.zip)我是小白，贴上广工10月8号刚更新的5.2.1P客户端(产品版本:5.2.1.201610081.A.W.100733)

**Comment by kman-c** [comment]
已拨通的，但是每次只能坚持一分钟就断网

**Comment by dgeibi** [comment]
没改服务器信息啊

广工的应该是
```
server = '10.0.3.2'
PPPoE_flag = '\x6a'
keep_alive2_flag = '\xdc'
```
