### ISSUE TITLE
p版配置生成器使用后报错

### ISSUE THREAD

**Issue by Lostpart** [drcoms/drcom-generic#135]
使用完脚本后，出现以下报错
D:\dr>C:\Python27\python.exe drcom_p_config.py > config.txt
Traceback (most recent call last):
  File "drcom_p_config.py", line 24, in <module>
    keep_alive2_flag = re.search('\x07.\x5c\x28\x00\x0b\x03(.)\x02', text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

使用3.5.2后显示如下
D:\dr>"C:\Program Files (x86)\Python35-32\python.exe" drcom_p_config.py > config.txt
  File "drcom_p_config.py", line 22
    print 'server = \'%s\'' % '.'.join([str(ord(i)) for i in text[offset-12:offset-8]])
                          ^
SyntaxError: invalid syntax

**Comment by mchome** [comment]
重新抓包试一下

**Comment by Lostpart** [comment]
配置文件已正确生成，然后运行latest-pppoe.py时出现以下报错【我有种全世界都不报错就我报错的感觉

D:\dr>C:\Python27\python.exe latest-pppoe.py
[*]  auth svr: 10.0.3.2
Traceback (most recent call last):
  File "latest-pppoe.py", line 336, in <module>
    main()
  File "latest-pppoe.py", line 326, in main
    log('pppoe_flag: ' + pppoe_flag.encode('hex'))
NameError: global name 'pppoe_flag' is not defined

然后前面忘记报学校了，广东工业大学，P版

**Comment by mchome** [comment]
按步骤重做一遍

**Comment by Lostpart** [comment]
好的，我再尝试几次
