### ISSUE TITLE
请问一下在PC上已经能正常上网了

### ISSUE THREAD

**Issue by Kosonlee** [drcoms/drcom-generic#137]
1.请问一下在PC上已经能正常上网了P版,但是我路由的eth0口已经使用电信拨号了 想把脚本改成使用eth1进行拨号,如何操作,
2.如何把拨号的账号密码加入到脚步当中,学校采取的是DHCP的方式.

**Comment by Kosonlee** [comment]
如果您看到了.希望回复一下我~爱你哦

**Comment by ly0** [comment]
是妹子么？

**Comment by mchome** [comment]
1.在`nic_name = ''`指定接口
2.[黑人问号.jpg]
