### ISSUE TITLE
LuCI上Dr.COM提示客户端未运行

### ISSUE THREAD

**Issue by Git2Frank** [drcoms/drcom-generic#138]
P版，要改的文件都改过了，启动项里也设置为启动了，PPPoE拨号成功，Dr.COM提示客户端未运行，请问该怎么办？newifi-mini，刷的就是https://github.com/drcoms/drcom-generic/tree/master/openwrt 里的。电脑上运行latest-pppoe.py可以联网。

**Comment by mchome** [comment]
不推荐用
