### ISSUE TITLE
执行./pppoe.sh提示endto: Network is unreachable

### ISSUE THREAD

**Issue by mountainliuliu** [drcoms/drcom-generic#140]
求教，路由器刷的是pandorabox.如何宽带拨号

**Comment by binshao1** [comment]
我来补充下这个问题，我的路由器是极路由hc5661a，刷pandarobox，按照教程的流程走，拨号后查看系统日志，总会提示，ping sendto network is unreachable。ping failed ，retry。谷歌之，网上教程说是没有设置网关，设置之后，再拨，还是不行，网络知识有限，只能暂时放放。可能潘多拉固件拨号的机制不大一样，不知道会不会是多拨的影响，潘多拉有两个wan口，一个wan，另一个wan6

**Comment by mchome** [comment]
拨号失败。。。

**Comment by ly0** [comment]
原因就是没有拨号成功。建议使用**原生openwrt**进行拨号，不然很难跟踪问题。

**Comment by dgeibi** [comment]
基于 http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=193113&highlight=5661a 提供的固件制作了装有 python 和 luci，自带drcom pppoe 脚本的固件，拨号用户名问题也解决了。
固件：  https://pan.baidu.com/s/1hs9H0va


也可自己给 OpenWrt （trunk）编译系统添加 hc5661a 支持，https://github.com/dgeibi/HC5661A.dts 自己编译

**Comment by mountainliuliu** [comment]
感谢大家的帮忙。后来我试着用回了极路由的固件~（就是一开始极路由自带的系统）。最后的情况是可以上网，但是会掉线然后重连。回宿舍在试试【dgeibi】的方法。

**Comment by binshao1** [comment]
谢谢degibi，用了dgeibi的固件，但是设置拨号pppoe协议后，输入用户名密码，之后还是连接不上，不知为何？

**Comment by dgeibi** [comment]
用户名前可能要加 \r\n

binshao1 <notifications@github.com>于2016年11月1日周二 17:26写道：

**Comment by binshao1** [comment]
现在可以了，路由器吃了屎啊，恢复下出厂设置就行了，MAC地址居然是0.0.0.0，也是醉了，总之谢谢了

**Comment by mountainliuliu** [comment]
用了新方法。最后是能开wifi，但是还是会掉线，然后立刻重连。dalao们有不掉线的方法吗？

**Comment by mountainliuliu** [comment]
还有就是，我帮两个宿舍的路由器开wifi，居然两个同时开的时候，wifi不可用。当一个断线的时候另外一个就可以连接了。。。。

**Comment by dgeibi** [comment]
没有新方法，/use/bin/drcom 是 Python 脚本

修改 WiFi 配置
/etc/config/network
```
config wifi-iface
        option device   radio0
        option network  lan
        option mode     ap
        option ssid     'wifissid'
        option wmm '0'
        option encryption 'psk2'
        option key 'wifipassword'
```

运行 /etc/init.d/network reload

**Comment by mountainliuliu** [comment]
路由器是不是需要断电在通电？

**Comment by mountainliuliu** [comment]
重启了路由并没有发现有新的ssid，还是原来的。不知道是不是reload没有成功。

**Comment by dgeibi** [comment]
@mountainliuliu 新ssid 被隐藏了（如果有 hidden 那一行，删掉），改一下信道试试 请仔细阅读 https://wiki.openwrt.org/doc/uci/wireless

**Comment by ly0** [comment]
是否成功解决？
