### ISSUE TITLE
之前都可正常登陆，今天突然无法登陆（吉大5.2.1d）

### ISSUE THREAD

**Issue by Claymorejy** [drcoms/drcom-generic#143]
之前用的是latest_521d.py，刚才又试了latest-wired.py，均无法登陆。求大神帮忙~

[challenge] recv 020279684224890001000100f203e8f000000000318c95c9f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020279684224890001000100f203e8f000000000318c95c9f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100194b0229332ccb870d29bde30797a5c5196c6a793136000000000000000000000000000000000000000000000000000000000000002004172423b4273213cd6a748581583532bf2a620d876de101318c95c9000000000000000000000000ae38fdef12ecd1730100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a0a00000000000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006800020cf0aafeb400005c260a870bf90000e913
[login] send 030100194b0229332ccb870d29bde30797a5c5196c6a793136000000000000000000000000000000000000000000000000000000000000002004172423b4273213cd6a748581583532bf2a620d876de101318c95c9000000000000000000000000ae38fdef12ecd1730100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a0a00000000000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006800020cf0aafeb400005c260a870bf90000e913
[login] recv 0500000515000000000000000000000000000000bfcdbba7b6cbd0e8d2aac9fdbcb6003139322e3136382e302e3833000000
[login] packet sent.
[login] login failed.

**Comment by ly0** [comment]
试试 `newclient.py` ?

**Comment by Claymorejy** [comment]
newclient.py 好用！新脚本之前可以用，为啥会回档呢……好奇怪。多谢大神~

**Comment by yaalsn** [comment]
OMG，线上故障了呀。

**Comment by mchome** [comment]
![zdto _bum wl ck q 8je s](https://cloud.githubusercontent.com/assets/7392658/19992921/c3d64ea6-a27c-11e6-844a-b6b2e5261ad6.jpg)

**Comment by ly0** [comment]
![image](https://cloud.githubusercontent.com/assets/1551736/19994280/6c8803aa-a287-11e6-8d0f-e3ca44cdc460.png)

**Comment by zaidao2023** [comment]
前来学习学习

**Comment by yaalsn** [comment]
@Claymorejy 你现在用newclient.py好使？

**Comment by zaidao2023** [comment]
@yaalsn 修改newclient.py双击后一闪而过是怎么回事？新手求教

**Comment by yaalsn** [comment]
python newclient.py

**Comment by Claymorejy** [comment]
@yaalsn 好用。一闪而过：必须把吉大客户端彻底关掉，右下角不能有小地球logo。IS_TEST 需要改成True；测试成功后改回False再放进路由器里

**Comment by zaidao2023** [comment]
谢谢赐教！！！

**Comment by zaidao2023** [comment]
试过了还是不好使，刚开始没添加信息时打开不一闪而过 添加后就一闪而过

**Comment by Claymorejy** [comment]
@yaalsn 在进程里把drcom、main、update那几个都关掉？不行重启下试试咯

**Comment by zhjc1124** [comment]
老哥，你的路由器还好使么，我不知道为什么路由器设置静态地址后连内网都ping不通了

**Comment by yaalsn** [comment]
mac地址改了吗？

**Comment by yaalsn** [comment]
@zhjc1124 你路由器坏了，5元收砖

**Comment by zhjc1124** [comment]
@yaalsn  改了也不好使。。。然而我都快折腾一个多月了，两个路由器都不好使我真是奇了怪了，下周末继续，这周先赶作业
