### ISSUE TITLE
5.2.1(p)心跳失败!

### ISSUE THREAD

**Issue by zxw7606** [drcoms/drcom-generic#146]
试过了#82的脚本 依旧失败.  仓库里的也试过了.也不行 
这是我客户端的抓爆 和三个版本试过的 日志
链接：http://pan.baidu.com/s/1nvRPeUd 密码：w28b
希望大大能帮忙看看.

另外非常感谢你们的成果,给我们这么大的便利

**Comment by zxw7606** [comment]
在电脑上运行py脚本，heartbeat response failed，retry
pppoe:reset idx to 0x01
想先拨号再运行脚本，
电脑上运行 pppoe拨号问题 中的客户端 ，拨号提示异常

**Comment by zxw7606** [comment]
运行#116后的代码出错
![baidushurufa_2016-11-5_12-28-40](https://cloud.githubusercontent.com/assets/3738414/20027623/82a5fdbe-a353-11e6-9771-5a336567f9d4.jpg)
![baidushurufa_2016-11-5_12-28-58](https://cloud.githubusercontent.com/assets/3738414/20027624/83260de2-a353-11e6-9d21-5b18a4cb11f1.jpg)
小白一个 求解救.

**Comment by ly0** [comment]
`latest-pppoe.py` 直接用这个试试

**Comment by zxw7606** [comment]
@ly0 找到问题了,原来是 新增了转义字符串 ,而且必须要先拨号才保持心跳. 谢谢了,

**Comment by zxw7606** [comment]
Sun Nov  6 20:35:01 2016 user.warn mwan3: Could not find gateway for interface wan (eth1)
Sun Nov  6 20:35:01 2016 user.notice firewall: Reloading firewall due to ifup of wan (eth1)
Sun Nov  6 20:35:05 2016 user.emerg syslog: /usr/bin/pppoe.sh: line 16: 1: not found
Sun Nov  6 20:35:06 2016 user.emerg syslog: [*]  auth svr:172.30.255.9
Sun Nov  6 20:35:06 2016 user.emerg syslog: pppoe_flag:26
Sun Nov  6 20:35:06 2016 user.emerg syslog: keep_alive2_flag:dc
Sun Nov  6 20:35:06 2016 user.emerg syslog: [*]  open local port:61440
Sun Nov  6 20:35:06 2016 user.emerg syslog: [*]  DEBUG MODE:False
Sun Nov  6 20:35:06 2016 user.emerg syslog: [*]  pppoe: send challenge request
Sun Nov  6 20:35:06 2016 user.emerg syslog: Traceback (most recent call last):
Sun Nov  6 20:35:06 2016 user.emerg syslog:   File "/usr/bin/drcom", line 288, in <module>
Sun Nov  6 20:35:06 2016 user.emerg syslog:     main()
Sun Nov  6 20:35:06 2016 user.emerg syslog:   File "/usr/bin/drcom", line 284, in main
Sun Nov  6 20:35:06 2016 user.emerg syslog:     pppoe.send(s)
Sun Nov  6 20:35:06 2016 user.emerg syslog:   File "/usr/bin/drcom", line 141, in send
Sun Nov  6 20:35:06 2016 user.emerg syslog:     s.send(data)
Sun Nov  6 20:35:06 2016 user.emerg syslog:   File "/usr/bin/drcom", line 73, in send
Sun Nov  6 20:35:06 2016 user.emerg syslog:     self.s.sendto(data, (self.server, self.port))
Sun Nov  6 20:35:06 2016 user.emerg syslog: socket.error: [Errno 128] Network is unreachable
Sun Nov  6 20:35:06 2016 user.emerg syslog: Shadowsocks is disabled.
Sun Nov  6 20:35:06 2016 user.emerg syslog: setting up led WAN LED (green)
Sun Nov  6 20:35:06 2016 user.emerg syslog: - init complete -
Sun Nov  6 20:35:15 2016 daemon.warn pppd[3418]: Timeout waiting for PADS packets
Sun Nov  6 20:35:15 2016 daemon.err pppd[3418]: Unable to complete PPPoE Discovery
Sun Nov  6 20:35:15 2016 daemon.info pppd[3418]: Exit.
Sun Nov  6 20:35:15 2016 daemon.notice netifd: Interface 'vwan1' is now down
Sun Nov  6 20:35:15 2016 daemon.notice netifd: Interface 'vwan1' is disabled
Sun Nov  6 20:35:15 2016 daemon.notice netifd: Interface 'vwan1' is enabled
Sun Nov  6 20:35:15 2016 daemon.notice netifd: Interface 'vwan1' is setting up now
Sun Nov  6 20:35:15 2016 daemon.notice netifd: Network device 'macvlan1' link is down
Sun Nov  6 20:35:15 2016 daemon.notice netifd: Interface 'vwan1' has link connectivity loss
Sun Nov  6 20:35:15 2016 daemon.notice netifd: Network device 'macvlan1' link is up
Sun Nov  6 20:35:15 2016 daemon.notice netifd: Interface 'vwan1' has link connectivity 
Sun Nov  6 20:35:15 2016 daemon.info pppd[3704]: Plugin rp-pppoe.so loaded.
Sun Nov  6 20:35:15 2016 daemon.info pppd[3704]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Sun Nov  6 20:35:15 2016 daemon.notice pppd[3704]: pppd 2.4.7 started by root, uid 0
Sun Nov  6 20:35:30 2016 daemon.warn pppd[3704]: Timeout waiting for PADS packets
Sun Nov  6 20:35:30 2016 daemon.err pppd[3704]: Unable to complete PPPoE Discovery
Sun Nov  6 20:35:30 2016 daemon.info pppd[3704]: Exit.
Sun Nov  6 20:35:30 2016 daemon.notice netifd: Interface 'vwan1' is now down
Sun Nov  6 20:35:30 2016 daemon.notice netifd: Interface 'vwan1' is disabled
Sun Nov  6 20:35:30 2016 daemon.notice netifd: Interface 'vwan1' is enabled
Sun Nov  6 20:35:30 2016 daemon.notice netifd: Interface 'vwan1' is setting up now
Sun Nov  6 20:35:30 2016 daemon.notice netifd: Network device 'macvlan1' link is down
Sun Nov  6 20:35:30 2016 daemon.notice netifd: Interface 'vwan1' has link connectivity loss
Sun Nov  6 20:35:30 2016 daemon.notice netifd: Network device 'macvlan1' link is up
Sun Nov  6 20:35:30 2016 daemon.notice netifd: Interface 'vwan1' has link connectivity 
Sun Nov  6 20:35:30 2016 daemon.info pppd[3739]: Plugin rp-pppoe.so loaded.
Sun Nov  6 20:35:30 2016 daemon.info pppd[3739]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Sun Nov  6 20:35:30 2016 daemon.notice pppd[3739]: pppd 2.4.7 started by root, uid 0
Sun Nov  6 20:35:40 201



我这个路由器莫名断网，这个是日志，请问一下这个问题如何解决？ @ly0 非常感谢

**Comment by zxw7606** [comment]
这个错误日志
Sun Nov  6 20:46:19 2016 daemon.notice netifd: Interface 'vwan1' is now up
Sun Nov  6 20:46:20 2016 user.notice mwan3: ifup interface vwan1 (pppoe-vwan1)
Sun Nov  6 20:46:20 2016 user.notice firewall: Reloading firewall due to ifup of vwan1 (pppoe-vwan1)
Sun Nov  6 20:46:21 2016 daemon.notice miniupnpd[3993]: shutting down MiniUPnPd
Sun Nov  6 20:46:22 2016 daemon.info dnsmasq[3967]: reading /tmp/resolv.conf.auto
Sun Nov  6 20:46:22 2016 daemon.info dnsmasq[3967]: using local addresses only for domain lan
Sun Nov  6 20:46:22 2016 daemon.info dnsmasq[3967]: using nameserver 202.96.104.27#53
Sun Nov  6 20:46:22 2016 daemon.info dnsmasq[3967]: using nameserver 202.96.104.17#53
Sun Nov  6 20:46:22 2016 daemon.err miniupnpd[5044]: could not open lease file: /var/upnp.leases
Sun Nov  6 20:46:22 2016 daemon.notice miniupnpd[5044]: HTTP listening on port 5000
Sun Nov  6 20:46:22 2016 daemon.notice miniupnpd[5044]: HTTP IPv6 address given to control points : [fdba:a6a7:5842::1]
Sun Nov  6 20:46:22 2016 daemon.notice miniupnpd[5044]: Listening for NAT-PMP/PCP traffic on port 5351
Sun Nov  6 20:46:29 2016 authpriv.info dropbear[4298]: Exit (root): Exited normally
Sun Nov  6 20:46:29 2016 authpriv.warn dropbear[4298]: Couldn't set SO_PRIORITY (Bad file descriptor)
Sun Nov  6 20:56:19 2016 daemon.info pppd[3739]: LCP terminated by peer
Sun Nov  6 20:56:19 2016 daemon.info pppd[3739]: Connect time 10.0 minutes.
Sun Nov  6 20:56:19 2016 daemon.info pppd[3739]: Sent 2701476 bytes, received 218038276 bytes.
Sun Nov  6 20:56:19 2016 daemon.err miniupnpd[5044]: Failed to get IP for interface pppoe-vwan1
Sun Nov  6 20:56:19 2016 daemon.warn miniupnpd[5044]: SendNATPMPPublicAddressChangeNotification: cannot get public IP address, stopping
Sun Nov  6 20:56:19 2016 daemon.notice netifd: Network device 'pppoe-vwan1' link is down
Sun Nov  6 20:56:19 2016 daemon.notice netifd: Interface 'vwan1' has lost the connection
Sun Nov  6 20:56:19 2016 user.notice mwan3: ifdown interface vwan1 (unknown)
Sun Nov  6 20:56:22 2016 daemon.notice pppd[3739]: Connection terminated.
Sun Nov  6 20:56:22 2016 daemon.notice pppd[3739]: Modem hangup
Sun Nov  6 20:56:34 2016 user.notice mwan3track: Interface vwan1 (pppoe-vwan1) is offline
Sun Nov  6 20:56:34 2016 user.notice mwan3: ifdown interface vwan1 (pppoe-vwan1)
Sun Nov  6 20:56:35 2016 daemon.warn dnsmasq[3967]: no servers found in /tmp/resolv.conf.auto, will retry

**Comment by zxw7606** [comment]
Sun Nov  6 21:06:55 2016 daemon.info pppd[3739]: LCP terminated by peer
Sun Nov  6 21:06:55 2016 daemon.info pppd[3739]: Connect time 10.0 minutes.
Sun Nov  6 21:06:55 2016 daemon.info pppd[3739]: Sent 2511241 bytes, received 178516556 bytes.
Sun Nov  6 21:06:55 2016 daemon.err miniupnpd[6123]: Failed to get IP for interface pppoe-vwan1
Sun Nov  6 21:06:55 2016 daemon.warn miniupnpd[6123]: SendNATPMPPublicAddressChangeNotification: cannot get public IP address, stopping
Sun Nov  6 21:06:55 2016 daemon.notice netifd: Network device 'pppoe-vwan1' link is down
Sun Nov  6 21:06:55 2016 daemon.notice netifd: Interface 'vwan1' has lost the connection
Sun Nov  6 21:06:56 2016 user.notice mwan3: ifdown interface vwan1 (unknown)
Sun Nov  6 21:06:58 2016 daemon.notice pppd[3739]: Connection terminated.
Sun Nov  6 21:06:58 2016 daemon.notice pppd[3739]: Modem hangup
Sun Nov  6 21:07:01 2016 daemon.warn dnsmasq[3967]: no servers found in /tmp/resolv.conf.auto, will retry
Sun Nov  6 21:07:06 2016 user.notice mwan3track: Interface vwan1 (pppoe-vwan1) is offline
Sun Nov  6 21:07:06 2016 user.notice mwan3: ifdown interface vwan1 (pppoe-vwan1)
Sun Nov  6 21:07:28 2016 daemon.info pppd[3739]: PPP session is 19985
Sun Nov  6 21:07:28 2016 daemon.warn pppd[3739]: Connected to e4:35:c8:7b:2b:41 via interface macvlan1
Sun Nov  6 21:07:28 2016 daemon.info pppd[3739]: Using interface pppoe-vwan1
Sun Nov  6 21:07:28 2016 daemon.notice pppd[3739]: Connect: pppoe-vwan1 <--> macvlan1
Sun Nov  6 21:07:31 2016 daemon.info pppd[3739]: syncppp not active
Sun Nov  6 21:07:32 2016 daemon.info pppd[3739]: Remote message: Welcome to Drcom System:167714476
Sun Nov  6 21:07:32 2016 daemon.notice pppd[3739]: PAP authentication succeeded
Sun Nov  6 21:07:32 2016 daemon.notice pppd[3739]: peer from calling number E4:35:C8:7B:2B:41 authorized
Sun Nov  6 21:07:32 2016 daemon.notice pppd[3739]: local  IP address 172.30.169.104
Sun Nov  6 21:07:32 2016 daemon.notice pppd[3739]: remote IP address 172.30.160.1
Sun Nov  6 21:07:32 2016 daemon.notice pppd[3739]: primary   DNS address 202.96.104.27
Sun Nov  6 21:07:32 2016 daemon.notice pppd[3739]: secondary DNS address 202.96.104.17
Sun Nov  6 21:07:32 2016 daemon.notice netifd: Network device 'pppoe-vwan1' link is up
Sun Nov  6 21:07:32 2016 daemon.notice netifd: Interface 'vwan1' is now up
Sun Nov  6 21:07:32 2016 user.notice mwan3: ifup interface vwan1 (pppoe-vwan1)

**Comment by ly0** [comment]
Sun Nov 6 20:56:22 2016 daemon.notice pppd[3739]: Connection terminated.
Sun Nov 6 20:56:22 2016 daemon.notice pppd[3739]: Modem hangup

可能是你的pppd有问题 也有可能是MTU没设对 我猜

**Comment by zxw7606** [comment]
很神奇啊，每次一发问题就自己找到问题了，已解决😂

**Comment by zxw7606** [comment]
很神奇啊，每次一发问题就自己找到问题了，已解决😂

**Comment by zxw7606** [comment]
嗯，是那个miniudhp出问题了。谢谢啦。

**Comment by zxw7606** [comment]
非常感谢！

**Comment by exview** [comment]
@zxw7606 你是怎么解决断网问题的？

**Comment by zxw7606** [comment]
@exview 路由器固件带了一个miniDHCP自启项服务，关掉就行了。 我看了你那个py，用仓库里最新的吧。

**Comment by exview** [comment]
用仓库的py是要替换掉那一个文件？ @zxw7606

**Comment by exview** [comment]
那个miniDHCP自启项服务在哪关掉
