### ISSUE TITLE
脚本能运行却莫名其妙地断开

### ISSUE THREAD

**Issue by z5n0w** [drcoms/drcom-generic#150]
log等下补上
gdut-drcom

**Comment by z5n0w** [comment]
[*]  auth svr: 10.0.3.2
[*]  pppoe_flag: 6b
[*]  keep_alive2_flag: dc
[*]  open local port:61440
[*]  DEBUG MODE:True
[*]  [keep-alive2] send1
	packet:070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[*]  [keep-alive2] recv file, resending..
[*]  [keep-alive2] send1
	packet:070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[*]  [keep-alive2] recv1
	packet:070128000b02dc022f12000000000000435d04000000000000000000000000000000000000000000
[*]  [keep-alive2] send2
	packet:070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[*]  [keep-alive2] recv2
	packet:070128000b02dc022f12000000000000435d04000000000000000000000000000000000000000000
[*]  [keep-alive2] send3
	packet:070228000b03dc022f12000000000000435d040026a3f4cc0722e6fc000000000000000000000000
[*]  [keep-alive2] recv3
	packet:070228000b04dc022f12000000000000435d04000000000000000000000000000000000000000000
[*]  [keep-alive2] keep-alive2 loop was in daemon.
[*]  [keep_alive2] send 3
	packet:070328000b01dc022f12000000000000435d04000000000000000000000000000000000000000000
[*]  [keep_alive2] recv
	packet:070328000b02dc022f12000000000000445d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 4
	packet:070428000b03dc022f12000000000000445d0400c72f31017e000000000000000000000000000000
[*]  [keep_alive2] recv
	packet:070428000b04dc022f12000000000000445d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 5
	packet:070528000b01dc022f12000000000000445d04000000000000000000000000000000000000000000
[*]  [keep_alive2] recv
	packet:070528000b02dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 6
	packet:070628000b03dc022f12000000000000a85d0400c72f31017e000000000000000000000000000000
[*]  [keep_alive2] recv
	packet:070628000b04dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
	packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
[*]  [keep_alive2] send 7
其实这时候连接已经断开了

**Comment by ly0** [comment]
2333 这明显在某个循环里出不来了 
```
[*] [keep_alive2] send 7
packet:070728000b01dc022f12000000000000a85d04000000000000000000000000000000000000000000
```

**Comment by lyhyl** [comment]
补充：
用drcom-generic/latest-pppoe.py
在
`[keep_alive2] send 255
	packet:07ff28000b03dc022f12000000000000ceef1f000249d36b08da5912000000000000000000000000
[keep_alive2] recv
	packet:07ff28000b0400002f12000000000000ceef1f000000000000000000000000000000000000000000`
之后就断了

[drcom_client.log.txt](https://github.com/drcoms/drcom-generic/files/595123/drcom_client.log.txt)

**Comment by z5n0w** [comment]
问题解决了：
修改上次能用的脚本
注释掉 main里面的
keepalive 那行
取消注释
send.pppoe(s)
加上
time.sleep(20)

**Comment by ly0** [comment]
![image](https://cloud.githubusercontent.com/assets/1551736/20376701/fdeb1b7a-acc3-11e6-9a75-26e4364ec656.png)

**Comment by codecosine** [comment]
GDUT龙洞，我遇到了同样进入循环的问题
@z5n0w 按你方法会报之前心跳包更新后， 心跳返回错误，reset idex to 0x01的错误。但是没有掉线，大概持续了30多分钟，就直接跳出了。
`[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
[*]  pppoe: received challenge response
Traceback (most recent call last):
  File "./drcom", line 336, in <module>
    main()
  File "./drcom", line 331, in main
    pppoe.send(s)
  File "./drcom", line 196, in send
    data = self._make_heartbeat(sip=sip, challenge_seed=seed, first=True)
  File "./drcom", line 164, in _make_heartbeat
    crc, foo = gen_crc(challenge_seed, encrypt_mode)
  File "./drcom", line 74, in gen_crc
    foo = hashlib.new('md4', data).digest()
  File "/usr/lib/python2.7/hashlib.py", line 110, in __py_new
    return __get_builtin_constructor(name)(string)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md4
`
这个错误就是前几天上面closed的心跳包错误的问题。请问你现在是怎么解决的，如果你可以用，可以贴出完整的脚本嘛，谢谢。

**Comment by lyhyl** [comment]
@codecosine [latest-pppoe.py](https://github.com/drcoms/drcom-generic/blob/master/latest-pppoe.py)
server 10.0.3.6
pppoe_flag 0x6b
keep_alive2_flag 0xdc

**Comment by codecosine** [comment]
@lyhyl 稳定15分钟了。厉害。真是神奇。我记得我昨晚用PC拨号截的包，pppoe_flag是x6a的。而且根本没有alive的flag。。最近校园网到底更新了什么东西。。

**Comment by lyhyl** [comment]
@codecosine 
啊我好像打错了= =pppoe_flag是6a吧……为什么你还能坚持15分钟……
![image](https://cloud.githubusercontent.com/assets/3370369/20473868/681a2d5a-affe-11e6-97aa-0509f649089b.png)
反正这个配置我都好多天没关机了

**Comment by codecosine** [comment]
@lyhyl 这到底是什么玄学。。我早上用这个 (latest-pppoe.py)[https://github.com/drcoms/drcom-generic/blob/master/latest-pppoe.py] 和那个你现在发的那个正常的龙洞配置，会出现https://github.com/drcoms/drcom-generic/issues/148 这个的问题，大概是5-10分钟一次。然后按这个issue改，又会出现这层楼主的现象。
不懂这个代码的我，已经开始怀疑这个和时间段有关系了。。。
现在用什么神奇打错的x6b，已经27分钟了。。。

**Comment by lyhyl** [comment]
@codecosine 尴尬,,ԾㅂԾ,,

**Comment by eczn** [comment]
难怪今天一阵一阵的顿卡的...  
然后去改了flag 改成 玄学x6b就稳定了... 

校园网老是这样搞，不知道windows客户端用户会怎么个卡法.....  😂😂😂😂

**Comment by z5n0w** [comment]
`ValueError: unsupported hash type md4`
这种错误的话
让pppoe.py重启就可以了，这样至少保证不会因为pppoe.py结束导致断开
```
while (1)
do
    pppoe.py
done
``` @codecosine

**Comment by ly0** [comment]
unsupported hash type md4
2333 我原本以为不会出现md4这种形式的，居然出现了

**Comment by mchome** [comment]
@z5n0w 如果出现hashlib不支持md4的情况，那就用回 #82 那个带md4 py实现的
