### ISSUE TITLE
有没有mac版本的？

### ISSUE THREAD

**Issue by B1anker** [drcoms/drcom-generic#151]
用你们的脚本在mac试过，没啥反应诶，虽然我自己的客户端可以用。。

**Comment by mchome** [comment]
格了装win 
![4y4 sti fgsr5s1cp 4q9dc](https://cloud.githubusercontent.com/assets/7392658/20352205/6ef5cf2c-ac51-11e6-93e1-b862ad246f00.jpg)

**Comment by B1anker** [comment]
摔，不是说gayhub的人都很乐于帮助吗？

**Comment by ly0** [comment]
![image](https://cloud.githubusercontent.com/assets/1551736/20374567/6ac09d70-acb4-11e6-9b42-7085e6a2b432.png)

**Comment by mchome** [comment]
道理我都懂，步骤、过程和错误呢

**Comment by chooop** [comment]
用你们的脚本在mac试过，没啥反应诶，虽然我自己的客户端可以用。。
哪个脚本 802.1x还是ppppoe 
什么报错
自己的客户端
兔鲁咔咔泥瓦

**Comment by mountainliuliu** [comment]
@B1anker 同学系统是什么版本~同是mac，会掉线。

**Comment by ly0** [comment]
请重新开一个issue，在标题中说明问题，提供相应的错误等等，本issue关闭。
