### ISSUE TITLE
校园网多线路问题

### ISSUE THREAD

**Issue by leeehan** [drcoms/drcom-generic#152]
学校的网有两个线路，一个是2m，一个是8m的
8m的是联通的 抓包看到账号后边比2m的多了个后缀@Unicom，对比了下生成的别的数据等一样
但用这个联通线路抓的包配置好路由器后 网速仍是2m的 重新试了几次都是这样 用客户端时候是8m的
想问下这是哪里的问题，谢谢
![xj9c 8isp qdmtq1 qba j](https://cloud.githubusercontent.com/assets/22447638/20349525/ce81fa4e-ac45-11e6-833d-79a78407abf6.png)

**Comment by ly0** [comment]
应该是有扩展的认证，可以先把包发上来。

**Comment by leeehan** [comment]
好的，两个线路的包上传到百度云了
http://pan.baidu.com/s/1dFOIpNz

**Comment by mchome** [comment]
可以发下脚本分别登陆的包吗

**Comment by leeehan** [comment]
@mchome 登陆用的脚本就是wiki里边那个，两个线路抓的包楼上那个链接里边就是啊

**Comment by mchome** [comment]
不是说客户端的包

**Comment by leeehan** [comment]
好吧...不好意思...没明白你的意思，要的是运行latest-wired.py这个脚本时生成的日志文件？

**Comment by mchome** [comment]
是数据包

**Comment by leeehan** [comment]
@mchome 
还是不知道是什么数据包...麻烦能说清楚点嘛...

**Comment by noe132** [comment]
我们学校也是双线路的。抓包发现也只是用户名多了个@unicom 的区别。

**Comment by leeehan** [comment]
@mchome 是用latest-wired.py这个脚本运行登陆时抓的包吗？

**Comment by noe132** [comment]
@leeehan 用5.2.1(D)客户端登陆抓包，发现用户名后增加了@unicom。用5.2.0(D)版本，在用户名后添加@unicom即可登陆，应该类似，用latest-wired.py，也只需要在用户名后添加@unicom字段即可

**Comment by leeehan** [comment]
@noe132 
不行...看一楼的叙述

**Comment by noe132** [comment]
@leeehan 那就不清楚你们学校具体是什么情况了~我们这是账号后添加@unicom就可以使用。。。

**Comment by HIROSH1** [comment]
咱是同一个学校的  你找着方法了吗
