### ISSUE TITLE
用着用着就没网速了，但拨号还连着

### ISSUE THREAD

**Issue by exview** [drcoms/drcom-generic#154]
![image](https://cloud.githubusercontent.com/assets/22767544/20460620/3fe9d0c8-af23-11e6-81a1-89fcab304897.png)

**Comment by exview** [comment]
执行pppoe.sh就提示这样，求解

**Comment by mchome** [comment]
你电脑客户端开了?

**Comment by exview** [comment]
是路由器的

**Comment by ly0** [comment]
检查是否已经开了客户端脚本 然后又开了一个

**Comment by exview** [comment]
怎么检查？
