### ISSUE TITLE
请问latest-wired.py在windows下使用登录成功不能上网

### ISSUE THREAD

**Issue by assassins110** [drcoms/drcom-generic#157]
我打开后显示
[login] loged in
[login] login sent
是不是就说明我已经登录上去了，但是不能联网。
auth svr: 172.16.1.2
username: *********
password: ********
mac: 0x696a6b6c6d6eL
bind ip: 0.0.0.0
[challenge] recv 0202a6188f00000000000100f203e8f000000000010116fdf000a8a600000bf2e2a800000000d802000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202a6188f00000000000100f203e8f000000000010116fdf000a8a600000bf2e2a800000000d802000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001e1b9e20a0004d371a6b0f49bac3512472313430333330323135320000000000000000000000000000000000000000000000000000000072f44bcc6d231377e6b04265b13e2ab5b93120ded55c0100000000000000000000000000000000dd2653ddb810e4ff0000000000667579756d69000000000000000000000000000000000000000000000000000088641100004c004e000000000000000000000000940000000500000001000000280a00000200000057696e646f777320313000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000437a0008193dc0ccc1a37819020cb0eb0bc80000696a6b6c6d6e0000e913
[login] send 0301001e1b9e20a0004d371a6b0f49bac3512472313430333330323135320000000000000000000000000000000000000000000000000000000072f44bcc6d231377e6b04265b13e2ab5b93120ded55c0100000000000000000000000000000000dd2653ddb810e4ff0000000000667579756d69000000000000000000000000000000000000000000000000000088641100004c004e000000000000000000000000940000000500000001000000280a00000200000057696e646f777320313000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000437a0008193dc0ccc1a37819020cb0eb0bc80000696a6b6c6d6e0000e913
[login] recv 0400000500fc32000000000000ffffffffff00000000004472636fac100102e805010116fd0178b00500030110
[login] packet sent.
[login] loged in
[login] login sent
package_tail 4472636fac100102e805010116fd0178
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff1b9e20a0004d371a6b0f49bac35124720000004472636fac100102e805010116fd017817d300000000
[keep-alive1] recv 07011000060017d3539d4a00010116fda8a600000bf2e2a800000000d8020000030000000000000000000000fc32000000000000ffffffffffffffffffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070010010b06d8022f12000000000000a8a600000bf2e2a800000000d80200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a2400000000000000be4ff959fa2e970afa2e970afa2e970aa30d840af82e970a81329b0afe2e970a7926ca0af02e970a7932990af82e970a95319c0afb2e970a95319d0aff2e970a9531930af82e970afa2e960a492e970acc08930af92e970acc089c0af22e970a3d28910afb2e970a050e930af92e970a
[keep-alive2] recv file, resending..
[keep-alive2] send2 070128000b01d8022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2 070128000b02d8022f12000000000000539d4a000000000000000000000000000000000000000000
[keep-alive2] send3 070228000b03d8022f12000000000000539d4a000000000000000000000000000000000000000000
[keep-alive2] recv3 070228000b04d8022f12000000000000539d4a000000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive1] send ff1b9e20a0004d371a6b0f49bac35124720000004472636fac100102e805010116fd017817e700000000
[keep-alive1] recv 07011000060017e70d9e4a00010116fda8a600000bf2e2a800000000d8020000170000000000000000000000fc32000000000000ffffffffffffffffffffffff
[keep_alive2] send 3 070328000b01d8022f12000000000000539d4a000000000000000000000000000000000000000000
[keep_alive2] recv 070328000b02d8022f120000000000000d9e4a000000000000000000000000000000000000000000
[keep_alive2] send 4 070428000b03d8022f120000000000000d9e4a000000000000000000000000000000000000000000
[keep_alive2] recv 070428000b04d8022f120000000000000d9e4a000000000000000000000000000000000000000000

**Comment by assassins110** [comment]
抓包文件链接：http://pan.baidu.com/s/1mimBbxm 密码：ef9w，因为抓的包毕竟包含的个人信息太多，明天中午我就取消分享吧。谢谢各位了！

**Comment by ly0** [comment]
看上去已经成功了

**Comment by mchome** [comment]
![85m e ia 40vzk8o d_klh](https://cloud.githubusercontent.com/assets/7392658/20757459/553056a6-b751-11e6-9c4f-ffc64de78e3f.jpg)
ping一下外网的ip，校园网的ip，看看是不是dns没好
