### ISSUE TITLE
重写了一个C语言的版本

### ISSUE THREAD

**Issue by yujincheng08** [drcoms/drcom-generic#158]
重写了一个C语言的版本，默认适合广东财经大学使用。
修改config.h应该可以适用d/x版本。
目前暂不支持ror version = True的版本，后续可以添加
后续有空可以弄搞一个通用版，用命令行输入各个参数，并且编译到各个架构的版本
https://github.com/yujincheng08/gdufe-drcom
> ar71xx
> bcm2708
> bcm53xx
> brcm47xx
> brcm63xx
> kirkwood
> mvebu
> oxnas
> ramips
> sunxi
> x86
> x86_64

望支持:)

**Comment by ly0** [comment]
赞

**Comment by Git2Frank** [comment]
厉害了！不太会python，想改个P版的不会改...

**Comment by mchome** [comment]
@Git2Frank 尝试这个https://github.com/mchome/dogcom

**Comment by Git2Frank** [comment]
@mchome 赞！感谢大神~
