### ISSUE TITLE
关于无线网接入的问题

### ISSUE THREAD

**Issue by TonyLee61** [drcoms/drcom-generic#161]
我校使用5.2.1（D）版本，但是学校只有无线网，可以用路由器链接drcom吗？应该需要两台路由器吧，一个做中继

**Comment by guliujian** [comment]
实际上一台中继也可以，不过一般推荐挂其他网卡做单独中继那样更稳定，也可以两台一台中继一台drcom

**Comment by TonyLee61** [comment]
@guliujian 但是我校接入方法特别蛋疼。。先是内网登陆，然后是drcom登陆，这样可以么。。。而且IP地址估计也得折腾一番。。学校真是煞费苦心
