### ISSUE TITLE
5.2D版，PC上可以联网，在路由器上不行

### ISSUE THREAD

**Issue by qyz777** [drcoms/drcom-generic#162]
北京信息科技大学
![qq 20161230193152](https://cloud.githubusercontent.com/assets/24841040/21564295/c520ac36-cec6-11e6-8f53-56945ed2e4da.png)

**Comment by guliujian** [comment]
network is unreachable

**Comment by qyz777** [comment]
请问这是什么问题呢

**Comment by ly0** [comment]
网线插了吗？ 确认是D版不是X或者p版吗？

**Comment by qyz777** [comment]
确认是D版，并且插了网线

**Comment by jlucsz** [comment]
是固定IP地址的吗？地址设置了吗？mac有没有改啊

**Comment by qyz777** [comment]
![image](https://cloud.githubusercontent.com/assets/24841040/21565043/f98eaafc-cecd-11e6-9696-398d6f7932e6.png)

**Comment by jlucsz** [comment]
我没懂啊，我是说账号是和路由器绑定的吗？

**Comment by qyz777** [comment]
您是说
![image](https://cloud.githubusercontent.com/assets/24841040/21565066/354cbe1c-cece-11e6-802e-ea59e817e618.png)这里的改了吗

**Comment by jlucsz** [comment]
不是这里，我是说路由器的，而不是脚本的

**Comment by qyz777** [comment]
我没有修改路由器的

**Comment by jlucsz** [comment]
路由器要修改成和账号对应的_IP地址和克隆绑定的mac

**Comment by qyz777** [comment]
您能告诉我一下怎么修改吗

**Comment by jlucsz** [comment]
登陆路由器，进wan口设置下面这些
![image](https://cloud.githubusercontent.com/assets/24754739/21565124/fda80682-cece-11e6-925f-5944df07e3d9.png)

**Comment by qyz777** [comment]
太感谢了，我先试试

**Comment by qyz777** [comment]
![image](https://cloud.githubusercontent.com/assets/24841040/21565244/5e10222e-ced0-11e6-902e-a7f9cdc56fc3.png)
我出现了这样的情况

**Comment by jlucsz** [comment]
这个不知道了，等大神回答

**Comment by qyz777** [comment]
好的，谢谢

**Comment by HYec** [comment]
试试能不能在路由器上ping通认证服务器ip地址
