### ISSUE TITLE
5.2.1(p)心跳失败，已参考过之前的issue

### ISSUE THREAD

**Issue by factoid0** [drcoms/drcom-generic#163]
![4](https://cloud.githubusercontent.com/assets/19859412/21600447/21f3b2e4-d1b7-11e6-93b3-be7cbd7b2feb.jpg)

这是在Ubuntu拨号后心跳运行后的失败提示！，用的是#116 楼的心跳文件。
大家帮忙看看是怎么回事

**Comment by mchome** [comment]
请用 [latest-pppoe.py](https://raw.githubusercontent.com/drcoms/drcom-generic/master/latest-pppoe.py).

**Comment by factoid0** [comment]
谢谢楼上 ，第一运行 latest-pppoe.py 没有成功，再次运行，已成功
