### ISSUE TITLE
关于抓包文件生成配置文件的问题

### ISSUE THREAD

**Issue by StubbornYang** [drcoms/drcom-generic#167]
很抱歉但是找不到其他地方咨询只好来这里咨询一下。
Traceback (most recent call last):
  File "drcom_d_config.py", line 20, in <module>
    offset = re.search('\xF0\x00\xF0\x00[\x00-\xFF]{4}[\x03\x07]\x01', text).start() + 8
AttributeError: 'NoneType' object has no attribute 'start'
请问一下是抓包失败了么？是抓包的方式不对么？

**Comment by ly0** [comment]
有可能是抓包没抓对，也有可能是这个配置程序有问题。。
如果找不到地方问可以加qq群：318495368
