### ISSUE TITLE
怎样注销网络？

### ISSUE THREAD

**Issue by noe132** [drcoms/drcom-generic#170]
用latest-wired.py登陆后，kill掉进程后实际登录没释放，再次登录会失败，因为其他设备已经登录了该账号
需要等待5分钟等登陆释放了才能使用

有发送注销包的方法么？

**Comment by mchome** [comment]
才5分钟。。。没这个必要

**Comment by XiaoCheney** [comment]
实在想要，有时间抓抓看

**Comment by noe132** [comment]
也不算刚需吧~如果有时间有精力可以添加一个这个功能~

**Comment by mchome** [comment]
lz做好了发pr吧
