### ISSUE TITLE
win10系统，使用d版登陆失败。

### ISSUE THREAD

**Issue by LithiumHydrogen** [drcoms/drcom-generic#172]
自带客户端正常工作，但因为学习linux需要需要在linux下使用校园网，学校没有 给linux的客户端。
本来打算是在win10下测试python版本通过后，在linux下使用。win10下抓包成功，启动后报错。以下为内容，求助。
Traceback (most recent call last):
  File "latest-wired.py", line 64, in <module>
    s.bind((bind_ip, 61440))
  File "C:\Python27\lib\socket.py", line 222, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10048] 通常每个套接字地址(协议/网络地址/端口)

**Comment by ly0** [comment]
麻烦关掉官方客户端。

**Comment by mchome** [comment]
用wine
