### ISSUE TITLE
drcom5.2.1版本，路由器可以用，但是不能连接两个及两个以上的设备，一连接立马掉线

### ISSUE THREAD

**Issue by alcy369** [drcoms/drcom-generic#174]
![screenshot_20170225-230156](https://cloud.githubusercontent.com/assets/17170859/23332148/dbdb1b12-fbaf-11e6-8748-de49e702c0b7.png)

**Comment by ly0** [comment]
绕过DRCOM路由器连接设备数量检查不属于本repo的讨论范围.
