### ISSUE TITLE
可以连接上 但隔一段时间总是Modem hangup

### ISSUE THREAD

**Issue by zxh326** [drcoms/drcom-generic#175]
Sat Feb 25 23:27:33 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:27:38 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:27:47 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:28:03 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:28:23 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:28:27 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:28:32 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:28:35 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:28:39 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:28:40 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:28:48 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:28:56 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:29:05 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:29:28 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:29:31 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:29:39 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:29:49 2017 daemon.info pppd[2771]: LCP terminated by peer
Sat Feb 25 23:29:49 2017 daemon.info pppd[2771]: Connect time 8.1 minutes.
Sat Feb 25 23:29:49 2017 daemon.info pppd[2771]: Sent 568432 bytes, received 4183868 bytes.
Sat Feb 25 23:29:49 2017 daemon.notice netifd: Network device 'pppoe-wan' link is down
**Sat Feb 25 23:29:49 2017 daemon.notice pppd[2771]: Modem hangup**
Sat Feb 25 23:29:49 2017 daemon.notice pppd[2771]: Connection terminated.
Sat Feb 25 23:29:49 2017 daemon.info pppd[2771]: Connect time 8.1 minutes.
Sat Feb 25 23:29:49 2017 daemon.info pppd[2771]: Sent 568432 bytes, received 4183868 bytes.
Sat Feb 25 23:29:49 2017 daemon.info pppd[2771]: Sent PADT
Sat Feb 25 23:29:50 2017 daemon.info pppd[2771]: Exit.
Sat Feb 25 23:29:50 2017 daemon.notice netifd: Interface 'wan' is now down
Sat Feb 25 23:29:50 2017 daemon.notice netifd: Interface 'wan' is disabled
Sat Feb 25 23:29:50 2017 kern.info kernel: [ 1569.000000] eth0: link down
Sat Feb 25 23:29:50 2017 kern.info kernel: [ 1569.000000] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Sat Feb 25 23:29:50 2017 daemon.notice netifd: Interface 'wan' is enabled
Sat Feb 25 23:29:50 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sat Feb 25 23:29:50 2017 daemon.warn dnsmasq[1588]: no servers found in /tmp/resolv.conf.auto, will retry
Sat Feb 25 23:29:50 2017 daemon.notice netifd: Network device 'eth0' link is down
Sat Feb 25 23:29:50 2017 daemon.notice netifd: Interface 'wan' has link connectivity loss
Sat Feb 25 23:29:50 2017 kern.info kernel: [ 1569.220000] eth0: link up (100Mbps/Full duplex)
Sat Feb 25 23:29:50 2017 kern.info kernel: [ 1569.220000] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sat Feb 25 23:29:50 2017 daemon.notice netifd: Network device 'eth0' link is up
Sat Feb 25 23:29:50 2017 daemon.notice netifd: Interface 'wan' has link connectivity 
Sat Feb 25 23:29:50 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sat Feb 25 23:29:50 2017 daemon.notice netifd: wan (2911): Command failed: Permission denied
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' is now down
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' is disabled
Sat Feb 25 23:29:51 2017 kern.info kernel: [ 1569.660000] eth0: link down
Sat Feb 25 23:29:51 2017 kern.info kernel: [ 1569.660000] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' is enabled
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Network device 'eth0' link is down
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' has link connectivity loss
Sat Feb 25 23:29:51 2017 daemon.notice netifd: wan (2938): Command failed: Permission denied
Sat Feb 25 23:29:51 2017 kern.info kernel: [ 1570.220000] eth0: link up (100Mbps/Full duplex)
Sat Feb 25 23:29:51 2017 kern.info kernel: [ 1570.220000] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Network device 'eth0' link is up
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' has link connectivity 
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' is now down
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' is disabled
Sat Feb 25 23:29:51 2017 kern.info kernel: [ 1570.550000] eth0: link down
Sat Feb 25 23:29:51 2017 kern.info kernel: [ 1570.550000] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' is enabled
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Network device 'eth0' link is down
Sat Feb 25 23:29:51 2017 daemon.notice netifd: Interface 'wan' has link connectivity loss
Sat Feb 25 23:29:52 2017 kern.info kernel: [ 1571.220000] eth0: link up (100Mbps/Full duplex)
Sat Feb 25 23:29:52 2017 kern.info kernel: [ 1571.220000] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sat Feb 25 23:29:52 2017 daemon.notice netifd: Network device 'eth0' link is up
Sat Feb 25 23:29:52 2017 daemon.notice netifd: Interface 'wan' has link connectivity 
Sat Feb 25 23:29:52 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sat Feb 25 23:29:52 2017 daemon.info pppd[2985]: Plugin rp-pppoe.so loaded.
Sat Feb 25 23:29:52 2017 daemon.info pppd[2985]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Sat Feb 25 23:29:52 2017 daemon.notice pppd[2985]: pppd 2.4.7 started by root, uid 0
Sat Feb 25 23:29:53 2017 daemon.info pppd[2985]: PPP session is 24411
Sat Feb 25 23:29:53 2017 daemon.warn pppd[2985]: Connected to 20:0b:c7:8f:21:8d via interface eth0
Sat Feb 25 23:29:53 2017 kern.info kernel: [ 1571.640000] pppoe-wan: renamed from ppp0
Sat Feb 25 23:29:53 2017 daemon.info pppd[2985]: Using interface pppoe-wan
Sat Feb 25 23:29:53 2017 daemon.notice pppd[2985]: Connect: pppoe-wan <--> eth0
Sat Feb 25 23:29:55 2017 daemon.warn dnsmasq-dhcp[1588]: DHCP packet received on eth0 which has no address
Sat Feb 25 23:29:56 2017 daemon.info pppd[2985]: CHAP authentication succeeded: Welcome to Drcom System:603789484
Sat Feb 25 23:29:56 2017 daemon.notice pppd[2985]: CHAP authentication succeeded
Sat Feb 25 23:29:56 2017 daemon.notice pppd[2985]: peer from calling number 20:0B:C7:8F:21:8D authorized
Sat Feb 25 23:29:56 2017 daemon.notice pppd[2985]: local  LL address fe80::7940:b3a0:55b1:ff78
Sat Feb 25 23:29:56 2017 daemon.notice pppd[2985]: remote LL address fe80::220b:c7ff:fe8f:218d
Sat Feb 25 23:29:56 2017 daemon.notice pppd[2985]: local  IP address 172.19.71.15
Sat Feb 25 23:29:56 2017 daemon.notice pppd[2985]: remote IP address 172.19.64.1
Sat Feb 25 23:29:56 2017 daemon.notice pppd[2985]: primary   DNS address 172.17.1.7
Sat Feb 25 23:29:56 2017 daemon.notice pppd[2985]: secondary DNS address 172.17.1.8
Sat Feb 25 23:29:56 2017 daemon.notice netifd: Network device 'pppoe-wan' link is up
Sat Feb 25 23:29:56 2017 daemon.notice netifd: Interface 'wan' is now up
Sat Feb 25 23:29:56 2017 daemon.info dnsmasq[1588]: reading /tmp/resolv.conf.auto
Sat Feb 25 23:29:56 2017 daemon.info dnsmasq[1588]: using local addresses only for domain lan
Sat Feb 25 23:29:56 2017 daemon.info dnsmasq[1588]: using nameserver 172.17.1.7#53
Sat Feb 25 23:29:56 2017 daemon.info dnsmasq[1588]: using nameserver 172.17.1.8#53
Sat Feb 25 23:29:56 2017 user.notice firewall: Reloading firewall due to ifup of wan (pppoe-wan)

**Comment by mchome** [comment]
我觉得是脚本没启动吧

**Comment by zxh326** [comment]
启动了啊，Modem hangup之后，又会重新连接

**Comment by mchome** [comment]
提供一下脚本日志

**Comment by zxh326** [comment]
Sun Feb 26 18:33:03 2017 user.notice firewall: Reloading firewall due to ifup of wan (pppoe-wan)
Sun Feb 26 23:04:27 2017 daemon.info pppd[1046]: LCP terminated by peer
Sun Feb 26 23:04:27 2017 daemon.info pppd[1046]: Connect time 3.0 minutes.
Sun Feb 26 23:04:27 2017 daemon.info pppd[1046]: Sent 379606 bytes, received 2129276 bytes.
Sun Feb 26 23:04:27 2017 daemon.notice netifd: Network device 'pppoe-wan' link is down
Sun Feb 26 23:04:27 2017 daemon.notice pppd[1046]: Modem hangup
Sun Feb 26 23:04:27 2017 daemon.notice pppd[1046]: Connection terminated.
Sun Feb 26 23:04:27 2017 daemon.info pppd[1046]: Connect time 3.0 minutes.
Sun Feb 26 23:04:27 2017 daemon.info pppd[1046]: Sent 379606 bytes, received 2129276 bytes.
Sun Feb 26 23:04:27 2017 daemon.info pppd[1046]: Sent PADT
Sun Feb 26 23:04:27 2017 daemon.info pppd[1046]: Exit.
Sun Feb 26 23:04:27 2017 daemon.notice netifd: Interface 'wan' is now down
Sun Feb 26 23:04:27 2017 daemon.notice netifd: Interface 'wan' is disabled
Sun Feb 26 23:04:27 2017 kern.info kernel: [  209.070000] eth0: link down
Sun Feb 26 23:04:27 2017 kern.info kernel: [  209.070000] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Sun Feb 26 23:04:27 2017 daemon.notice netifd: Interface 'wan' is enabled
Sun Feb 26 23:04:27 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sun Feb 26 23:04:27 2017 daemon.warn dnsmasq[1161]: no servers found in /tmp/resolv.conf.auto, will retry
Sun Feb 26 23:04:27 2017 daemon.notice netifd: Network device 'eth0' link is down
Sun Feb 26 23:04:27 2017 daemon.notice netifd: Interface 'wan' has link connectivity loss
Sun Feb 26 23:04:27 2017 kern.info kernel: [  209.140000] eth0: link up (100Mbps/Full duplex)
Sun Feb 26 23:04:27 2017 kern.info kernel: [  209.140000] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sun Feb 26 23:04:27 2017 daemon.notice netifd: Network device 'eth0' link is up
Sun Feb 26 23:04:27 2017 daemon.notice netifd: Interface 'wan' has link connectivity 
Sun Feb 26 23:04:27 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sun Feb 26 23:04:27 2017 daemon.notice netifd: wan (1289): Command failed: Permission denied
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' is now down
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' is disabled
Sun Feb 26 23:04:28 2017 kern.info kernel: [  209.730000] eth0: link down
Sun Feb 26 23:04:28 2017 kern.info kernel: [  209.730000] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' is enabled
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Network device 'eth0' link is down
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' has link connectivity loss
Sun Feb 26 23:04:28 2017 daemon.notice netifd: wan (1315): Command failed: Permission denied
Sun Feb 26 23:04:28 2017 kern.info kernel: [  210.140000] eth0: link up (100Mbps/Full duplex)
Sun Feb 26 23:04:28 2017 kern.info kernel: [  210.140000] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Network device 'eth0' link is up
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' has link connectivity 
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' is now down
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' is disabled
Sun Feb 26 23:04:28 2017 kern.info kernel: [  210.380000] eth0: link down
Sun Feb 26 23:04:28 2017 kern.info kernel: [  210.380000] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' is enabled
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Network device 'eth0' link is down
Sun Feb 26 23:04:28 2017 daemon.notice netifd: Interface 'wan' has link connectivity loss
Sun Feb 26 23:04:29 2017 daemon.notice netifd: wan (1337): Command failed: Permission denied
Sun Feb 26 23:04:29 2017 kern.info kernel: [  211.140000] eth0: link up (100Mbps/Full duplex)
Sun Feb 26 23:04:29 2017 kern.info kernel: [  211.140000] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Sun Feb 26 23:04:29 2017 daemon.notice netifd: Network device 'eth0' link is up
Sun Feb 26 23:04:29 2017 daemon.notice netifd: Interface 'wan' has link connectivity 
Sun Feb 26 23:04:29 2017 daemon.notice netifd: Interface 'wan' is setting up now
Sun Feb 26 23:04:30 2017 daemon.info pppd[1372]: Plugin rp-pppoe.so loaded.
Sun Feb 26 23:04:30 2017 daemon.info pppd[1372]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Sun Feb 26 23:04:30 2017 daemon.notice pppd[1372]: pppd 2.4.7 started by root, uid 0
Sun Feb 26 23:04:30 2017 daemon.info pppd[1372]: PPP session is 5189
Sun Feb 26 23:04:30 2017 daemon.warn pppd[1372]: Connected to 20:0b:c7:8f:21:8d via interface eth0
Sun Feb 26 23:04:30 2017 daemon.info pppd[1372]: Using interface pppoe-wan
Sun Feb 26 23:04:30 2017 daemon.notice pppd[1372]: Connect: pppoe-wan <--> eth0
Sun Feb 26 23:04:30 2017 kern.info kernel: [  211.530000] pppoe-wan: renamed from ppp0
Sun Feb 26 23:04:33 2017 daemon.info pppd[1372]: CHAP authentication succeeded: Welcome to Drcom System:603789484

**Comment by zxh326** [comment]
已解决。

**Comment by liuxu0076** [comment]
同样的问题，请问怎么解决的？
