### ISSUE TITLE
5.2.1p版本，拨号后执行latest-pppoe.py后不能一直上网，大概半分钟左右就会断网

### ISSUE THREAD

**Issue by liuxu0076** [drcoms/drcom-generic#176]
这里是开始拨号到运行latest-pppoe.py后再到最后断网过程的包
链接: http://pan.baidu.com/s/1mhLB1X2 密码: 35ap

谢谢。

**Comment by mchome** [comment]
如果你不能登录，请发Issue的时候附上用哪个脚本文件，脚本的日志输出，正常客户端的抓包，并且附上你的学校的名称，最好可以提供相关的Windows和Linux下的客户端，提高沟通效率。

**Comment by liuxu0076** [comment]
现在运行latest-pppoe.py也不能维持心跳，出现如下错误
，使用的脚本就是p版简略使用和配置说明文章中的代码
C:\Users\asus2\Desktop\新建文件夹>python latest-pppoe.py
Traceback (most recent call last):
  File "latest-pppoe.py", line 336, in <module>
    main()
  File "latest-pppoe.py", line 323, in main
    daemon()
  File "latest-pppoe.py", line 318, in daemon
    with open('/var/run/drcom_p.pid','w') as f:
IOError: [Errno 2] No such file or directory: '/var/run/drcom_p.pid'

**Comment by liuxu0076** [comment]
看到支持的学校里面就有我的学校，是长江大学

**Comment by liuxu0076** [comment]
正常客户端抓包链接: http://pan.baidu.com/s/1mhY3sAs 密码: ksyf

**Comment by mchome** [comment]
IS_TEST = False改成IS_TEST = True

**Comment by liuxu0076** [comment]
将IS_TEST = False改成IS_TEST = True后提示如下信息

C:\Users\asus2\Desktop\新建文件夹>python latest-pppoe.py
[*]  auth svr: 10.151.0.254
[*]  pppoe_flag: 2a
[*]  keep_alive2_flag: dc
Traceback (most recent call last):
  File "latest-pppoe.py", line 336, in <module>
    main()
  File "latest-pppoe.py", line 329, in main
    s = Socket(server)
  File "latest-pppoe.py", line 101, in __init__
    self.s.bind(("0.0.0.0", 61440))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10048] 通常每个套接字地址(协议/网络地址/端口)

**Comment by liuxu0076** [comment]
后重启电脑后运行latest-pppoe.py正常

**Comment by wu5546945** [comment]
请问解决了吗？我的issue跟你一样。。

**Comment by XiaohuihuiHuang** [comment]
你好，我是武汉职业技术学院的，电脑上可以用，路由器上不行，请问你在路由器上成功了吗？
