### ISSUE TITLE
重写了一个 PHP 版本

### ISSUE THREAD

**Issue by dantmnf** [drcoms/drcom-generic#178]
主要还是因为 Python 版在路由器上启动太慢了（
基本上是照着 latest-wired.py 写的，不过不排除行为不一致的可能

https://github.com/dantmnf/drcom-client

**Comment by ly0** [comment]
666666666

**Comment by jackeyt** [comment]
@dantmnf PHP版本在openwrt路由上使用方法？

**Comment by dantmnf** [comment]
@jackeyt 
1. 把抓包得到的配置信息照葫芦画瓢写到 config-openwrt.php 里（有些可以自动获取，自行测试）
2. 改名成 config.php
3. `opkg install php5-cli php5-mod-sockets php5-mod-json php5-mod-mbstring php5-mod-pcntl`
4. `php5-cli drcomfucker.php`
