### ISSUE TITLE
5.20D版本无法解出连接信息（config.txt为0kb）

### ISSUE THREAD

**Issue by chenjiageng** [drcoms/drcom-generic#179]
@Everyb0dyLies 
@ly0 
@qoddi 
@Artoria2e5 
![default](https://cloud.githubusercontent.com/assets/26062629/23446741/febf8b08-fe80-11e6-96db-eed9aa384ae4.png)

校园网客户端（西安石油大学）和抓包文件
https://pan.baidu.com/s/1pL34OZL

**Comment by chenjiageng** [comment]
已加群318495368，尚无解决办法

**Comment by chenjiageng** [comment]
已解决，麻烦了

**Comment by chenjiageng** [comment]
希望有一个python脚本适配我们学校

**Comment by ly0** [comment]
所以是解决了还是没解决

**Comment by chenjiageng** [comment]
大神，可以写一个生成连接信息的python脚本吗？

**Comment by noterpopo** [comment]
深圳大学5.20D，同样的问题

**Comment by mchome** [comment]
丢上你抓的包

**Comment by caishenpc** [comment]
深圳大学可以用啊，是不是抓的包有问题。
