### ISSUE TITLE
latest-wired.py 的换行符问题

### ISSUE THREAD

**Issue by mchome** [drcoms/drcom-generic#18]
上次修改latest-wired.py的时候，git给自动改成了crlf换行了，在linux下执行会出现not found问题，改回lf换行可解决问题。

**Comment by ly0** [comment]
= = 真麻烦 给你Owner权限壕了

**Comment by mchome** [comment]
你下次改动的时候顺便改回来就行 →_→

**Comment by ly0** [comment]
╮(╯▽╰)╭ 交给你辣
