### ISSUE TITLE
Newifi mini潘多拉固件后台登录密码

### ISSUE THREAD

**Issue by caishenpc** [drcoms/drcom-generic#182]
刷了openwrt里面提供的newifi mini的潘多拉固件，但是不知道后台登录的密码。
提示用户名root，密码试了root，admin，toor，rootroot，等都不行。
想问一问固件的作者登录密码是什么，或者谁知道一些其他的方法可以来修改密码。

**Comment by leetking** [comment]
问固件作者啊？你来这里又没人知道你的密码

**Comment by caishenpc** [comment]
就是不知道怎么去找固件作者啊

**Comment by ly0** [comment]
不知道怎么找就不要用不知道来源的固件了
