### ISSUE TITLE
请问有人成功的将 latest-wired.py  这个文件在python3上运行吗

### ISSUE THREAD

**Issue by luzhengyang1995** [drcoms/drcom-generic#183]
```
t = struct.pack("<H", int(ran)%(0xFFFF)) #这里的 t 的 type 为 bytes

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

s.sendto("\x01\x02"+t+"\x09"+"\x00"*15, (svr, 61440))
```
在python3里面会提示TypeError: Can't convert 'bytes' object to str implicitly
我将
`s.sendto("\x01\x02"+t+"\x09"+"\x00"*15, (svr, 61440))`
改写成
`s.sendto('\x01\x02'.encode('utf-8')+t+"\x09".encode('utf-8')+"\x00".encode('utf-8')*15, (svr, 61440))`
不提示报错了，但是一直登陆失败。

**Comment by mchome** [comment]
试下 [2to3](https://docs.python.org/2/library/2to3.html)

**Comment by luzhengyang1995** [comment]
经过测试，失败，
代码经过我之前那样修改以后，会不停的出现[challenge] timeout, retrying...

**Comment by dantmnf** [comment]
与 socket 相关的全部要改成 bytes

**Comment by ly0** [comment]
何必做porting.
字符串处理部分都在前面加b前缀差不多了吧

**Comment by luzhengyang1995** [comment]
@dantmnf  发现错误地方好多在log地方用了encode(hex)，然后提示这个，
`'bytes' object has no attribute 'encode'`
我删除log以后提示这个`sequence item 1: expected str instance, bytes found`
调试了一晚上，水平不够，我放弃了

**Comment by luzhengyang1995** [comment]
@ly0 我是刚开始用python3的，之前加了b了发现登陆失败，然后以为python3删除了这个语法

**Comment by mchome** [comment]
有空还是port一下吧 (滑稽

**Comment by ly0** [comment]
@mchome 
![image](https://cloud.githubusercontent.com/assets/1551736/23833326/c6e570b0-077e-11e7-9132-b3957bea2bc4.png)

**Comment by dantmnf** [comment]
我是感觉与其改这改那不如重写一遍（
