### ISSUE TITLE
电脑上pppoe拨号成功，路由器上失败

### ISSUE THREAD

**Issue by liuxu0076** [drcoms/drcom-generic#184]
长江大学5.2.1p版本
电脑上pppoe拨号正常，路由器上失败
![5 66fiiq0r6pi 7 p v](https://cloud.githubusercontent.com/assets/25142784/23831835/b687df2a-0763-11e7-99f1-c562a8cde447.png)

![Uploading image.png…]()

显示网络不可达，确认账号密码正确，网线连接正常

**Comment by liuxu0076** [comment]
也已经将is_test=true改为了is_test=false

**Comment by ly0** [comment]
可能这就是命吧

**Comment by ly0** [comment]
可能这就是命吧。

**Comment by yaalsn** [comment]
路由器没连接好。

**Comment by mchome** [comment]
没拨上号.jpg

**Comment by XiaohuihuiHuang** [comment]
你好，我是武汉职业技术学院的，跟你一样的错误结果，电脑上可以用，路由器上不可以，请问你解决了吗？我们俩所在的学校很近啊。

**Comment by yaalsn** [comment]
可约

2017年3月22日 12:16，"XiaohuihuiHuang" <notifications@github.com>写道：

**Comment by liuxu0076** [comment]
不知怎么就好了

**Comment by XiaohuihuiHuang** [comment]
我的裴讯k2刷的K2-PandoraBox-160922-adbyby

**Comment by XiaohuihuiHuang** [comment]
冒昧的问一下你刷的什么固件

**Comment by ly0** [comment]
武汉鸭脖好吃啊
