### ISSUE TITLE
你好，你的pppoe-dialer.exe软件下载不下来，希望重新分享一下，谢谢

### ISSUE THREAD

**Issue by XiaohuihuiHuang** [drcoms/drcom-generic#187]
你好，你的pppoe-dialer.exe软件下载不下来，显示服务器禁止访问此链接，希望重新分享一下，谢谢，在路由器跑得时候不成功，故想试一下windows上的，因自带的pppoe出现691错误，下载你的软件试一下。

**Comment by XiaohuihuiHuang** [comment]
[root@PandoraBox_EB79:/usr/bin]#./drcom 
[*]  auth svr: 172.16.1.2
[*]  pppoe_flag: 24
[*]  keep_alive2_flag: d8
[*]  open local port:61440
[*]  DEBUG MODE:False
[*]  pppoe: send challenge request
Traceback (most recent call last):
  File "./drcom", line 336, in <module>
    main()
  File "./drcom", line 332, in main
    pppoe.send(s)
  File "./drcom", line 183, in send
    s.send(data)
  File "./drcom", line 109, in send
    self.s.sendto(data, (self.server, self.port))
socket.error: [Errno 128] Network is unreachable

**Comment by mchome** [comment]
留下邮箱啊

**Comment by XiaohuihuiHuang** [comment]
1692013123@qq.com 谢谢
