### ISSUE TITLE
测试脚本无法连接

### ISSUE THREAD

**Issue by Wsuika** [drcoms/drcom-generic#19]
![qq 20150916213143](https://cloud.githubusercontent.com/assets/12707115/9905970/929107ae-5cba-11e5-959d-4ce3fd7fada3.png)
按照wiki走到测试，连接的时候最后出现这样的文字后闪退。

**Comment by Wsuika** [comment]
https://www.dropbox.com/s/oyczod6enl0sq97/dr.pcapng?dl=0 截的包

**Comment by ly0** [comment]
svr写的是？

**Comment by Wsuika** [comment]
是config里面的server么？ svr:ac130102

**Comment by Wsuika** [comment]
刚刚又试了一下在线配置器  得到了一个正常的ip  更换后一切正常可以连接   请关闭这个issue吧

**Comment by mchome** [comment]
能用就好
