### ISSUE TITLE
5.20（x）配置后latest-wired.py 一直显示timeout

### ISSUE THREAD

**Issue by GIIIMAN** [drcoms/drcom-generic#192]
截取包后按包数据配置完
pcapng file: dr.pcapng
copy following statements to drcom.conf or overwrite field between "# CONFIG" and "# CONFIG_END" in latest-wired.py

server = '****'
username='****'
password=''
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x01'
host_ip = '10.50.15.243'
IPDOG = '\x01'
host_name = 'DRCOMFUCKER'
PRIMARY_DNS = '123.125.81.6'
dhcp_server = '10.50.15.254'
AUTH_VERSION = '\x14\x00'
mac = ****
host_os = 'WINDIAOS'
KEEP_ALIVE_VERSION = '\x1d\x00'

打开latest-wired.py 一直显示timeout重连

**Comment by mchome** [comment]
补上server的空项未认证服务器的ip

**Comment by GIIIMAN** [comment]
@mchome 
![image](https://cloud.githubusercontent.com/assets/26688778/24641714/7ef1e942-1934-11e7-8d7f-1549bf469ffd.png)
事实上我已经按照包内容全部COPY打上了，原客户端也关闭了，但是电脑端测试一直通不过，

**Comment by ly0** [comment]
802.1x部分通过认证了吗?

**Comment by mchome** [comment]
试下先用mentohust通过802.1x验证

**Comment by GIIIMAN** [comment]
十分感谢用mentohust通过802.1x验证后网络连接上了。这是否认为着我把mentohust移植到路由器上就可以了。
还有我通过 https://github.com/drcoms/drcom8021x中的main.py无法通过8021x认证然后Drcom认证也无法通过。或者说这本来在WIN10就运行不了的


#coding=utf-8
import os
import multiprocessing
import drcom
import eapauth

user_info = {'username': "201610*****@*****.GZ",
             'password': "0419****",
             'ethernet_interface': "eth0",
             'daemon': False,
             'dhcp_command': ''
             }

need_drcom = True

if not (os.getuid() == 0):
    print 'Need root'
    exit(-1)
    
# 802.1x成功以后就进入正常drcom认证
if need_drcom:
    auth = eapauth.EAPAuth(user_info, success_handler=drcom.main)
    auth.serve_forever()
else:
    auth = eapauth.EAPAuth(user_info)
    auth.serve_forever()

**Comment by ly0** [comment]
@GIIIMAN 是的，win10运行不了因为没有权限发送mac帧

**Comment by GIIIMAN** [comment]
@mchome @ly0 十分感谢用mentohust通过802.1x验证后网络连接上了。这是否认为着我把mentohust移植到路由器上就可以了。
还有我通过 https://github.com/drcoms/drcom8021x中的main.py无法通过8021x认证然后Drcom认证也无法通过。或者说这本来在WIN10就运行不了的
#coding=utf-8
import os
import multiprocessing
import drcom
import eapauth
user_info = {'username': "201610*****@*****.GZ",
'password': "0419****",
'ethernet_interface': "eth0",
'daemon': False,
'dhcp_command': ''
}
need_drcom = True
if not (os.getuid() == 0):
print 'Need root'
exit(-1)
802.1x成功以后就进入正常drcom认证
if need_drcom:
auth = eapauth.EAPAuth(user_info, success_handler=drcom.main)
auth.serve_forever()
else:
auth = eapauth.EAPAuth(user_info)
auth.serve_forever()

**Comment by mchome** [comment]
ok，那用mentohust就可以了。
