### ISSUE TITLE
5.2D版  电脑py文件可以拨号上网 ，路由器不能。

### ISSUE THREAD

**Issue by reezoo** [drcoms/drcom-generic#194]
路由器信息为
auth svr: 10.2.2.51
username: 2562
password: 446659
mac: 0xd8cb8a8e5840
bind ip: 0.0.0.0
[challenge] recv 0202c01639175f0000000100d003e8f0000000000a026140040000800000c737f3a2000000001d000000
[DEBUG] challenge:
0202c01639175f0000000100d003e8f0000000000a026140040000800000c737f3a2000000001d000000
[challenge] challenge packet sent.
[mkpkt] 03010018eded9ee8e630c3468e53d7d6ea9fe91e3235363200000000000000000000000000000000000000000000000000000000000000000c0235261466be709b08fa6bd8087190d8a4e7ced106858c010a026f820000000000000000000000007496bfc7cfe5447e0100000000667579756d6900000000000000000000000000000000000000000000000000000a02010b1e01fff3000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000900020c9009c5df0000d8cb8a8e58400000e913
[login] send 03010018eded9ee8e630c3468e53d7d6ea9fe91e3235363200000000000000000000000000000000000000000000000000000000000000000c0235261466be709b08fa6bd8087190d8a4e7ced106858c010a026f820000000000000000000000007496bfc7cfe5447e0100000000667579756d6900000000000000000000000000000000000000000000000000000a02010b1e01fff3000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000900020c9009c5df0000d8cb8a8e58400000e913
Traceback (most recent call last):
  File "/usr/bin/drcom", line 472, in <module>
    main()
  File "/usr/bin/drcom", line 462, in main
    package_tail = login(username, password, server)
  File "/usr/bin/drcom", line 377, in login
    data, address = s.recvfrom(1024)
socket.timeout: timed out

**Comment by mchome** [comment]
@reezoo 路由器坏了 😂

**Comment by ly0** [comment]
@reezoo 路由器坏了

**Comment by reezoo** [comment]
没坏啊

**Comment by reezoo** [comment]
是广电网的drcom

**Comment by ly0** [comment]
@reezoo 尝试换固件 换路由器 或者这就是命吧。。

**Comment by reezoo** [comment]
本地的drcom，电脑连接路由器也不能拨号，只能广电网线直接连接电脑拨号。

**Comment by reezoo** [comment]
固件也没问题的。斐讯k2 路由器

**Comment by reezoo** [comment]
是不是这个drcom比较特别，和校园网的不一样

**Comment by mchome** [comment]
@reezoo 不是路由器的话，那么就是你的电脑比较特别 →_→

**Comment by ly0** [comment]
@reezoo 在PC上直连测试成功说明脚本的逻辑没有问题，能造成和PC上行为不一致的可能性千奇百怪，这个本项目无法一一去寻找原因～

**Comment by reezoo** [comment]
谢谢大神及时回复。抓包的时候电脑需要连接路由器？可是电脑连接路由器就不能拨号啊

**Comment by reezoo** [comment]
原来要把drcom里面的ip和mac改成路由器wan口的ip和mac。这样就顺利上网啦。很多教程都没提这步。

**Comment by ly0** [comment]
@reezoo 。。。wiki里不是有写吗

**Comment by reezoo** [comment]
没看到。哎。

**Comment by reezoo** [comment]
请教一下，drcom.conf这个文件干什么用的，有drcom这个文件不就够了吗

**Comment by ly0** [comment]
@reezoo 看文档看文档看文档
