### ISSUE TITLE
5.2.1D 脚本PC端运行正常，移植到路由器出现timeout

### ISSUE THREAD

**Issue by universalarm** [drcoms/drcom-generic#195]
路由器：斐讯K2路由器
Python环境：Python-mini
脚本：[https://github.com/drcoms/jlu-drcom-client/blob/master/newclient.py](url)
系统日志：[syslog.txt](https://github.com/drcoms/drcom-generic/files/888187/syslog.txt)

已更改istest为False，新建drcom.conf到/etc,
更改路由器wan口为静态协议及其Mac地址，wan口已插网线，
求助，谢谢！

**Comment by ly0** [comment]
@universalarm 吉大的用那个 newclient.py 就好
