### ISSUE TITLE
广东财经大学5.2d版本  断线不能重连  一直在认证界面 

### ISSUE THREAD

**Issue by lcmysoph** [drcoms/drcom-generic#197]
Wed Apr  5 20:11:33 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:11:33 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:12:37 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:12:37 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:13:19 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:13:20 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:13:20 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:13:20 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:13:20 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:13:20 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:13:20 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:13:58 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:13:58 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:15:58 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:15:58 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:17:50 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:17:50 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:18:20 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:18:21 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:18:21 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:18:21 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:18:21 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:18:21 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:18:21 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:18:57 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:18:57 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:20:00 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:20:00 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:22:00 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:22:00 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:23:06 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:23:06 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:23:21 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:23:22 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:23:22 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:23:22 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:23:22 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:23:22 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:23:22 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:24:35 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:24:35 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:25:48 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:25:48 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:26:59 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:26:59 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:27:03 2017 user.emerg syslog: DrCOM Auth Router for GDUFE
Wed Apr  5 20:27:03 2017 user.emerg syslog: [challenge] challenge packet sent.
Wed Apr  5 20:27:03 2017 user.emerg syslog: [login] packet sent.
Wed Apr  5 20:27:03 2017 user.emerg syslog: [login] login in
Wed Apr  5 20:27:03 2017 user.emerg syslog: [login] login Success
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send1
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive] keep-alive loop was in daemon.
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep_alive1] send
Wed Apr  5 20:27:03 2017 user.emerg syslog: [keep-alive2] send
Wed Apr  5 20:28:03 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:28:03 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:28:22 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:28:23 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:28:23 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:28:23 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:28:23 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:28:23 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:28:23 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:29:31 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:29:31 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:30:43 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:30:43 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:32:10 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:32:10 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:33:22 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:33:22 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:33:23 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:33:25 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:33:25 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:33:25 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:33:25 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:33:25 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:33:25 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:34:25 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:34:25 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:36:05 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:36:05 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:38:06 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:38:06 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:38:25 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:38:26 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:38:26 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:38:26 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:38:26 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:38:26 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:38:26 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:39:34 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:39:34 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:40:01 2017 authpriv.info dropbear[6210]: Child connection from 192.168.1.197:6735
Wed Apr  5 20:40:04 2017 authpriv.notice dropbear[6210]: Password auth succeeded for 'root' from 192.168.1.197:6735
Wed Apr  5 20:40:47 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:40:47 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:42:07 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:42:07 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC
Wed Apr  5 20:43:01 2017 authpriv.info dropbear[6210]: Exit (root): Exited normally
Wed Apr  5 20:43:26 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:43:27 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:43:27 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:43:27 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:43:27 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:43:27 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:43:27 2017 daemon.warn odhcpd[1509]: DHCPV6 SOLICIT IA_NA from 00010001200e726ba4badbba248d on br-lan: no addresses available 
Wed Apr  5 20:44:08 2017 daemon.info dnsmasq-dhcp[2307]: DHCPINFORM(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f 
Wed Apr  5 20:44:08 2017 daemon.info dnsmasq-dhcp[2307]: DHCPACK(br-lan) 192.168.1.197 f0:7b:cb:80:03:4f chen-PC

**Comment by mchome** [comment]
程序都掉了怎么重连

**Comment by lcmysoph** [comment]
如果掉了的话  怎么让它自己启动 已经添加了hotplug
