### ISSUE TITLE
使用6.0（d）版客户端登录失败，联通宽带，账号为字母加数字

### ISSUE THREAD

**Issue by yushaye** [drcoms/drcom-generic#199]
日志如下
[log.txt](https://github.com/drcoms/drcom-generic/files/904819/log.txt)

**Comment by mchome** [comment]
如果你不能登录，请发Issue的时候附上用哪个脚本文件，脚本的日志输出，正常客户端的抓包，并且附上你的学校的名称，最好可以提供相关的Windows和Linux下的客户端，提高沟通效率。

**Comment by ly0** [comment]
不清楚你用的哪个脚本，这个repo里的脚本似乎搜不到`Failed to keep in touch with server` 这样的关键字

**Comment by mchome** [comment]
苦主应该是用dogcom，但是你latest-wired.py测试过能用吗

**Comment by yushaye** [comment]
唉。。。是用的dogcom，我能用，我们学校的师妹不能用，我们是电信5.2（d）版，她是联通，6.0（d）版，我这边测试不到她那里的情况。。。

**Comment by yushaye** [comment]
这是6.0（D）版的客户端和6.0、5.2客户端的抓包，6.0客户端不知道为什么抓的包很小，貌似没抓到。

**Comment by mchome** [comment]
从log的时间上看是收到了登陆失败的包，可以发下账号密码吗，另外建议使用latest-wired.py来测试。

**Comment by vlw** [comment]
@yushaye I know!

**Comment by yushaye** [comment]
这个客户端是我师妹用的，我也没她密码0.0

**Comment by yushaye** [comment]
账号是：NV13032322565@cqjtdx  密码123456

**Comment by mchome** [comment]
你上传的抓包的账号是631303040619......

**Comment by yushaye** [comment]
那个，前前后后没表达明白，我们学校师妹住的雅园，用的客户端是6.0（d）版，跟我们所用的5.2（d）版不一样，不通用，我这边测试用6.0（d）无法登陆，她用5.2（d）也无法登陆，抓的包是我这边用5.2（d）版抓的，大大可以忽略。。。我发的账号是她的账号

**Comment by mchome** [comment]
你应该上传你师妹6.0的抓包

**Comment by ly0** [comment]
上传一个师妹上来吧

**Comment by yushaye** [comment]
我觉得让她去抓包有点难，她电脑白痴。。。

**Comment by mchome** [comment]
fixed at https://github.com/mchome/dogcom/commit/23a501c6f47ad93e099ec467e87de680ad912d1e

**Comment by vc5** [comment]
@yushaye 遇到校友了，可以留个联系方式私下交流一下吗

**Comment by DaltonHugh** [comment]
我们学校也是，联通的，帐号是字母加数字，然后WIFI不能开热点，Python运行一段时间自己就会掉，估计有nat检测 认命吧

2017年9月9日 下午3:56，"Vincent" <notifications@github.com>写道：
