### ISSUE TITLE
路由器无法在启动后运行脚本

### ISSUE THREAD

**Issue by Wsuika** [drcoms/drcom-generic#20]
不好意思我又出了点问题，我路由器刷的openwrt，按照教程在rc.local里面添加了 drcom & 。 但是并没有自动运行。手动输入命令运行一切正常，但是它就是不会随路由器启动而运行。

**Comment by mchome** [comment]
建议补全路径 例：python /usr/bin/drcom &

**Comment by Wsuika** [comment]
补全后依然没有自动连接

**Comment by ly0** [comment]
看一下dmesg

**Comment by Wsuika** [comment]
root@OpenWrt:~# dmesg
[    0.000000] Linux version 3.18.20 (buildbot@builder1) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r46450) ) #1 Fri Sep 4 21:55:57 CEST 2015
[    0.000000] MyLoader: sysp=07e72918, boardp=37075c4b, parts=9854d1f2
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019374 (MIPS 24Kc)
[    0.000000] SoC: Atheros AR9330 rev 1
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 04000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x00000000-0x03ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00000000-0x03ffffff]
[    0.000000] Initmem setup node 0 [mem 0x00000000-0x03ffffff]
[    0.000000] On node 0 totalpages: 16384
[    0.000000] free_area_init_node: node 0, pgdat 8034e2b0, node_mem_map 81000000
[    0.000000]   Normal zone: 128 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 16384 pages, LIFO batch:3
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
[    0.000000] Kernel command line:  board=GL-INET  console=ttyATH0,115200 rootfstype=squashfs,jffs2 noinitrd
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 61004K/65536K available (2621K kernel code, 129K rwdata, 344K rodata, 224K init, 194K bss, 4532K reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:51
[    0.000000] Clocks: CPU:400.000MHz, DDR:400.000MHz, AHB:200.000MHz, Ref:25.000MHz
[    0.000000] Calibrating delay loop... 265.42 BogoMIPS (lpj=1327104)
[    0.080000] pid_max: default: 32768 minimum: 301
[    0.080000] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.090000] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.100000] NET: Registered protocol family 16
[    0.100000] MIPS: machine is GL-CONNECT INET v1
[    0.590000] Switched to clocksource MIPS
[    0.590000] NET: Registered protocol family 2
[    0.600000] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.600000] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.600000] TCP: Hash tables configured (established 1024 bind 1024)
[    0.610000] TCP: reno registered
[    0.610000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.620000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.630000] NET: Registered protocol family 1
[    0.630000] PCI: CLS 0 bytes, default 32
[    0.630000] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.660000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.660000] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.670000] msgmni has been set to 119
[    0.680000] io scheduler noop registered
[    0.680000] io scheduler deadline registered (default)
[    0.680000] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.690000] ar933x-uart: ttyATH0 at MMIO 0x18020000 (irq = 11, base_baud = 1562500) is a AR933X UART
[    0.700000] console [ttyATH0] enabled
[    0.710000] bootconsole [early0] disabled
[    0.720000] m25p80 spi0.0: found w25q128, expected m25p80
[    0.720000] m25p80 spi0.0: w25q128 (16384 Kbytes)
[    0.730000] 5 tp-link partitions found on MTD device spi0.0
[    0.730000] Creating 5 MTD partitions on "spi0.0":
[    0.740000] 0x000000000000-0x000000020000 : "u-boot"
[    0.740000] 0x000000020000-0x00000012c530 : "kernel"
[    0.750000] 0x00000012c530-0x000000ff0000 : "rootfs"
[    0.750000] mtd: device 2 (rootfs) set to be root filesystem
[    0.760000] 1 squashfs-split partitions found on MTD device rootfs
[    0.760000] 0x000000360000-0x000000ff0000 : "rootfs_data"
[    0.770000] 0x000000ff0000-0x000001000000 : "art"
[    0.770000] 0x000000020000-0x000000ff0000 : "firmware"
[    0.800000] libphy: ag71xx_mdio: probed
[    1.390000] ag71xx ag71xx.0: connected to PHY at ag71xx-mdio.1:04 [uid=004dd041, driver=Generic PHY]
[    1.400000] eth0: Atheros AG71xx at 0xb9000000, irq 4, mode:MII
[    1.990000] ag71xx-mdio.1: Found an AR7240/AR9330 built-in switch
[    2.020000] eth1: Atheros AG71xx at 0xba000000, irq 5, mode:GMII
[    2.020000] TCP: cubic registered
[    2.030000] NET: Registered protocol family 17
[    2.030000] bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.
[    2.040000] Bridge firewalling registered
[    2.050000] 8021q: 802.1Q VLAN Support v1.8
[    2.060000] VFS: Mounted root (squashfs filesystem) readonly on device 31:2.
[    2.070000] Freeing unused kernel memory: 224K (80368000 - 803a0000)
[    3.290000] init: Console is alive
[    3.290000] init: - watchdog -
[    4.740000] usbcore: registered new interface driver usbfs
[    4.750000] usbcore: registered new interface driver hub
[    4.750000] usbcore: registered new device driver usb
[    4.760000] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.770000] ehci-platform: EHCI generic platform driver
[    4.770000] ehci-platform ehci-platform: EHCI Host Controller
[    4.780000] ehci-platform ehci-platform: new USB bus registered, assigned bus number 1
[    4.790000] ehci-platform ehci-platform: irq 3, io mem 0x1b000000
[    4.810000] ehci-platform ehci-platform: USB 2.0 started, EHCI 1.00
[    4.810000] hub 1-0:1.0: USB hub found
[    4.810000] hub 1-0:1.0: 1 port detected
[    5.350000] init: - preinit -
[    6.090000] random: procd urandom read with 9 bits of entropy available
[    9.460000] jffs2: notice: (337) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
[    9.480000] mount_root: switching to jffs2 overlay
[    9.560000] procd: - early -
[    9.560000] procd: - watchdog -
[   10.360000] procd: - ubus -
[   11.370000] procd: - init -
[   12.550000] NET: Registered protocol family 10
[   12.560000] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   12.600000] Loading modules backported from Linux version master-2015-03-09-0-g141f155
[   12.600000] Backport generated by backports.git backports-20150129-0-gdd4a670
[   12.610000] ip_tables: (C) 2000-2006 Netfilter Core Team
[   12.630000] nf_conntrack version 0.5.0 (956 buckets, 3824 max)
[   12.680000] xt_time: kernel timezone is -0000
[   12.710000] cfg80211: Calling CRDA to update world regulatory domain
[   12.740000] cfg80211: World regulatory domain updated:
[   12.740000] cfg80211:  DFS Master region: unset
[   12.740000] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[   12.750000] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[   12.760000] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[   12.770000] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm), (N/A)
[   12.780000] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
[   12.790000] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
[   12.800000] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm), (0 s)
[   12.800000] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
[   12.810000] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm), (N/A)
[   12.880000] PPP generic driver version 2.4.2
[   12.890000] NET: Registered protocol family 24
[   12.960000] ath: EEPROM regdomain: 0x0
[   12.960000] ath: EEPROM indicates default country code should be used
[   12.960000] ath: doing EEPROM country->regdmn map search
[   12.960000] ath: country maps to regdmn code: 0x3a
[   12.960000] ath: Country alpha2 being used: US
[   12.960000] ath: Regpair used: 0x3a
[   12.970000] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[   12.980000] ieee80211 phy0: Atheros AR9330 Rev:1 mem=0xb8100000, irq=2
[   12.980000] cfg80211: Calling CRDA for country: US
[   13.000000] cfg80211: Regulatory domain changed to country: US
[   13.000000] cfg80211:  DFS Master region: FCC
[   13.010000] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[   13.020000] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 3000 mBm), (N/A)
[   13.020000] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 1700 mBm), (N/A)
[   13.030000] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2300 mBm), (0 s)
[   13.040000] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 3000 mBm), (N/A)
[   13.050000] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 4000 mBm), (N/A)
[   24.750000] device eth1 entered promiscuous mode
[   24.750000] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   24.810000] device eth0 entered promiscuous mode
[   24.810000] br-wan: port 1(eth0) entered forwarding state
[   24.820000] br-wan: port 1(eth0) entered forwarding state
[   26.200000] br-wan: port 1(eth0) entered disabled state
[   27.890000] eth0: link up (100Mbps/Half duplex)
[   27.890000] br-wan: port 1(eth0) entered forwarding state
[   27.900000] br-wan: port 1(eth0) entered forwarding state
[   28.120000] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   28.160000] device wlan0 entered promiscuous mode
[   28.160000] br-lan: port 2(wlan0) entered forwarding state
[   28.170000] br-lan: port 2(wlan0) entered forwarding state
[   28.180000] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   28.200000] br-lan: port 2(wlan0) entered disabled state
[   29.900000] br-wan: port 1(eth0) entered forwarding state
[   30.560000] br-lan: port 2(wlan0) entered forwarding state
[   30.560000] br-lan: port 2(wlan0) entered forwarding state
[   30.570000] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   32.560000] br-lan: port 2(wlan0) entered forwarding state
[   43.120000] random: nonblocking pool is initialized

**Comment by mchome** [comment]
在python /usr/bin/drcom 前面加上sleep 10延长10秒试下；或者写hotplug，让接口up后执行。

**Comment by Wsuika** [comment]
解决了，现学现卖写的hotplug XD

```
#!/bin/sh
# /etc/hotplug.d/iface/99-drcom

if [ "$ACTION" = ifup ]; then 
    if [ "${INTERFACE}" = "wan" ]; then
        sleep 10 && drcom
    fi
fi
```

另外如果要是用迅雷下载东西，过一段时间会断？？

**Comment by Wsuika** [comment]
在win下运行测试脚本并不会断，路由器自动运行时候如果开迅雷大概1分钟左右就会断，用PuTTY输入drcom大概能坚持半小时，然后看就只能看到send看不到recv，好像如果看视频或者开下载都会断。

**Comment by ly0** [comment]
这个应该和脚本无关，是你路由器性能上有问题，注意python本身会吃掉一坨RAM，如果在wifi环境下下载会吃掉一大坨，可能会挂掉或者不稳定。

**Comment by jiangjianrui11** [comment]
我也是出现这种，不随路由器启动的情况，楼上说的那小段代码应该放到哪呢？求救~

**Comment by jiangjianrui11** [comment]
另，在这里表示一下对作者的衷心感谢@ly0

**Comment by Wsuika** [comment]
/etc/hotplug.d/iface/ 然后文件起名为 99-drcom

**Comment by jiangjianrui11** [comment]
搞定，本来好像不行，根据网上的改动了一点就行了 ，感谢！
#!/bin/sh
# /etc/hotplug.d/iface/99-drcom

if [ "$ACTION" = ifup ]; then 
    if [ "$INTERFACE" = wan ]; then
       python /usr/bin/drcom
    fi
fi
