### ISSUE TITLE
Luci(D)版本在5.2.0下无法使用 

### ISSUE THREAD

**Issue by TonyLee61** [drcoms/drcom-generic#200]
Sun Apr  9 10:11:57 2017 daemon.err uhttpd[2253]: sh: /etc/init.d/drcom: line 4: 
: not found
Sun Apr  9 10:11:57 2017 daemon.err uhttpd[2253]: sh: /etc/init.d/drcom: line 6: {
: not found
Sun Apr  9 10:11:57 2017 daemon.err uhttpd[2253]: sh: local: line 7: enable
: bad variable name
Sun Apr  9 10:11:57 2017 daemon.err uhttpd[2253]: sh: /etc/init.d/drcom: line 8: config_get_bool: not found
Sun Apr  9 10:11:57 2017 daemon.err uhttpd[2253]: sh: /etc/init.d/drcom: line 40: syntax error: unexpected end of file (expecting "then")

**Comment by mchome** [comment]
luci非必须

**Comment by mchome** [comment]
luci已没人维护，所有luci问题都不予回答。
