### ISSUE TITLE
5.2D版，PC上运行latest-wired.py提示socket.timeout: timed out

### ISSUE THREAD

**Issue by MakotoKo** [drcoms/drcom-generic#201]
出于隐私已隐藏username和password，实际设置无异常
c:\Python27>python latest-wired.py
auth svr: 202.202.0.163
username: 
password: 
mac: 0x7845c4c36697
bind ip: 0.0.0.0
[challenge] recv 0202364c5a12010000000100f303e8f000000000ac180a7cf000a8a20000294d4d3f00000000d802000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202364c5a12010000000100f303e8f000000000ac180a7cf000a8a20000294d4d3f00000000d802000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001cddbaa4c82ee2643489d6be457a2d48e03230313333383634000000000000000000000000000000000000000000000000000000002004a5ff600b48751b1f594c81fad6c4f494b1742b26e14c01ac180a7c000000000000000000000000fdcd44bd8ba1fdcc010000000047494c4947494c494559450000000000000000000000000000000000000000003d80c044caca0232000000000000000000000000940000000500000001000000280a0000020000004e4f54453700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000025000006671cecefc09e020cf01866d500007845c4c366970000e913
[login] send 0301001cddbaa4c82ee2643489d6be457a2d48e03230313333383634000000000000000000000000000000000000000000000000000000002004a5ff600b48751b1f594c81fad6c4f494b1742b26e14c01ac180a7c000000000000000000000000fdcd44bd8ba1fdcc010000000047494c4947494c494559450000000000000000000000000000000000000000003d80c044caca0232000000000000000000000000940000000500000001000000280a0000020000004e4f54453700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000025000006671cecefc09e020cf01866d500007845c4c366970000e913
[login] recv 0400000500cc4300005fcd2604ffffffffff00000000004472636fcaca00a35dc3ac180a7c0192b00500030110
[login] packet sent.
[login] loged in
[login] login sent
package_tail 4472636fcaca00a35dc3ac180a7c0192
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send ffddbaa4c82ee2643489d6be457a2d48e00000004472636fcaca00a35dc3ac180a7c01924c1300000000
Traceback (most recent call last):
  File "latest-wired.py", line 477, in <module>
    main()
  File "latest-wired.py", line 473, in main
    keep_alive1(SALT,package_tail,password,server)
  File "latest-wired.py", line 434, in keep_alive1
    data, address = s.recvfrom(1024)
socket.timeout: timed out

**Comment by ly0** [comment]
@MakotoKo 注视掉keep_alive1的调用处 试试？有的地方不需要keepalive1

**Comment by MakotoKo** [comment]
确实是在main里面注释掉这一段就好了，十分感谢
