### ISSUE TITLE
5.2.1(p)版路由器PPPoE拨号问题

### ISSUE THREAD

**Issue by heng19970427** [drcoms/drcom-generic#202]
心跳包的问题已经没问题了。
在PC上抓包发现账号部分前面有 ”\r\n“ 。
那么路由器上的ppp.sh应该怎么修改呢？

**Comment by heng19970427** [comment]
根据你的那个shell更改后还是无法登陆

**Comment by mchome** [comment]
@heng19970427 这个你只能自己解决了

**Comment by fububanzangly** [comment]
修改 /lib/netifd/proto/ppp.sh
![image](https://cloud.githubusercontent.com/assets/7714693/25032828/33c8aec8-210a-11e7-866e-945aa3c4df70.png)
增加\r\n

**Comment by heng19970427** [comment]
感谢 fububanzangly 的回答。
不过你的这种我没有测试，应该也可行。
我在ppp.sh用echo -e 打开转义后，拨号时账号前直接加上\r\n就可以了。
井冈山大学成功。

路由：斐讯K1 K2
固件：PandoraBox 17.01
心跳：用的 mentoGDUT
拨号 直接用wan口拨号不成功，添加接口拨号。并且按照wiki内的解决方案，开启username的转义。拨号时加上\r\n就可以了。
