### ISSUE TITLE
关于掉线无法重连的处理

### ISSUE THREAD

**Issue by ListenerRi** [drcoms/drcom-generic#203]
在`latest-wired.py`文件中的`keep_alive2()`函数的最后一句:
https://github.com/drcoms/drcom-generic/blob/master/latest-wired.py#L251
**当捕捉到while循环中的错误时应该`break`才对** 

比如掉线后在`keep_alive2()`循环中执行`keep_alive1()`函数, 这个函数没有捕捉错误的语句块,
其中的`s.recv`方法出现错误后回到`keep_alive2()`函数, 由于没有处理这个错误, 重新循环, 死循环

而且如果是`pass`, 那么`main()`函数中的while循环根本没有意义, 
因为程序会一直在`keep_alive2()`函数中循环

`pass`改为`break`, 捕捉到错误, 跳出`keep_alive2()`函数, 回到`main()`中重新开始`login`

**Comment by mchome** [comment]
pull request welcome
