### ISSUE TITLE
求大神看看怎么老是报错的？

### ISSUE THREAD

**Issue by yzliusha** [drcoms/drcom-generic#210]
报错如下：
Traceback (most recent call last):
  File "drcom_for_dlnu_520.py", line 62, in <module>
    s.bind((bind_ip, 61440))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10049]
捉包文件、客户端等都上传了：
http://pan.baidu.com/s/1sloBatn

**Comment by mchome** [comment]
用 [latest-wired.py](https://github.com/drcoms/drcom-generic/raw/master/latest-wired.py).

**Comment by yzliusha** [comment]
又错线了一下错误：
Traceback (most recent call last):
  File "latest-wired.py", line 71, in <module>
    s.bind((bind_ip, 61440))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10048] 通常每个套接字地址(协议/网络地址/端口)

**Comment by yzliusha** [comment]
@mchome

**Comment by mchome** [comment]
@yzliusha 关掉原版客户端

**Comment by yzliusha** [comment]
@mchome 
auth svr: 58.63.128.210
username: 201510224618@ZHKU1.GZ
password: 1026253X
mac: 0x74e6e253d7a8
bind ip: 0.0.0.0
[challenge] timeout, retrying...
[challenge] timeout, retrying...
[challenge] timeout, retrying...
[challenge] timeout, retrying...
[challenge] timeout, retrying...
[challenge] timeout, retrying...
[challenge] timeout, retrying...
[challenge] timeout, retrying...
[challenge] timeout, retrying...
[challenge] timeout, retrying...
[challenge] timeout, retrying...
一直都是这样的，没有成功，是哪里出现问题了吗？

**Comment by mchome** [comment]
@yzliusha 检查下网线，网口，看看能不能ping通 58.63.128.210

**Comment by yzliusha** [comment]
@mchome 登录上才能ping通，没有登录上就ping不通

**Comment by yzliusha** [comment]
ping 58.63.128.210

正在 Ping 58.63.128.210 具有 32 字节的数据:
PING：传输失败。常见故障。
PING：传输失败。常见故障。
PING：传输失败。常见故障。
PING：传输失败。常见故障。

**Comment by mchome** [comment]
@yzliusha 你是x版吧，需要先通过802.1x认证，用mentohust试下

**Comment by yzliusha** [comment]
@mchome mentohust怎使用？不是很懂

**Comment by mchome** [comment]
@yzliusha 我也没用过，自己搜索吧

**Comment by yzliusha** [comment]
[keep_alive2] recv 072f28000b021d002f12000000000000f7c05d180000000000000000000000000000000000000000
[keep_alive2] send 48 073028000b031d002f12000000000000f7c05d1800000000000000000a321a4a0000000000000000
[keep_alive2] error raise Exception to main()
[main] error something was wrong in keep_alives, do everything again
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 020278ef5c59770000000100f203e8f0000000000a321a4af00000800000c737f3a2000000001d00000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020278ef5c59770000000100f203e8f0000000000a321a4af00000800000c737f3a2000000001d00000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100296a1d3a6abf629c31cd9b14d3c1233939323031353130323234363138405a484b55312e475a00000000000000000000000000000020051efbd83968cacd864876e4e805c5c4b238e932e5deff010a321a4a000000000000000000000000c798453134d15e5901000000004452434f4d4655434b4552000000000000000000000000000000000000000000ca6080560a321afe000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400020cf0c367ef000074e6e253d7a80000e913
[login] send 030100296a1d3a6abf629c31cd9b14d3c1233939323031353130323234363138405a484b55312e475a00000000000000000000000000000020051efbd83968cacd864876e4e805c5c4b238e932e5deff010a321a4a000000000000000000000000c798453134d15e5901000000004452434f4d4655434b4552000000000000000000000000000000000000000000ca6080560a321afe000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400020cf0c367ef000074e6e253d7a80000e913
Traceback (most recent call last):
  File "latest-wired.py", line 489, in <module>
    main()
  File "latest-wired.py", line 472, in main
    package_tail = login(username, password, server)
  File "latest-wired.py", line 383, in login
    data, address = s.recvfrom(1024)
socket.timeout: timed out
@mchome

**Comment by yzliusha** [comment]
我用其他方法通过802.1x认证，但是使用latest-wried.py后，使用一段时间后就会出现以上错误！

**Comment by yzliusha** [comment]
@mchome

**Comment by mchome** [comment]
用新的脚本来一遍

**Comment by yzliusha** [comment]
上面latest-wired.py不是最新版吗？

**Comment by yzliusha** [comment]
@mchome

**Comment by yzliusha** [comment]
@mchome
