### ISSUE TITLE
用一段时间大概几分钟就断开连接 然后又重连 然后又几分钟反复这样掉线重连

### ISSUE THREAD

**Issue by GeeJoe** [drcoms/drcom-generic#218]
用一段时间大概几分钟就断开连接 然后又重连 然后又几分钟反复这样掉线重连
我用的是极路由3
这是我后台执行pppoe.sh之后返回的日志
root@Hiwifi:/tmp/drcom_shell# ./pppoe.sh
Test connectivity to auth server
PING 10.0.3.2 (10.0.3.2): 56 data bytes
64 bytes from 10.0.3.2: seq=0 ttl=61 time=4.340 ms

--- 10.0.3.2 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 4.340/4.340/4.340 ms
OK
python: can't open file '/usr/bin/drcom': [Errno 2] No such file or directory
root@Hiwifi:/tmp/drcom_shell# a

**Comment by hongwei666** [comment]
python: can't open file '/usr/bin/drcom': [Errno 2] No such file or directory
这句话的意思是在'/usr/bin/drcom'这个目录下面没有找到，名字是drcom的文件

**Comment by JoeLeeDreamer** [comment]
那该如何解决呢

**Comment by hongwei666** [comment]
没有的话，注意文件格式 重新放进去就好了
