### ISSUE TITLE
在电脑上能用放入路由器后就用不了了，以下是错误信息，请帮忙看一下是哪里的问题。

### ISSUE THREAD

**Issue by YUMKP** [drcoms/drcom-generic#219]
auth svr: 210.43.0.195
username: **********
password: *******
mac: 0x1c1b0d0e37e2
bind ip: 0.0.0.0
[challenge] timeout, retrying...
[challenge] recv 02021fef71031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02021fef71031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010020be661344d190fdd7ad95c0ee523329643136313431393034303132320000000000000000000000000000000000000000000000002003a27d1e4ae672af7f4da32ed63d49e57cd7be5ac1648a01ac1169230000000000000000000000008b8ec66d130cbcde010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c2037cb6300001c1b0d0e37e20000e913
[login] send 03010020be661344d190fdd7ad95c0ee523329643136313431393034303132320000000000000000000000000000000000000000000000002003a27d1e4ae672af7f4da32ed63d49e57cd7be5ac1648a01ac1169230000000000000000000000008b8ec66d130cbcde010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c2037cb6300001c1b0d0e37e20000e913
[login] packet sent.
[login] recv 0400000500d43600006b8c5304ffffffffff00000000004472636fd22b00c308c0ac11699c01e3b005090001000000b7aa377affffffff00000000d22b0000fffff00000000000d3545000fffff00000000000dac6c000fffff00000000000b7aa3000fffff00000000000d22b0000fffff00000000000ac100000ffff000000000000c0a80000ffff00000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636fd22b00c308c0ac11699c01e3
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send ffbe661344d190fdd7ad95c0ee523329640000004472636fd22b00c308c0ac11699c01e3ef0500000000
[keep_alive1] error raise Exception to main() or keep_alive2()
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "drcom", line 487, in main
    keep_alive1(SALT,package_tail,password,server)
  File "drcom", line 444, in keep_alive1
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 0202e7ef77031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202e7ef77031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010020d751db2315110a86a22385df23a97e603136313431393034303132320000000000000000000000000000000000000000000000002003cb4ad62d22f36d7c060d81f0bc438efa01de88533bb201ac1169230000000000000000000000004a6165e154093e44010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c50f559b600001c1b0d0e37e20000e913
[login] send 03010020d751db2315110a86a22385df23a97e603136313431393034303132320000000000000000000000000000000000000000000000002003cb4ad62d22f36d7c060d81f0bc438efa01de88533bb201ac1169230000000000000000000000004a6165e154093e44010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c50f559b600001c1b0d0e37e20000e913
[login] packet sent.
timed out
[login] recv timeout.
[challenge] recv 0202e7ef77031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202e7ef77031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010020d751db2315110a86a22385df23a97e603136313431393034303132320000000000000000000000000000000000000000000000002003cb4ad62d22f36d7c060d81f0bc438efa01de88533bb201ac1169230000000000000000000000004a6165e154093e44010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c50f559b600001c1b0d0e37e20000e913
[login] send 03010020d751db2315110a86a22385df23a97e603136313431393034303132320000000000000000000000000000000000000000000000002003cb4ad62d22f36d7c060d81f0bc438efa01de88533bb201ac1169230000000000000000000000004a6165e154093e44010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c50f559b600001c1b0d0e37e20000e913
[login] packet sent.
timed out
[login] recv timeout.
[challenge] recv 0202d9ef7b031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202d9ef7b031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301002032686591e6b56f47fa023d3c7282bf7d31363134313930343031323200000000000000000000000000000000000000000000000020032e73689fd157569fcc027dfdd39184c3ad99a95c4f9c01ac1169230000000000000000000000005ddc2c4294cce8ac010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c30e752c200001c1b0d0e37e20000e913
[login] send 0301002032686591e6b56f47fa023d3c7282bf7d31363134313930343031323200000000000000000000000000000000000000000000000020032e73689fd157569fcc027dfdd39184c3ad99a95c4f9c01ac1169230000000000000000000000005ddc2c4294cce8ac010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c30e752c200001c1b0d0e37e20000e913
[login] packet sent.
[login] recv 0400000500d53600006b8c5304ffffffffff00000000004472636fd22b00c318c0ac11699c01efb005090001000000b7aa377affffffff00000000d22b0000fffff00000000000d3545000fffff00000000000dac6c000fffff00000000000b7aa3000fffff00000000000d22b0000fffff00000000000ac100000ffff000000000000c0a80000ffff00000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636fd22b00c318c0ac11699c01ef
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff32686591e6b56f47fa023d3c7282bf7d0000004472636fd22b00c318c0ac11699c01efef1700000000
[keep-alive1] recv 070110000600ef175a87f901ac11699ca8ac00004fe416c100000000dc020000030000000000000000000000d53600006b8c5304ffffffffffffffffffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "drcom", line 488, in main
    keep_alive2(SALT,package_tail,password,server)
  File "drcom", line 178, in keep_alive2
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] timeout, retrying...
[challenge] recv 02020df086031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02020df086031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100207e04b772d69e4a20eb4dfb604130331f3136313431393034303132320000000000000000000000000000000000000000000000002003621fba7ce17ce61ef3acb3363fb35ad58f1856350b5201ac11692300000000000000000000000094f4bf0801a7a094010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c80c1342e00001c1b0d0e37e20000e913
[login] send 030100207e04b772d69e4a20eb4dfb604130331f3136313431393034303132320000000000000000000000000000000000000000000000002003621fba7ce17ce61ef3acb3363fb35ad58f1856350b5201ac11692300000000000000000000000094f4bf0801a7a094010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c80c1342e00001c1b0d0e37e20000e913
[login] packet sent.
[login] recv 0400000500d63600006b8c5304ffffffffff00000000004472636fd22b00c32fc0ac11699c0102b005090001000000b7aa377affffffff00000000d22b0000fffff00000000000d3545000fffff00000000000dac6c000fffff00000000000b7aa3000fffff00000000000d22b0000fffff00000000000ac100000ffff000000000000c0a80000ffff00000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636fd22b00c32fc0ac11699c0102
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff7e04b772d69e4a20eb4dfb604130331f0000004472636fd22b00c32fc0ac11699c0102ef2600000000
[keep_alive1] error raise Exception to main() or keep_alive2()
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "drcom", line 487, in main
    keep_alive1(SALT,package_tail,password,server)
  File "drcom", line 444, in keep_alive1
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 020223f08f031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020223f08f031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010020933a341adf7059aea9335d3740b3e99931363134313930343031323200000000000000000000000000000000000000000000000020038f213914e892578e4cdbcc69d2e6297bd41f1edd84de01ac1169230000000000000000000000003d7e730e1a367da4010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c5049cb9500001c1b0d0e37e20000e913
[login] send 03010020933a341adf7059aea9335d3740b3e99931363134313930343031323200000000000000000000000000000000000000000000000020038f213914e892578e4cdbcc69d2e6297bd41f1edd84de01ac1169230000000000000000000000003d7e730e1a367da4010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c5049cb9500001c1b0d0e37e20000e913
[login] packet sent.
[login] recv 0400000500d73600006b8c5304ffffffffff00000000004472636fd22b00c338c0ac11699c010ab005090001000000b7aa377affffffff00000000d22b0000fffff00000000000d3545000fffff00000000000dac6c000fffff00000000000b7aa3000fffff00000000000d22b0000fffff00000000000ac100000ffff000000000000c0a80000ffff00000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636fd22b00c338c0ac11699c010a
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff933a341adf7059aea9335d3740b3e9990000004472636fd22b00c338c0ac11699c010aef3200000000
[keep-alive1] recv 070110000600ef326888f901ac11699ca8ac00004fe416c100000000dc020000030000000000000000000000d73600006b8c5304ffffffffffffffffffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070010010b06dc022f12000000000000a8ac00004fe416c100000000dc0200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000100100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a24000000000000007cc5835a38a4ed0938a4ed0938a4ed096187fe093aa4ed0943b8e10939a4ed09bbacb00932a4ed09bbb8e3093aa4ed0957bbe60939a4ed0957bbe7093da4ed0957bbe9093aa4ed0938a4ec0982a4ed090e82e9093ba4ed090e82e60930a4ed09ffa2eb0939a4ed09c784e9093ba4ed09
[keep-alive2] recv file, resending..
[keep-alive2] send2 070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2 070128000b02dc022f120000000000006888f9010000000000000000000000000000000000000000
[keep-alive2] send3 070228000b03dc022f120000000000006888f9010000000000000000ac1169230000000000000000
[keep-alive2] recv3 070228000b04dc022f120000000000006888f9010000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive1] send ff933a341adf7059aea9335d3740b3e9990000004472636fd22b00c338c0ac11699c010aef4600000000
[keep-alive1] recv 070110000600ef462f89f901ac11699ca8ac00004fe416c100000000dc020000170000000500000003000000d73600006b8c5304ffffffffffffffffffffffff
[keep_alive2] send 3 070328000b01dc022f120000000000006888f9010000000000000000000000000000000000000000
[keep_alive2] error raise Exception to main()
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "drcom", line 488, in main
    keep_alive2(SALT,package_tail,password,server)
  File "drcom", line 231, in keep_alive2
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 020245f0a0031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020245f0a0031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100209c16a96b27eb80ed87f69af1aa919edb3136313431393034303132320000000000000000000000000000000000000000000000002003800da46510096a2e201320ab6d08ac9f1f5cfb6d6c1a01ac11692300000000000000000000000066b1e82a17ca8ba8010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c8048e63f00001c1b0d0e37e20000e913
[login] send 030100209c16a96b27eb80ed87f69af1aa919edb3136313431393034303132320000000000000000000000000000000000000000000000002003800da46510096a2e201320ab6d08ac9f1f5cfb6d6c1a01ac11692300000000000000000000000066b1e82a17ca8ba8010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c8048e63f00001c1b0d0e37e20000e913
[login] packet sent.
timed out
[login] recv timeout.
[challenge] recv 020220f0a0031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020220f0a0031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100209c16a96b27eb80ed87f69af1aa919edb3136313431393034303132320000000000000000000000000000000000000000000000002003800da46510096a2e201320ab6d08ac9f1f5cfb6d6c1a01ac11692300000000000000000000000066b1e82a17ca8ba8010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c8048e63f00001c1b0d0e37e20000e913
[login] send 030100209c16a96b27eb80ed87f69af1aa919edb3136313431393034303132320000000000000000000000000000000000000000000000002003800da46510096a2e201320ab6d08ac9f1f5cfb6d6c1a01ac11692300000000000000000000000066b1e82a17ca8ba8010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c8048e63f00001c1b0d0e37e20000e913
[login] packet sent.
timed out
[login] recv timeout.
[challenge] recv 0202f6efa2031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202f6efa2031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100202671d5f9466c088d8068a7d12f6a734331363134313930343031323200000000000000000000000000000000000000000000000020033a6ad8f7718efbafe6aca8a8e4b3b9a6018075499cf601ac11692300000000000000000000000031d425eac9ea7893010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020cc0eaaff000001c1b0d0e37e20000e913
[login] send 030100202671d5f9466c088d8068a7d12f6a734331363134313930343031323200000000000000000000000000000000000000000000000020033a6ad8f7718efbafe6aca8a8e4b3b9a6018075499cf601ac11692300000000000000000000000031d425eac9ea7893010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020cc0eaaff000001c1b0d0e37e20000e913
[login] packet sent.
timed out
[login] recv timeout.
[challenge] timeout, retrying...
[challenge] recv 020278efa4031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020278efa4031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010020f591d167652ca4402726b8be78c8a12f3136313431393034303132320000000000000000000000000000000000000000000000002003e98adc6952ce79c2b31a5105727f09d4b7a877c6d2c701ac116923000000000000000000000000b2333e90611e6aa5010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c708aa60500001c1b0d0e37e20000e913
[login] send 03010020f591d167652ca4402726b8be78c8a12f3136313431393034303132320000000000000000000000000000000000000000000000002003e98adc6952ce79c2b31a5105727f09d4b7a877c6d2c701ac116923000000000000000000000000b2333e90611e6aa5010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c708aa60500001c1b0d0e37e20000e913
[login] packet sent.
timed out
[login] recv timeout.
[challenge] recv 020250f0a4031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020250f0a4031f0000000100f303e8f000000000ac11699c0400a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010020f591d167652ca4402726b8be78c8a12f3136313431393034303132320000000000000000000000000000000000000000000000002003e98adc6952ce79c2b31a5105727f09d4b7a877c6d2c701ac116923000000000000000000000000b2333e90611e6aa5010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c708aa60500001c1b0d0e37e20000e913
[login] send 03010020f591d167652ca4402726b8be78c8a12f3136313431393034303132320000000000000000000000000000000000000000000000002003e98adc6952ce79c2b31a5105727f09d4b7a877c6d2c701ac116923000000000000000000000000b2333e90611e6aa5010000000047494c4947494c49455945000000000000000000000000000000000000000000d22b0008ac1169fe000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002800020c708aa60500001c1b0d0e37e20000e913
[login] packet sent.
timed out
[login] recv timeout.
[login] recv timeout exception occured 5 times.

**Comment by ly0** [comment]
路由器的问题 应该

**Comment by YUMKP** [comment]
谢谢
