### ISSUE TITLE
在线配置生成不到正确的ip

### ISSUE THREAD

**Issue by YingkitTse** [drcoms/drcom-generic#22]
使用在线的配置生成器，搞出来的东西一直不正常的样子，
server是空的，username一长串乱码，mac也对不上……

盘.百度.com/s/1pJBu21P
这是抓到的包

嗯，我用的是x版

**Comment by mchome** [comment]
诶，你的包有点像P版，试下802.1X登陆加P版的心跳吧

**Comment by YingkitTse** [comment]
搞定啦谢谢~
最后我还是选择了Shindo的版本，对照着你的配置提示，看着他的代码，改好了
原来我用的是U64版本，跟你写的U62不一样，配置难怪出不来

后期我看能不能贡献点U64的资料上来>_<
