### ISSUE TITLE
OpenWrt:运行pppoe.sh报错/usr/bin/pppoe.sh: exec: line 17: python: not found

### ISSUE THREAD

**Issue by zjfresh** [drcoms/drcom-generic#221]
这个是斐讯K2的，16年11、12月份刷的，当时就是一分半掉线一次。

今天17年5月24刷了个极路由，用的也是当初的脚本，结果问题依然出现。

下了一份新版的大学城drcom_shell，对比之前的，发现是drcom这个文件不是新版的，换了后极路由立马不会掉线。然后我想，斐讯K2的难道也是这个问题？

然而依然出错。。。帮忙看看谢谢谢谢谢谢谢。

对了，好像是心跳脚本没有配置对，ps | grep python 没有Python drcom出现。可是我应该没有配置错啊？

**Comment by mchome** [comment]
`python: not found` 没有python环境
