### ISSUE TITLE
padavan怎么运行drcom？

### ISSUE THREAD

**Issue by madman43** [drcoms/drcom-generic#222]
目前只做了这个
找到文件 /tmp/ppp/options.wan0 ， 寻找并修改 user '\r\n你的帐号'，password '你的密码' 。
执行
killall pppd
/usr/sbin/pppd file /tmp/ppp/options.wan0 >/dev/null 2>&1 &
拨号后就有网了
并且无法执行这条命令
执行 cp /tmp/ppp/options.wan0 /jffs/options.wan0
提示

[RT-AC54U /home/root]# cp /tmp/ppp/options.wan0 /jffs/options.wan0
cp: can't create '/jffs/options.wan0': No such file or directory

**Comment by ly0** [comment]
```
拨号后就有网了
并且无法执行这条命令
```
没看懂这句话什么意思

**Comment by madman43** [comment]
我修改了tmp/ppp/options.wan0 里面的文件成这样后user '\r\n你的帐号'，password '你的密码' 
然后执行了
killall pppd
/usr/sbin/pppd file /tmp/ppp/options.wan0 >/dev/null 2>&1 &
这条命令就有网了
但是无法执行cp /tmp/ppp/options.wan0 /jffs/options.wan0这条命令，无法创建jffs文件夹

**Comment by ly0** [comment]
mkdir /jffs 试试

**Comment by madman43** [comment]
mkdir /jffs
提示只读文件系统
mkdir: can't create directory '/jffs': Read-only file system

**Comment by mchome** [comment]
找下你系统的自启脚本，把拨号过程粘上去，

**Comment by madman43** [comment]
拨号过程发到这？

**Comment by mchome** [comment]
就是让你把拨号过程粘在你的自启脚本上
