### ISSUE TITLE
按照教程配置开机前几分钟不掉线，然后一分半断一次

### ISSUE THREAD

**Issue by Tsahao** [drcoms/drcom-generic#225]
用 putty 运行 pppoe.sh 如图

Test connectivity to auth server
PING 10.0.3.2 (10.0.3.2): 56 data bytes
64 bytes from 10.0.3.2: seq=0 ttl=61 time=0.600 ms

--- 10.0.3.2 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.600/0.600/0.600 ms
OK
[*]  auth svr: 10.0.3.2
[*]  pppoe_flag: 6a
[*]  keep_alive2_flag: dc
Traceback (most recent call last):
  File "/usr/bin/drcom", line 336, in <module>
    main()
  File "/usr/bin/drcom", line 328, in main
    s = Socket(server)
  File "/usr/bin/drcom", line 101, in __init__
    self.s.bind(("0.0.0.0", 61440))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 125] Address already in use

**Comment by mchome** [comment]
@Tsahao socket.error: [Errno 125] Address already in use wiki都写着关了客户端才启动怎么老是有这些问题。。。

**Comment by ly0** [comment]
检查一下你的路由器上是不是已经运行过drcom了

**Comment by Tsahao** [comment]
电脑上的退出了，路由器就是第一次运行啊…然后现在是四十分钟之后就掉线

**Comment by zhenyadoc** [comment]
掉线了，你就在计划任务里搞一个检测脚本。掉线自动重启
