### ISSUE TITLE
掉线后自动重新拨号？

### ISSUE THREAD

**Issue by ichengzi** [drcoms/drcom-generic#23]
我们学校的校园网每天凌晨会关主路由器，导致掉线。早上重新开校园网后，drcom不会自动重新拨号，该如何让drcom自动重启啊？

**Comment by uzanief** [comment]
大致意思是 进程确定还在运行 但并没有重新拨号 是吗？

**Comment by ichengzi** [comment]
是啊，我目前都是通过重启路由器来解决的。`latest_wired.py`在哪个目录下？我目前用的是极路由，用的https://github.com/drcoms/drcom-HC5661-1s-patch 这个版本。

**Comment by uzanief** [comment]
我看了一下这个版本
脚本名应该还是`wired.py`，在路由器的/usr/bin/目录下。
默认`UNLIMITED_RETRY`是开着的呀

要么参考一下`readme.md`里的_Tricks_试试？

`Tricks
可以在 /etc/inittab 中加入 ::respawn:/usr/bin/dog_drcom 来防止 dog_drcom 挂掉。`

**Comment by ichengzi** [comment]
好的，谢谢啊，解决了
