### ISSUE TITLE
广工大学城，网络不稳定

### ISSUE THREAD

**Issue by gczhcm** [drcoms/drcom-generic#230]
执行pppoe.sh后的结果：
Test connectivity to auth server
PING 10.0.3.2 (10.0.3.2): 56 data bytes
64 bytes from 10.0.3.2: seq=0 ttl=61 time=0.640 ms

--- 10.0.3.2 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.640/0.640/0.640 ms
OK
[*]  auth svr: 10.0.3.2
[*]  pppoe_flag: 6a
[*]  keep_alive2_flag: dc
Traceback (most recent call last):
  File "/usr/bin/drcom", line 336, in <module>
    main()
  File "/usr/bin/drcom", line 328, in main
    s = Socket(server)
  File "/usr/bin/drcom", line 101, in __init__
    self.s.bind(("0.0.0.0", 61440))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 125] Address already in use
请问是什么问题？
邮箱：1774081830@qq.com

**Comment by ly0** [comment]
重复运行了认证脚本把

**Comment by gczhcm** [comment]
我是这方面的小白，请问应该怎么弄
