### ISSUE TITLE
/usr/bin/drcom 文件中的server  username  password 等参量的值单引号或双引号有区别吗

### ISSUE THREAD

**Issue by lweo** [drcoms/drcom-generic#231]
之前这些参量的值我都是用单引号，上不了网，用双引号括起来就能上网了；不过刚刚测试另外一个路由器，发现用单引号竟然也可以上网？然后跟这无关?

**Comment by mchome** [comment]
在python里面没所谓的，编程风格不同而已 
https://www.python.org/dev/peps/pep-0008/#string-quotes
