### ISSUE TITLE
Dr.com安装 出现问题

### ISSUE THREAD

**Issue by small-nerd** [drcoms/drcom-generic#232]
#Dr.com 安装不完全
![chrome_2017-07-16_16-01-21](https://user-images.githubusercontent.com/10249315/28246841-346ad168-6a56-11e7-9747-27fe66b4d3e6.png)

**Comment by mchome** [comment]
luci已经停止维护

**Comment by small-nerd** [comment]
这个问题能解决吗？？思路是什么？

**Comment by mchome** [comment]
lua语法错误，翻一下lua的文档改下估计能用

**Comment by small-nerd** [comment]
我看看。你这个不更新了吗？ 以前我搞过一次，成功了，现在你的文档和以前的不太一样了，我记不清楚当时的细节了。。。

**Comment by small-nerd** [comment]
只修改

> server = "10.151.0.254"
pppoe_flag = '\x2a'
keep_alive2_flag = '\xdc'

不上传 `drp.pcapng`  ， 这样可以的吧。

**Comment by small-nerd** [comment]
解决了。
把
> pppoe_flag = s:option(Value, "pppoe_flag", translate("pppoe_flag"))
keep_alive2_flag = s:option(Value, "keep_alive2_flag", translate("keep_alive2_flag"))

提到 

> return m

之前就好了

**Comment by ly0** [comment]
解决了就好 :)

**Comment by small-nerd** [comment]
博主，你能把 PPPoE-Dialer 发过来吗？ Github上下载不了。

2017-07-17 10:05 GMT+08:00 latyas(懒) <notifications@github.com>:
