### ISSUE TITLE
学校校园网更新后login fail

### ISSUE THREAD

**Issue by hyh19962008** [drcoms/drcom-generic#233]
用的是5.2.0 D版，之前一直正常使用，这两天学校更新了校园网，现在可以直接在web网页上认证登录了，继续用drcom客户端登录也没有问题，就是python脚本提示login fail了，重新抓包也不行

auth svr: 10.250.250.12
username: 2014021111@xnzf1
password: 012736
mac: 0x3065ecaad01d
bind ip: 0.0.0.0
[challenge] recv 020266561543000000000100f303e8f000000000ac12210df000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020266561543000000000100f303e8f000000000ac12210df000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010024dfe18585bdf7ebb07bda4ee990510be03230313430323131313140786e7a663100000000000000000000000000000000000000002002ef84692f6dea7c6d10e001a3749695ef01b9e3a17d2e01ac12210d00000000000000000000000031e940936214f666010000000047494c4947494c49455945000000000000000000000000000000000000000000caca50210a140164000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00020c909f20eb00003065ecaad01d0000e913
[login] send 03010024dfe18585bdf7ebb07bda4ee990510be03230313430323131313140786e7a663100000000000000000000000000000000000000002002ef84692f6dea7c6d10e001a3749695ef01b9e3a17d2e01ac12210d00000000000000000000000031e940936214f666010000000047494c4947494c49455945000000000000000000000000000000000000000000caca50210a140164000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00020c909f20eb00003065ecaad01d0000e913
[login] packet sent.
[login] recv 020266561543000000000100f303e8f000000000ac12210df000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[login] login failed.
[challenge] recv 0400000500c401000006bc090000000000ff00000000004472636f0afafa0cb703ac12210d0143b00500030100
[DEBUG] challenge:
0400000500c401000006bc090000000000ff00000000004472636f0afafa0cb703ac12210d0143b00500030100

**Comment by ly0** [comment]
你好,看上去应该登陆成功了(出现了04开头的包) 但是看上去这个流程不大对(01->02->03->02->04), 用的是哪个脚本?

**Comment by hyh19962008** [comment]
latest-wired.py

**Comment by mchome** [comment]
把抓包丢上来看看

**Comment by hyh19962008** [comment]
[3.pcapng.zip](https://github.com/drcoms/drcom-generic/files/1171938/3.pcapng.zip)

7z压缩的，可能需要改一下后缀

**Comment by mchome** [comment]
不知为何出现很多重复的数据包

**Comment by hyh19962008** [comment]
抓包的时间比较长……
