### ISSUE TITLE
吉大定制版，newclient.py，一直卡在timeout，retreying

### ISSUE THREAD

**Issue by Gwzlchn** [drcoms/drcom-generic#237]
我在openwrt中测试时一直卡在timeout，脚本中的nic_name='eth0.2'，eth0.2 的确给的静态ip和克隆mac，有什么没注意到的地方吗？

**Comment by ly0** [comment]
@Gwzlchn traceroute一下看看是不是走的eth0.2

**Comment by Gwzlchn** [comment]
traceroute 10.10.10.10 以及10.100.61.3 均返回 * * * 
ping这两个也过不去
附上firewall 设置

	config defaults
			option syn_flood '1'
			option input 'ACCEPT'
			option output 'ACCEPT'
			option forward 'REJECT'

	config zone
			option name 'lan'
			option input 'ACCEPT'
			option output 'ACCEPT'
			option forward 'ACCEPT'
			option network 'lan'

	config zone
			option name 'wan'
			option input 'REJECT'
			option output 'ACCEPT'
			option forward 'REJECT'
			option masq '1'
			option mtu_fix '1'
			option network 'wan6 wan'

	config forwarding
			option src 'lan'
			option dest 'wan'

	config rule
			option name 'Allow-DHCP-Renew'
			option src 'wan'
			option proto 'udp'
			option dest_port '68'
			option target 'ACCEPT'
			option family 'ipv4'

	config rule
			option name 'Allow-Ping'
			option src 'wan'
			option proto 'icmp'
			option icmp_type 'echo-request'
			option family 'ipv4'
			option target 'ACCEPT'

	config rule
			option name 'Allow-IGMP'
			option src 'wan'
			option proto 'igmp'
			option family 'ipv4'
			option target 'ACCEPT'

	config rule
			option name 'Allow-DHCPv6'
			option src 'wan'
			option proto 'udp'
			option src_ip 'fc00::/6'
			option dest_ip 'fc00::/6'
			option dest_port '546'
			option family 'ipv6'
			option target 'ACCEPT'

	config rule
			option name 'Allow-MLD'
			option src 'wan'
			option proto 'icmp'
			option src_ip 'fe80::/10'
			list icmp_type '130/0'
			list icmp_type '131/0'
			list icmp_type '132/0'
			list icmp_type '143/0'
			option family 'ipv6'
			option target 'ACCEPT'

	config rule
			option name 'Allow-ICMPv6-Input'
			option src 'wan'
			option proto 'icmp'
			list icmp_type 'echo-request'
			list icmp_type 'echo-reply'
			list icmp_type 'destination-unreachable'
			list icmp_type 'packet-too-big'
			list icmp_type 'time-exceeded'
			list icmp_type 'bad-header'
			list icmp_type 'unknown-header-type'
			list icmp_type 'router-solicitation'
			list icmp_type 'neighbour-solicitation'
			list icmp_type 'router-advertisement'
			list icmp_type 'neighbour-advertisement'
			option limit '1000/sec'
			option family 'ipv6'
			option target 'ACCEPT'

	config rule
			option name 'Allow-ICMPv6-Forward'
			option src 'wan'
			option dest '*'
			option proto 'icmp'
			list icmp_type 'echo-request'
			list icmp_type 'echo-reply'
			list icmp_type 'destination-unreachable'
			list icmp_type 'packet-too-big'
			list icmp_type 'time-exceeded'
			list icmp_type 'bad-header'
			list icmp_type 'unknown-header-type'
			option limit '1000/sec'
			option family 'ipv6'
			option target 'ACCEPT'

	config include
			option path '/etc/firewall.user'

	config rule
			option src 'wan'
			option dest 'lan'
			option proto 'esp'
			option target 'ACCEPT'

	config rule
			option src 'wan'
			option dest 'lan'
			option dest_port '500'
			option proto 'udp'
			option target 'ACCEPT'

	config include 'miniupnpd'
			option type 'script'
			option path '/usr/share/miniupnpd/firewall.include'
			option family 'any'
			option reload '1'

	config include 'redsocks2'
			option type 'script'
			option path '/usr/share/redsocks2/firewall.include'
			option reload '1'

	config include 'shadowsocks'
			option type 'script'
			option path '/usr/share/shadowsocks/firewall.include'
			option reload '1'

**Comment by mchome** [comment]
不需要修改`nic_name`，请说清楚timeout的位置。

**Comment by CoderNeko** [comment]
@mchome It's very helpful to me

**Comment by Gwzlchn** [comment]
发生在challenge这个函数里，一直输出
`[challenge] timeout, retrying...`
现在问题应该是我没法ping通10.10.10.10 以及10.100.61.3
再贴一下我 `/etc/config/network` 的设置

	config interface 'loopback'
			option ifname 'lo'
			option proto 'static'
			option ipaddr '127.0.0.1'
			option netmask '255.0.0.0'

	config globals 'globals'
			option ula_prefix 'fd40:3903:d05a::/48'

	config interface 'lan'
			option type 'bridge'
			option ifname 'eth0.1'
			option proto 'static'
			option ipaddr '192.168.1.1'
			option netmask '255.255.255.0'
			option ip6assign '60'

	config device 'lan_dev'
			option name 'eth0.1'
			option macaddr 'd8:c8:e9:62:4c:15'

	config interface 'wan'
			option ifname 'eth0.2'
			option _orig_ifname 'eth0.2'
			option _orig_bridge 'false'
			option proto 'static'
			option ipaddr '49.140.60.132'
			option netmask '255.255.255.0'
			option gateway '49.140.60.254'
			option dns '10.10.10.10'
			option macaddr '4C:CC:6A:85:3A:B2'

	config device 'wan_dev'
			option name 'eth0.2'
			option macaddr 'd8:c8:e9:62:4c:16'

	config interface 'wan6'
			option ifname 'eth0.2'
			option proto 'dhcpv6'

	config switch
			option name 'switch0'
			option reset '1'
			option enable_vlan '1'

	config switch_vlan
			option device 'switch0'
			option vlan '1'
			option ports '0 1 2 3 6t 7t'

	config switch_vlan
			option device 'switch0'
			option vlan '2'
			option ports '4 6t 7t'

**Comment by mchome** [comment]
重新抓包，生成配置文件

**Comment by Gwzlchn** [comment]
重做了，然后在windows10 上测试成功了
现在关键的一点是，windows10 上运行`newclient.py` 之前，只插网线是能ping通10.10.10.10和10.100.61.3（认证服务器）
而路由器上的openwrt就不行，ping不通……

跟`newclient.py`这个脚本关系不大应该……
    # CONFIG
    server = '10.100.61.3'
    username=
    password=
    host_ip = 
    mac = 
    host_name = '++++++++'#计算机名
    host_os = 'Windows 10'#操作系统
    CONTROLCHECKSTATUS = '\x20'
    ADAPTERNUM = '\x03'
    IPDOG = '\x01'
    PRIMARY_DNS = '10.10.10.10'
    dhcp_server = '0.0.0.0'
    AUTH_VERSION = '\x68\x00'
    KEEP_ALIVE_VERSION = '\xdc\x02'
    # CONFIG_END

**Comment by ly0** [comment]
路由器的设置问题
