### ISSUE TITLE
求  拨号器 PPPoE-Dialer

### ISSUE THREAD

**Issue by small-nerd** [drcoms/drcom-generic#238]
原有地址下不了

**Comment by mchome** [comment]
aws嘛，科学上网

**Comment by small-nerd** [comment]
下载速度很慢。。。

**Comment by small-nerd** [comment]
已 科学上网

**Comment by ly0** [comment]
@small-nerd 换更高级的科学工具

**Comment by mchome** [comment]
https://github.com/mchome/PPPoE-Dialer/releases/download/v1.1/pppoe-dialer.exe

**Comment by small-nerd** [comment]
路由器 安装 Dr.com 后 无法启动

> Wed Aug 23 23:10:34 2017 daemon.info pppd[9245]: PPP session is 7
Wed Aug 23 23:10:34 2017 daemon.warn pppd[9245]: Connected to 50:da:00:7c:20:4e via interface eth0.2
Wed Aug 23 23:10:34 2017 daemon.info pppd[9245]: Using interface pppoe-wan
Wed Aug 23 23:10:34 2017 daemon.notice pppd[9245]: Connect: pppoe-wan <--> eth0.2
Wed Aug 23 23:10:34 2017 daemon.info pppd[9245]: syncppp not active
Wed Aug 23 23:10:34 2017 daemon.info pppd[9245]: CHAP authentication failed: userid error5
Wed Aug 23 23:10:34 2017 daemon.err pppd[9245]: CHAP authentication failed
Wed Aug 23 23:10:34 2017 daemon.notice pppd[9245]: Connection terminated.
Wed Aug 23 23:10:34 2017 daemon.info pppd[9245]: Sent PADT
Wed Aug 23 23:10:34 2017 daemon.info pppd[9245]: Exit.
Wed Aug 23 23:10:34 2017 daemon.notice netifd: wan (9245): connect as 49f9cba8
Wed Aug 23 23:10:34 2017 daemon.notice netifd: Interface 'wan' is now down
Wed Aug 23 23:10:34 2017 daemon.notice netifd: Interface 'wan' is setting up now
Wed Aug 23 23:10:34 2017 daemon.notice netifd: wan (9279): uci: Entry not found
Wed Aug 23 23:10:34 2017 daemon.info pppd[9289]: Plugin rp-pppoe.so loaded.
Wed Aug 23 23:10:34 2017 daemon.info pppd[9289]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Wed Aug 23 23:10:34 2017 daemon.warn pppd[9289]: [pppoe hook debug] syscall operations name probe pandorabox ok!
Wed Aug 23 23:10:34 2017 daemon.warn pppd[9289]: [pppoe hook debug] hook status=1
Wed Aug 23 23:10:34 2017 daemon.notice pppd[9289]: pppd 2.4.7 started by root, uid 0
Wed Aug 23 23:10:34 2017 daemon.info pppd[9289]: PPP session is 7
Wed Aug 23 23:10:34 2017 daemon.warn pppd[9289]: Connected to 50:da:00:7c:20:4e via interface eth0.2
Wed Aug 23 23:10:34 2017 daemon.info pppd[9289]: Using interface pppoe-wan
Wed Aug 23 23:10:34 2017 daemon.notice pppd[9289]: Connect: pppoe-wan <--> eth0.2
Wed Aug 23 23:10:34 2017 daemon.info pppd[9289]: syncppp not active
Wed Aug 23 23:10:34 2017 daemon.info pppd[9289]: CHAP authentication failed: userid error5
Wed Aug 23 23:10:34 2017 daemon.err pppd[9289]: CHAP authentication failed
Wed Aug 23 23:10:34 2017 daemon.notice pppd[9289]: Connection terminated.
Wed Aug 23 23:10:34 2017 daemon.info pppd[9289]: Sent PADT
Wed Aug 23 23:10:34 2017 daemon.info pppd[9289]: Exit.
Wed Aug 23 23:10:34 2017 daemon.notice netifd: wan (9289): connect as c9e98451
Wed Aug 23 23:10:35 2017 daemon.notice netifd: Interface 'wan' is now down
Wed Aug 23 23:10:35 2017 daemon.notice netifd: Interface 'wan' is setting up now
Wed Aug 23 23:10:35 2017 daemon.notice netifd: wan (9323): uci: Entry not found
Wed Aug 23 23:10:35 2017 daemon.info pppd[9345]: Plugin rp-pppoe.so loaded.
Wed Aug 23 23:10:35 2017 daemon.info pppd[9345]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Wed Aug 23 23:10:35 2017 daemon.warn pppd[9345]: [pppoe hook debug] syscall operations name probe pandorabox ok!
Wed Aug 23 23:10:35 2017 daemon.warn pppd[9345]: [pppoe hook debug] hook status=1
Wed Aug 23 23:10:35 2017 daemon.notice pppd[9345]: pppd 2.4.7 started by root, uid 0
Wed Aug 23 23:10:35 2017 daemon.info pppd[9345]: PPP session is 7
Wed Aug 23 23:10:35 2017 daemon.warn pppd[9345]: Connected to 50:da:00:7c:20:4e via interface eth0.2
Wed Aug 23 23:10:35 2017 daemon.info pppd[9345]: Using interface pppoe-wan
Wed Aug 23 23:10:35 2017 daemon.notice pppd[9345]: Connect: pppoe-wan <--> eth0.2
Wed Aug 23 23:10:35 2017 daemon.info pppd[9345]: syncppp not active
Wed Aug 23 23:10:35 2017 daemon.info pppd[9345]: CHAP authentication failed: userid error5
Wed Aug 23 23:10:35 2017 daemon.err pppd[9345]: CHAP authentication failed
Wed Aug 23 23:10:35 2017 daemon.notice pppd[9345]: Connection terminated.
Wed Aug 23 23:10:35 2017 daemon.info pppd[9345]: Sent PADT
Wed Aug 23 23:10:35 2017 daemon.info pppd[9345]: Exit.
Wed Aug 23 23:10:35 2017 daemon.notice netifd: wan (9345): connect as e88a5cd0
Wed Aug 23 23:10:35 2017 daemon.notice netifd: Interface 'wan' is now down
Wed Aug 23 23:10:35 2017 daemon.notice netifd: Interface 'wan' is setting up now
Wed Aug 23 23:10:35 2017 daemon.notice netifd: wan (9397): uci: Entry not found
Wed Aug 23 23:10:35 2017 daemon.info pppd[9409]: Plugin rp-pppoe.so loaded.
Wed Aug 23 23:10:35 2017 daemon.info pppd[9409]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Wed Aug 23 23:10:35 2017 daemon.warn pppd[9409]: [pppoe hook debug] syscall operations name probe pandorabox ok!
Wed Aug 23 23:10:35 2017 daemon.warn pppd[9409]: [pppoe hook debug] hook status=1
Wed Aug 23 23:10:35 2017 daemon.notice pppd[9409]: pppd 2.4.7 started by root, uid 0
Wed Aug 23 23:10:35 2017 daemon.info pppd[9409]: PPP session is 7
Wed Aug 23 23:10:35 2017 daemon.warn pppd[9409]: Connected to 50:da:00:7c:20:4e via interface eth0.2
Wed Aug 23 23:10:35 2017 daemon.info pppd[9409]: Using interface pppoe-wan
Wed Aug 23 23:10:35 2017 daemon.notice pppd[9409]: Connect: pppoe-wan <--> eth0.2
Wed Aug 23 23:10:35 2017 daemon.info pppd[9409]: syncppp not active
Wed Aug 23 23:10:35 2017 daemon.info pppd[9409]: CHAP authentication failed: userid error5
Wed Aug 23 23:10:35 2017 daemon.err pppd[9409]: CHAP authentication failed
Wed Aug 23 23:10:35 2017 daemon.notice pppd[9409]: Connection terminated.
Wed Aug 23 23:10:35 2017 daemon.info pppd[9409]: Sent PADT
Wed Aug 23 23:10:35 2017 daemon.info pppd[9409]: Exit.
Wed Aug 23 23:10:35 2017 daemon.notice netifd: wan (9409): connect as de8c89b2

能看看是什么问题吗？？？

**Comment by mchome** [comment]
CHAP authentication failed
