### ISSUE TITLE
drcom 6.0.0p版的问题

### ISSUE THREAD

**Issue by SBKK** [drcoms/drcom-generic#239]
现在学校drcom 升到6.0.0p版，开始我没注意版本，直接用以前的5.2.x p版的脚本，能用，但是会出现如下所示的情况，然后基本没有网络，但是拨号没断

![ytzvqm 3p 5ap_zmw5apv0](https://user-images.githubusercontent.com/13724584/29776593-a5bcf8e4-8c3b-11e7-9a88-37941b7f800a.png)

部分send / recv重复，不知道问题是不是出在这。。。

然后想重新抓包看看是不是什么flag变了，但是那个配置生成器drcom_p_config.py无法抓到信息，然后我注意到wiki里表示是5.2.0p版，才发现现在学校的是6.0.0p版的了
然后我去看了一下要抓的内容，感觉很相似，但不知道具体该怎么改，不会python
抓包内容如下：
看到代码里好像bind了61440端口，于是过滤看udp 61440的端口
![1zq h z 8armhyms llnph](https://user-images.githubusercontent.com/13724584/29776577-9b999818-8c3b-11e7-9282-3796fbf46c4f.png)

接下来都是len 8,32,296,48,4个40的重复了，其中一个len = 296包的数据为：

![a6bml5ypmzd8xae_7w y j](https://user-images.githubusercontent.com/13724584/29777013-1fca20ac-8c3d-11e7-97c4-02496a593238.png)

好像前面的长度len为8,32,296,48的包分别就是challenge request 、challenge response、heartbeat request、heartbeat response，然后下面的4个40就是keepalive的send/recv，send/recv，不了解这些是什么协议，但刚好还有以前5.2.x p版的抓包，对比一看，发现5.2.x的heartbeat request 长度len是96的，所以python代码里有个地方填的是 '\x60\x00' # length，而那个配置生成器正则表达式是匹配这一段的，所以6.0.0p版匹配为空，这个296的包貌似就是多了主机的名称 + DrCom + 一段不知道什么玩意

![p d ipzln _3kr7kk4 tr](https://user-images.githubusercontent.com/13724584/29777168-9af893d0-8c3d-11e7-81ce-3c87388889df.png)

抓了几次，下面那段数字是不变的

目前使用latest_pppoe.py，pppoe_flag填的是 '\x2d'，运行在 小米路由器R3 openwrt系统，刚开始网络正常，后面就出现上面的截图send/recv重复很多，虽然没有断线，但是网速几乎没有

1.请问 send /recv 重复（很有规律的仅一部分重复）是什么造成的？是表示出了问题，还是正常的呢？
2.正常官方客户端是296长度的heartbeat request，而这个脚本发的是96长度，但也能收到challenge response，heartbeat response，和keepalive response，是不是表示那边也能支持这种类型，那这个drcom的协议大概是什么原理？哪里可以了解呢？有无必要改成官方那种6.0.0p版的响应方式？然后该怎么改呢？

感谢大神们~

**Comment by ly0** [comment]
1. 客户端是6.0.0p并不表示服务端不兼容5.2.0p的协议, 你用5.2.0p的协议心跳能成功应该说明服务端是兼容该版本协议的
2. 注意看你的包的16进制表示,不是wireshark右边没显示为ASCII就表示对应的字节是0的,所以结构并不是 `主机名+DrCOM+fixed str`
3. 出现你所描述的问题应该是重复发相同id的心跳包引起的, 建议把脚本的包抓一遍,正常的包抓一遍,然后传上来, 只有截图并不能从中获得出什么有效信息.

**Comment by SBKK** [comment]
感谢回复

这是脚本的包和正常的包，发现只能上传10m，所以只抓了一点应该够吧
[capture.zip](https://github.com/drcoms/drcom-generic/files/1258997/capture.zip)

发现在发重复的包之前都没有打印hearbeat request和heartbeat response，只有challenge的，不懂python，没打印是不是就是没有发，没有发也能进行keepalive的send/recv吗？

另外，玄学的是好像有网络了....过几小时我再看看
