### ISSUE TITLE
测试模式下登陆出错会无限无间断重试

### ISSUE THREAD

**Issue by agentmario** [drcoms/drcom-generic#24]
测试环境是 Win10 + python 2.7.10, 修改 lastest-wired.py 开启测试模式后如果账号密码或其他参数填错，会不断的重新登陆，导致认证服务器临时禁用相应账号

**Comment by mchome** [comment]
那...UNLIMITED_RETRY设成False吧

**Comment by agentmario** [comment]
这个设置我一开始就 false 了，好像没用。。。
2015年10月9日 22:28，fuyumi <notifications@github.com>写道：那...UNLIMITED_RETRY设成False吧

**Comment by mchome** [comment]
improved at [98180fb](https://github.com/drcoms/drcom-generic/commit/98180fb5d766909e703acd5edf34863e18f9b623 "")
