### ISSUE TITLE
5.2.1p版使用p版配置器失败

### ISSUE THREAD

**Issue by wsssw** [drcoms/drcom-generic#240]
学校客户端5.2.1p和6.0.0p均可使用。多次抓包后使用p版配置器均失败，两种客户端抓包均有尝试。
Traceback (most recent call last):
  File "drcom_p_config.py", line 19, in <module>
    offset = re.search('\x07[\x00-\xFF]\x60\x00\x03\x00', text).start()
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by wsssw** [comment]
[抓包文件.zip](https://github.com/drcoms/drcom-generic/files/1272202/default.zip)

**Comment by mchome** [comment]
```python
server = '111.74.32.34'
pppoe_flag = '\x2d'
keep_alive2_flag = '\xdc'
```

**Comment by vc5** [comment]
[drp.zip](https://github.com/drcoms/drcom-generic/files/1284996/drp.zip)
遇到了同样的问题，学校强制升级了6.0p，出现了同样的错误
```
Traceback (most recent call last):
  File "drcom_p_config.py", line 20, in <module>
    offset = re.search('\x07[\x00-\xFF]\x60\x00\x03\x00', text).start()
AttributeError: 'NoneType' object has no attribute 'start'
```

**Comment by mchome** [comment]
```python
server = '222.11.39.50'
pppoe_flag = '\x2d'
keep_alive2_flag = '\xdc'
```

**Comment by wsssw** [comment]
好像有些p版不需要心跳包，直接@telecom后可以直接登陆
