### ISSUE TITLE
广东财经大学广州校区32栋（新宿舍）问题

### ISSUE THREAD

**Issue by Rccc1299** [drcoms/drcom-generic#244]
文件在其他栋宿舍都能使用
到了32栋运行的时候，在路由日志文件只显示
auth svr:
username:
password
mac
这四行，然后无法登录，但是在电脑上跑drcom.py可以跑起来，求原因。

**Comment by mchome** [comment]
路由器坏了.png

**Comment by Rccc1299** [comment]
然而同一栋的路由器基本不能用

**Comment by Rccc1299** [comment]
@mchome 然而同一栋的路由器都不能用

**Comment by mchome** [comment]
可能这就是命吧.jpg
电脑能用路由器不能用，代表协议并没有问题
