### ISSUE TITLE
燕京理工学院6.0（D）无法正常使用，recv 0500000503

### ISSUE THREAD

**Issue by oxcz** [drcoms/drcom-generic#245]
这个学期刚刚更新的drcom客户端系统。同时发现了一件很有意思的事情，登陆github不需要登陆校园网就可以登陆。
上传相关log。

 > svr: 10.10.10.5
username: 1
password: 6
mac: 0xbc307
bind ip: 0.0.0.0
[challenge] timeout, retrying...
[challenge] recv 02027af53a49010001000100f303e8f000000000ac123a65f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02027af53a49010001000100f303e8f000000000ac123a65f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001d956bfdd422fb3c79879d17fb51034d323135313231303033380000000000000000000000000000000000000000000000000000002006295b80606c90fb8497640269abdd7c8fdd5cf5b4831001ac123a65000000000000000000000000c5059a653383a36201000000004c495955414e5955414e00000000000000000000000000000000000000000000727272720a0a0aad000000000000000000000000940000000500000001000000280a00000200000038303839440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00020c40a496570000bc307db44e6b0000e913
[login] send 0301001d956bfdd422fb3c79879d17fb51034d323135313231303033380000000000000000000000000000000000000000000000000000002006295b80606c90fb8497640269abdd7c8fdd5cf5b4831001ac123a65000000000000000000000000c5059a653383a36201000000004c495955414e5955414e00000000000000000000000000000000000000000000727272720a0a0aad000000000000000000000000940000000500000001000000280a00000200000038303839440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00020c40a496570000bc307db44e6b0000e913
[login] packet sent.
[login] recv 0500000503
[login] login failed.
[challenge] recv 020259f53e49010001000100f303e8f000000000ac123a65f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020259f53e49010001000100f303e8f000000000ac123a65f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001d67e5fc7a3f27a8626aa92ee5057572913135313231303033380000000000000000000000000000000000000000000000000000002006dbd581ce714cbaef2911c9b0868d71ab97de622dc1a401ac123a6500000000000000000000000058849b627403910201000000004c495955414e5955414e00000000000000000000000000000000000000000000727272720a0a0aad000000000000000000000000940000000500000001000000280a00000200000038303839440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00020c40ca066f0000bc307db44e6b0000e913
[login] send 0301001d67e5fc7a3f27a8626aa92ee5057572913135313231303033380000000000000000000000000000000000000000000000000000002006dbd581ce714cbaef2911c9b0868d71ab97de622dc1a401ac123a6500000000000000000000000058849b627403910201000000004c495955414e5955414e00000000000000000000000000000000000000000000727272720a0a0aad000000000000000000000000940000000500000001000000280a00000200000038303839440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00020c40ca066f0000bc307db44e6b0000e913
[login] packet sent.
[login] recv 0500000503
[login] login failed.

还有一段使用dogcom的日志

> [2015/01/01 Thu 00:07:50] [Challenge sent] 010241282f000000000000000000000000000000
[2015/01/01 Thu 00:07:50] [Challenge recv] 020241288130010001000100f303e8f000000000ac123a65f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[2015/01/01 Thu 00:07:50] [Login sent] 0301001d630eaa00eed9a4710f0c69686b1eb55131353132313030343200000000000000000000000000000000000000000000000000000020073825d5b9acdbaf27de34c8bd6991667530023ef99eff01ac1a228b000000000000000000000000da614341ec30e99f0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aae000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00020c40f6250b00005b2b7fb942020000e913
[2015/01/01 Thu 00:07:50] [login recv] 05000005030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[2015/01/01 Thu 00:07:50] <<< Logged in >>>
[2015/01/01 Thu 00:07:50] Retrying...
[2015/01/01 Thu 00:07:53] [Challenge sent] 01029d382f000000000000000000000000000000
[2015/01/01 Thu 00:07:53] [Challenge recv] 02029d388130010001000100f303e8f000000000ac123a65f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[2015/01/01 Thu 00:07:53] [Login sent] 0301001d630eaa00eed9a4710f0c69686b1eb55131353132313030343200000000000000000000000000000000000000000000000000000020073825d5b9acdbaf27de34c8bd6991667530023ef99eff01ac1a228b000000000000000000000000da614341ec30e99f0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aae000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00020c40f6250b00005b2b7fb942020000e913
[2015/01/01 Thu 00:07:53] [login recv] 05000005030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[2015/01/01 Thu 00:07:53] <<< Logged in >>>

**Comment by oxcz** [comment]
不太知道都该上传什么资料，先上传这一点吧，剩下的再补充。

**Comment by mchome** [comment]
![i 8 ouhsa9wfqvkk e5i13](https://user-images.githubusercontent.com/7392658/30063254-a016b808-9280-11e7-8d70-e6b5c41b4fbe.png)
一直没看到，强行logged in了...

**Comment by oxcz** [comment]
`#coding=UTF-8
#test version 


import socket, struct, time,random,re
from hashlib import md5

#config
server = '10.10.10.5'
username='*****'
password='*****'
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x06'
host_ip = '172.26.34.139'
IPDOG = '\x01'
host_name = ''
PRIMARY_DNS = '10.10.10.22'
dhcp_server = '10.10.10.173'
AUTH_VERSION = '\x2f\x00'
mac = 0x00000000
host_os = 'WINDIAOS'
KEEP_ALIVE_VERSION = '\xdc\x02'

#config_end

class ChallengeException (Exception):
  def __init__(self):
    pass

class loginException (Exception):
  def __init__(self):
    pass
	
def try_socket():
#sometimes cannot get the port
	global s,salt
	try:
		s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
		s.bind(("0.0.0.0", 61440))
		s.settimeout(3)
	except:
		print ("."),
		time.sleep(0.5)
		print ("."),
		time.sleep(0.5)
		print (".")
		time.sleep(0.5)
		print ("...reopen")
		time.sleep(10)
		main()
	else:
		SALT= ''

UNLIMITED_RETRY = True
EXCEPTION = False
	
def get_randmac():
	mac = [ 0x00, 0x16, 0x3e,random.randint(0x00, 0x7f),random.randint(0x00, 0xff),random.randint(0x00, 0xff) ]
	return ''.join(map(lambda x: "%02x" % x, mac))
	#print randomMAC()
	
def version():
	print ("DrCOM Auth Router for GDUFE") 
	
	
def challenge(svr,ran):
    while True:
      t = struct.pack("<H", int(ran)%(0xFFFF))
      s.sendto("\x01\x02"+t+"\x09"+"\x00"*15, (svr, 61440))
      try:
        data, address = s.recvfrom(1024)
        #print('[challenge] recv',data.encode('hex'))
      except:
        print('[challenge] timeout, retrying...')
        continue
        
      if address == (svr, 61440):
        break
      else:
        continue
    #print('[DEBUG] challenge:\n' + data.encode('hex'))
    if data[0] != '\x02':
      raise ChallengeException
    print('[challenge] challenge packet sent.')
    return data[4:8]

def md5sum(s):
    m = md5()
    m.update(s)
    return m.digest()

def dump(n):
    s = '%x' % n
    if len(s) & 1:
        s = '0' + s
    return s.decode('hex')

def ror(md5, pwd):
    ret = ''
    for i in range(len(pwd)):
        x = ord(md5[i]) ^ ord(pwd[i])
        ret += chr(((x<<3)&0xFF) + (x>>5))
    return ret

def keep_alive_package_builder(number,random,tail,type=1,first=False):
    data = '\x07'+ chr(number) + '\x28\x00\x0b' + chr(type)
    data += KEEP_ALIVE_VERSION+'\x2f\x12' + '\x00' * 6
    data += tail
    data += '\x00' * 4
    #data += struct.pack("!H",0xdc02)
    if type == 3:
      foo = ''.join([chr(int(i)) for i in host_ip.split('.')]) # host_ip
	#use double keep in main to keep online .Ice
      crc = '\x00' * 4
      #data += struct.pack("!I",crc) + foo + '\x00' * 8
      data += crc + foo + '\x00' * 8
    else: #packet type = 1
      data += '\x00' * 16
    return data

def packet_CRC(s):
    ret = 0
    for i in re.findall('..', s):
        ret ^= struct.unpack('>h', i)[0]
        ret &= 0xFFFF
    ret = ret * 0x2c7
    return ret



def keep_alive2(*args):
    tail = ''
    packet = ''
    svr = server
    ran = random.randint(0,0xFFFF)
    ran += random.randint(1,10)   
    
    packet = keep_alive_package_builder(0,dump(ran),'\x00'*4,1,True)
    #packet = keep_alive_package_builder(0,dump(ran),dump(ran)+'\x22\x06',1,True)
    print ('[keep-alive2] send1')#packet.encode('hex')
    while True:
        s.sendto(packet, (svr, 61440))
        data, address = s.recvfrom(1024)
        if data.startswith('\x07'):
            break
        else:
			print ('[keep-alive2] recv/unexpected',data.encode('hex'))
			continue
    ran += random.randint(1,10)   
    packet = keep_alive_package_builder(1,dump(ran),'\x00'*4,1,False)
    #print '[keep-alive2] send2',packet.encode('hex')
    s.sendto(packet, (svr, 61440))
    while True:
        data, address = s.recvfrom(1024)
        if data[0] == '\x07':
            break
    #print '[keep-alive2] recv2',data.encode('hex')
    tail = data[16:20]
    

    ran += random.randint(1,10)   
    packet = keep_alive_package_builder(2,dump(ran),tail,3,False)
    #print '[keep-alive2] send3',packet.encode('hex')
    s.sendto(packet, (svr, 61440))
    while True:
        data, address = s.recvfrom(1024)
        if data[0] == '\x07':
            break
    #print '[keep-alive2] recv3',data.encode('hex')
    tail = data[16:20]
    print ("[keep-alive] keep-alive loop was in daemon.")
    i = 3

    while True:
      try:
		keep_alive1(SALT,package_tail,password,server)
		print '[keep-alive2] send'
		ran += random.randint(1,10)   
		packet = keep_alive_package_builder(i,dump(ran),tail,1,False)
		#print('DEBUG: keep_alive2,packet 4\n',packet.encode('hex'))
		#print '[keep_alive2] send',str(i),packet.encode('hex')
		s.sendto(packet, (svr, 61440))
		data, address = s.recvfrom(1024)
		#print '[keep_alive2] recv',data.encode('hex')
		tail = data[16:20]
		#print('DEBUG: keep_alive2,packet 4 return\n',data.encode('hex'))
        
		ran += random.randint(1,10)   
		packet = keep_alive_package_builder(i+1,dump(ran),tail,3,False)
		#print('DEBUG: keep_alive2,packet 5\n',packet.encode('hex'))
		s.sendto(packet, (svr, 61440))
		#print('[keep_alive2] send',str(i+1),packet.encode('hex'))
		data, address = s.recvfrom(1024)
		#print('[keep_alive2] recv',data.encode('hex'))
		tail = data[16:20]
		#print('DEBUG: keep_alive2,packet 5 return\n',data.encode('hex'))
		i = (i+2) % 0xFF
		time.sleep(20)
      except:
        pass

def checksum(s):
    ret = 1234
    for i in re.findall('....', s):
        ret ^= int(i[::-1].encode('hex'), 16)
    ret = (1968 * ret) & 0xffffffff
    return struct.pack('<I', ret)


def mkpkt(salt, usr, pwd, mac):
    data = '\x03\x01\x00'+chr(len(usr)+20)
    data += md5sum('\x03\x01'+salt+pwd)
    data += usr.ljust(36, '\x00')
    data += '\x20' #fixed unknow 1
    data += '\x02' #unknow 2
    data += dump(int(data[4:10].encode('hex'),16)^mac).rjust(6,'\x00') #mac xor md51
    data += md5sum("\x01" + pwd + salt + '\x00'*4) #md52
    data += '\x01' #NIC count
    data += hexip #your ip address1 
    data += '\00'*4 #your ipaddress 2
    data += '\00'*4 #your ipaddress 3
    data += '\00'*4 #your ipaddress 4
    data += md5sum(data + '\x14\x00\x07\x0b')[:8] #md53
    data += '\x01' #ipdog
    data += '\x00'*4 #delimeter
    data += host_name.ljust(32, '\x00')
    data += '\x72\x72\x72\x72' #primary dns: 114.114.114.114
    data += '\x0a\xff\x00\xc5' #DHCP server
    data += '\x08\x08\x08\x08' #secondary dns:8.8.8.8
    data += '\x00' * 8 #delimeter
    data += '\x94\x00\x00\x00' # unknow
    data += '\x05\x00\x00\x00' #os major
    data += '\x01\x00\x00\x00' # os minor
    data += '\x28\x0a\x00\x00' # OS build
    data += '\x02\x00\x00\x00' #os unknown
    data += host_os.ljust(32,'\x00')
    data += '\x00' * 96
    #data += '\x01' + host_os.ljust(128, '\x00')
    #data += '\x0a\x00\x00'+chr(len(pwd)) # \0x0a represents version of client, algorithm: DRCOM_VER + 100
    #data += ror(md5sum('\x03\x01'+salt+pwd), pwd)
    data += AUTH_VERSION
    data += '\x02\x0c'
    data += checksum(data+'\x01\x26\x07\x11\x00\x00'+dump(mac))
    data += '\x00\x00' #delimeter
    data += dump(mac)
    data += '\x00' # auto logout / default: False
    data += '\x00' # broadcast mode / default : False
    data += '\xc2\x66' #unknown
    
    
    return data

def login(usr, pwd, svr):
    global SALT
 
    i = 0
    while True:
        salt = challenge(svr,time.time()+random.randint(0xF,0xFF))
        SALT = salt
        packet = mkpkt(salt, usr, pwd, mac)
        #print('[login] send',packet.encode('hex'))
        s.sendto(packet, (svr, 61440))
        data, address = s.recvfrom(1024)
        #print('[login] recv',data.encode('hex'))
        print('[login] packet sent.')
        if address == (svr, 61440):
            if data[0] == '\x04':
              print('[login] login in')
              break
            else:
              continue
        else:
            if i >= 5 and UNLIMITED_RETRY == False :
              print('[login] exception occured.')
              sys.exit(1)
            else:
              continue
            
    print('[login] login Success')
    return data[23:39]
    #return data[-22:-6]

def keep_alive1(salt,tail,pwd,svr):
    foo = struct.pack('!H',int(time.time())%0xFFFF)
    data = '\xff' + md5sum('\x03\x01'+salt+pwd) + '\x00\x00\x00'
    data += tail
    data += foo + '\x00\x00\x00\x00'
    print '[keep_alive1] send'#data.encode('hex'))

    s.sendto(data, (svr, 61440))
    while True:
        data, address = s.recvfrom(1024)
        if data[0] == '\x07':
            break
        else:
            print '[keep-alive1]recv/not expected'#data.encode('hex')
    #print('[keep-alive1] recv',data.encode('hex'))

def empty_socket_buffer():
#empty buffer
    print('starting to empty socket buffer')
    try:
        while True:
            data, address = s.recvfrom(1024)
            #print 'recived sth unexcepted',data.encode('hex')
            if s == '':
                break
    except:
        # get exception means it has done.
        print('exception in empty_socket_buffer')
        pass
    print('emptyed')


		
def main():
	global server,username,password,host_name,host_os,dhcp_server,mac,hexip,host_ip
	hexip=socket.inet_aton(host_ip)
	#host_ip=ip
	host_name = "est-pc"
	host_os = "8089D"   #default is 8089D
	dhcp_server = "0.0.0.0"
	#mac = 0xE0DB55BAE012 
	#it is a mac in programme and it may crush with other users so I use randMAC to avoid it
	loginpart()
	
def loginpart():
	global package_tail
	while True:
		try:
			package_tail = login(username, password, server)
		except loginException:
			continue
		#print('package_tail',package_tail.encode('hex'))
		keeppart()
		
def keeppart():
	#empty_socket_buffer()
	#empty_socket_buffer()
	keep_alive2(SALT,package_tail,password,server)

		
if __name__ == "__main__":
	try_socket()
	version()
	#get_conf()
	main()


`

**Comment by oxcz** [comment]
不是太明白，一直没看到，强行logged in了...，这个是什么意思。

**Comment by oxcz** [comment]
这个是刚才新抓取的日志，并没有被服务器禁止登陆。

> [2015/01/01 Thu 02:33:16] [Challenge sent] 010244aa2f000000000000000000000000000000
[2015/01/01 Thu 02:33:16] [Challenge recv] 020244aa8750010001000100f303e8f000000000ac123a65f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[2015/01/01 Thu 02:33:16] [Login sent] 0301001d2821321141d2dc21d8127a407a877ab73135313231303033380000000000000000000000000000000000000000000000000000002007730a4da803d0c1d509e94b34ca64d01df20dca11681301ac1a228b000000000000000000000000e1b7515c921d19910100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aae000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00020c00dab68c00005b2b7fb942020000e913
[2015/01/01 Thu 02:33:16] [login recv] 05000005030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[2015/01/01 Thu 02:33:16] <<< Logged in >>>
[2015/01/01 Thu 02:33:16] Retrying...
[2015/01/01 Thu 02:33:19] [Challenge sent] 010259752f000000000000000000000000000000
[2015/01/01 Thu 02:33:19] [Challenge recv] 020259758750010001000100f303e8f000000000ac123a65f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[2015/01/01 Thu 02:33:19] [Login sent] 0301001d2821321141d2dc21d8127a407a877ab73135313231303033380000000000000000000000000000000000000000000000000000002007730a4da803d0c1d509e94b34ca64d01df20dca11681301ac1a228b000000000000000000000000e1b7515c921d19910100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aae000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00020c00dab68c00005b2b7fb942020000e913
[2015/01/01 Thu 02:33:19] [login recv] 05000005030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[2015/01/01 Thu 02:33:19] <<< Logged in >>>
[2015/01/01 Thu 02:33:19] Retrying...

**Comment by oxcz** [comment]
@ly0 我看到这个了，但事实上帐号和密码是没有问题的。recv 0500000503是取最后两位是错误码吗？

**Comment by ly0** [comment]
实际情况是你需要确认一下是不是官方客户端会在你的用户名前后加点别的东西 比如\r\n之类或者@xxxnet之类

**Comment by mchome** [comment]
试下新版

**Comment by alanhi** [comment]
校友，我电脑可以登录，没有问题。

**Comment by 509820490** [comment]
github可以访问  有没有可能可以设置一个代理  把所有的访问请求都伪装成访问github  像手机免流那样  不用花钱就上网？

**Comment by oxcz** [comment]
更下错误信息。
[challenge] recv 02026c4726e7070001000100f303e8f000000000ac1a228bf000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02026c4726e7070001000100f303e8f000000000ac1a228bf000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001d5dfecf7d86a3b8a5e3b5911dd251ec6b3135313231303036330000000000000000000000000000000000000000000000000000002006e1ceb2c9c8c8cc008d8af91afb5056472a49ddf05f5f01ac1a228b0000000000000000000000006e6f4f3fd618f38c01000000004c495955414e5955414e00000000000000000000000000000000000000000000727272720a0a0aad000000000000000000000000940000000500000001000000280a00000200000038303839440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f0000066366e74a9dac020cf0af17930000bc307db44e6b0000e913
[login] send 0301001d5dfecf7d86a3b8a5e3b5911dd251ec6b3135313231303036330000000000000000000000000000000000000000000000000000002006e1ceb2c9c8c8cc008d8af91afb5056472a49ddf05f5f01ac1a228b0000000000000000000000006e6f4f3fd618f38c01000000004c495955414e5955414e00000000000000000000000000000000000000000000727272720a0a0aad000000000000000000000000940000000500000001000000280a00000200000038303839440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f0000066366e74a9dac020cf0af17930000bc307db44e6b0000e913
[login] packet sent.
[login] recv 0400000500dd0400004aee6400f9010000ff00000000004472636f0a0a0a05bf08ac1a228b019bb00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636f0a0a0a05bf08ac1a228b019b
starting to empty socket buffer
recived sth unexpected 4d38d6e53830d4aab0fcd4c2b2bbcfdec1f7c1bfccd7b2cda3ac3130d4c231c8d5c6f0c9fad0a7a3acbfc9cda8b9fdd7d4d6fab7fecef1d4a4d4bcb0ecc0ed31302e31302e31302e383a383038302f53656c66a3bbbcc6cab1ccd7b2cdb2bbcfdec1f7c1bfa3acb2bbcfdebdf0b6ee302e303038d4aa2fb7d6d6d3a3bb00
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff5dfecf7d86a3b8a5e3b5911dd251ec6b0000004472636f0a0a0a05bf08ac1a228b019b469300000000
[keep_alive1] error raise Exception to main() or keep_alive2()
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "C:\Users\Hasee\Desktop\latest-wired.py", line 496, in main
    keep_alive1(SALT,package_tail,password,server)
  File "C:\Users\Hasee\Desktop\latest-wired.py", line 453, in keep_alive1
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 0202944730e7070001000100f303e8f000000000ac1a228bf000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202944730e7070001000100f303e8f000000000ac1a228bf000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001deed3e9a2fd800780e58c1e236b707fe0313531323130303633000000000000000000000000000000000000000000000000000000200652e39416b3ebec248f825d0a81aeb02fe528fde37f0f01ac1a228b0000000000000000000000006dd9ff43e354e32401000000004c495955414e5955414e00000000000000000000000000000000000000000000727272720a0a0aad000000000000000000000000940000000500000001000000280a00000200000038303839440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006fe0fd6b446b5020c90ddb3a60000bc307db44e6b0000e913
[login] send 0301001deed3e9a2fd800780e58c1e236b707fe0313531323130303633000000000000000000000000000000000000000000000000000000200652e39416b3ebec248f825d0a81aeb02fe528fde37f0f01ac1a228b0000000000000000000000006dd9ff43e354e32401000000004c495955414e5955414e00000000000000000000000000000000000000000000727272720a0a0aad000000000000000000000000940000000500000001000000280a00000200000038303839440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006fe0fd6b446b5020c90ddb3a60000bc307db44e6b0000e913
[login] packet sent.
[login] recv 0400000500de0400005bee6400f9010000ff00000000004472636f0a0a0a05cb08ac1a228b01a7b00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636f0a0a0a05cb08ac1a228b01a7
starting to empty socket buffer
recived sth unexpected 4d3884133830d4aab0fcd4c2b2bbcfdec1f7c1bfccd7b2cda3ac3130d4c231c8d5c6f0c9fad0a7a3acbfc9cda8b9fdd7d4d6fab7fecef1d4a4d4bcb0ecc0ed31302e31302e31302e383a383038302f53656c66a3bbbcc6cab1ccd7b2cdb2bbcfdec1f7c1bfa3acb2bbcfdebdf0b6ee302e303038d4aa2fb7d6d6d3a3bb00
exception in empty_socket_buffer
emptyed
[keep_alive1] send ffeed3e9a2fd800780e58c1e236b707fe00000004472636f0a0a0a05cb08ac1a228b01a7469f00000000
[keep_alive1] error raise Exception to main() or keep_alive2()
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "C:\Users\Hasee\Desktop\latest-wired.py", line 496, in main
    keep_alive1(SALT,package_tail,password,server)
  File "C:\Users\Hasee\Desktop\latest-wired.py", line 453, in keep_alive1
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 0202ce4635e7070001000100f303e8f000000000ac1a228bf000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202ce4635e7070001000100f303e8f000000000ac1a228bf000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001dbfcfcd07d1ea5e950cfda23356233649313531323130303633000000000000000000000000000000000000000000000000000000200603ffb0b39f8162af4558e1c13e798611baffb609bb3101ac1a228b000000000000000000000000a648904ff40215a701000000004c495955414e5955414e00000000000000000000000000000000000000000000727272720a0a0aad000000000000000000000000940000000500000001000000280a00000200000038303839440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000674eff79927e6020cd0f4d8d20000bc307db44e6b0000e913
[login] send 0301001dbfcfcd07d1ea5e950cfda23356233649313531323130303633000000000000000000000000000000000000000000000000000000200603ffb0b39f8162af4558e1c13e798611baffb609bb3101ac1a228b000000000000000000000000a648904ff40215a701000000004c495955414e5955414e00000000000000000000000000000000000000000000727272720a0a0aad000000000000000000000000940000000500000001000000280a00000200000038303839440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000674eff79927e6020cd0f4d8d20000bc307db44e6b0000e913
[login] packet sent.
[login] recv 0400000500df0400006bee6400f8010000ff00000000004472636f0a0a0a05d308ac1a228b01afb00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636f0a0a0a05d308ac1a228b01af
starting to empty socket buffer
recived sth unexpected 4d38b2c83830d4aab0fcd4c2b2bbcfdec1f7c1bfccd7b2cda3ac3130d4c231c8d5c6f0c9fad0a7a3acbfc9cda8b9fdd7d4d6fab7fecef1d4a4d4bcb0ecc0ed31302e31302e31302e383a383038302f53656c66a3bbbcc6cab1ccd7b2cdb2bbcfdec1f7c1bfa3acb2bbcfdebdf0b6ee302e303038d4aa2fb7d6d6d3a3bb00
exception in empty_socket_buffer
emptyed
[keep_alive1] send ffbfcfcd07d1ea5e950cfda233562336490000004472636f0a0a0a05d308ac1a228b01af46ab00000000
[keep_alive1] error raise Exception to main() or keep_alive2()
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "C:\Users\Hasee\Desktop\latest-wired.py", line 496, in main
    keep_alive1(SALT,package_tail,password,server)
  File "C:\Users\Hasee\Desktop\latest-wired.py", line 453, in keep_alive1
    data, address = s.recvfrom(1024)
timeout: timed out

**Comment by oxcz** [comment]
@mchome

**Comment by ly0** [comment]
把496行注释掉试试

**Comment by lwxyl** [comment]
同燕京理工，你解决了没？
