### ISSUE TITLE
请问一下这个5.2.1D版本的dr

### ISSUE THREAD

**Issue by qiufeng666** [drcoms/drcom-generic#248]
我拿python拨号，电脑开wifi共享大师就掉线，然后time out  之后自动拨号重连，要等20S左右，请问5.2.1D版本还能解决开wifi拨号不掉线吗，不然我刷路由器固件进去也没用。
server = '10.65.16.3'
username='13272.........'
password='6340.........'
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x06'
host_ip = '10.64.6.75'
IPDOG = '\x01'
host_name = 'GILIGILIEYE'
PRIMARY_DNS = '58.20.127.170'
dhcp_server = '10.64.0.1'
AUTH_VERSION = '\x2e\x00'
mac = 0x902b34ba2c52
host_os = 'NOTE7'
KEEP_ALIVE_VERSION = '\xd8\x02'
ror_version = False 

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>C:\Users\Administrator\Desktop\新建文件夹\latest-wired.py

auth svr: 10.65.16.3
username: 1327
password: 634
mac: 0x902b34ba2c52
bind ip: 0.0.0.0
[challenge] recv 0202dcde7853020000000100f303e8f0000000000a40064bf000a8a6000070c
da0a300000000d802000000000000000000000000000000000000000000000000000000000000000
000000000
[DEBUG] challenge:
0202dcde7853020000000100f303e8f0000000000a40064bf000a8a6000070cda0a300000000d802
000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100294585078e1315a67548869231f81411603133323732343030353034406d696e67
7a68656e670000000000000000000000000000002006d5ae33343f47034188cf21addab045d85dd6
627a0ad0010a40064b000000000000000000000000b221c5100616e5d3010000000047494c494749
4c494559450000000000000000000000000000000000000000003a147faa0a400001000000000000
000000000000940000000500000001000000280a0000020000004e4f544537000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000002e00020c3036
7c960000902b34ba2c520000e913
[login] send 030100294585078e1315a67548869231f81411603133323732343030353034406d6
96e677a68656e670000000000000000000000000000002006d5ae33343f47034188cf21addab045d
85dd6627a0ad0010a40064b000000000000000000000000b221c5100616e5d3010000000047494c4
947494c494559450000000000000000000000000000000000000000003a147faa0a4000010000000
00000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000002e00020
c30367c960000902b34ba2c520000e913
[login] packet sent.
[login] recv 0400000500000000000000000000000000ff00000000004472636f0a411003f2c60
a40064b0146b00500030100
[login] loged in
[login] login sent
package_tail 4472636f0a411003f2c60a40064b0146
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff4585078e1315a67548869231f81411600000004472636f0a411003f2c60
a40064b0146de5000000000
[keep-alive1] recv 070110000600de5033be6a000a40064ba8a6000070cda0a300000000d8020
000030000001700000019000000000000000000000000000000803a0900ffffffff
[keep-alive2] send1 070028000b010f272f120000000000000000000000000000000000000000
00000000000000000000
[keep-alive2] recv1 070010010b06d8022f12000000000000a8a6000070cda0a300000000d802
00004d5a90000300000004000000ffff0000b8000000000000004000000000000000000000000000
00000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21
546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d
0d0a2400000000000000be4ff959fa2e970afa2e970afa2e970aa30d840af82e970a81329b0afe2e
970a7926ca0af02e970a7932990af82e970a95319c0afb2e970a95319d0aff2e970a9531930af82e
970afa2e960a492e970acc08930af92e970acc089c0af22e970a3d28910afb2e970a050e930af92e
970a
[keep-alive2] recv file, resending..
[keep-alive2] send2 070128000b01d8022f120000000000000000000000000000000000000000
00000000000000000000
[keep-alive2] recv2 070128000b02d8022f1200000000000033be6a0000000000000000000000
00000000000000000000
[keep-alive2] send3 070228000b03d8022f1200000000000033be6a0000000000000000000a40
064b0000000000000000
[keep-alive2] recv3 070228000b04d8022f1200000000000033be6a0000000000000000000000
00000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive1] send ff4585078e1315a67548869231f81411600000004472636f0a411003f2c60
a40064b0146de6400000000
[keep-alive1] recv 070110000600ffffc6be6a000a40064ba8a6000070cda0a300000000d8020
00045e13b016200000044010000000000000000000000000000803a0900ffffffff
[keep_alive2] send 3 070328000b01d8022f1200000000000033be6a000000000000000000000
000000000000000000000
[keep_alive2] recv 4d38b40cc7bfd6c6c0ebcfdf2c20d6d5b6cb203e2031
[keep_alive2] send 4 070428000b03d8022f12000000000000b6cb203e00000000000000000a4
0064b0000000000000000
[keep_alive2] recv 4d15fe9e41646d696e5265736574
[keep_alive1] send ff4585078e1315a67548869231f81411600000004472636f0a411003f2c60
a40064b0146de7800000000
[keep-alive1] recv 070328000b02d8022f12000000000000fbbe6a00000000000000000000000
0000000000000000000
[keep_alive2] send 5 070528000b01d8022f12000000000000000000000000000000000000000
0000000000000
[keep_alive2] error raise Exception to main()
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\新建文件夹\latest-wired.py", line 489, in
 main
    keep_alive2(SALT,package_tail,password,server)
  File "C:\Users\Administrator\Desktop\新建文件夹\latest-wired.py", line 232, in
 keep_alive2
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 020266df8853020000000100f303e8f0000000000a40064bf000a8a6000070c
da0a300000000d802000000000000000000000000000000000000000000000000000000000000000
000000000
[DEBUG] challenge:
020266df8853020000000100f303e8f0000000000a40064bf000a8a6000070cda0a300000000d802
000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010029f661b1575aec37cdb8fc1fc9f3fac4733133323732343030353034406d696e67
7a68656e670000000000000000000000000000002006664a85ed76be3e73bbdf1ad6a43a178bf01b
73bf7dcc010a40064b0000000000000000000000005696f509b7b4b26e010000000047494c494749
4c494559450000000000000000000000000000000000000000003a147faa0a400001000000000000
000000000000940000000500000001000000280a0000020000004e4f544537000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000002e00020c50b5
d01e0000902b34ba2c520000e913
[login] send 03010029f661b1575aec37cdb8fc1fc9f3fac4733133323732343030353034406d6
96e677a68656e670000000000000000000000000000002006664a85ed76be3e73bbdf1ad6a43a178
bf01b73bf7dcc010a40064b0000000000000000000000005696f509b7b4b26e010000000047494c4
947494c494559450000000000000000000000000000000000000000003a147faa0a4000010000000
00000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000002e00020
c50b5d01e0000902b34ba2c520000e913
[login] packet sent.
[login] recv 0400000500000000000000000000000000ff00000000004472636f0a411003fec60
a40064b0152b00500030100
[login] loged in
[login] login sent
package_tail 4472636f0a411003fec60a40064b0152
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send fff661b1575aec37cdb8fc1fc9f3fac4730000004472636f0a411003fec60
a40064b0152de8400000000
[keep-alive1] recv 070110000600de843bc06a000a40064ba8a6000070cda0a300000000d8020
000030000005c0000000b020000000000000000000000000000803a0900ffffffff
[keep-alive2] send1 070028000b010f272f120000000000000000000000000000000000000000
00000000000000000000
[keep-alive2] recv1 070010010b06d8022f12000000000000a8a6000070cda0a300000000d802
00004d5a90000300000004000000ffff0000b8000000000000004000000000000000000000000000
00000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21
546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d
0d0a2400000000000000be4ff959fa2e970afa2e970afa2e970aa30d840af82e970a81329b0afe2e
970a7926ca0af02e970a7932990af82e970a95319c0afb2e970a95319d0aff2e970a9531930af82e
970afa2e960a492e970acc08930af92e970acc089c0af22e970a3d28910afb2e970a050e930af92e
970a
[keep-alive2] recv file, resending..
[keep-alive2] send2 070128000b01d8022f120000000000000000000000000000000000000000
00000000000000000000
[keep-alive2] recv2 070128000b02d8022f120000000000003bc06a0000000000000000000000
00000000000000000000
[keep-alive2] send3 070228000b03d8022f120000000000003bc06a0000000000000000000a40
064b0000000000000000
[keep-alive2] recv3 070228000b04d8022f120000000000003bc06a0000000000000000000000
00000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.

**Comment by ly0** [comment]
你的意思是不开就正常是吗

**Comment by qiufeng666** [comment]
是的  我这边不开wifi就不会掉线的，然后我这边电脑共享wif 我手机一台设备连接 都掉线

**Comment by ly0** [comment]
应该是带了NAT检测，建议路由上搭一个代理，下挂设备的流量都走代理，或者尝试把路由的NAT设置成Symmetric NAT尝试一下。

**Comment by mchome** [comment]
@qiufeng666

**Comment by mchome** [comment]
![image](https://user-images.githubusercontent.com/7392658/30237683-074de9ba-956a-11e7-8aa8-c8b0ddf378c9.png)

**Comment by qiufeng666** [comment]
如果是电脑的话，我这边先不刷进路由器，有什么方法解决吗。以前没升级之前，5.2.0D完美破解开wifi，最开始我拿网页拨号都不会掉线。

**Comment by qiufeng666** [comment]
@mchome 难受的一批。。。实在不能解决我换其他运营商算了。销卡去

**Comment by ly0** [comment]
请自行查找有关NAT检测 多终端检测 等相关资料，本 issue 关闭。
