### ISSUE TITLE
福建江夏学院 ver5.2.0D Login failed

### ISSUE THREAD

**Issue by 1453374029** [drcoms/drcom-generic#250]
前期反馈
https://github.com/drcoms/drcom-generic/issues/50
https://github.com/mchome/dogcom/issues/19

C:\Users\14533\Desktop\dogcom1.4.3-win>dogcom_v1.4.3.exe -m dhcp -c drcom.conf -l 20170911105428.log -v
server = '10.2.255.250'
username = '13107638070'
password = '10201616'
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x04'
host_ip = '10.3.116.66'
IPDOG = '\x01'
host_name = 'fuyumi'
PRIMARY_DNS = '10.1.1.88'
dhcp_server = '10.3.116.254'
AUTH_VERSION = '\x16\x00'
mac = 0xf0421cb70ade
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'
ror_version = True

You are binding at 0.0.0.0!

[Challenge sent] 010255ea16000000000000000000000000000000
[Challenge recv] 020255eab4f900000a000100f203e8f0000000000a037459f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001fc4e2fcd561b2c23b0b592686c2d1a0c6313331303736333830373000000000000000000000000000000000000000000000000000200434a0e0626b6cab6af7c87fd5bb140365e5bb8cc777df010a037442000000000000000000000000f35e272c2d9ac4f60100000000667579756d6900000000000000000000000000000000000000000000000000000a0101580a0374fe000000000000000000000000940000000500000001000000280a00000200000057696e646f77730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000008af96762f8224020cb082770b0000f0421cb70ade0000e913
[login recv] 050000051500000000000000000000000000000032393b5573657228313331303736333830373040666a6a7878792927732041757468656e204174747269622861692d536572766963652d50617373776f72643a204e4153206973203230373937393461
<<< Login failed >>>
Retrying...
[Challenge sent] 0102049c16000000000000000000000000000000
[Challenge recv] 0202049cb4f900000a000100f203e8f0000000000a037459f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001fc4e2fcd561b2c23b0b592686c2d1a0c6313331303736333830373000000000000000000000000000000000000000000000000000200434a0e0626b6cab6af7c87fd5bb140365e5bb8cc777df010a037442000000000000000000000000f35e272c2d9ac4f60100000000667579756d6900000000000000000000000000000000000000000000000000000a0101580a0374fe000000000000000000000000940000000500000001000000280a00000200000057696e646f77730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000008af96762f8224020cb082770b0000f0421cb70ade0000e913
[login recv] 050000051500000000000000000000000000000032393b5573657228313331303736333830373040666a6a7878792927732041757468656e204174747269622861692d536572766963652d50617373776f72643a204e4153206973203230373937393461
<<< Login failed >>>
Retrying...
[Challenge sent] 0102cd3816000000000000000000000000000000
[Challenge recv] 0202cd38b6f900000a000100f203e8f0000000000a037459f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001f3e3d93dce3dbb7aa1c55ca8cf5cbb3093133313037363338303730000000000000000000000000000000000000000000000000002004ce7f8f6be905ac2289bcb9b3c0e31bfa13227d3309f2010a037442000000000000000000000000cce008c538833c8f0100000000667579756d6900000000000000000000000000000000000000000000000000000a0101580a0374fe000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001600000878680d67966f020c708081a70000f0421cb70ade0000e913
[login recv] 050000051500000000000000000000000000000032393b5573657228313331303736333830373040666a6a7878792927732041757468656e204174747269622861692d536572766963652d50617373776f72643a204e4153206973203061346339646236
<<< Login failed >>>
Retrying...
[Challenge sent] 01022d1f16000000000000000000000000000000
[Challenge recv] 02022d1fb6f900000a000100f203e8f0000000000a037459f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001f3e3d93dce3dbb7aa1c55ca8cf5cbb3093133313037363338303730000000000000000000000000000000000000000000000000002004ce7f8f6be905ac2289bcb9b3c0e31bfa13227d3309f2010a037442000000000000000000000000cce008c538833c8f0100000000667579756d6900000000000000000000000000000000000000000000000000000a0101580a0374fe000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001600000878680d67966f020c708081a70000f0421cb70ade0000e913
[login recv] 050000051500000000000000000000000000000032393b5573657228313331303736333830373040666a6a7878792927732041757468656e204174747269622861692d536572766963652d50617373776f72643a204e4153206973203061346339646236
<<< Login failed >>>
Retrying...
[Challenge sent] 0102888316000000000000000000000000000000
[Challenge recv] 02028883b8f900000a000100f203e8f0000000000a037459f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001f25722253fcf9fdfbf66c4af56a1409b43133313037363338303730000000000000000000000000000000000000000000000000002004d5303ee4f627858a4e4b58f0b5e41571e563badbfafe010a037442000000000000000000000000cd13d70e6da3fd4a0100000000667579756d6900000000000000000000000000000000000000000000000000000a0101580a0374fe000000000000000000000000940000000500000001000000280a00000200000057696e646f77730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000008a012801b6e7e020cd0e3cee40000f0421cb70ade0000e913
[login recv] 050000051500000000000000000000000000000032393b5573657228313331303736333830373040666a6a7878792927732041757468656e204174747269622861692d536572766963652d50617373776f72643a204e4153206973203163323930353433
<<< Login failed >>>
Retrying...

Failed to keep in touch with server, exiting <<<<<

**Comment by ly0** [comment]
python版的能用吗？能用 @mchome 23333

**Comment by 1453374029** [comment]
不能

**Comment by mchome** [comment]
ror部分多了2个字节，感觉吉大下面那部分应该用的上。
```python
if (len(pwd) / 4) != 4:
    data += '\x00' * (len(pwd) / 4)#strange。。。
```

**Comment by 1453374029** [comment]
请问大神这个问题能解决么？

**Comment by mchome** [comment]
尝试一下

**Comment by mchome** [comment]
那就先用这个
