### ISSUE TITLE
广东财经大学广州校区32栋整栋都用不了

### ISSUE THREAD

**Issue by qouson** [drcoms/drcom-generic#251]
路由器在多个宿舍试过，刚开始以为是抓包问题，然后重新抓过，在装有python的windows操作系统上可以运行脚本，也可以正常上网，但是放进路由器之后就不行，然后通过可以通过putty连接路由器手动运行脚本，可以上网，但是关掉putty之后就断掉了，就是这么神奇，有人知道怎么解决吗

**Comment by mchome** [comment]
发出你的错误日志

**Comment by qouson** [comment]
错误日志在哪里

**Comment by qouson** [comment]
附上客户端，脚本文件
[windows(通用版).zip](https://github.com/drcoms/drcom-generic/files/1302148/windows.zip)
[Drcom-广东财经大学.zip](https://github.com/drcoms/drcom-generic/files/1302156/Drcom-.zip)

**Comment by ly0** [comment]
用nohup运行脚本

**Comment by mchome** [comment]
魔改版请找魔改的人。

**Comment by qouson** [comment]
这个固件内存已经满了，而且没有nohup，咋办
