### ISSUE TITLE
5.2.0D版 python版 timed out C语言版 Failed to recv data; Resource temporarily unavailable

### ISSUE THREAD

**Issue by luoanjun** [drcoms/drcom-generic#254]
使用最新latest-wirde.py日志
auth svr: 222.168.144.50
username: 2015302050119
password: 2333333
mac: 0x902b34861c99
bind ip: 0.0.0.0
[challenge] recv 02029ed5436b07000a000100f303e8f000000000ac106b0df000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02029ed5436b07000a000100f303e8f000000000ac106b0df000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100212c7c34ee6895d90c8c71adfbc76c1c8d3230313533303230353031313900000000000000000000000000000000000000000000002001bc570068740c4a73c83a857dbe79e2ad3f9a1e8311ea01ac106b0d0000000000000000000000005fb84166276ba60e0100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006f05a18d6ca0d020c80e263ec0000902b34861c990000e913
[login] send 030100212c7c34ee6895d90c8c71adfbc76c1c8d3230313533303230353031313900000000000000000000000000000000000000000000002001bc570068740c4a73c83a857dbe79e2ad3f9a1e8311ea01ac106b0d0000000000000000000000005fb84166276ba60e0100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006f05a18d6ca0d020c80e263ec0000902b34861c990000e913
[login] packet sent.
[login] recv 0400000500000000000000000000000000ff00000000004472636fdea890328126ac106b0d01f7b00500030110
[login] loged in
[login] login sent
package_tail 4472636fdea890328126ac106b0d01f7
starting to empty socket buffer
recived sth unexpected 4d38f835cda8d6aaa3bac8e7b9fbd3d0b5c7c2bcd1a7bac5baf3cedeb7a8d5fdb3a3c9cfcdf8b5c4c7e9bff6a3acc7ebd7a2cffab2a2c9beb3fd43c5cc4452434f4dcec4bcfea3acd6d8d0c2b0b2d7b0d0a3d4b0cdf8d4adb0e6b5c4c8cfd6a4b5c7c2bcbfcdbba7b6cba3acd4da4e454550552d574c414ebbb7beb3cfc2cfc2d4d8b5c4bfcdbba7b6cbbbf2cedeb7a8d5fdb3a3cab9d3c3a3a1
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff2c7c34ee6895d90c8c71adfbc76c1c8d0000004472636fdea890328126ac106b0d01f7d4e000000000
[keep_alive1] error raise Exception to main() or keep_alive2()
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "test.py", line 489, in main
    keep_alive1(SALT,package_tail,password,server)
  File "test.py", line 446, in keep_alive1
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 02026ad54e6b07000a000100f303e8f000000000ac106b0df000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02026ad54e6b07000a000100f303e8f000000000ac106b0df000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301002145cbcf5f597adfae953f5f58cac0d61c3230313533303230353031313900000000000000000000000000000000000000000000002001d5e0fbd945e31f4694a49128b236df73b2a745dc4aa701ac106b0d000000000000000000000000977d22e98a6982360100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006bbe7c75b4372020c00d08b340000902b34861c990000e913
[login] send 0301002145cbcf5f597adfae953f5f58cac0d61c3230313533303230353031313900000000000000000000000000000000000000000000002001d5e0fbd945e31f4694a49128b236df73b2a745dc4aa701ac106b0d000000000000000000000000977d22e98a6982360100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006bbe7c75b4372020c00d08b340000902b34861c990000e913
[login] packet sent.
[login] recv timeout.
[challenge] recv 02022ad54e6b07000a000100f303e8f000000000ac106b0df000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02022ad54e6b07000a000100f303e8f000000000ac106b0df000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301002145cbcf5f597adfae953f5f58cac0d61c3230313533303230353031313900000000000000000000000000000000000000000000002001d5e0fbd945e31f4694a49128b236df73b2a745dc4aa701ac106b0d000000000000000000000000977d22e98a6982360100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006bbe7c75b4372020c00d08b340000902b34861c990000e913
[login] send 0301002145cbcf5f597adfae953f5f58cac0d61c3230313533303230353031313900000000000000000000000000000000000000000000002001d5e0fbd945e31f4694a49128b236df73b2a745dc4aa701ac106b0d000000000000000000000000977d22e98a6982360100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006bbe7c75b4372020c00d08b340000902b34861c990000e913
[login] packet sent.
[login] recv 0400000500000000000000000000000000ff00000000004472636fdea890328726ac106b0d01fdb00500030110
[login] loged in
[login] login sent
package_tail 4472636fdea890328726ac106b0d01fd
starting to empty socket buffer
recived sth unexpected 4d38a238cda8d6aaa3bac8e7b9fbd3d0b5c7c2bcd1a7bac5baf3cedeb7a8d5fdb3a3c9cfcdf8b5c4c7e9bff6a3acc7ebd7a2cffab2a2c9beb3fd43c5cc4452434f4dcec4bcfea3acd6d8d0c2b0b2d7b0d0a3d4b0cdf8d4adb0e6b5c4c8cfd6a4b5c7c2bcbfcdbba7b6cba3acd4da4e454550552d574c414ebbb7beb3cfc2cfc2d4d8b5c4bfcdbba7b6cbbbf2cedeb7a8d5fdb3a3cab9d3c3a3a1
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff45cbcf5f597adfae953f5f58cac0d61c0000004472636fdea890328726ac106b0d01fdd4ef00000000
[keep_alive1] error raise Exception to main() or keep_alive2()
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "test.py", line 489, in main
    keep_alive1(SALT,package_tail,password,server)
  File "test.py", line 446, in keep_alive1
    data, address = s.recvfrom(1024)
timeout: timed out

**Comment by whhz** [comment]
噫，校友
出现了一样的错误，错误日志和客户端[http://pan.baidu.com/s/1nv40lFb](url)
大神求解决！

**Comment by hy20000000** [comment]
哈哈哈 已经有两个校友比我还快了

**Comment by ly0** [comment]
keep_alive1 屌用注释掉

**Comment by lweo** [comment]
东电有这么多人都会刷这个？我以为就我会呢 - -

**Comment by luoanjun** [comment]
注释掉keep_alive1 后卡在keep-alive2上，附日志
auth svr: 222.168.144.50
username: 2015302050119
password: 23333
mac: 0x902b34861c99
bind ip: 0.0.0.0
[challenge] recv 0202ad5f60c307000a000100f303e8f000000000ac106b0df000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202ad5f60c307000a000100f303e8f000000000ac106b0df000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100219feea7e6a02b79c41abdf89b9cd1fd1832303135333032303530313139000000000000000000000000000000000000000000000020010fc59360bcb2362f28ffc59c31d91d7e0c7f05af7f9901ac106b0d000000000000000000000000647f148146402d180100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f777320313000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000210000066dce84968cf8020c809fa6fd0000902b34861c990000e913
[login] send 030100219feea7e6a02b79c41abdf89b9cd1fd1832303135333032303530313139000000000000000000000000000000000000000000000020010fc59360bcb2362f28ffc59c31d91d7e0c7f05af7f9901ac106b0d000000000000000000000000647f148146402d180100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f777320313000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000210000066dce84968cf8020c809fa6fd0000902b34861c990000e913
[login] packet sent.
[login] recv timeout.
[challenge] recv 02021c6060c307000a000100f303e8f000000000ac106b0df000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02021c6060c307000a000100f303e8f000000000ac106b0df000a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100219feea7e6a02b79c41abdf89b9cd1fd1832303135333032303530313139000000000000000000000000000000000000000000000020010fc59360bcb2362f28ffc59c31d91d7e0c7f05af7f9901ac106b0d000000000000000000000000647f148146402d180100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f777320313000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000210000066dce84968cf8020c809fa6fd0000902b34861c990000e913
[login] send 030100219feea7e6a02b79c41abdf89b9cd1fd1832303135333032303530313139000000000000000000000000000000000000000000000020010fc59360bcb2362f28ffc59c31d91d7e0c7f05af7f9901ac106b0d000000000000000000000000647f148146402d180100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f777320313000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000210000066dce84968cf8020c809fa6fd0000902b34861c990000e913
[login] packet sent.
[login] recv 0400000500000000000000000000000000ff00000000004472636fdea89032a85bac106b0d011cb00500030110
[login] loged in
[login] login sent
package_tail 4472636fdea89032a85bac106b0d011c
starting to empty socket buffer
recived sth unexpected 4d3806c1cda8d6aaa3bac8e7b9fbd3d0b5c7c2bcd1a7bac5baf3cedeb7a8d5fdb3a3c9cfcdf8b5c4c7e9bff6a3acc7ebd7a2cffab2a2c9beb3fd43c5cc4452434f4dcec4bcfea3acd6d8d0c2b0b2d7b0d0a3d4b0cdf8d4adb0e6b5c4c8cfd6a4b5c7c2bcbfcdbba7b6cba3acd4da4e454550552d574c414ebbb7beb3cfc2cfc2d4d8b5c4bfcdbba7b6cbbbf2cedeb7a8d5fdb3a3cab9d3c3a3a1
exception in empty_socket_buffer
emptyed
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070010010b06dc022f12000000000000a8a80000e659f16700000000dc0200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a24000000000000007cc3835a38a2ed0938a2ed0938a2ed096181fe093aa2ed0943bee10939a2ed09bbaab00932a2ed09bbbee3093aa2ed0957bde60939a2ed0957bde7093da2ed0957bde9093aa2ed0938a2ec0981a2ed090e84e9093ba2ed090e84e60930a2ed09ffa4eb0939a2ed09c782e9093ba2ed09
[keep-alive2] recv file, resending..
[keep-alive2] send2 070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2 070128000b02dc022f120000000000006af036020000000000000000000000000000000000000000
[keep-alive2] send3 070228000b03dc022f120000000000006af036020000000000000000ac106b0d0000000000000000
[keep-alive2] recv3 070228000b04dc022f120000000000006af036020000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive2] send 3 070328000b01dc022f120000000000006af036020000000000000000000000000000000000000000
[keep_alive2] recv 070328000b02dc022f1200000000000028f136020000000000000000000000000000000000000000
[keep_alive2] send 4 070428000b03dc022f1200000000000028f136020000000000000000ac106b0d0000000000000000
[keep_alive2] recv 070428000b04dc022f1200000000000028f136020000000000000000000000000000000000000000
[keep_alive2] send 5 070528000b01dc022f1200000000000028f136020000000000000000000000000000000000000000
[keep_alive2] recv 070528000b02dc022f12000000000000e7f136020000000000000000000000000000000000000000
[keep_alive2] send 6 070628000b03dc022f12000000000000e7f136020000000000000000ac106b0d0000000000000000
[keep_alive2] recv 070628000b04dc022f12000000000000e7f136020000000000000000000000000000000000000000
[keep_alive2] send 7 070728000b01dc022f12000000000000e7f136020000000000000000000000000000000000000000
[keep_alive2] recv 070728000b02dc022f12000000000000a5f236020000000000000000000000000000000000000000
[keep_alive2] send 8 070828000b03dc022f12000000000000a5f236020000000000000000ac106b0d0000000000000000
[keep_alive2] recv 070828000b04dc022f12000000000000a5f236020000000000000000000000000000000000000000

**Comment by hy20000000** [comment]
不知道是不是我的注释的方法不对 和楼上一样 也是用不了

**Comment by xsm1997** [comment]
我这里抓包的结果来看，应该是心跳包发生改变了。
附上心跳包：
0000   ff 00 00 00 00 00 00 00 c1 37 69 02 e8 58 b3 b1
0010   fb f8 2c db 44 72 63 6f de a8 90 32 f3 02 ac 10
0020   5e 2e 01 19 79 4e
以及
0000   ff 00 00 00 00 00 00 00 d5 38 69 02 b1 6c df e0
0010   e7 3a b1 33 44 72 63 6f de a8 90 32 f3 02 ac 10
0020   5e 2e 01 19 96 4e
这两个是能正常使用的官方drcom客户端的抓包。
其中44 72 63 6f de a8 90 32 f3 02 ac 10 5e 2e 01 19为package_tail，没有改变。前12字节不知道是什么，应该不是md5了（md5长度不够）。
求大神解决。

**Comment by yinziminganion** [comment]
楼上提到的12个字节 我只发现前四个字节的由来
官方客户端首先会发送一条07开头的数据包然后服务器也回复一条07开头的数据包 然后取出data[8:12] 作为前4个字节的内容 接着客户端发送ff+00*7+刚才提到的4个字节+剩下未知的8个字节内容+......的keep-alive1心跳包
但剩下的8个字节我试着用md5的结果取其中8个字节比如[:8]、[4:12]、[8:]等等都没有成功
求大神解决

**Comment by ly0** [comment]
@luoanjun 怎么个卡法？我看日志挺正常？

**Comment by xsm1997** [comment]
不是卡住，而是无限循环在keep_alive2，但是无法上网。按照学校上一个版本的drcom，login了之后也无法上网，只有心跳包keep_alive1一去一回之后才能上网。

**Comment by ly0** [comment]
@yinziminganion 你可以试试这8个字节用0填充？

**Comment by yinziminganion** [comment]
@ly0 
1、用0填充也是timeout
2、每一轮的心跳包中这未知的8个字节内容也都不一样，似乎固定内容填充也不能解决
3、试着把抓包得到的数据按照原来的顺序发送到服务器，包括了认证过程和两轮的心跳
结果如下：
[send] 01……
[recv] 02……
[send] 03……
[recv] 04……
[send] 0702080001000000
[recv] 0702100002010000fdc3cd02ac103d2ea8a80000e659f16700000000dc020000
[send] ff000000000000006f6975022449d0163e19c3e24472636fdea89032ad50ac103d2e01d08d96
[recv]timeout
[send] 070028000b010f276b4a000000000000000000000000000000000000000000000000000000000000
[recv] 070010010b06dc026b4a000000000000a8a80000e659f16700000000dc0200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a24000000000000007cc3835a38a2ed0938a2ed0938a2ed096181fe093aa2ed0943bee10939a2ed09bbaab00932a2ed09bbbee3093aa2ed0957bde60939a2ed0957bde7093da2ed0957bde9093aa2ed0938a2ec0981a2ed090e84e9093ba2ed090e84e60930a2ed09ffa4eb0939a2ed09c782e9093ba2ed09
[send] 070128000b01dc026e4a000000000000000000000000000000000000000000000000000000000000
[recv] 070128000b02dc026e4a0000000000001ac4cd020000000000000000000000000000000000000000
[send] 070228000b03dc026e4a00000000000084697502000000003a6f5000ac103d2e0000000000000000
[recv]timeout
[send] 0703080001000000
[recv] 070310000202000036c4cd02ac103d2ea8a80000e659f16700000000dc020000
[send] ff00000000000000276a7502c6e34d3f3f8cef024472636fdea89032ad50ac103d2e01d0a096
[recv]timeout
[send] 070328000b01dc02b04a000000000000846975020000000000000000000000000000000000000000
[recv] 070328000b02dc02b04a00000000000053c4cd020000000000000000000000000000000000000000
[send] 070428000b03dc02b04a000000000000426a75020000000002044800ac103d2e0000000000000000
[recv]timeout

**Comment by xsm1997** [comment]
在看了一天的IDA之后，算法大致是搞出来了。那个神秘的8个字节其实是pppoe验证的一部分，和latest-pppoe.py中的gen_crc函数中的算法完全一致，采用md5、md4、sha-1计算12个字节的前4个字节，并且取若干字节组成12个字节中的后8个字节。 @yinziminganion 像您说的一样，12字节的前4个字节是服务器回复的，而且在每次发送keep_alive1的包之前都会发送07开头的包，然后获取服务器返回的值作为keep_alive1包12字节的前4个字节。
不知道keep_alive2的算法有没有更改。。。。。。
本人技拙，不会编写python。恳请校友或大神采用这个思路编写python脚本。

**Comment by ly0** [comment]
@xsm1997 赞，看来d版也启用这个feature了

**Comment by mchome** [comment]
`keepalive1`的第一个返回包（第二个包）中含有第6个字节含有摘要方式，第9个字节到第12个字节含有`keepalive`的challenge包，作为被进行摘要算法的输入。

**Comment by yinziminganion** [comment]
@ly0 我按照 @xsm1997 提供的算法更改了latest-wired.py的内容之后测试有效 但是在这里上传py文件提示不支持 麻烦大神下载一下http://vultr.yinziming.com/latest-wired.py 然后上传

**Comment by mchome** [comment]
我做个keepalive1 toggle再merge进去吧

**Comment by xsm1997** [comment]
@mchome 大神把您的dogcom有时间也更新一下吧，路由器跑python还是太沉了。

**Comment by yinziminganion** [comment]
@xsm1997 我按照同样的思路更改了dogcom中的keepalive.c文件，把原dogcom项目中的keepalive.c文件替换为http://vultr.yinziming.com/keepalive.c应该就可以了，我在ubuntu环境下测试成功的，路由器的环境就交给你了（傻笑~

**Comment by mchome** [comment]
dogcom已更新至1.6.0，如果出现keepalive1问题的，配置文件结尾新加一行keepalive1_mod = True。
