### ISSUE TITLE
广东工业大学，按教程配置好后，每一分半钟就断线重连

### ISSUE THREAD

**Issue by HFWXX7** [drcoms/drcom-generic#255]
PING 10.0.3.2 (10.0.3.2): 56 data bytes
64 bytes from 10.0.3.2: seq=0 ttl=61 time=0.787 ms

--- 10.0.3.2 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.787/0.787/0.787 ms
OK
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/usr/bin/drcom", line 3, in <module>
    import socket
ImportError: No module named socket

**Comment by mchome** [comment]
python环境有问题，需要重新安装

**Comment by HFWXX7** [comment]
Test connectivity to auth server
PING 10.0.3.2 (10.0.3.2): 56 data bytes
64 bytes from 10.0.3.2: seq=0 ttl=61 time=0.702 ms

--- 10.0.3.2 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.702/0.702/0.702 ms
OK
Traceback (most recent call last):
  File "/usr/bin/drcom", line 7, in <module>
    import random
  File "/usr/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/usr/lib/python2.7/hashlib.py", line 149, in <module>
    import logging
ImportError: No module named logging
root@OpenWrt:/tmp# ImportError: No module named logging
-ash: ImportError:: not found
请问这又是什么情况呢麻烦了谢谢

**Comment by ly0** [comment]
python环境有问题，需要重新安装 + 1
