### ISSUE TITLE
\r\n拨号问题：拨号软件也不成功

### ISSUE THREAD

**Issue by NERD-k** [drcoms/drcom-generic#258]
使用P版拨号软件：拨号出现异常
![inkedpppoe-dialer_2017-10-05_13-50-43_li](https://user-images.githubusercontent.com/28424691/31212839-82d2c50e-a9d5-11e7-885c-145412e0220e.jpg)
这个Dr.com版本的拨号的确是有 `\r\n` 的
![inkedwireshark_2017-10-05_13-55-51_li](https://user-images.githubusercontent.com/28424691/31212894-e77c7cac-a9d5-11e7-96a2-4141e538d86e.jpg)
**求大神指出问题所在。**

**Comment by fububanzangly** [comment]
修改ppp.sh

**Comment by NERD-k** [comment]
这是在电脑上啊，请问怎么修改ppp.sh？

**Comment by mchome** [comment]
关闭客户端

**Comment by NERD-k** [comment]
我没有打开客户端的，抓包的时候装上Dr.com，之后就卸载的。

**Comment by mchome** [comment]
试试这个 [pppoe-dialer](https://github.com/mchome/PPPoE-Dialer/releases/download/v1.1/pppoe-dialer.exe)

**Comment by NERD-k** [comment]
还是这样，不明白问题所在啊。。。
![inkedpppoe-dialer_2017-10-05_15-13-43_li](https://user-images.githubusercontent.com/28424691/31214970-533b47ac-a9e0-11e7-92d8-ec0dcfb6e5e3.jpg)

**Comment by mchome** [comment]
抓pppoe-dialer的包来看咯

**Comment by NERD-k** [comment]
明白了，是登陆机器数量的问题

![inkedwireshark_2017-10-05_15-25-47_li](https://user-images.githubusercontent.com/28424691/31215374-d14e0d4a-a9e1-11e7-8843-0b8a230ad269.jpg)

**谢大神提点**

**Comment by NERD-k** [comment]
尴尬，纠结这么久的问题，是最简单的问题
