### ISSUE TITLE
latest-pppoe.py与latest-wired.py的区别

### ISSUE THREAD

**Issue by NERD-k** [drcoms/drcom-generic#259]
请问：latest-pppoe.py与latest-wired.py的区别是什么啊？
我想要用Pythin3，还是用latest-pppoe.py，然后修改适应Python3吗？

**Comment by ly0** [comment]
pppoe是p版的 wired是d版的

**Comment by NERD-k** [comment]
pppoe目前版本不支持Python3的环境吧？

**Comment by mchome** [comment]
不支持，你可以移植一下。

**Comment by NERD-k** [comment]
有谁感兴趣的看看这个 转 python3 的
![sublime_text_2017-10-06_19-08-39](https://user-images.githubusercontent.com/28424691/31275773-065c0098-aacb-11e7-9ef0-b881adc184e8.png)

后面全是0？？？看来我做的不对啊

**Comment by NERD-k** [comment]
不太懂啊，我只能让他能跑起来，但都是得到的 recv1/unexpected，不太懂啊

![conemu64_2017-10-07_19-02-49](https://user-images.githubusercontent.com/28424691/31307231-2de60ef2-ab92-11e7-8fd2-1d0d514eb475.png)

**Comment by NERD-k** [comment]
运行 通不过的。应该是字节的问题。foo 等等也是要转化 为 byte
![conemu64_2017-10-12_23-47-42](https://user-images.githubusercontent.com/28424691/31505664-f50458ea-afa7-11e7-89ea-8ef04472f6c7.png)

**Comment by NERD-k** [comment]
我稍微改了一下后，又有这个错误。。。
![sublime_text_2017-10-13_01-30-04](https://user-images.githubusercontent.com/28424691/31510058-297d6608-afb6-11e7-98dd-0d5a5be287af.png)

**Comment by NERD-k** [comment]
修改这些

>  λ  git diff
>  diff --git a/pppoe.py b/pppoe.py
>  index 2cfc2ca..695d392 100644
>  --- a/pppoe.py
>  +++ b/pppoe.py
>  @@ -7,6 +7,7 @@ import sys
>   import random
>   import os
>   import hashlib
>  +import binascii
>  
>   # CONFIG
>   server = '172.30.1.80'
>  @@ -31,10 +32,10 @@ def log(*args, **kwargs):
>       if DEBUG:
>           with open(LOG_PATH,'ab') as f:
>               try:
>  -                f.write(s)
>  +                f.write(bytes(s))
>                   f.write('\n')
>               except:
>  -                f.write('FUCK WINDOWS' + '\n')
>  +                f.write(b'FUCK WINDOWS' + b'\n')
>   def dump(n):
>       s = '%x' % n
>       if len(s) & 1:
>  @@ -324,8 +325,8 @@ def main():
>           daemon()
>           execfile(CONF, globals())
>       log('auth svr: ' + server)
>  -    log('pppoe_flag: ' + binascii.hexlify(pppoe_flag))
>  -    log('keep_alive2_flag: ' + binascii.hexlify(keep_alive2_flag))
>  +    log('pppoe_flag: ' + str(binascii.hexlify(pppoe_flag)))
>  +    log('keep_alive2_flag: ' + str(binascii.hexlify(keep_alive2_flag)))
>  
>       s = Socket(server)
>       while True:
>  @@ -334,4 +335,4 @@ def main():
>           keep_alive2(s, pppoe)
>  
>   if __name__ == '__main__':
>  -    main()
>  \ No newline at end of file
>  +    main()
>  C:\Users\NERD\Desktop [master +21 ~1 -0 !]
>  λ
