### ISSUE TITLE
登录成功但卡在[keep_alive1] error raise Exception to main() or keep_alive2()

### ISSUE THREAD

**Issue by lwxyl** [drcoms/drcom-generic#261]
客户端抓包文件：https://pan.baidu.com/s/1slLofAd

mac: 0xd8cb8aef65b9
bind ip: 0.0.0.0
[challenge] recv 0202f27a110d020001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202f27a110d020001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001dc8eabca7b4f32f99aa41a1c98a2f0aa5313530323630303034000000000000000000000000000000000000000000000000000000200710213648d14a4bc81f1500f366d6b995dbeead0557c201ac1f2469000000000000000000000000b62b761e2a4d195a0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006d7c674ac340e020c10b4f9bb0000d8cb8aef65b90000e913
[login] send 0301001dc8eabca7b4f32f99aa41a1c98a2f0aa5313530323630303034000000000000000000000000000000000000000000000000000000200710213648d14a4bc81f1500f366d6b995dbeead0557c201ac1f2469000000000000000000000000b62b761e2a4d195a0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006d7c674ac340e020c10b4f9bb0000d8cb8aef65b90000e913
[login] packet sent.
[login] recv 0400000500932e0000ae8ae10783220000ff00000000004472636f0a0a0a051474ac1f246901adb00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636f0a0a0a051474ac1f246901ad
starting to empty socket buffer
recived sth unexpected 4d38f0443830d4aab0fcd4c2b2bbcfdec1f7c1bfccd7b2cda3ac3130d4c231c8d5c6f0c9fad0a7a3acbfc9cda8b9fdd7d4d6fab7fecef1d4a4d4bcb0ecc0ed31302e31302e31302e383a383038302f53656c66a3bbbcc6cab1ccd7b2cdb2bbcfdec1f7c1bfa3acb2bbcfdebdf0b6ee302e303038d4aa2fb7d6d6d3a3bb00
exception in empty_socket_buffer
emptyed
[keep_alive1] send ffc8eabca7b4f32f99aa41a1c98a2f0aa50000004472636f0a0a0a051474ac1f246901ad7a4300000000
[keep_alive1] error raise Exception to main() or keep_alive2()
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "X:\Desktop\Drcom.py", line 491, in main
    keep_alive1(SALT,package_tail,password,server)
  File "X:\Desktop\Drcom.py", line 448, in keep_alive1
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 0202c17a1b0d020001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202c17a1b0d020001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001dba78ccf03f9a6641a1729ba7e365fbbb313530323630303034000000000000000000000000000000000000000000000000000000200762b3461f5a23a2984e2f7e8652cef523bc1cd7144bcb01ac1f2469000000000000000000000000ee768ce79c12af770100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f0000064452f7166845020ca09d90ed0000d8cb8aef65b90000e913
[login] send 0301001dba78ccf03f9a6641a1729ba7e365fbbb313530323630303034000000000000000000000000000000000000000000000000000000200762b3461f5a23a2984e2f7e8652cef523bc1cd7144bcb01ac1f2469000000000000000000000000ee768ce79c12af770100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f0000064452f7166845020ca09d90ed0000d8cb8aef65b90000e913
[login] packet sent.
[login] recv 0400000500942e0000ae8ae10783220000ff00000000004472636f0a0a0a052374ac1f246901bbb00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636f0a0a0a052374ac1f246901bb
starting to empty socket buffer
recived sth unexpected 4d38ac933830d4aab0fcd4c2b2bbcfdec1f7c1bfccd7b2cda3ac3130d4c231c8d5c6f0c9fad0a7a3acbfc9cda8b9fdd7d4d6fab7fecef1d4a4d4bcb0ecc0ed31302e31302e31302e383a383038302f53656c66a3bbbcc6cab1ccd7b2cdb2bbcfdec1f7c1bfa3acb2bbcfdebdf0b6ee302e303038d4aa2fb7d6d6d3a3bb00
exception in empty_socket_buffer
emptyed
[keep_alive1] send ffba78ccf03f9a6641a1729ba7e365fbbb0000004472636f0a0a0a052374ac1f246901bb7a4f00000000
[keep_alive1] error raise Exception to main() or keep_alive2()
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "X:\Desktop\Drcom.py", line 491, in main
    keep_alive1(SALT,package_tail,password,server)
  File "X:\Desktop\Drcom.py", line 448, in keep_alive1
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 0202b97a210d020001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202b97a210d020001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001d1457a2ad1ce4a18976171d531e94275f3135303236303030340000000000000000000000000000000000000000000000000000002007cc9c2842795d582c8a77b3f86b5182d9ebdb9e2258b701ac1f246900000000000000000000000080bc8d492a6593d50100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006312b84fc71b6020cb056c9ec0000d8cb8aef65b90000e913
[login] send 0301001d1457a2ad1ce4a18976171d531e94275f3135303236303030340000000000000000000000000000000000000000000000000000002007cc9c2842795d582c8a77b3f86b5182d9ebdb9e2258b701ac1f246900000000000000000000000080bc8d492a6593d50100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006312b84fc71b6020cb056c9ec0000d8cb8aef65b90000e913
[login] packet sent.
[login] recv 0400000500942e0000ae8ae10783220000ff00000000004472636f0a0a0a053474ac1f246901ccb00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636f0a0a0a053474ac1f246901cc
starting to empty socket buffer
recived sth unexpected 4d3818ce3830d4aab0fcd4c2b2bbcfdec1f7c1bfccd7b2cda3ac3130d4c231c8d5c6f0c9fad0a7a3acbfc9cda8b9fdd7d4d6fab7fecef1d4a4d4bcb0ecc0ed31302e31302e31302e383a383038302f53656c66a3bbbcc6cab1ccd7b2cdb2bbcfdec1f7c1bfa3acb2bbcfdebdf0b6ee302e303038d4aa2fb7d6d6d3a3bb00
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff1457a2ad1ce4a18976171d531e94275f0000004472636f0a0a0a053474ac1f246901cc7a5b00000000
[keep_alive1] error raise Exception to main() or keep_alive2()
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "X:\Desktop\Drcom.py", line 491, in main
    keep_alive1(SALT,package_tail,password,server)
  File "X:\Desktop\Drcom.py", line 448, in keep_alive1
    data, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer

**Comment by lwxyl** [comment]
版本6.0.0D，系统win10，燕京理工学院

**Comment by lwxyl** [comment]
nic_name在win10系统上应该怎么看呢？我试着填了 Killer e2400 Gigabit Ethernet Controller、以太网、eth0.1、eth0.2 ......，都不对。。。

**Comment by lwxyl** [comment]
估计是nic_name不对，日志如下

mac: 0xd8cb8aef65b9
bind ip: 0.0.0.0
[challenge] recv 0202a0016872020001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202a0016872020001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001d23efdffb3823a4d234a810a2508e224c3135303236303030340000000000000000000000000000000000000000000000000000002007fb2455145d9a64d8a5c981d1fe7d136cbfff268d3fe101ac1f24690000000000000000000000001bc887fe9e67846f0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000688ee6f4e5088020c60dc7c300000d8cb8aef65b90000e913
[login] send 0301001d23efdffb3823a4d234a810a2508e224c3135303236303030340000000000000000000000000000000000000000000000000000002007fb2455145d9a64d8a5c981d1fe7d136cbfff268d3fe101ac1f24690000000000000000000000001bc887fe9e67846f0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000688ee6f4e5088020c60dc7c300000d8cb8aef65b90000e913
[login] packet sent.
[login] recv 0400000500e3340000cc85170883220000ff00000000004472636f0a0a0a054b7eac1f2469010cb00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636f0a0a0a054b7eac1f2469010c
starting to empty socket buffer
recived sth unexpected 4d382ab73830d4aab0fcd4c2b2bbcfdec1f7c1bfccd7b2cda3ac3130d4c231c8d5c6f0c9fad0a7a3acbfc9cda8b9fdd7d4d6fab7fecef1d4a4d4bcb0ecc0ed31302e31302e31302e383a383038302f53656c66a3bbbcc6cab1ccd7b2cdb2bbcfdec1f7c1bfa3acb2bbcfdebdf0b6ee302e303038d4aa2fb7d6d6d3a3bb00
exception in empty_socket_buffer
emptyed
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020100008ddda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020100008ddda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020100008ddda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020100008ddda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020100008ddda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020100008ddda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020100008ddda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020100008ddda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008edda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020300008fdda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020300008fdda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020300008fdda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020300008fdda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020300008fdda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020300008fdda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020300008fdda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020300008fdda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020300008fdda500ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020300008fdda500ac1f2469a8ac00004fe416c100000000dc020000

**Comment by mchome** [comment]
fixed
