### ISSUE TITLE
新版改成true能上网了，但是后台可以查到每三分钟重新登录一次

### ISSUE THREAD

**Issue by lwxyl** [drcoms/drcom-generic#262]
不知道是脚本的问题还是路由器的问题，也可能是学校做了什么限制和这种方法有冲突。。。
有没有遇到类似情况的同学呀？？？

**Comment by lwxyl** [comment]
更新了代码，还是会掉，好尴尬。。。

**Comment by lwxyl** [comment]
换回了新版dogcom，完美了，感谢大神！

**Comment by NERD-k** [comment]
新版dogcom 是什么版本的啊？？？

**Comment by NERD-k** [comment]
看到了。。。

**Comment by NERD-k** [comment]
我想问一下，你的python3版本能用吗？？？ @lwxyl

**Comment by lwxyl** [comment]
不知道诶，我每试过python3版的。 @NERD-k
