### ISSUE TITLE
校网再次更新，之前的方法都失效了，能登录但上不了网，就连上次能用的至尊版客户端都废了

### ISSUE THREAD

**Issue by lwxyl** [drcoms/drcom-generic#265]
原版抓包：

https://pan.baidu.com/s/1kVDtkc3

python版日志：

mac: 0xd8cb8aef65b9
bind ip: 0.0.0.0
[challenge] recv 020216ea7817000001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020216ea7817000001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001daafae02fb03cd086289f2a6a14e54be4313530323630303034000000000000000000000000000000000000000000000000000000200872316ac0d585e341d29876ff15f3d799e61519e0b0d901ac1f24690000000000000000000000006dffa0d7768d2f100100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006c44696e81470020c00c194c20000d8cb8aef65b90000e913
[login] send 0301001daafae02fb03cd086289f2a6a14e54be4313530323630303034000000000000000000000000000000000000000000000000000000200872316ac0d585e341d29876ff15f3d799e61519e0b0d901ac1f24690000000000000000000000006dffa0d7768d2f100100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006c44696e81470020c00c194c20000d8cb8aef65b90000e913
[login] packet sent.
[login] recv 0400000500f04800006748b90983220000ff00000000004472636f0a0a0a059b55ac1f246901a0b00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636f0a0a0a059b55ac1f246901a0
starting to empty socket buffer
recived sth unexpected 4d38ccf23830d4aab0fcd4c2b2bbcfdec1f7c1bfccd7b2cda3ac3130d4c231c8d5c6f0c9fad0a7a3acbfc9cda8b9fdd7d4d6fab7fecef1d4a4d4bcb0ecc0ed31302e31302e31302e383a383038302f53656c66a3bbbcc6cab1ccd7b2cdb2bbcfdec1f7c1bfa3acb2bbcfdebdf0b6ee302e303038d4aa2fb7d6d6d3a3bb00
exception in empty_socket_buffer
emptyed
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07ae100002820000eebe0700ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1] send ff00000000000000eebe07003c39714ae3ce9bac4472636f0a0a0a059b55ac1f246901a0e9c4
[keep-alive1] error
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "X:\Desktop\latest-wired.py", line 574, in main
    keep_alive1(SALT,package_tail,password,server)
  File "X:\Desktop\latest-wired.py", line 511, in keep_alive1
    res, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 02022bea8217000001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02022bea8217000001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001d948723d221c2dc9ba9042da8b0db194631353032363030303400000000000000000000000000000000000000000000000000000020084c4ca93d447b02b44e3389360f4c893a3a0ec555686c01ac1f24690000000000000000000000009a7c0edae62283a70100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000635ad88079887020cb0138df90000d8cb8aef65b90000e913
[login] send 0301001d948723d221c2dc9ba9042da8b0db194631353032363030303400000000000000000000000000000000000000000000000000000020084c4ca93d447b02b44e3389360f4c893a3a0ec555686c01ac1f24690000000000000000000000009a7c0edae62283a70100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000635ad88079887020cb0138df90000d8cb8aef65b90000e913
[login] packet sent.
[login] recv 0400000500f14800006748b90983220000ff00000000004472636f0a0a0a05a755ac1f246901acb00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636f0a0a0a05a755ac1f246901ac
starting to empty socket buffer
recived sth unexpected 4d3818553830d4aab0fcd4c2b2bbcfdec1f7c1bfccd7b2cda3ac3130d4c231c8d5c6f0c9fad0a7a3acbfc9cda8b9fdd7d4d6fab7fecef1d4a4d4bcb0ecc0ed31302e31302e31302e383a383038302f53656c66a3bbbcc6cab1ccd7b2cdb2bbcfdec1f7c1bfa3acb2bbcfdebdf0b6ee302e303038d4aa2fb7d6d6d3a3bb00
exception in empty_socket_buffer
emptyed
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07ba10000282000066bf0700ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1] send ff0000000000000066bf0700894494e2f5ad73a04472636f0a0a0a05a755ac1f246901ace9d0
[keep-alive1] error
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "X:\Desktop\latest-wired.py", line 574, in main
    keep_alive1(SALT,package_tail,password,server)
  File "X:\Desktop\latest-wired.py", line 511, in keep_alive1
    res, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 0202f6e98717000001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202f6e98717000001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001de89f450878cce470f34213ef5949a16031353032363030303400000000000000000000000000000000000000000000000000000020083054cfe71d75af9a0a5dfbc8c69dc3b9b4e56b00b99001ac1f2469000000000000000000000000b08dc090db90af8a0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006d66dbbd152f7020ca0da894d0000d8cb8aef65b90000e913
[login] send 0301001de89f450878cce470f34213ef5949a16031353032363030303400000000000000000000000000000000000000000000000000000020083054cfe71d75af9a0a5dfbc8c69dc3b9b4e56b00b99001ac1f2469000000000000000000000000b08dc090db90af8a0100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a170a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006d66dbbd152f7020ca0da894d0000d8cb8aef65b90000e913
[login] packet sent.
[login] recv 0400000500f14800006748b90983220000ff00000000004472636f0a0a0a05b155ac1f246901b6b00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636f0a0a0a05b155ac1f246901b6
starting to empty socket buffer
recived sth unexpected 4d38b0643830d4aab0fcd4c2b2bbcfdec1f7c1bfccd7b2cda3ac3130d4c231c8d5c6f0c9fad0a7a3acbfc9cda8b9fdd7d4d6fab7fecef1d4a4d4bcb0ecc0ed31302e31302e31302e383a383038302f53656c66a3bbbcc6cab1ccd7b2cdb2bbcfdec1f7c1bfa3acb2bbcfdebdf0b6ee302e303038d4aa2fb7d6d6d3a3bb00
exception in empty_socket_buffer
emptyed
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07c6100002820000debf0700ac1f2469a8ac00004fe416c100000000dc020000
[keep_alive1] send ff00000000000000debf0700827f8e5b270f257c4472636f0a0a0a05b155ac1f246901b6e9dc
[keep-alive1] error
timed out
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "X:\Desktop\latest-wired.py", line 574, in main
    keep_alive1(SALT,package_tail,password,server)
  File "X:\Desktop\latest-wired.py", line 511, in keep_alive1
    res, address = s.recvfrom(1024)
timeout: timed out

c版日志：

CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x08'
host_ip = '172.31.36.105'
IPDOG = '\x01'
host_name = 'fuyumi'
PRIMARY_DNS = '10.10.10.22'
dhcp_server = '10.10.10.173'
AUTH_VERSION = '\x2f\x00'
mac = 0xD8CB8AEF65B9
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'
ror_version = True
keepalive1_mod = True

You are binding at 0.0.0.0!

[Challenge sent] 010216b62f000000000000000000000000000000
[Challenge recv] 020216b6e016000001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001dd6acbadfe3daa65b7723f2a268ac27d531353032363030303400000000000000000000000000000000000000000000000000000020080e673030866393bd3fb67b9373a5014cd15dceb5cc9001ac1f24690000000000000000000000007ca3ccfc31e163490100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a160a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f00000627f4446f8e47020ce075e95b0000d8cb8aef65b90000e913
[login recv] 0400000500f04800006748b90983220000ff00000000004472636f0a0a0a05c854ac1f246901cdb0050100010000000000000000000000011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000000000006000000000000000300
[Keepalive1 challenge_recv] 07011000028200002ab50700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232e016000000000000000301e0160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000200000006000000000000000300
[Keepalive1 challenge_recv] 070110000283000047b50700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232e016000000000000000301e0160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000300000006000000000000000300
[Keepalive1 challenge_recv] 070110000282000066b50700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232e016000000000000000301e0160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000200000006000000000000000300
[Keepalive1 challenge_recv] 070110000283000083b50700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232e016000000000000000301e0160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000300000006000000000000000300
[Keepalive1 challenge_recv] 0701100002820000a2b50700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232e016000000000000000301e0160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000200000006000000000000000300
[Keepalive1 challenge_recv] 0701100002830000bfb50700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232e016000000000000000301e0160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000300000006000000000000000300
[Keepalive1 challenge_recv] 0701100002820000deb50700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232e016000000000000000301e0160000323232323232320031000301001d
Failed to recv data: No error
[Challenge sent] 01024eb72f000000000000000000000000000000
[Challenge recv] 02024eb7f316000001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001d4b7ee242d136bda151ba72aee92d6da4313530323630303034000000000000000000000000000000000000000000000000000000200893b568adb48ff077577668ca8b80db420c03e887a4f501ac1f2469000000000000000000000000add5d3949459f2b50100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a160a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006cb6286831f20020c00919e880000d8cb8aef65b90000e913
[login recv] 0400000500f14800006748b90983220000ff00000000004472636f0a0a0a05db54ac1f246901e0b0050100010000000000000000000000011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000000000006000000000000000300
[Keepalive1 challenge_recv] 0701100002830000ffb50700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232f316000000000000000301f3160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000300000006000000000000000300
[Keepalive1 challenge_recv] 07011000028100001db60700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232f316000000000000000301f3160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000100000006000000000000000300
[Keepalive1 challenge_recv] 07011000028300003bb60700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232f316000000000000000301f3160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000300000006000000000000000300
[Keepalive1 challenge_recv] 070110000281000059b60700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232f316000000000000000301f3160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000100000006000000000000000300
[Keepalive1 challenge_recv] 070110000283000077b60700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232f316000000000000000301f3160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000300000006000000000000000300
[Keepalive1 challenge_recv] 070110000281000095b60700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232f316000000000000000301f3160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000100000006000000000000000300
[Keepalive1 challenge_recv] 0701100002830000b3b60700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232f316000000000000000301f3160000323232323232320031000301001d
Failed to recv data: No error
[Challenge sent] 010222f42f000000000000000000000000000000
[Challenge recv] 020222f4ff16000001000100f303e8f000000000ac1f2469f000a8ac00004fe416c100000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[Login sent] 0301001d6e403972d68c832c5144462c5ea056633135303236303030340000000000000000000000000000000000000000000000000000002008b68bb39db3358962207696e00d622163a2a448b6c4d401ac1f2469000000000000000000000000e866e69069fa54e00100000000667579756d6900000000000000000000000000000000000000000000000000000a0a0a160a0a0aad000000000000000000000000940000000500000001000000280a00000200000057696e646f7773000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000006e293580227f5020c402287bb0000d8cb8aef65b90000e913
[login recv] 0400000500f14800006748b90983220000ff00000000004472636f0a0a0a05e954ac1f246901eeb0050100010000000000000000000000011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
<<< Logged in >>>
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000000000006000000000000000300
[Keepalive1 challenge_recv] 0701100002830000d3b60700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232ff16000000000000000301ff160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000300000006000000000000000300
[Keepalive1 challenge_recv] 0701100002820000f2b60700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232ff16000000000000000301ff160000323232323232320031000301001d
Failed to recv data: No error
[Keepalive1 sent] 070108000100000000000000520100000000000000000000060000000200000006000000000000000300
[Keepalive1 challenge_recv] 07011000028300000fb70700ac1f2469a8ac00004fe416c100000000dc020000020c012607110000d8cb8aef65b90000000061000000000083f561000000000001323232323232ff16000000000000000301ff160000323232323232320031000301001d

**Comment by lwxyl** [comment]
燕京理工学院，教学不咋地，坑钱技术倒是6的很。。。

**Comment by ly0** [comment]
去掉 keepalive1试试？
