### ISSUE TITLE
drcom6.0（P）版抓包后，使用P版配置生成器生成txt失败

### ISSUE THREAD

**Issue by bybwHX** [drcoms/drcom-generic#266]
使用的客户端是广东工业大学提供的6.0P版客户端，按照wiki步骤进行抓包
cmd显示

![default](https://user-images.githubusercontent.com/14385798/31731972-694e8aac-b469-11e7-8437-f7e9bd78be7e.JPG)

多次重复抓取和配置均失败，生成的txt文件一片空白。
求教，6.0p是不是不适合用wiki的配置文件？

抓包文件双手奉上_(:з」∠)_

[11.zip](https://github.com/drcoms/drcom-generic/files/1395580/11.zip)

**Comment by mchome** [comment]
```
server = '10.0.3.2'
pppoe_flag = '\x2e'
keep_alive2_flag = '\xdc'
```
