### ISSUE TITLE
NoneType' object has no attribute 'start'   6.0.0 p版 广东工业大学

### ISSUE THREAD

**Issue by Hanson7300** [drcoms/drcom-generic#267]
抓包文件如下 https://pan.baidu.com/s/1miefsCg   
生成的config一片空白
有好的解决办法吗?

**Comment by Hanson7300** [comment]
6.00p版啊老哥

**Comment by Hanson7300** [comment]
找到解决办法了,在这里选择Drcom版本并上传抓包文件dr.pcapng,等待一点时间即可
https://drcoms.github.io/drcom-generic/
我也不知道对不对,还在试...

**Comment by mchome** [comment]
#266

**Comment by mchome** [comment]
下次发百度云的一律不看
