### ISSUE TITLE
广工大学城1~2分钟掉一次线，能重连，运行pppoe.sh，报错结果如下

### ISSUE THREAD

**Issue by 622115717** [drcoms/drcom-generic#268]
root@Hiwifi:~# pppoe.sh
Test connectivity to auth server
PING 10.0.3.2 (10.0.3.2) 56(84) bytes of data.
64 bytes from 10.0.3.2: icmp_req=1 ttl=61 time=97.6 ms

--- 10.0.3.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 97.660/97.660/97.660/0.000 ms
OK
[*]  auth svr: 10.0.3.2
[*]  pppoe_flag: 6a
[*]  keep_alive2_flag: dc
[*]  open local port:61440
[*]  DEBUG MODE:False
[*]  pppoe: send challenge request
[*]  pppoe: received challenge response
[*]  pppoe: send heartbeat request
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
[*]  pppoe: received challenge response
Traceback (most recent call last):
  File "/usr/bin/drcom", line 336, in <module>
    main()
  File "/usr/bin/drcom", line 331, in main
    pppoe.send(s)
  File "/usr/bin/drcom", line 196, in send
    data = self._make_heartbeat(sip=sip, challenge_seed=seed, first=True)
  File "/usr/bin/drcom", line 164, in _make_heartbeat
    crc, foo = gen_crc(challenge_seed, encrypt_mode)
  File "/usr/bin/drcom", line 74, in gen_crc
    foo = hashlib.new('md4', data).digest()
  File "/usr/lib/python2.7/hashlib.py", line 110, in __py_new
    return __get_builtin_constructor(name)(string)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md4

**Comment by mchome** [comment]
已更新
