### ISSUE TITLE
p版配置生成器生成config出错

### ISSUE THREAD

**Issue by ghdefe** [drcoms/drcom-generic#270]
已经修改filename，但还是怎样都不行
提示这个
C:\Users\wrdef\Desktop\抓包>python drcom_p_config.py > config.txt
Traceback (most recent call last):
  File "drcom_p_config.py", line 20, in <module>
    offset = re.search('\x07[\x00-\xFF]\x60\x00\x03\x00', text).start()
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by NERD-k** [comment]
可以用Wiki里提到的其他库里的方法，有人做了一个网站直接提取出来的

**Comment by ghdefe** [comment]
@NERD-k 在哪里？？找不到啊，能给个地址么

**Comment by mchome** [comment]
...把你抓包拽上输入框

**Comment by manba024** [comment]
怎么的我的拽上去没用？直接提示我下载了？？
