### ISSUE TITLE
中国民航大学网络升级后原脚本不再维护

### ISSUE THREAD

**Issue by feilongfl** [drcoms/drcom-generic#271]
由于校园网络升级，原有dr.com程序不再维护

中国民航大学的朋友请转移到

[https://gist.github.com/feilongfl/d6c6c7b09a574e7f105b8a458f773d63/raw/7521f0d6fe1cfa1fa069e64455d59212a8ca5c8b/dr.fish](https://gist.github.com/feilongfl/d6c6c7b09a574e7f105b8a458f773d63/raw/7521f0d6fe1cfa1fa069e64455d59212a8ca5c8b/dr.fish)

**Comment by ly0** [comment]
已更新wiki 本issue关闭。
