### ISSUE TITLE
fail to connect the internet

### ISSUE THREAD

**Issue by weearc** [drcoms/drcom-generic#272]
for i use 5.2.x-d in chongqing univercity on my manjaro with python 3.6 i can't connect to the net use the present latest-wired.py as well as  the python3 veresion,which gives back 
`File "latest-wired.py", line 86
    print s
          ^
SyntaxError: Missing parentheses in call to 'print'
`
for the python version

**Comment by mchome** [comment]
![image](https://user-images.githubusercontent.com/7392658/32312234-b23d8f6e-bfd7-11e7-84f6-e9cdfc1e6177.png)
