### ISSUE TITLE
6.0.0p版登陆一段时间后掉线，日志显示有heartbeat response failed

### ISSUE THREAD

**Issue by wertasy** [drcoms/drcom-generic#273]
在电脑上能使用脚本进行登陆，但是过2到3分钟就会掉线。
放到路由器里掉线后会重连。
请大神帮忙看下，如何能不掉线稳定使用。
附上log：
[drcom_client.log](https://github.com/drcoms/drcom-generic/files/1453137/drcom_client.log)

**Comment by wertasy** [comment]
challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:070110000200000081312c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002e81312c00df73c895e613e5b600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
auth svr: 172.18.0.7
pppoe_flag: 2e
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000a8312c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002ea8312c00c22ce8ef0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0702300004002000300bfabb000000004439d8edca90000e6a1ab2aeb85b04deb0824000100000000000000000000000
[keep-alive2] send1
	packet:070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv file, resending..
[keep-alive2] send1
	packet:070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1
	packet:070128000b02dc022f12000000000000a8312c000000000000000000000000000000000000000000
[keep-alive2] send2
	packet:070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2
	packet:070128000b02dc022f12000000000000a8312c000000000000000000000000000000000000000000
[keep-alive2] send3
	packet:070228000b03dc022f12000000000000a8312c00c72f31017e000000000000000000000000000000
[keep-alive2] recv3
	packet:070228000b04dc022f12000000000000a8312c000000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive2] send 3
	packet:070328000b01dc022f12000000000000a8312c000000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070328000b02dc022f12000000000000a8312c000000000000000000000000000000000000000000
[keep_alive2] send 4
	packet:070428000b03dc022f12000000000000a8312c00c72f31017e000000000000000000000000000000
[keep_alive2] recv
	packet:070428000b04dc022f12000000000000a8312c000000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0702080001000000
pppoe: received challenge response
	packet:07021000020000000c322c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070360000300000000000000ca758b6b0063002e0c322c008a35b8f50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0703300004002000300bfabb000000004439d8edca90000e6a1ab2aeb85b04deb0824000100000000000000000000000
[keep_alive2] send 5
	packet:070528000b01dc022f12000000000000a8312c000000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070528000b02dc022f120000000000000c322c000000000000000000000000000000000000000000
[keep_alive2] send 6
	packet:070628000b03dc022f120000000000000c322c00c72f31017e000000000000000000000000000000
[keep_alive2] recv
	packet:070628000b04dc022f120000000000000d322c000000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0703080001000000
pppoe: received challenge response
	packet:070310000200000071322c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070460000300000000000000ca758b6b0063002e71322c00228fcc3d961502a900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000008f322c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002e8f322c009486fd0588d4059400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000ad322c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002ead322c00fbd328c0a2cb249800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000cb322c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002ecb322c008916d1dae005db6300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000e9322c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002ee9322c003abb5f570b16a97c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:070110000200000007332c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002e07332c0022b7195cadd6ea6e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:070110000200000026332c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002e26332c00388ba3b9f6ea9eff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000009d332c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002e9d332c00d87176b80eceff8d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000bb332c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002ebb332c00392276dff2d340c400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000d9332c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002ed9332c000f58245d107a1cdc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000f7332c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002ef7332c00530eba44708cce4100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:070110000200000015342c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002e15342c00eb332a6462ff80ff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:070110000200000034342c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002e34342c00faa5ccbd0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0702300004002000300bfabb000000004439d8edca90000e6a1ab2aeb85b04deb0824000100000000000000000000000
[keep_alive2] send 7
	packet:070728000b01dc022f120000000000000d322c000000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070728000b02dc022f1200000000000034342c000000000000000000000000000000000000000000
[keep_alive2] send 8
	packet:070828000b03dc022f1200000000000034342c00c72f31017e000000000000000000000000000000
[keep_alive2] recv
	packet:070828000b04dc022f1200000000000034342c000000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0702080001000000
pppoe: received challenge response
	packet:070210000200000098342c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070360000300000000000000ca758b6b0063002e98342c00a25e8f870000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0703300004002000300bfabb000000004439d8edca90000e6a1ab2aeb85b04deb0824000100000000000000000000000
[keep_alive2] send 9
	packet:070928000b01dc022f1200000000000034342c000000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070928000b02dc022f1200000000000098342c000000000000000000000000000000000000000000
[keep_alive2] send 10
	packet:070a28000b03dc022f1200000000000098342c00c72f31017e000000000000000000000000000000
[keep_alive2] recv
	packet:070a28000b04dc022f1200000000000098342c000000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0703080001000000
pppoe: received challenge response
	packet:0703100002000000fc342c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070460000300000000000000ca758b6b0063002efc342c006a6bc8340000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0704300004002000300bfabb000000004439d8edca90000e6a1ab2aeb85b04deb0824000100000000000000000000000
[keep_alive2] send 11
	packet:070b28000b01dc022f1200000000000098342c000000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070b28000b02dc022f12000000000000fc342c000000000000000000000000000000000000000000
[keep_alive2] send 12
	packet:070c28000b03dc022f12000000000000fc342c00c72f31017e000000000000000000000000000000
[keep_alive2] recv
	packet:070c28000b04dc022f12000000000000fc342c000000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0704080001000000
pppoe: received challenge response
	packet:070410000200000060352c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070560000300000000000000ca758b6b0063002e60352c005236b6ac0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0705300004002000300bfabb000000004439d8edca90000e6a1ab2aeb85b04deb0824000100000000000000000000000
[keep_alive2] send 13
	packet:070d28000b01dc022f12000000000000fc342c000000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070d28000b02dc022f1200000000000060352c000000000000000000000000000000000000000000
[keep_alive2] send 14
	packet:070e28000b03dc022f1200000000000060352c00c72f31017e000000000000000000000000000000
[keep_alive2] recv
	packet:070e28000b04dc022f1200000000000060352c000000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0705080001000000
pppoe: received challenge response
	packet:0705100002000000c4352c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070660000300000000000000ca758b6b0063002ec4352c001ab5ff8f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0706300004002000300bfabb000000004439d8edca90000e6a1ab2aeb85b04deb0824000100000000000000000000000
[keep_alive2] send 15
	packet:070f28000b01dc022f1200000000000060352c000000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070f28000b02dc022f12000000000000c4352c000000000000000000000000000000000000000000
[keep_alive2] send 16
	packet:071028000b03dc022f12000000000000c4352c00c72f31017e000000000000000000000000000000
[keep_alive2] recv
	packet:071028000b04dc022f12000000000000c4352c000000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0706080001000000
pppoe: received challenge response
	packet:07061000020000002f362c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070760000300000000000000ca758b6b0063002e2f362c002f1c8f0ac18c5b0600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000004d362c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002e4d362c006898b893199da4bb00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000006b362c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002e6b362c004a055a9f92a8e66c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:070110000200000089362c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ca758b6b0062002e89362c00777f2cf771c4ce8300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000a7362c00ca758b6ba8a80000e659f16700000000dc020000
pppoe: send heartbeat request

**Comment by ly0** [comment]
是当前项目下最新的 latest-pppoe.py 吗

**Comment by CGxyol** [comment]
6.0.0p哥们加下我好友，咱们一块讨论讨论（教教我= =）a8530516@163.com

**Comment by mchome** [comment]
提供一下抓包

**Comment by CGxyol** [comment]
抓包里面有我的学号和密码= =发下你的邮箱然后我私发给你吧
