### ISSUE TITLE
drcom版本 5.2.0d，已经拨号成功了，运行脚本 报错，windows闪退 如图，不知问题出在哪

### ISSUE THREAD

**Issue by WangNingkai** [drcoms/drcom-generic#275]
![snipaste_2017-11-21_14-06-24](https://user-images.githubusercontent.com/23030927/33057452-0afab42c-cec6-11e7-8f9d-4ae78d3fb724.png)
![snipaste_2017-11-21_14-10-34](https://user-images.githubusercontent.com/23030927/33057461-12e96db8-cec6-11e7-836f-5f37eee482bb.png)

**Comment by ly0** [comment]
提交 log 文件，配置好的脚本，官方客户端抓包文件
