### ISSUE TITLE
latest-wired.py 存在错误，已尝试修改成功，请查看。

### ISSUE THREAD

**Issue by Jumeo7** [drcoms/drcom-generic#276]
File "/Users/download/latest-wired.py", line 564
    keep_alive1(SALT,package_tail,password,server)
    ^
IndentationError: unexpected indent

**Comment by Jumeo7** [comment]
@mchome 谢谢您为此所做的一切。:)

**Comment by ly0** [comment]
![image](https://user-images.githubusercontent.com/1551736/33369777-8bd8120e-d530-11e7-9ef4-b0437874b79c.png)
还能zhe'zho这种操作
