### ISSUE TITLE
5.2.0（D版）配置生成器生成config出错，在线生成器也不行

### ISSUE THREAD

**Issue by zigitn** [drcoms/drcom-generic#278]
我抓包的流程是先退出drcom，然后打开wireshark，开始抓包，然后登陆，等待十几秒之后注销，点结束抓包，导出文件。
运行结果：
`Traceback (most recent call last):`
`File ".\drcom_d_config.py", line 20, in <module>`
`offset = re.search('\xF0\x00\xF0\x00[\x00-\xFF]{4}[\x03\x07]\x01', text).start() + 8`
`AttributeError: 'NoneType' object has no attribute 'start'`
使用在线配置生成器一片空白......

这是我抓的包，麻烦各位帮忙看看，先行谢过。
[dr.zip](https://github.com/drcoms/drcom-generic/files/1545364/dr.zip)

**Comment by mchome** [comment]
```
server = '192.168.255.249'
username = '201608010122'
password = ''
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x01'
host_ip = '10.29.6.244'
IPDOG = '\x01'
host_name = 'fuyumi'
PRIMARY_DNS = '119.29.29.29'
dhcp_server = '0.0.0.0'
AUTH_VERSION = '\x0a\x00'
mac = 0x6045cba1b647
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'
ror_version = False
```
