### ISSUE TITLE
协议细节?

### ISSUE THREAD

**Issue by WenceyWang** [drcoms/drcom-generic#279]
我认为我可以参与做一些事情,可是几乎没有面向开发者的文档.

我希望知道协议的运作细节.

现有的代码看起来混乱,我该如何入手阅读?

**Comment by ly0** [comment]
https://github.com/drcoms/drcom-generic/blob/master/latest-wired.py
从这里的main开始读

**Comment by mchome** [comment]
一边跑，一边用wireshark看，就懂了。
