### ISSUE TITLE
關於D版5.2.0的IPv6

### ISSUE THREAD

**Issue by as03051026** [drcoms/drcom-generic#28]
配置完成之後IPv4能夠正常使用，但是IPv6只能Ping通校內網，請問是沒有加入IPv6的相關認證嗎

**Comment by ly0** [comment]
你们居然IPV6也要认证 cernet 不是明确要求教育网必须免费么？
我记得drcom是有个ipv6的控制字段，但是时间太久我忘了，麻烦标准客户端正常登陆一次把截的包发一下。

**Comment by as03051026** [comment]
抱歉，這幾天一直沒上Gmail所以沒看到，現在發給你，請幫我看一下，謝謝

在 2015年11月2日 下午8:31，latyas(懒) <notifications@github.com>写道：

**Comment by as03051026** [comment]
以及我們學校似乎是鑽了個空子，宿舍區是運營商網絡，教學區是可以上教育網的貌似，不過上外網也要註冊運營商網絡才行

在 2015年11月2日 下午8:31，latyas(懒) <notifications@github.com>写道：

**Comment by ly0** [comment]
😂 说好的包呢？

**Comment by mchome** [comment]
@as03051026 https://github.com/drcoms/drcom-generic/blob/master/latest-wired.py#L262 改成
``` python
data += '\xa8\x39' #delimeter
```
试下

**Comment by as03051026** [comment]
發你私人郵箱了

2015-11-08 19:14 GMT+08:00 latyas(懒) <notifications@github.com>:

**Comment by as03051026** [comment]
链接: http://pan.baidu.com/s/1sjxL8W9 密码: ppd3

**Comment by as03051026** [comment]
@mchome 不行呢…… 
@ly0 請問可以幫我看一下抓包結果嗎

**Comment by szy18** [comment]
@as03051026  终于找到了可用的插件了，安装即可，免配置。

先给下载地址：http://downloads.openwrt.org.cn/PandoraBox/ralink/mt7620_old/packages/6relayd_2013-07-26-2ed520c500b0fbb484cfad5687eb39a0da43dcf7_ralink.ipk

安装方法：
打开WinSCP，选择SCP模式。地址192.168.1.1，端口号22，用户名root，密码admin。把下载的ipk文件复制到路由的tmp目录，运行ipk，再重启路由器。
最后说一下，安装完成之后重启路由，在路由后台--系统--启动项，把6relayd由“已禁用”改为“启动”，再重启，就可以上校外的ipv6了。

试试吧，我已经成功了！

**Comment by szy18** [comment]
成功了吗？奇怪！我的突然又不行了。

**Comment by iceriverweng** [comment]
问题解决了吗？
