### ISSUE TITLE
广东工业大学大学城心跳失败

### ISSUE THREAD

**Issue by Liudaxian12** [drcoms/drcom-generic#281]
auth svr: 10.0.3.2
pppoe_flag: 2f
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000a3d8cd050a1e43f7a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1e43f70062002fa3d8cd0526e4de095e101b6200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0702300004002000aa12c5a0000000004439d8eda0000c049f5682c334bf0440b0820060000000000000000000000000
[keep-alive2] send1
	packet:070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv file, resending..
[keep-alive2] send1
	packet:070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1
	packet:070128000b02dc022f12000000000000a4d8cd050000000000000000000000000000000000000000
[keep-alive2] send2
	packet:070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2
	packet:070128000b02dc022f12000000000000a4d8cd050000000000000000000000000000000000000000
[keep-alive2] send3
	packet:070228000b03dc022f12000000000000a4d8cd05c72f31017e000000000000000000000000000000
[keep-alive2] recv3
	packet:070228000b04dc022f12000000000000a4d8cd050000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive2] send 3
	packet:070328000b01dc022f12000000000000a4d8cd050000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070328000b02dc022f12000000000000a5d8cd050000000000000000000000000000000000000000
[keep_alive2] send 4
	packet:070428000b03dc022f12000000000000a5d8cd05fefdf63b5e4f3073000000000000000000000000
[keep_alive2] recv
	packet:070428000b04dc022f12000000000000a5d8cd050000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0702080001000000
pppoe: received challenge response
	packet:070210000201000009d9cd050a1e43f7a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0703600003000000000000000a1e43f70063002f09d9cd053a67f3c94f53c3a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0703300004002000aa12c5a0000000004439d8eda0000c049f5682c334bf0440b0820060000000000000000000000000
[keep_alive2] send 5
	packet:070528000b01dc022f12000000000000a5d8cd050000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070528000b02dc022f1200000000000009d9cd050000000000000000000000000000000000000000
[keep_alive2] send 6
	packet:070628000b03dc022f1200000000000009d9cd05e7d4d21a8800ce7f000000000000000000000000
[keep_alive2] recv
	packet:070628000b04dc022f1200000000000009d9cd050000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0703080001000000
pppoe: received challenge response
	packet:07031000020100006dd9cd050a1e43f7a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0704600003000000000000000a1e43f70063002f6dd9cd05552086e98d98439b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0704300004002000aa12c5a0000000004439d8eda0000c049f5682c334bf0440b0820060000000000000000000000000
[keep_alive2] send 7
	packet:070728000b01dc022f1200000000000009d9cd050000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070728000b02dc022f120000000000006dd9cd050000000000000000000000000000000000000000
[keep_alive2] send 8
	packet:070828000b03dc022f120000000000006dd9cd057911d15d96589c0e000000000000000000000000
[keep_alive2] recv
	packet:070828000b04dc022f120000000000006dd9cd050000000000000000000000000000000000000000
pppoe: send challenge request
	packet:0704080001000000
pppoe: received challenge response
	packet:0704100002010000d1d9cd050a1e43f7a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0705600003000000000000000a1e43f70063002fd1d9cd0582d3c91964d6880700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0705300004002000aa12c5a0000000004439d8eda0000c049f5682c334bf0440b0820060000000000000000000000000
[keep_alive2] send 9
	packet:070928000b01dc022f120000000000006dd9cd050000000000000000000000000000000000000000
[keep_alive2] recv
	packet:070928000b02dc022f12000000000000d2d9cd050000000000000000000000000000000000000000
[keep_alive2] send 10
	packet:070a28000b03dc022f12000000000000d2d9cd05cb0d005defae0bdb000000000000000000000000
[keep_alive2] recv
	packet:070a28000b04dc022f12000000000000d2d9cd050000000000000000000000000000000000000000

双手献上抓包

**Comment by Liudaxian12** [comment]
[dr3.zip](https://github.com/drcoms/drcom-generic/files/1585393/dr3.zip)

**Comment by ly0** [comment]
昂？看上去这个流程有毒，是用的哪个脚本？

**Comment by jiangming1399** [comment]
没收到相关消息，目前正常，尝试使用贴吧版本？
