### ISSUE TITLE
在线匹配无法获取信息

### ISSUE THREAD

**Issue by nuomi1** [drcoms/drcom-generic#29]
本地提取出错：

```
Traceback (most recent call last):
  File "drcom_d_config.py", line 20, in <module>
    offset = re.search('\xf0\x00\xf0\x00[\x00-\xFF]{4}\x03\x01', text).start() + 8
AttributeError: 'NoneType' object has no attribute 'start'
```

在线提取无法获取 server，username 乱码。

————————————————————

链接： http://share.weiyun.com/af74a0d0670893974970383a371512f5 （密码：Z2sy）

这是抓包。

链接： http://share.weiyun.com/b4456aa5928fec4f58cb43b42c478397 （密码：qRL3）

这是学校客户端的日志，貌似从 u62 升级到了 u64。

————————————————————

有时客户端发神经，显示获取用户信息超时，但此时可以通过网页进行账号认证。
该网页认证同时用于 WiFi 接入的认证。

**Comment by mchome** [comment]
试下 http://pastebin.com/QH0WgEAM 和 http://pastebin.com/D59NnMDA

**Comment by nuomi1** [comment]
忘记补充了，DRCOM 版本是 5.2.0 X，使用静态地址。

路由器 Lenovo Y1，固件 PandoraBox R2 14.09 / LuCI Trunk (0.12+svn-r1024)。

已在「网络-接口-WAN-基础设置-协议」处选择静态地址，并正确填写 IP、子网掩码、网关、DNS 信息。

下面是运行结果：

--------------------------------------------
/www# python /usr/bin/drcom.py
--------------------------------------------

auth svr:210.38.163.138
username:151110101
hostname:DESKTOP-POIJ8
[login] login sent
Traceback (most recent call last):
  File "/usr/bin/drcom.py", line 275, in <module>
    main()
  File "/usr/bin/drcom.py", line 266, in main
    package_tail = login(username, hostname, server)
  File "/usr/bin/drcom.py", line 222, in login
    data, address = s.recvfrom(1024)
socket.timeout: timed out

**Comment by ly0** [comment]
你这个是x版 参考插版的方法
2015年11月5日 下午6:48，"nuomi1" <notifications@github.com>写道：

**Comment by nuomi1** [comment]
@ly0

按照 X 版 wiki 操作，D 版配置生成器无法使用，错误信息在 1L。

使用 2L 提取的 config 和 drcom.py，错误信息在 3L。

把 2L 提取的信息填写至 https://github.com/drcoms/drcom8021x/blob/master/main.py 和 https://github.com/drcoms/drcom-generic/blob/master/latest-wired.py，一直卡在「Sending EAPOL start」。

再补充一句，认证工具写着「银河风云」出品，实际内容则是 DRCOM。

**Comment by ly0** [comment]
应该是802.1X认证没过。@mchome NTR君帮解决下

**Comment by mchome** [comment]
先尝试只登陆802.1x

**Comment by nuomi1** [comment]
``need_drcom = False`` 依旧卡在 ``Sending EAPOL start``。

路由器安装 wpa-cli、wpa-supplicant 和 luci-app-w8021x，在「网络 - 有线网络 IEEE 802.1X 认证」中填写「EAP-Method = MD5-质询」和「网络类型 = 局域网 / 互联网」，认证均失败。

**Comment by nuomi1** [comment]
这几天又搞了一下，mentohust -a2（赛尔）可以找到服务器，并且发送账号，密码和 MAC，但提示认证失败。
————————————————————
Windows 下用官方客户端，A 账号登陆，点击取消，提示取消 802.1X 登陆，但此时可以使用 B 账号走网页认证。
————————————————————
猜测走 802.1X 就可以了，但怎么都搞不好……

**Comment by nuomi1** [comment]
之前拿别人的电脑过来测试，使用的是我的 IP，忘记改回他的了。
改回来后，直接执行 main.py（need_drcom = False）即可通过 802.1x 认证，DRCOM 方面直接走网页认证。

所以说 X 版有何卵用←_←

**Comment by ly0** [comment]
2333333 你们学校真好

**Comment by nuomi1** [comment]
@ly0 其实有可能是后台改了策略，正在测试 5GHz WiFi，不过不知道能不能部署。

**Comment by nuomi1** [comment]
刚又试了一下，直接 wpa_supplicant 走一遍 IEEE 802.1X with MD5 就可以了……
