### ISSUE TITLE
路由器无法自启脚本上网，Putty手动运行正常（5.2.0 D版）

### ISSUE THREAD

**Issue by seaswimmer** [drcoms/drcom-generic#295]
尝试了以下方法，重启路由器后无法自启脚本，无法上网：
1、 /etc/rc.local中添加sleep 10 && python /usr/bin/drcom &
2、 /etc/hotplug.d/iface/99-drcom:
#!/bin/sh
#/etc/hotplug.d/iface/99-drcom
if [ "$ACTION" = ifup ]; then 
    if [ "${INTERFACE}" = "wan" ]; then
        sleep 10 && python /usr/bin/drcom
    fi
fi

以上均chmod +x

但是，通过putty连上路由器后，直接运行命令：python /usr/bin/drcom，可以上网。

请问该怎么解决这个问题呢？

[drcom_client.log](https://github.com/drcoms/drcom-generic/files/1855351/drcom_client.log)
[Drcom.txt](https://github.com/drcoms/drcom-generic/files/1855360/Drcom.txt)

**Comment by seaswimmer** [comment]
auth svr: 192.168.255.251
username: 219065
password: 
mac: 0x20c903fa844
bind ip: 0.0.0.0
[challenge] recv 0202c8b6a90422000a000100f203e8f000000000ac158bf8f000a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202c8b6a90422000a000100f203e8f000000000ac158bf8f000a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001afcff66b5ce2e4982e8c1f9ee36b3c11b3231393036350000000000000000000000000000000000000000000000000000000000002001fef3f68a666adc8903e076e999635470a8f637e229ea01ac158bf90000000000000000000000003d032b6f81bdf55701000000004452434f4d4655434b4552000000000000000000000000000000000000000000d2270021ac158bfe000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000067e76926cbfb8020c705139d40000020c903fa8440000e913
[login] send 0301001afcff66b5ce2e4982e8c1f9ee36b3c11b3231393036350000000000000000000000000000000000000000000000000000000000002001fef3f68a666adc8903e076e999635470a8f637e229ea01ac158bf90000000000000000000000003d032b6f81bdf55701000000004452434f4d4655434b4552000000000000000000000000000000000000000000d2270021ac158bfe000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000067e76926cbfb8020c705139d40000020c903fa8440000e913
[login] packet sent.
[login] recv 04000005001e15000059a22300ffffffffff00000000004472636fc0a8fedca0ccac158bf801d1b00500030100
[login] loged in
[login] login sent
package_tail 4472636fc0a8fedca0ccac158bf801d1
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send fffcff66b5ce2e4982e8c1f9ee36b3c11b0000004472636fc0a8fedca0ccac158bf801d1b5ec00000000
[keep-alive1] recv 070110000600b5ecd004f60dac158bf8a8ac00004fe416c100000000dc0200000300000003000000050000001e15000059a22300ffffffffffffffffffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070010010b06dc022f12000000000000a8ac00004fe416c100000000dc0200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000100100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a24000000000000007cc5835a38a4ed0938a4ed0938a4ed096187fe093aa4ed0943b8e10939a4ed09bbacb00932a4ed09bbb8e3093aa4ed0957bbe60939a4ed0957bbe7093da4ed0957bbe9093aa4ed0938a4ec0982a4ed090e82e9093ba4ed090e82e60930a4ed09ffa2eb0939a4ed09c784e9093ba4ed09
[keep-alive2] recv file, resending..
[keep-alive2] send2 070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2 070128000b02dc022f12000000000000d004f60d0000000000000000000000000000000000000000
[keep-alive2] send3 070228000b03dc022f12000000000000d004f60d0000000000000000ac158bf90000000000000000
[keep-alive2] recv3 070228000b04dc022f12000000000000d104f60d0000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive1] send fffcff66b5ce2e4982e8c1f9ee36b3c11b0000004472636fc0a8fedca0ccac158bf801d1b61d00000000
[keep-alive1] recv 070110000600b61d9805f60dac158bf8a8ac00004fe416c100000000dc02000017000000290000008c0000001e15000059a22300ffffffffffffffffffffffff
[keep_alive2] send 3 070328000b01dc022f12000000000000d104f60d0000000000000000000000000000000000000000
[keep_alive2] recv 070328000b02dc022f120000000000009805f60d0000000000000000000000000000000000000000
[keep_alive2] send 4 070428000b03dc022f120000000000009805f60d0000000000000000ac158bf90000000000000000
[keep_alive2] recv 070428000b04dc022f120000000000009805f60d0000000000000000000000000000000000000000

**Comment by ly0** [comment]
查一下wan ifup 的启动脚本怎么放。
