### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'start'

### ISSUE THREAD

**Issue by XTStarry** [drcoms/drcom-generic#296]
Traceback (most recent call last):
  File "drcom_p_config.py", line 20, in <module>
    offset = re.search('\x07[\x00-\xFF]\x60\x00\x03\x00', text).start()
AttributeError: 'NoneType' object has no attribute 'start'
所用脚本为drcom_p_config.py

**Comment by ly0** [comment]
试试  http://drcoms.github.io/drcom-generic/
