### ISSUE TITLE
大神好，6.0P File "drcom_p_config.py", line 20, in <module> AttributeError: 'NoneType' object has no attribute 'start'

### ISSUE THREAD

**Issue by crazzy01** [drcoms/drcom-generic#297]
C:\Users\Administrator\Desktop\drcom-generic-master>python drcom_p_config.py > 1
.txt
Traceback (most recent call last):
  File "drcom_p_config.py", line 20, in <module>
    offset = re.search('\x07[\x00-\xFF]\x60\x00\x03\x00', text).start()
AttributeError: 'NoneType' object has no attribute 'start'
在线版的等了半天也没有啥数据

[11.zip](https://github.com/drcoms/drcom-generic/files/1878280/11.zip)

**Comment by mchome** [comment]
请换浏览器，谢谢。
![auto configure](https://user-images.githubusercontent.com/7392658/38343857-cb600e4a-38b8-11e8-826c-3ed4cd53898c.png)

**Comment by crazzy01** [comment]
谢谢！~
