### ISSUE TITLE
请求作者大大做一个C版本的

### ISSUE THREAD

**Issue by clingings** [drcoms/drcom-generic#298]
![xud3 y z8hwo _kamse](https://user-images.githubusercontent.com/38092646/38534717-3dfff9c2-3cb2-11e8-90e3-2bbe0ffeed5c.png)

作者大大能否做一个这个python版的C语言版本  ，我们学校这个可以使用    但目前这个python环境装不到路由上

**Comment by Charlesmingquan** [comment]
https://github.com/mchome/dogcom

// 自己编译吧

**Comment by clingings** [comment]
怎么编译  我是特指图中红色的那个的C版本

**Comment by ly0** [comment]
你图中的是Python版的

**Comment by Charlesmingquan** [comment]
什么固件的路由。

**Comment by clingings** [comment]
小米路由器3g刷的老毛子固件Pandavan

**Comment by Charlesmingquan** [comment]
发你邮箱过来，我把Pandavan的发给你。

**Comment by clingings** [comment]
1147546989@qq.com  非常感谢
