### ISSUE TITLE
我用的是长沙保险职业学院_u6x   要填写的那里 修改了几个数字

### ISSUE THREAD

**Issue by HINSKAN** [drcoms/drcom-generic#3]
是不是这个PY 每过一段时间 会自动断一下 然后又好了  窗口不会关也没有任何异常显示 就是 网会断一下子  我现在是湖南农大的联通网

**Comment by iceriverweng** [comment]
额？如果再出现请帮忙抓个包看看

**Comment by HINSKAN** [comment]
有收到邮件吗

**Comment by iceriverweng** [comment]
收到了，您的反馈是？

2015-04-08 16:57 GMT+08:00 HINSKAN <notifications@github.com>:

**Comment by HINSKAN** [comment]
前面都是评论提醒自动邮箱 我发了你没收到 给我邮箱

**Comment by iceriverweng** [comment]
iceriverweng@gmail.com

2015-04-08 22:49 GMT+08:00 HINSKAN <notifications@github.com>:

**Comment by HINSKAN** [comment]
已发送
