### ISSUE TITLE
电脑测试登陆不上

### ISSUE THREAD

**Issue by xdker** [drcoms/drcom-generic#30]
抓包文件    http://pan.baidu.com/s/1jGk2wjs  密码 3k7t

**Comment by mchome** [comment]
用latest-wired.py的时候抓个包

**Comment by xdker** [comment]
http://pan.baidu.com/s/10rHk6

**Comment by iceriverweng** [comment]
有试过使用d版本的配置吗？

**Comment by xdker** [comment]
用的就是d版

**Comment by iceriverweng** [comment]
好的。。能加群吗。。我们在进一步测试 
318495368

**Comment by xdker** [comment]
Type: Wrong client version or account has been banned. (0x15)  ?
