### ISSUE TITLE
openwrt luci上的drcom客户端未运行

### ISSUE THREAD

**Issue by InDimension** [drcoms/drcom-generic#301]
配置好luci页面的参数，并且选择开启Dr.com后，客户端运行检测脚本，即该页面顶端的显示为客户端未运行。且进入openwrt的启动项中，若选择启用Drcom该项，会在刷新后变为禁用。以至于未能正常使用该luci客户端。

**Comment by InDimension** [comment]
root@OpenWrt:~# drcom
Traceback (most recent call last):
  File "/bin/drcom", line 6, in <module>
    from hashlib import md5
  File "/usr/lib/python2.7/hashlib.py", line 149, in <module>
    import logging
ImportError: No module named logging

**Comment by Rabenda** [comment]
这显示的是你没有logging包吧
试试安装一下？ pip install logging

**Comment by Rabenda** [comment]
看起来像hash全炸了一样 重新装一下hashlib？

**Comment by InDimension** [comment]
在安装了pip包然后顺带一系列的code包也捆绑安装后，hash的错误没了
出现了
root@OpenWrt:~# drcom
Traceback (most recent call last):
  File "/bin/drcom", line 11, in <module>
    execfile('/etc/config/drcom.conf',globals())
IOError: [Errno 2] No such file or directory: '/etc/config/drcom.conf'
而该目录下的文件为drcom，内容就是luci页面配置的内容
若drcom尾缀添加.conf则会出现
root@OpenWrt:~# drcom
Traceback (most recent call last):
  File "/bin/drcom", line 11, in <module>
    execfile('/etc/config/drcom.conf',globals())
  File "/etc/config/drcom.conf", line 2
    config drcom
               ^
SyntaxError: invalid syntax

**Comment by InDimension** [comment]
查看了一下以往相关问题，暂不推荐使用。
