### ISSUE TITLE
6.0.0P配置生成问题

### ISSUE THREAD

**Issue by 827764082** [drcoms/drcom-generic#303]
C:\Users\Administrator\Desktop\s>python drcom_p_config.py > config.txt
Traceback (most recent call last):
  File "drcom_p_config.py", line 20, in <module>
    offset = re.search('\x07[\x00-\xFF]\x60\x00\x03\x00', text).start() 
AttributeError: 'NoneType' object has no attribute 'start'
附上抓包文件

[dr.zip](https://github.com/drcoms/drcom-generic/files/2019990/dr.zip)

**Comment by cxgreat2014** [comment]
同样的问题，6.0版本貌似特征改了不少

**Comment by mchome** [comment]
server = '221.12.83.102'
pppoe_flag = '\x2d'
keep_alive2_flag = '\x00'
