### ISSUE TITLE
重庆大学更新drcom版本为6.0.0（D）

### ISSUE THREAD

**Issue by weearc** [drcoms/drcom-generic#308]
rt，建议将wiki中的相关说明移除，目前在尝试使用6.0.0版本进行脚本跟进。

**Comment by mchome** [comment]
自己改

**Comment by lbbym** [comment]
六年前上大学一直在用，当时用的一个不要钱的渣路由器，又插了个树莓派执行程序，让我能成功在学校连上可用的互联网。
