### ISSUE TITLE
drcom6.0（P）版抓包后，使用P版配置生成器生成txt失败

### ISSUE THREAD

**Issue by noahhhi** [drcoms/drcom-generic#310]
按照教程抓包，但是第一步生成配置文件一直是空白，更换电脑也一样，之前的issue也看到差不多的问题，所以也来求助了d.
https://drive.google.com/file/d/1DSyGQxVpIO6X8hw7UEyEWLrQK9v13q1l/view?usp=sharing

**Comment by mchome** [comment]
server = '221.12.83.102'
pppoe_flag = '\x2d'
keep_alive2_flag = '\x00'

**Comment by yh-cs** [comment]
> server = '221.12.83.102'
> pppoe_flag = '\x2d'
> keep_alive2_flag = '\x00'

你好我的也是6.0p版生成配置失败
[drp.zip](https://github.com/drcoms/drcom-generic/files/3579815/drp.zip)
能帮忙看一下问题在哪里吗？

**Comment by amekao** [comment]
> server = '221.12.83.102'
> pppoe_flag = '\x2d'
> keep_alive2_flag = '\x00'

那个自动配置网好像崩了，然后我下载drcom_p_config提示offset = re.search('\x07[\x00-\xFF]\x60\x00', text).start()这句是none无法start，请问是怎么解决
