### ISSUE TITLE
5.21P版本，出现691报错，无法拨号.

### ISSUE THREAD

**Issue by wang08270** [drcoms/drcom-generic#313]
大佬你的关于P版的PPPoE拨号问题解释看不懂呀。

**Comment by Rabenda** [comment]
691是账号本身问题 请用官方客户端测试你的账号可用性

**Comment by mchome** [comment]
你倒是说哪里不懂呀。

**Comment by wang08270** [comment]
这下面我不知道是在哪里执行
如果网络通了，继续执行以下操作。

执行 cp /tmp/ppp/options.wan0 /jffs/options.wan0
在/jffs/scripts里面新建一个services-start。写入以下内容：
#!/bin/sh
i=30
while [ `ps |grep pppd |grep -v grep |wc -l` -eq 0 ]
do
if [ $i -lt 1 ] ; then
logger "Could not restart pppd"
exit
fi
i=$(($i-1))
sleep 1
done
killall pppd
cp /jffs/options.wan0 /tmp/ppp/options.wan0
/usr/sbin/pppd file /tmp/ppp/options.wan0 &
然后添加执行属性。

当然你可以需要在后面加上执行latest-pppoe.py的命令（大概可以新建个/jffs/scripts/wan-start来执行）。

**Comment by wang08270** [comment]
现在的情况是一台设备连接正常，超过两台就会断开，显示691代码错误

**Comment by wang08270** [comment]
有没有企鹅交流群。

**Comment by Rabenda** [comment]
PPPoE本身的功能并不是脚本能够跨越的
你这属于多播问题

**Comment by wang08270** [comment]
这是我的拨号日志
Oct 18 22:47:40 Hiwifi daemon.info pppd[17857]: Plugin rp-pppoe.so loaded.
Oct 18 22:47:40 Hiwifi daemon.info pppd[17857]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.5
Oct 18 22:47:40 Hiwifi daemon.notice pppd[17857]: pppd 2.4.5 started by root, uid 0
Oct 18 22:47:40 Hiwifi daemon.debug pppd[17857]: Send PPPOE Discovery V1T1 PADI session 0x0 length 12
Oct 18 22:47:40 Hiwifi daemon.debug pppd[17857]:  dst ff:ff:ff:ff:ff:ff  src d4:ee:7:49:9a:1
Oct 18 22:47:40 Hiwifi daemon.debug pppd[17857]:  [service-name] [host-uniq  c1 45 00 00]
Oct 18 22:47:40 Hiwifi daemon.debug pppd[17857]: Recv PPPOE Discovery V1T1 PADI session 0x0 length 4
Oct 18 22:47:40 Hiwifi daemon.debug pppd[17857]:  dst ff:ff:ff:ff:ff:ff  src d4:ee:7:21:61:79
Oct 18 22:47:40 Hiwifi daemon.debug pppd[17857]:  [service-name]
Oct 18 22:47:40 Hiwifi daemon.debug pppd[17857]: Recv PPPOE Discovery V1T1 PADO session 0x0 length 28
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]:  dst d4:ee:7:49:9a:1  src 60:8:10:29:39:56
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]:  [service-name] [host-uniq  c1 45 00 00] [AC-name GZGD-LD-ME60]
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]: Send PPPOE Discovery V1T1 PADR session 0x0 length 12
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]:  dst 60:8:10:29:39:56  src d4:ee:7:49:9a:1
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]:  [service-name] [host-uniq  c1 45 00 00]
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]: Recv PPPOE Discovery V1T1 PADS session 0x27ad length 12
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]:  dst d4:ee:7:49:9a:1  src 60:8:10:29:39:56
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]:  [service-name] [host-uniq  c1 45 00 00]
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]: PADS: Service-Name: ''
Oct 18 22:47:41 Hiwifi daemon.info pppd[17857]: PPP session is 10157
Oct 18 22:47:41 Hiwifi daemon.warn pppd[17857]: Connected to 60:08:10:29:39:56 via interface eth2.2
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]: using channel 23
Oct 18 22:47:41 Hiwifi daemon.info pppd[17857]: Using interface pppoe-wan
Oct 18 22:47:41 Hiwifi daemon.notice pppd[17857]: Connect: pppoe-wan <--> eth2.2
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]: sent [LCP ConfReq id=0x1 <mru 1480> <magic 0xfe85c007>]
Oct 18 22:47:41 Hiwifi daemon.debug pppd[17857]: rcvd [LCP ConfAck id=0x1 <mru 1480> <magic 0xfe85c007>]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: rcvd [LCP ConfReq id=0x2 <mru 1492> <auth pap> <magic 0xe235aeb8>]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: sent [LCP ConfAck id=0x2 <mru 1492> <auth pap> <magic 0xe235aeb8>]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: sent [LCP EchoReq id=0x0 magic=0xfe85c007]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: sent [PAP AuthReq id=0x1 user="\r\n2111808023" password=<hidden>]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: rcvd [LCP EchoRep id=0x0 magic=0xe235aeb8]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: rcvd [PAP AuthAck id=0x1 "Welcome to Drcom System:100859914"]
Oct 18 22:47:44 Hiwifi daemon.info pppd[17857]: Remote message: Welcome to Drcom System:100859914
Oct 18 22:47:44 Hiwifi daemon.notice pppd[17857]: PAP authentication succeeded
Oct 18 22:47:44 Hiwifi daemon.notice pppd[17857]: peer from calling number 60:08:10:29:39:56 authorized
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: sent [IPCP ConfReq id=0x1 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: rcvd [IPCP ConfReq id=0x1 <addr 10.31.36.1>]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: sent [IPCP ConfAck id=0x1 <addr 10.31.36.1>]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: rcvd [IPCP ConfNak id=0x1 <addr 10.31.39.107> <ms-dns1 222.200.115.251> <ms-dns2 222.200.115.252>]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: sent [IPCP ConfReq id=0x2 <addr 10.31.39.107> <ms-dns1 222.200.115.251> <ms-dns2 222.200.115.252>]
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: rcvd [IPCP ConfAck id=0x2 <addr 10.31.39.107> <ms-dns1 222.200.115.251> <ms-dns2 222.200.115.252>]
Oct 18 22:47:44 Hiwifi daemon.notice pppd[17857]: local  IP address 10.31.39.107
Oct 18 22:47:44 Hiwifi daemon.notice pppd[17857]: remote IP address 10.31.36.1
Oct 18 22:47:44 Hiwifi daemon.notice pppd[17857]: primary   DNS address 222.200.115.251
Oct 18 22:47:44 Hiwifi daemon.notice pppd[17857]: secondary DNS address 222.200.115.252
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: Script /lib/netifd/ppp-up started (pid 18007)
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: Script /lib/netifd/ppp-up finished (pid 18007), status = 0x0

**Comment by wang08270** [comment]
那要怎么解决呢？

**Comment by Rabenda** [comment]
请勿发表和本repo无关的issue，无关的issue一般包含但不限于下列议题：

**p版如何多播?**

**Comment by wang08270** [comment]
> 请勿发表和本repo无关的issue，无关的issue一般包含但不限于下列议题：
> 
> **p版如何多播?**

那可以告诉我691问题的步骤是要在哪执行吗
执行 cp /tmp/ppp/options.wan0 /jffs/options.wan0
在/jffs/scripts里面新建一个services-start。写入以下内容：
#!/bin/sh
i=30
while [ ps |grep pppd |grep -v grep |wc -l -eq 0 ]
do
if [ $i -lt 1 ] ; then
logger "Could not restart pppd"
exit
fi
i=$(($i-1))
sleep 1
done
killall pppd
cp /jffs/options.wan0 /tmp/ppp/options.wan0
/usr/sbin/pppd file /tmp/ppp/options.wan0 &
然后添加执行属性。

当然你可以需要在后面加上执行latest-pppoe.py的命令（大概可以新建个/jffs/scripts/wan-start来执行）。

**Comment by Rabenda** [comment]
你验证过你的账号的有效性吗? 691一般是账号无效的错误码

**Comment by wang08270** [comment]
账号是有效的，用官方客户端可以正常登陆，在路由器上拨号也可以成功，
超过两台设备就会691

**Comment by mchome** [comment]
pppd哪来的691?

**Comment by wang08270** [comment]
应该是刷的openwrt固件
你说的pppd是什么意思？我是拨号上网的。

**Comment by mchome** [comment]
```
Oct 18 22:47:44 Hiwifi daemon.debug pppd[17857]: rcvd [PAP AuthAck id=0x1 "Welcome to Drcom System:100859914"]
Oct 18 22:47:44 Hiwifi daemon.info pppd[17857]: Remote message: Welcome to Drcom System:100859914
Oct 18 22:47:44 Hiwifi daemon.notice pppd[17857]: PAP authentication succeeded
```
我觉得没有问题，可以关了。
