### ISSUE TITLE
请问模拟手机哆点登录需要填写什么参数呢

### ISSUE THREAD

**Issue by yushaye** [drcoms/drcom-generic#319]
想用电脑模拟一下手机的登录，因为学校开通了双终端登录，可以手机电脑同时在线，想和别人公用一个账号，附上安卓哆点app登录的tcpdump抓包
[duodian.zip](https://github.com/drcoms/drcom-generic/files/2671578/duodian.zip)

**Comment by qoddi** [comment]
手机版校验方式和电脑版完全不同+需要证书验证，建议放弃

**Comment by yushaye** [comment]
我们学校的哆点没有加固，把libDrClientLib.so取出来去掉里面VerifyAPP的检测 后写了个 APP来调用libDrClientLib.so里面的httplogin可以认证，下面是SendData函数发送的内容，证书是在so里面的吗，
POST  HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Charset: utf-8
Date: 2019-01-22 14:58:35
Time: 1548140314
Uip: va5=1.2.3.4.09df17159dd70b6ba8fb12b3d4cf5a6d29798a15
Content-Length: 125
Host: 202.202.0.180
User-Agent: DrCOM-HttpClient
DDDDD=xxxxxxxxx&upass=xxxxxxx&0MKKey=0123456789&ver=1.5.100.201609061.G.L.A.R&sim_sp=undefine&cver1=1&cver2=0010500100&R6=

**Comment by yushaye** [comment]
好像跟电脑版的网页认证差不多，调试了以下httplogout就是get F.htm来登出，可能重点在于Uip中的va5参数的计算

**Comment by yushaye** [comment]
已经解决了，ssl认证复现不了，只能去掉DrClientLib.so中的代理检测，然后用手机连电脑开的热点或者路由器开的wifi来认证，这样电脑也可以上网了。

**Comment by muzhiyun** [comment]
> 已经解决了，SSL认证复现不了，只能去掉DrClientLib.so中的代理检测，然后用手机连电脑开的热点或者路由器开的无线网络来认证，这样电脑也可以上网了。

麻烦打扰下，不懂安卓编程，你把这个APP做出来了吗？能不能发我一份？万分感谢

**Comment by yushaye** [comment]
你试试能不能用吧，不知道是否只有我们学校可用。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: muzhiyun <notifications@github.com>
发送时间: Friday, March 15, 2019 8:06:54 PM
收件人: drcoms/drcom-generic <drcom-generic@noreply.github.com>
抄送: yushaye <yushaye@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [drcoms/drcom-generic] 请问模拟手机哆点登录需要填写什么参数呢 (#319)


已经解决了，SSL认证复现不了，只能去掉DrClientLib.so中的代理检测，然后用手机连电脑开的热点或者路由器开的无线网络来认证，这样电脑也可以上网了。

麻烦打扰下，不懂安卓编程，你把这个APP做出来了吗？能不能发我一份？万分感谢

―
