### ISSUE TITLE
电脑测试能上，但路由器不能上

### ISSUE THREAD

**Issue by starsingchow** [drcoms/drcom-generic#33]
我在电脑上测试了能上的，但是放到路由器上就不行了
我 python /usr/bin/drcom
但就会显示
DrCOM Auth Router for GDUFE
[challenge] challenge packet sent.
Traceback (most recent call last):
  File "/usr/bin/drcom", line 345, in <module>
    main()
  File "/usr/bin/drcom", line 323, in main
    loginpart()
  File "/usr/bin/drcom", line 329, in loginpart
    package_tail = login(username, password, server)
  File "/usr/bin/drcom", line 258, in login
    packet = mkpkt(salt, usr, pwd, mac)
  File "/usr/bin/drcom", line 214, in mkpkt
    data += dump(int(data[4:10].encode('hex'),16)^mac).rjust(6,'\x00') #mac xor md51
LookupError: no codec search functions registered: can't find encoding
这应该是路由器没插网线的情况下出现吧？但通过opkg update能过更新列表的（ustc的软件源，学校不用登都能上）这说明网线有插的
哪我是什么原因导致不能上？

**Comment by mchome** [comment]
应该是你的路由器的python环境有问题。

**Comment by starsingchow** [comment]
解决了的确是python环境问题，加上python-codecs后就可以了。
还有在这里表示一下对作者和对这项目参与者的感激

**Comment by tdxddt** [comment]
解决了我的问题 谢谢
