### ISSUE TITLE
长江大学6.0.0(p)配置文件更新

### ISSUE THREAD

**Issue by NERD-k** [drcoms/drcom-generic#334]
pppoe帐号前缀是 ` \r\n`

我目前是使用的C语言版的dogcom，配置文件是
```
server = '10.151.0.249'
KEEP_ALIVE_VERSION = '\xDC\x02'
```

**Comment by pridewang** [comment]
你好 可以分享下c语言版的dogcom吗

**Comment by zhenqiongxi** [comment]
还有我

**Comment by pridewang** [comment]
> 还有我
在恩上论坛可以找到 但是目前我在路由器没用成功 如果可以的话，可以留下联系方式交流一下

**Comment by NERD-k** [comment]
**提问之前可以先看看 [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)**，提出你们在解决问题的过程中遇到的问题；

Wiki里面的描述还是足够详细的，请按照Wiki中 [关于P版的PPPoE拨号问题](https://github.com/drcoms/drcom-generic/wiki/%E5%85%B3%E4%BA%8EP%E7%89%88%E7%9A%84PPPoE%E6%8B%A8%E5%8F%B7%E9%97%AE%E9%A2%98)、[p版简略使用和配置说明](https://github.com/drcoms/drcom-generic/wiki/p%E7%89%88%E7%AE%80%E7%95%A5%E4%BD%BF%E7%94%A8%E5%92%8C%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E) 的步骤操作

**Comment by NERD-k** [comment]
目前在 OpenWRT 的 master 上的 PPPoE 的读取配置脚本文件应该是 `/lib/netifd/proto/ppp.sh` 第150行的 `${username:+user "$username" password "$password"}`  这一句
