### ISSUE TITLE
为啥用d版配置生成器和在线配置生成的两个配置是不同的？

### ISSUE THREAD

**Issue by hjiachuang** [drcoms/drcom-generic#371]
用drcom_d_config.py生成的，python2.7版本
server = '202.38.210.131'
username=''
password=''
CONTROLCHECKSTATUS = '\x54'
ADAPTERNUM = '\x42'
host_ip = '0.0.0.202'
IPDOG = '\x00'
host_name = 'GILIGILIEYE'
PRIMARY_DNS = '0.0.0.0'
dhcp_server = '0.0.0.0'
AUTH_VERSION = '\xd2\x83'
mac = 0xb'0701f400030c'
host_os = 'NOTE7'
KEEP_ALIVE_VERSION = '\xdb\x02'
ror_version = False 

在线生成的conf文件，用Notepad++打开复制的
server = '202.38.210.131'
username = 'ô 0#	RÚÀ¤&" *'
password = ''
CONTROLCHECKSTATUS = '\x54'
ADAPTERNUM = '\x42'
host_ip = '0.0.0.202'
IPDOG = '\x00'
host_name = 'fuyumi'
PRIMARY_DNS = '0.0.0.0'
dhcp_server = '0.0.0.0'
AUTH_VERSION = '\xd2\x83'
mac = 0x5290dac0a426
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdb\x02'
ror_version = True

**Comment by hjiachuang** [comment]
华南理工五山校区，5.2.1（x）版，用d版的latest-wired.py，在windows 10下运行，用这两个配置，用户名密码均为校园网账号密码，结果都是发心跳包发啊发的就停了，报
[[challenge] timeout, retrying...

**Comment by lieka1** [comment]
弄好了么，检查一下是不是同时登陆的问题，我这边一个网络下只能有一个登陆器运行

**Comment by hjiachuang** [comment]
没弄好。最后用 https://github.com/scutclient/scutclient 这个大佬的代码编译的ipk安装到路由器解决了。
