### ISSUE TITLE
drcom6.0D版在win10运行py脚本时可用，但是放到r2s，friendlywrt21.02上时运行无反应

### ISSUE THREAD

**Issue by lengweijin** [drcoms/drcom-generic#374]
friendlywrt（官方说是按照openwrt改的，觉得应该兼容就没管）安装的是python3
按照教程中的方法给予了权限，输入chmod +x /sur/bin/drcom回车无反馈是否正常？
设置了开机自启，但是不知道怎么判断脚本有无运行（但是软路由管理界面无连接，电脑的网络仍然需要认证）
后续添加了issue中的99-drcom文件也是软路由管理界面无连接，电脑的网络仍然需要认证
刚接触相关领域，还需要什么补充还请指出

**Comment by dadavinson** [comment]
已收到，谢谢|

**Comment by lengweijin** [comment]
> friendlywrt（官方说是按照openwrt改的，觉得应该兼容就没管）安装的是python3 按照教程中的方法给予了权限，输入chmod +x /sur/bin/drcom回车无反馈是否正常？ 设置了开机自启，但是不知道怎么判断脚本有无运行（但是软路由管理界面无连接，电脑的网络仍然需要认证） 后续添加了issue中的99-drcom文件也是软路由管理界面无连接，电脑的网络仍然需要认证 刚接触相关领域，还需要什么补充还请指出
