### ISSUE TITLE
微博、淘宝等需要账号密码验证的网页无法加载

### ISSUE THREAD

**Issue by Shouduo** [drcoms/drcom-generic#38]
通过配置、我的路由已经能够上外网了
但是我发现有一些需要账号密码验证的网页却打不开（比如微博登录界面、输入账号密码按登录、会显示无法打开此网页、同样的情况还有淘宝、百度、论坛等）
试过其他电脑其他浏览器（包括LAN口和wifi的连接方式）、通过排查感觉是latest-wired.py这个文件的问题、即我用网线直连笔记本、打开这个脚本后能上其他网站、但遇到账号密码验证的网页就只能加载登录页、但填完信息后登录网页却无法显示的情况。

产品版本:5.2.0.201504291.A.W.100591
主模块:5.2.0.201504290.A.W.100591
通讯模块:0.8(U64.R110908)Build(k35.20150404)
升级模块:5.2.0.201504110.A.W.100591
检测模块:5.2.0.201504110.A.W.100591
网际协议:IPV4
认证/封装方式:Dr.COM / 不封装防代理
内网认证:已禁用

**Comment by Shouduo** [comment]
啊啊啊啊！问题有了新的进展
今晚把路由刷回官方的固件（极路由2-9013）
wan口接墙上的网口、lan口接电脑、用win10下的dr.com 5.2.0（D）上网居然成功了- -！
但是！！之前所说的账号密码登录页的问题依旧存在、、、错怪latest-wired.py了、、
在cmd里去ping weibo.com 的结果是超时、、

**Comment by darkaccount** [comment]
## 个人认为是校园网的锅。
我在学校碰到情况和你的差不多，挂上代理就好了。

**Comment by Shouduo** [comment]
问题终于解决了= =
网上查找的反馈一般有两种：
1、MTU设置
MTU（最小传输单元）默认是1500、但不同ISP会有不同的包长、所以如果超过的话超过的部分会被分包处理、、（大概是这个意思= =）
详细的检测和设置方法网上很多、不再赘述、

2、错误设置IP地址
正常情况下，一台主机应该有一个网卡，一个IP地址，或多个网卡，多个IP地址（这些地址一定要处于不同的IP子网）。但如果一台电脑的“拨号网络适配器”（相当于一块软网卡）的TCP/IP设置中，设置了一个与网卡IP地址处于同一子网的IP地址，这样，在IP层协议看来，这台主机就有两个不同的接口处于同一网段内。当从这台主机Ping其他的机器时，会存在这样的问题：
A、主机不知道将数据包发到哪个网络接口，因为有两个网络接口都连接在同一网段。
B、主机不知道用哪个地址作为数据包的源地址。因此，从这台主机去Ping其他机器，IP层协议会无法处理，超时后，Ping 就会给出一个“超时无应答”的错误信息提示。
（引自：http://www.45fan.com/a/question/2423.html）
开始怀疑以为是以前用X豹开wifi留下的虚拟网卡IP冲突了、
但打开设备管理器发现一切正常、、
------------------------------------------------------------------------------------------------------------------------------
尝试按上面两种情况去解决发现都不适用、
后来又截了一下dr.com客户端的登录动作、
发现插上网线识别网络完成时的DNS、和客户端认证完毕时的DNS是不同的、想想也是学校的网络是可以自己选择订购移动或者电信的服务的= =
于是将截包并检索后得到的txt文件打开、修改其DNS为客户端认证后得到的DNS值
在电脑上双击执行测试脚本、发现微博、淘宝等已可以顺利打开、
开心地将脚本放入路由中、重启后发现wan口的DNS还是之前的DNS、、、看来是服务器自己分配的呢= =
最后只好将wan口协议由DHCP改为静态、手动配置IP和DNS等、、、
再次重启、成功~(*´∇｀*)

（第一次接触TCP/IP、、如上述描述有错、望指出、谢谢！）

**Comment by mchome** [comment]
```latest-wired.py``` 的dns好像是写实了 ```8.8.8.8```，怎么改也是 ```8.8.8.8``` 的，而且没影响吧，实际上你终端的dns是可以随意指定的。

**Comment by Shouduo** [comment]
我尝试过直接在电脑上的网络适配器中指定ipv4的DNS、但ping weibo.com的结果依然是超时、
只有指定路由器的dns才能正常访问微博、我也不太清楚其中的原因、、
对了、在认证前的DNS是我们学校内部网的DNS、解析微博的IP是正确的、不知为何总是超时、、
认证后的DNS是广东移动的（因为我办理的就是移动的网）、、可以愉快的上微博、
