### ISSUE TITLE
您好，5.20P版用不了

### ISSUE THREAD

**Issue by xinhuak** [drcoms/drcom-generic#4]
我们学校是5.20P的，抓包替换后点系统自带的pppoe客户端 输入账号密码后点链接就马上提升错误。好像是服务器拒绝了，然后点开latest-pppot.py后代码一闪而过，什么都没有，网上不了。怎么办？抓的包已经发您邮箱

**Comment by ly0** [comment]
需要先拨号成功后才能使用latest-pppoe心跳
