### ISSUE TITLE
电脑测试能连接上但是马上断开。

### ISSUE THREAD

**Issue by datidu** [drcoms/drcom-generic#40]
能连接上就是一小会 能收到QQ信息

链接: http://pan.baidu.com/s/1skmxYbj 密码: pgi5

求解答。

**Comment by datidu** [comment]
运行显示
ValueError: chr() arg not in range(256) 
用的是python2.7

**Comment by mchome** [comment]
recv file之前，客户端发的是```dc02```，不是```0f27```，所以判断```KEEP_ALIVE_VERSION```出了问题。```KEEP_ALIVE_VERSION```处应是```d802```。
