### ISSUE TITLE
运行配置生成器报错

### ISSUE THREAD

**Issue by lihonglinglory** [drcoms/drcom-generic#43]
我是X版的drcom，就是D+802.1X认证的。。按照步骤：输入 python drcom_d_config.py > config.txt后，报错了。。C:\Users\admin\Desktop\a>python drcom_d_config.py> config.txt
Traceback (most recent call last):
  File "drcom_d_config.py", line 19, in <module>
    offset = re.search('\xf0\x00\xf0\x00[\x00-\xFF]{4}\x03\x01', text).start() +
 8
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by yaalsn** [comment]
配置脚本 这一行 offset = re.search('\xf0\x00\xf0\x00[\x00-\xFF]{4}\x03\x01', text).start() + 8
改成这样 offset = re.search('\xf0\x00\xf0\x00[\x00-\xFF]{4}[\x03\x07]\x01', text).start() + 8

**Comment by lihonglinglory** [comment]
修改后的运行不包错，但是只能正常读取出server
