### ISSUE TITLE
drcom p版 v5.2.0 拨号成功，运行上不了网

### ISSUE THREAD

**Issue by prettys** [drcoms/drcom-generic#44]
参照此教程   https://github.com/drcoms/drcom-generic/wiki/p%E7%89%88%E7%AE%80%E7%95%A5%E4%BD%BF%E7%94%A8%E5%92%8C%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E
进行到此步 ：  拨号成功（用pppoe-dialer.exe拨号） 但是 运行 latest-pppoe.py 并不能上网。。
电脑已配置python环境。
正常用联通客户端拨号的抓包文件及所用文件如下：
百度云链接：http://pan.baidu.com/s/1gdM1sGF 密码：r1ct
在此谢谢您了。。

**Comment by prettys** [comment]
求解答

**Comment by mchome** [comment]
latest-pppoe.py生成的日志有木有

**Comment by prettys** [comment]
请问下 这个生成的日志在哪?谢谢了

**Comment by mchome** [comment]
在同目录

**Comment by prettys** [comment]
再同目录里 没有日志文件

**Comment by mchome** [comment]
那你没有运行成功吧

**Comment by prettys** [comment]
我是右键 选择python 打开  窗口闪了 一下 就没了
求解  方法不对吗？

**Comment by mchome** [comment]
cmd进入latest-pppoe.py所在目录，```python latest-pppoe.py```.

**Comment by prettys** [comment]
链接：http://pan.baidu.com/s/1dDYJyWp 密码：8xdy
只有这个文件。。看看行不行。。。谢谢。

**Comment by mchome** [comment]
重下latest-pppoe.py，怎么带html标签了......

**Comment by prettys** [comment]
66666  执行后可以上网。。
不过我的路由器 好像最后加这个自启命令，并不能启动。没有python user/bin/drcom 这个进程  也就不能上网。
 pppoe.sh 里的server改了  最后一行的执行命令 也改成python user/bin/drcom  应该是路由的锅。
 在想 把这个python user/bin/drcom 添加到系统会自启的进程中 想着应该会成功。可行？

**Comment by mchome** [comment]
依附在其他自启服务可以吧。
