### ISSUE TITLE
login failed 

### ISSUE THREAD

**Issue by oldwu** [drcoms/drcom-generic#45]
auth svr:202.195.192.197
username:152070006
password:030615
mac:0x20ce0b12ea1L
[challenge] recv 0202c70080bc030001000100f003e8f000000000c0a85213f000a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202c70080bc030001000100f003e8f000000000c0a85213f000a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001daa6ed52c322267736f6845534c9341053135323037303030360000000000000000000000000000000000000000000000000000002007a862359d1c83bf219dde2d21aa3b19c5bde0a3f0b99801c0a852130000000000000000000000000a12c58f40a1404501000000004452434f4d4655434b4552000000000000000000000000000000000000000000da02870100000000000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001f00020c8081438d0000020ce0b12ea10000e913
[login] send 0301001daa6ed52c322267736f6845534c9341053135323037303030360000000000000000000000000000000000000000000000000000002007a862359d1c83bf219dde2d21aa3b19c5bde0a3f0b99801c0a852130000000000000000000000000a12c58f40a1404501000000004452434f4d4655434b4552000000000000000000000000000000000000000000da02870100000000000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001f00020c8081438d0000020ce0b12ea10000e913
[login] recv 050000050b28d24431d69f
[login] packet sent.
[login] login failed.

**Comment by prettys** [comment]
d版？

**Comment by oldwu** [comment]
是D版，配置什么的都是按照教程来的，应该没有错，就是登陆的时候直接failed，密码也确认过

**Comment by oldwu** [comment]
已经解决，mac地址没有更改，我们这边绑定mac地址

**Comment by youqingxiaozhua** [comment]
请教楼主，我也遇到了相同的问题，mac地址已经修改了呀。配置里这行：
`mac:0x20ce0b12ea1L`
这一行mac显示的错了一位，但是在配置文件里是正确的，请问如何解决的？
