### ISSUE TITLE
能拨上号但是无法执行这个pppoe.sh

### ISSUE THREAD

**Issue by 18607013358** [drcoms/drcom-generic#46]
可以的话可以采用https://github.com/drcoms/drcom-generic/raw/master/custom/pppoe.sh，修改放入 /usr/bin/pppoe.sh ，并且给予执行权限 (chmod +x /usr/bin/pppoe.sh) 然后在 /etc/rc.local 的 exit 0 前加
sleep 15
pppoe.sh
这个执行了还是有心跳

**Comment by ly0** [comment]
?到底是可以了还是不可以

**Comment by 18607013358** [comment]
packet:072428000b04d8022f12000000000000b793ae060000000000000000000000000000000000000000
auth svr:172.16.1.2
pppoe_flag:24
keep_alive2_flag:d8
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
auth svr:172.16.1.2
pppoe_flag:24
keep_alive2_flag:d8
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
auth svr:172.16.1.2
pppoe_flag:24
keep_alive2_flag:d8
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
