### ISSUE TITLE
d版  how to log out  

### ISSUE THREAD

**Issue by zkl99999** [drcoms/drcom-generic#47]
kill which process

**Comment by ly0** [comment]
ps一下kill掉等几分钟自己会掉线的

**Comment by zkl99999** [comment]
which process？

**Comment by ly0** [comment]
`ps aux | grep python` then you will see which process the script is.

**Comment by prettys** [comment]
666

**Comment by zkl99999** [comment]
if  i  already open other python application

**Comment by mchome** [comment]
@zkl99999 find the pid file or check udp port at 61440

**Comment by ly0** [comment]
`lsof -i:61440` to see port 61440 is occupied by which process.

Further, could you please speak Chinese in issues since the project is only concerned by Chinese speaker, using an universal language is a good practice in github but it seems cause some difficulties for who is weak in English.
