### ISSUE TITLE
hostip字段是否需要编辑

### ISSUE THREAD

**Issue by MikeMiao** [drcoms/drcom-generic#48]
我们学校刚开始上dr.com，D版，我按照教程配置成功了，请问拷贝给室友测试时，config里面的host_ip字段不改或者干脆留空会不会有影响

**Comment by mchome** [comment]
可以不改，留空就出错了

**Comment by MikeMiao** [comment]
谢谢，感谢大神为我们搞出如此通用的dr.com方案。
