### ISSUE TITLE
latest-wired 电脑端测试登陆失败

### ISSUE THREAD

**Issue by superlxz** [drcoms/drcom-generic#49]
使用latest-wired测试登陆失败（从头开始试了好多次，还换了台pc），我将drcom和latest-wired的抓包记录，drcom_client.log都上传到网盘里了。求问各位大大，十分感谢！

我们学校（SZU）的drcom客户端在输入账号密码前有选择运营商这一项，但是版本还是5.2.0(D)。不知道是不是这个影响。

另外，发现抓包转换后的config.txt里的mac值每一次都不一样，不知道有没有关= =

链接: http://pan.baidu.com/s/1jIhbRqm 密码: w15b

**Comment by mchome** [comment]
密码错了，吧？

**Comment by superlxz** [comment]
密码应该不会错，drcom客户端亲测。

**Comment by mchome** [comment]
```mac = 0x0024bee9e05f```
修改试下

**Comment by superlxz** [comment]
一样不行呢。会不会是问题出在我的pc环境上？我发现每登录一次drcom，dns设置就会从自动获取跳成某个地址...

**Comment by superlxz** [comment]
刚刚翻了一下 drcom_client.log 发现之前有一次是成功loged in的，但是同样配置的latest-wired不可重复...

**Comment by ly0** [comment]
机器上没装各种东西 麻烦把脚本的log和抓包结果 03 包都发上来？

**Comment by superlxz** [comment]
@ly0 log搜索loged in可以看到两次成功的，另外抓包结果03不明白是什么意思0 0）就发了最近一次的。
麻烦您了。
链接: http://pan.baidu.com/s/1skNkSNz 密码: gtmr

**Comment by mchome** [comment]
https://gist.github.com/mchome/d35d38455de574966964
尝试一下这个，注意你的包用配置器出来的mac是不对的，要你自己填

**Comment by blb2514235934** [comment]
跟版本也有关吧，你的是什么版本的
