### ISSUE TITLE
p版pc能用路由器不能用附上详细调试信息

### ISSUE THREAD

**Issue by jujf1111** [drcoms/drcom-generic#5]
路由器 openwrt  14.07 barrier_breaker cpu：ar7241 
版本：barrier_breaker/14.07/ar71xx/generic/packages/oldpackages/
python_2.7.3-2_ar71xx.ipk 
python-pcap_1.1-1_ar71xx.ipk
以及安装上述软件包所需的相关依赖

调试信息：
路由器：
root@OpenWrt:~# pppoe.sh
/usr/bin/pppoe.sh: line 16: 1: not found
[*]  open local port:61440
[*]  DEBUG MODE:True
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:07011000020000000cbf610c0a000188a8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000000a0001880062001a0cbf610cf8bfa2320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:070110000200000028bf610c0a000188a8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000000a0001880062001a28bf610cb0bfa2320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:070110000200000045bf610c0a000188a8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000000a0001880062001a45bf610ceabfa2320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:070110000200000062bf610c0a000188a8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000000a0001880062001a62bf610c24bfa2320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:07011000020000007ebf610c0a000188a8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000000a0001880062001a7ebf610c1cbfa2320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:07011000020000009abf610c0a000188a8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000000a0001880062001a9abf610cd4bfa2320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
 PC：
drcom-pppoe2.py
[*]  open local port:61440
[*]  DEBUG MODE:True
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:07011000020000006ec0610c0a000188a8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000000a0001880062001a6ec0610cce5fd571000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000
[*]  pppoe: received heartbeat response
        packet:07023000040020007ebb2da0000000004439d8eddd58e0244c3a8200104404a2b
0824000100000000000000000000000
[*]  [keep-alive2] send1
        packet:070028000b010f272f12000000000000000000000000000000000000000000000
000000000000000
[*]  received message packet, dropped. message:联通微信沃派全面升级，5大特权免费
享，每月赠送2.5G上网流量；同时现场开通沃支付业务，可享9元看电影， 95折购物，加油
减3毛等优惠，详情请咨询联通校园营业厅
[*]  received message packet, dropped. message:联通微信沃派全面升级，5大特权免费
享，每月赠送2.5G上网流量；同时现场开通沃支付业务，可享9元看电影， 95折购物，加油
减3毛等优惠，详情请咨询联通校园营业厅
[*]  [keep-alive2] recv file, resending..
[*]  [keep-alive2] send1
        packet:070128000b01dc022f12000000000000000000000000000000000000000000000
000000000000000
[*]  [keep-alive2] recv1
        packet:070128000b02dc022f120000000000006fc0610c0000000000000000000000000
000000000000000
[*]  [keep-alive2] send2
        packet:070128000b01dc022f12000000000000000000000000000000000000000000000
000000000000000
[*]  [keep-alive2] recv2
        packet:070128000b02dc022f120000000000006fc0610c0000000000000000000000000
000000000000000
[*]  [keep-alive2] send3
        packet:070228000b03dc022f120000000000006fc0610c0000000000000000dd0b38120
000000000000000
[*]  [keep-alive2] recv3
        packet:070228000b04dc022f120000000000006fc0610c0000000000000000000000000
000000000000000
[*]  [keep-alive2] keep-alive2 loop was in daemon.
[*]  [keep_alive2] send 3
        packet:070328000b01dc022f120000000000006fc0610c0000000000000000000000000
000000000000000

**Comment by ly0** [comment]
目测路由器上没拨号成功，PC上目测成功了的。
pppoe版的使用方法是：
1. 路由器正常设置拨号账号密码
2. 修改`pppoe.sh`中`server`部分，修改为认证服务器IP

这样可以保证拨号成功后就开始心跳

**Comment by jujf1111** [comment]
不是的，我是在路由器的wan上pppoe 然后在lan下的pc上心跳，都是成功的！！需要我提供别的参数吗？

**Comment by ly0** [comment]
你是说路由器上拨号成功以后心跳失败么?

**Comment by jujf1111** [comment]
对了有个补充情况给您，就是路由器不支持 import platform
if platform.uname()[0] != 'Windows':
        return string.decode('gb2312').encode().decode()
    else:
        return string.decode('gb2312')
我修改成
if 1 :
        return string.decode('gb2312').encode().decode()
    else:
        return string.decode('gb2312') 了

**Comment by jujf1111** [comment]
拨号应该是成功的，很神奇的是，在路由器上拨号，心跳竟然可以在pc上进行！

**Comment by ly0** [comment]
是的，drcom的p版心跳和pppoe拨号是分开的。
路由器上出现failed，应是无法和认证服务器通信问题，检查一下PC上和路由器上的latest_pppoe.py上server配置是不是一样？

**Comment by jujf1111** [comment]
保证是一样的！

**Comment by ly0** [comment]
不知道你是否使用qq，用的话可以加此群看看具体情况 `318495368`
