### ISSUE TITLE
福建江夏学院DR.COM5.2 (D)版

### ISSUE THREAD

**Issue by 1453374029** [drcoms/drcom-generic#50]
福建江夏学院DR.COM5.2 (D)版
产品版本:5.2.0.201310121.A.W.100291
主模块:5.2.0.201310120.A.W.100291
通讯模块:0.8(U64.R110908)Build(k22.20131011)
升级模块:5.2.0.201303040.A.W.100291
检测模块:5.2.0.201303040.A.W.100291
网际协议:IPV4
认证/封装方式:Dr.COM / 不封装防代理
内网认证:已禁用

pcapng file: dr.pcapng
copy following statements to drcom.conf or overwrite field between "# CONFIG" and "# CONFIG_END" in latest-wired.py

server = '10.2.255.250'
username='13107651772'
password=''
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x03'
host_ip = '10.3.116.165'
IPDOG = '\x01'
host_name = 'DRCOMFUCKER'
PRIMARY_DNS = '10.1.1.88'
dhcp_server = '10.3.116.254'
AUTH_VERSION = '\x16\x00'
mac = 0x020c80546f0c
host_os = 'WINDIAOS'
KEEP_ALIVE_VERSION = '\xdc\x02'

**Comment by 1453374029** [comment]
发不了附件
下面是截获的包
链接：http://pan.baidu.com/s/1hsxvpbA 密码：u25b

**Comment by 1453374029** [comment]
谢谢了！
我的邮箱（e-mail）：1453374029@qq.com

**Comment by 1453374029** [comment]
password='152517'

**Comment by mchome** [comment]
https://gist.github.com/mchome/d35d38455de574966964
试一下这个

**Comment by 1453374029** [comment]
auth svr:10.2.255.250
username:13107651772@fjjxxy
password:152517
mac:0x20c80546f0cL
0.0.0.0
[challenge] recv 0202b20fe0f740000a000100f203e8f0000000000a0374a5f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202b20fe0f740000a000100f203e8f0000000000a0374a5f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010026a9fc55b716da167c921691d6c2f7ede0313331303736353137373240666a6a7878790000000000000000000000000000000000002003abf0d5e379d69262d04eea3f439778825d7f3efcef7d010a0374a500000000000000000000000053e1ad0b19a29f7201000000004452434f4d4655434b45520000000000000000000000000000000000000000000a0101580a0374fe000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001600020cf01209a300000000000000000000020c80546f0c0000e913
[login] send 03010026a9fc55b716da167c921691d6c2f7ede0313331303736353137373240666a6a7878790000000000000000000000000000000000002003abf0d5e379d69262d04eea3f439778825d7f3efcef7d010a0374a500000000000000000000000053e1ad0b19a29f7201000000004452434f4d4655434b45520000000000000000000000000000000000000000000a0101580a0374fe000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001600020cf01209a300000000000000000000020c80546f0c0000e913
[login] recv 050000051500000000000000000000000000000031323b526f616d696e67205573657228313331303736353137373240666a6a78787940666a6a7878792920636f6d6d20776974682052656d6f746520526164697573204572726f722c20546f203133302e33382e31362e32372c2054696d656f7574203531396d73204572726f722c20526571756573742044656e7920620000
[login] packet sent.
[login] login failed.
@mchome 还是不行

**Comment by mchome** [comment]
你的mac是```0xd0534932ebf7```

**Comment by 1453374029** [comment]
嗯，试试

发自我的 iPhone

**Comment by 1453374029** [comment]
文件里是填的0xd0534932ebf7，运行.py文件生成的日志里面才出现的L
@mchome

**Comment by 1453374029** [comment]
dr.com客户端
链接：http://pan.baidu.com/s/1jH9mtvg 密码：q8h1 
@mchome

**Comment by mchome** [comment]
你填的是```0x20c80546f0c```..........

**Comment by 1453374029** [comment]
auth svr:10.2.255.250
username:13107651772
password:152517
mac:0xd0534932ebf7L
0.0.0.0
[challenge] recv 02021efff93141000a000100f203e8f0000000000a0374e6f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02021efff93141000a000100f203e8f0000000000a0374e6f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001f7946d4b401758b301f7b0abf82b95d353133313037363531373732000000000000000000000000000000000000000000000000002003a9159d86ea8273905ad293d054cab39eea6c22c5ba57010a0374a50000000000000000000000005127baf6fb142a4901000000004452434f4d4655434b45520000000000000000000000000000000000000000000a0101580a0374fe000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001600020cc0b0c9b100000000000000000000d0534932ebf70000e913
[login] send 0301001f7946d4b401758b301f7b0abf82b95d353133313037363531373732000000000000000000000000000000000000000000000000002003a9159d86ea8273905ad293d054cab39eea6c22c5ba57010a0374a50000000000000000000000005127baf6fb142a4901000000004452434f4d4655434b45520000000000000000000000000000000000000000000a0101580a0374fe000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001600020cc0b0c9b100000000000000000000d0534932ebf70000e913
[login] recv 050000051500000000000000000000000000000032393b5573657228313331303736353137373240666a6a7878792927732041757468656e204174747269622861692d536572766963652d50617373776f72643a204e41532069732033323363663630656434306636396366643862336461383762656564343036332c2052616469757320697320613562303962393032310000
[login] packet sent.
[login] login failed.
@mchome

**Comment by 1453374029** [comment]
@mchome 这个有办法解决吗？
需要什么资料？
谢谢

**Comment by 1453374029** [comment]
@mchome 0515扩展认证是什么意思？现在有解决的办法吗？
谢谢

**Comment by yecw** [comment]
看来我跟你遇到的问题一样，这就尴尬了😅，楼主解决了记得发一下

**Comment by 1453374029** [comment]
@yecw 没有解决，已经准备换移动宽带了
