### ISSUE TITLE
CQU D版本 的问题。

### ISSUE THREAD

**Issue by Trevery** [drcoms/drcom-generic#51]
在OS X 中遇到的问题。
我们学校使用的是5.2.0D版本。

timeout retrying....
timeout retrying....
@ly0 

该问题已解决，多谢@fake

**Comment by MikeMiao** [comment]
我在配置的时候也遇到过一次，貌似是py环境的问题，在确认你网络连接正常的前提下，外挂个u盘把python依赖装全就好了
