### ISSUE TITLE
偶尔出现脚本无法运行的错误

### ISSUE THREAD

**Issue by Wsuika** [drcoms/drcom-generic#52]
Traceback (most recent call last):
  File "latest-wired.py", line 34, in <module>
    s.bind(("0.0.0.0", 61440))
  File "C:\python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10013]

重启电脑之后就又能运行了

**Comment by mchome** [comment]
端口被占用了，检查僵死进程

**Comment by Wsuika** [comment]
sorry 我又看了下wiki发现早就说了解决方法  不过一直在windows上用  总之就是检查占用61440端口的进程对吧

**Comment by mchome** [comment]
linux举个栗子 ```sudo netstat -anp | grep :61440 | awk '{print $7}'| awk -F"/" '{ print $1 }' | sudo xargs kill```，如果有pid文件的话，顺便删掉吧。

windows的话好像没有awk之类的，只能```netstat -aon|findstr 61440```看pid，然后```taskkill /PID yourpid /F```。

**Comment by Wsuika** [comment]
好的  感谢指教

**Comment by Wsuika** [comment]
不好意思  之后又出现 我试了一下并没有找到占用61440端口的进程 但是脚本还是同样的提示无法运行  会不会是权限的问题？

**Comment by mchome** [comment]
错误消息一样吗？

**Comment by Wsuika** [comment]
一样的

**Comment by mchome** [comment]
那应该是权限问题了

**Comment by Wsuika** [comment]
是python本身不能某一类创建端口么？ 我试着全局替换了61440为9000 脚本就可以跑 但是并不能连上 都是超时没有响应 请问有什么思路么  之前这个问题我重启了一下就好了 但是一连不上网就得保存工作再重启又有些麻烦

**Comment by Wsuika** [comment]
创建某一类  打错😂

**Comment by mchome** [comment]
10013 好像是WIndows的错误号，绑定0.0.0.0会弹uac吧好像。我总觉得是端口被占了。。。
随便哪里借用的batch，你试下。
```batch
@echo off
@echo.
@echo. Timeout: 2s

:Scan

@echo. PRESS CTRL+C to quit; Searching for port 61440
@echo.

REM To change search speed, replace 1 with a higher or lower value
TIMEOUT /T 1 /NOBREAK >NUL

@echo. [#############- TABLE -#############]
REM If you want to try a different port, replace 61440 with the port number.

netstat -an | findstr ":61440.*:[^:]*$"

If %ERRORLEVEL% equ 0 (
 @echo. [##########- PORT IN USE -##########]
) ELSE (
 @echo. [#########- PORT AVAILABLE -########]
 @echo. [#############- TABLE -#############]
 GOTO Scan
)
@echo. [#############- TABLE -#############]
pause

:EOF
exit /b
```

**Comment by Wsuika** [comment]
不好意思电脑没电了   我明天试下😷

**Comment by Wsuika** [comment]
![default](https://cloud.githubusercontent.com/assets/12707115/14933687/ddd85718-0e5c-11e6-8435-5082ca6237f3.PNG)
看来没被占用

**Comment by mchome** [comment]
用管理员权限执行再试下

**Comment by Wsuika** [comment]
是指在管理员下的cmd么？那个之前我试过，一样的提示。

**Comment by mchome** [comment]
尝试一下打开被封印的第61行
``s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)``

**Comment by Wsuika** [comment]
不好意思我才发现之前用的不是最新的脚本:joy:，我用的版本还是15年9月的，等我换新的试下。
另外这个问题有点难复现（随机出现，重启就解决了），不过最近出现的频率蛮高，下次再出现我照你说的试下。

**Comment by Wsuika** [comment]
又出现了 于是这回我用新的脚本试了一下貌似还是不行  无论有没有第61行
![3](https://cloud.githubusercontent.com/assets/12707115/14937881/a8117afc-0f46-11e6-85d7-8ea37f380f88.PNG)

**Comment by Wsuika** [comment]
管理员下也是一样
![4](https://cloud.githubusercontent.com/assets/12707115/14937891/0941e5dc-0f47-11e6-854a-264eb0978102.PNG)

**Comment by ly0** [comment]
http://stackoverflow.com/questions/10968182/windows-socket-error-10013
参考了一下 10013 错误，权限问题

你配置发一下

**Comment by Wsuika** [comment]
# CONFIG
server = "172.19.1.2"
username = ""
password = ""
host_name = "LIYUANYUAN"
host_os = "8089D"
host_ip = "10.8.41.73"
PRIMARY_DNS = "114.114.114.114"
dhcp_server = "202.202.240.101"
mac = 0x0090f5f3ed30
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x01'
KEEP_ALIVE_VERSION = '\xdc\x02'
AUTH_VERSION = '\x0a\x00'
IPDOG = '\x01'
# CONFIG_END
