### ISSUE TITLE
如果IP是自动获取，那个host_ip = 应该怎么填写啊？

### ISSUE THREAD

**Issue by shaoyan177** [drcoms/drcom-generic#53]
如题，重庆大学A区宿舍是自动获取IP,应该如何填写呢？

**Comment by shaoyan177** [comment]
总不能每次都查询下获取IP，再修改吧？有办法自动获取并改写这个文件么？

**Comment by shaoyan177** [comment]
我试了下。。。那个host_ip =  可以随意填写。。。谢谢drcom代码还有教程，成功搞进路由器。

**Comment by wangshoukun121** [comment]
不需要管那个IP  我是随便填的





-------------------------------------------------------------


王守坤 
Wang Shoukun


重庆大学 计算机学院
Computer College of Chongqing University


在2016年04月19 11时21分, "shaoyan177"<notifications@github.com>写道:



总不能每次都查询下获取IP，再修改吧？有办法自动获取并改写这个文件么？

**Comment by mchome** [comment]
恭喜，那个 ```host_ip``` 一般都不检验的。
