### ISSUE TITLE
Ver5.2.1(X)无法提取配置文件且认证失败

### ISSUE THREAD

**Issue by gatesyoung** [drcoms/drcom-generic#54]
////2016.05.01 update////
目前的情况是先用别的办法通过1x之后手动运行drcom.py，会出现fail错误，具体的错误代码参看楼下几楼。搜索、思考和测试了几天，目前暂时没有任何进展。我会一直留意这个issue的情况。
/////

一些信息：
我使用的Drcom拨号器是Ver5.2.1(X)版本（已附带安装包），协议信息如下：
产品版本:5.2.1.201507101.A.W.100440
主模块:5.2.1.201506110.A.W.100440
通讯模块:0.8(U62.R110908)(1x)Build(k36.20150515)
升级模块:5.2.1.201506110.A.W.100440
检测模块:5.2.1.201506110.A.W.100440
网际协议:IPV4
认证/封装方式:802.1X_Ext / 不封装防代理
内网认证:已禁用

现在的情况：
我用贵项目中的在线配置器 http://drcoms.github.io/drcom-generic/，按要求生成配置信息之后，发现MAC识别错和identity识别不出来，所以我手动修正了这些数据，然后粘贴替换了配置信息。
还有就是，我这里的交换机对1x的多播不能识别，所以我改成0xff广播了。

现在的情况就是，可以通过802.1x认证，也可以反应802.1x心跳。但是，始终没有发送Drcom协议的UDP包（61440端口），通过Wireshark抓包，也可以程序中根本没有发出UDP包。不知道这是什么情况，头疼了很多天，特来请教。。

头疼了很多天了都，希望你们技术牛人可以帮帮我。万分感激。有关抓包文件和拨号器安装包已经传到网盘。链接: http://pan.baidu.com/s/1o8UuDfW 密码: m1wc

谢谢大家。。。

**Comment by ly0** [comment]
看一下通过8021x认证以后认证服务器是否可以连同

**Comment by gatesyoung** [comment]
@ly0 首先感谢你的回复，Thks u so much！我刚刚测试了一下，通过1x认证之后，是可以ping通认证服务器（192.168.127.129）的，网关也可ping通。。

**Comment by gatesyoung** [comment]
@mchome urgently looking for help！

**Comment by mchome** [comment]
可以附上配置信息吗

**Comment by gatesyoung** [comment]
@mchome 非常感谢你的回复。
以下是我的配置信息：
server = '192.168.127.129'
username = '14115032041'【注：原来在线配置工具识别出来是乱码，我手动修正了一下】
password = '111111'
CONTROLCHECKSTATUS = '\x63'
ADAPTERNUM = '\x00'
host_ip = '0.0.0.0'
IPDOG = '\x00'
host_name = 'fuyumi'
PRIMARY_DNS = '0.0.0.0'
dhcp_server = '0.0.0.0'
AUTH_VERSION = '\xca\xa7'
mac = 0x60a44cad5196 【注：原来在线配置工具识别出来是不对的MAC，我手动修正了一下】
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'

user_info = {'username': "14115032041",
             'password': "111111",
             'ethernet_interface': "eth0",
             'daemon': True,
             'dhcp_command': ''
             }


【我还修改了eappacket.py里有关的地址如下，因为我这里真正可用的多播地址是\x01\xd0\xf8\x00\x00\x03，用01:80开头的那个默认的多播地址，服务器无回应】
PAE_GROUP_ADDR = "\x01\xd0\xf8\x00\x00\x03" # same for all
BROADCAST_ADDR ="\x01\xd0\xf8\x00\x00\x03"

如果需要更多信息，请联系我

**Comment by ly0** [comment]
登陆脚本输出的log发一下吧

**Comment by gatesyoung** [comment]
@ly0 
找不到log。我已经将IS_TEST = True和DEBUG = True，但是仍然没有找到/var/log/drcom_client.log这个文件。很奇怪，不是吗？

登录过程屏幕输出的文字如下：
【之所以出现那么多Got Unknown EAP Response，是因为与我同一个网络中有很多人是采用0xff广播来发包认证的，故我能收到他们发出的response】
➜  test-drcom8021x-master  sudo python main.py
[sudo] password for youngshendu: 
Start Packet info: 
	From: 01d0f8000003
	To: 60a44cad5196
	Type: 888e
	Content: 01010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[*] Sending EAPOL start
[*] Got EAP Request for identity
Response_ID Packet info: 
	From: 01d0f8000003
	To: 60a44cad5196
	Type: 888e
	Content: 0100001002010010013134313135303332303431
[*] Sending EAP response with identity = [14115032041]
[*] Got EAP Request for MD5-Challenge
Response_MD5 Packet info: 
	From: 01d0f8000003
	To: 60a44cad5196
	Type: 888e
	Content: 01000021020000210410faa1de58f4445e25b1a2130f2a79f0703134313135303332303431000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[*] Sending EAP response with password
[*] Got EAP Success
[*] Got EAP Request for identity
Response_ID Packet info: 
	From: 01d0f8000003
	To: 60a44cad5196
	Type: 888e
	Content: 0100001002010010013134313135303332303434
[*] Sending EAP response with identity = [14115032041]
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got unknown EAPOL type 1
[*] Got unknown EAP code (0)
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got unknown EAPOL type 1
[*] Got unknown EAP code (0)
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got unknown EAPOL type 1
[*] Got unknown EAP code (0)
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got unknown EAPOL type 2
[*] Got unknown EAP code (0)
[*] Got unknown EAPOL type 2
[*] Got unknown EAP code (0)
[*] Got unknown EAPOL type 1
[*] Got unknown EAP code (0)
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got unknown EAPOL type 2
[*] Got unknown EAP code (0)
[*] Got unknown EAPOL type 1
[*] Got unknown EAP code (0)
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
[*] Got Unknown EAP Response
^CInterrupted by user
Logoff Packet info: 
	From: 01d0f8000003
	To: 60a44cad5196
	Type: 888e
	Content: 01020000
[*] Sending EAPOL logoff

**Comment by ly0** [comment]
咦，怎么有一种并没有运行Ｄ版部分认证脚本的感觉。

**Comment by gatesyoung** [comment]
@ly0 那怎么会并没有运行Ｄ版部分认证脚本呢？是不是我缺少哪个文件？我的文件和python版本如下

➜  test-drcom8021x-master  ll
总用量 68K
-rw------- 1 youngshendu youngshendu  240 12月  3  2014 AUTHORS
-rw------- 1 youngshendu youngshendu  13K  4月 22 18:23 drcom.py
-rw------- 1 root        root         12K  4月 22 18:24 drcom.pyc
-rw------- 1 youngshendu youngshendu 6.3K  4月  3 17:49 eapauth.py
-rw------- 1 root        root        6.1K  4月  3 17:49 eapauth.pyc
-rw------- 1 youngshendu youngshendu 1.6K  4月 21 23:39 eappacket.py
-rw------- 1 root        root        2.1K  4月 21 23:39 eappacket.pyc
-rw------- 1 youngshendu youngshendu 1.1K 12月  3  2014 LICENSE
-rw------- 1 youngshendu youngshendu  579  4月 21 23:42 main.py
-rw------- 1 youngshendu youngshendu  930 12月  3  2014 README.md
➜  test-drcom8021x-master  python --version
Python 2.7.6

**Comment by ly0** [comment]
可以尝试一下手工运行drcom.py？

**Comment by gatesyoung** [comment]
@ly0 抱歉昨天重装了一下系统，今天才测试了一下。。回复晚了。。
手工运行drcom.py屏幕结果如下，在与drcom.py的同目录出现了drcom_client.log，其内容也如下

young@young-pc:~/桌面/test-drcom8021x-master$ sudo python drcom.py
[sudo] young 的密码：
auth svr:192.168.127.129
username:14115032041
password:111111
mac:0x60a44cad5196
0.0.0.0
[challenge] recv 0202a7c0c100000000000100f203e8f000000000c0a8caa7f000a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202a7c0c100000000000100f203e8f000000000c0a8caa7f000a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001f8280dbe115622ab00331f6564453f6b23134313135303332303431000000000000000000000000000000000000000000000000006300e224974c44f4ef743e65b951dbd7f3914c141a6c5c480100000000000000000000000000000000fe92168a98503d1c0000000000667579756d6900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000940000000500000001000000280a00000200000057696e646f777320313000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000caa7020c8047fe70000060a44cad51960000e913
[login] send 0301001f8280dbe115622ab00331f6564453f6b23134313135303332303431000000000000000000000000000000000000000000000000006300e224974c44f4ef743e65b951dbd7f3914c141a6c5c480100000000000000000000000000000000fe92168a98503d1c0000000000667579756d6900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000940000000500000001000000280a00000200000057696e646f777320313000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000caa7020c8047fe70000060a44cad51960000e913
[login] recv 05000005150000000000000000000000000000005b30315d2c20b1bed5cabac5d6bbc4dcd4dad6b8b6a8564c414e4944cab9d3c328302e323032290000
[login] packet sent.
[login] login failed.

**Comment by ly0** [comment]
`0x15 客户端版本不正确` 可能是某些字段不对，是用生成器生成的字段吗？

**Comment by gatesyoung** [comment]
@ly0 配置文件是用贵项目中的在线生成器生成的。用那个配置生成的脚本会报语法错，所以我只能用在线配置生成器。具体的抓包文件已经传到网盘（1楼链接）。。能不能帮我看看在哪里修改呢？

**Comment by gatesyoung** [comment]
@ly0 @mchome 请求支持。。

**Comment by gatesyoung** [comment]
我短时间内拿不到我其他学校那个朋友的实际环境的抓包文件。
不过我用他的拨号器（比我学校官方的drcom版本低一些）在我学校拨号，可以完美保持在线，在我学校环境抓包如下。还有一个线索就是，我朋友他是用贵项目中的源代码，可以完美运行保持在线，所以我觉得我也应该能用才对。。
链接: http://pan.baidu.com/s/1o8H3J1S 密码: a5ux

@mchome

**Comment by mchome** [comment]
@gatesyoung  你朋友的配置文件现在有吗?

**Comment by gatesyoung** [comment]
配置文件短时间内拿不到，他留在家里了，要几个月之后才能拿到。@mchome

**Comment by hdoodle** [comment]
我这里与楼主状况类似，5.2.1(X)版的，也是抓包后生成配置文件乱码或部分内容为空，试了抓过好多次依然如此。

版本信息如下

产品版本:5.2.1.201510281.A.W.100660
主模块:5.2.1.201510280.A.W.100660
通讯模块:0.8(U62.R110908)(1x)Build(k38.20150921)
升级模块:5.2.1.201510280.A.W.100660
检测模块:5.2.1.201510280.A.W.100660
网际协议:IPV4
认证/封装方式:802.1X_Ext / 不封装防代理
内网认证:已禁用

其中一次抓包生成的文件如下

pcapng file: dr.pcapng
copy following statements to drcom.conf or overwrite field between "# CONFIG" and "# CONFIG_END" in latest-wired.py


server = '1.1.1.5'
username=''
password=''
CONTROLCHECKSTATUS = '\x00'
ADAPTERNUM = '\x00'
host_ip = '1.192.168.0'
IPDOG = '\x00'
host_name = 'DRCOMFUCKER'
PRIMARY_DNS = '0.0.0.0'
dhcp_server = '0.0.0.0'
AUTH_VERSION = '\xac\x8f'
mac = 0xb0cd19d45010
host_os = 'WINDIAOS'
KEEP_ALIVE_VERSION = '\x1d\x00'

**Comment by gatesyoung** [comment]
@hdoodle 你有没有办法解决呢？

**Comment by hdoodle** [comment]
@gatesyoung 我没有解决这个问题...

**Comment by gatesyoung** [comment]
大神，能否有办法支持这个客户端？@mchome

**Comment by mchome** [comment]
@gatesyoung 试下
```
server = '192.168.127.129'
username = '141150320'
password = '111111'
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x02'
host_ip = '192.168.202.166'
IPDOG = '\x01'
host_name = 'fuyumi'
PRIMARY_DNS = '0.0.0.0'
dhcp_server = '0.0.0.0'
AUTH_VERSION = '\x0a\x00'
mac = 0xc45444585e72
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'
```

**Comment by gatesyoung** [comment]
用以上配置文件依旧不行。
虽然这个配置文件我改了一下，以适应我的账号。
server = '192.168.127.129'
username = '14115032041'
password = '111111'
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x02'
host_ip = '192.168.123.456'
IPDOG = '\x01'
host_name = 'fuyumi'
PRIMARY_DNS = '0.0.0.0'
dhcp_server = '0.0.0.0'
AUTH_VERSION = '\x0a\x00'
mac = 0xabcdefghijkl
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'
[login] send 0301001fbb00a9a4daef96935936b890907a4ad53134313135303332303431000000000000000000000000000000000000000000000000002002dba4e5098b792cd8fdfbf70760101a261d3d0f1682e901c0a8caa70000000000000000000000003dd64b7429f50a640100000000667579756d6900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00020c20d221f00000abcdefghijkl0000e913
[login] recv 05000005150000000000000000000000000000005b30315d2c20b1bed5cabac5d6bbc4dcd4dad6b8b6a8564c414e4944cab9d3c328302e323032290000
[login] packet sent.
[login] login failed.

另外，能不能麻烦你update一下评论，帮我把identity、host_ip和mac这三样打打码？谢谢，用简单的字符abcd之类的代替就行，我能看懂的。

**Comment by mchome** [comment]
ADAPTERNUM = '\x01'到 '\x05' 多试下
AUTH_VERSION 试下其他学校的

**Comment by gatesyoung** [comment]
好的，我试试 @mchome

**Comment by blb2514235934** [comment]
请问这个版本用路由器能上网吗？
