### ISSUE TITLE
Ver5.2.0(X)无法认证

### ISSUE THREAD

**Issue by KingChoo** [drcoms/drcom-generic#57]
看列表里说我们学校只需要认证802.1x就可以了
802项目的所有py文件下载并配置好了 放进usr\bin文件夹并且编辑好了rc.local
重启路由器没有进行认证是怎么回事
另外“段落拷贝到/etc/drcom.conf中”并没有找到这个文件 我新建了文本并拷贝其中上传到etc文件夹当中 是否有所影响
谢谢

**Comment by ly0** [comment]
手工跑一下脚本试试

**Comment by KingChoo** [comment]
@ly0 
putty执行python /usr/bin/main.py 
返回
Traceback (most recent call last):
  File "/usr/bin/main.py", line 3, in <module>
    import multiprocessing
ImportError: No module named multiprocessing

**Comment by ly0** [comment]
你需要装库
