### ISSUE TITLE
var510x 802.1x认证后不能自动进行drcom认证

### ISSUE THREAD

**Issue by deckvig** [drcoms/drcom-generic#58]
root@raspberrypi:~# python ~/drcom8021x/main.py 
[*] Sending EAPOL start
[*] Got EAP Request for identity
[*] Sending EAP response with identity = [llj2]
[*] Got EAP Request for MD5-Challenge
[*] Sending EAP response with password
[*] Got EAP Success

运行main.py后执行到这里就停止了，
drcom.py debug输出停止到输出bind-ip，但是停止main.py进程手动运行drcom.py，能够正常验证drcom。

**Comment by mchome** [comment]
drcoms/drcom8021x: main.py里面dhcp_command配置一下``dhclient wan口``

**Comment by deckvig** [comment]
正常工作了，我按照wiki重做了一遍，并没有填写 dhclient wan也能工作，但是之前出错的时候填写了 dhclient wan仍然不行，感谢:)

from Deckvig
On 周五, 5月 6, 2016 at 17:43, fuyumi <notifications@github.com> wrote:
drcoms/drcom8021x: main.py里面dhcp_command配置一下 dhclient wan口
