### ISSUE TITLE
5.2.0p版出现问题

### ISSUE THREAD

**Issue by lan5635** [drcoms/drcom-generic#59]
> 进入命令提示符(或shell)进入 drcom_p_config.py 所在目录，输入 python drcom_p_config.py > config.txt 

到了这步，我的cmder出现以下问题：
E:\drcom-generic-master
λ python drcom_p_config.py > config.txt
  File "drcom_p_config.py", line 22
    print 'server = \'%s\'' % '.'.join([str(ord(i)) for i in text[offset-12:offset-8]])
不知道是出现了啥问题，是因为我安装了最新的python 3 没有安装python2 的原因咩
我的wireshark抓包文件：http://pan.baidu.com/s/1c2oIx7i

**Comment by ly0** [comment]
用py2

**Comment by mchome** [comment]
server = '172.16.30.98'
pppoe_flag = '\x0a'
keep_alive2_flag = '\xdc'
