### ISSUE TITLE
5.2.0(P)问题，拨号不上

### ISSUE THREAD

**Issue by madman43** [drcoms/drcom-generic#60]
双击latest-pppoe.py等了几秒就关闭了，然后用系统拨号提示691密码帐号不对，
[文件在百度云](http://pan.baidu.com/s/1i49WE7V)
我把x00全部替换成了获取到的代码，但是还是不行。

**Comment by mchome** [comment]
请务必先拨上号，明明wiki都写这么清楚。

**Comment by madman43** [comment]
这就是先拨号，在运行脚本的还是拨号不通过，691




D:\drcom>python latest-pppoe.py
[*]  auth svr:119.6.23.78
pppoe_flag:00
keep_alive2_flag:dc
[*]  open local port:61440
[*]  DEBUG MODE:True
[*]  pppoe: send challenge request
        packet:0701080001000000
Traceback (most recent call last):
  File "latest-pppoe.py", line 288, in <module>
    main()
  File "latest-pppoe.py", line 284, in main
    pppoe.send(s)
  File "latest-pppoe.py", line 142, in send
    data, address = s.recv()
  File "latest-pppoe.py", line 77, in recv
    data, address = self.s.recvfrom(1024)
socket.timeout: timed out

**Comment by mchome** [comment]
拨号归拨号，脚本归脚本，pppoe拨号是你独立完成的

**Comment by madman43** [comment]
啥意思？先拨号，后脚本也不对吗？

**Comment by mchome** [comment]
你都说了691拨号失败，连ip都拿不到怎么跑脚本

**Comment by madman43** [comment]
就是拿不到IP，通过p版抓去出来IPping不通，但是用客户端登录后可以ping通，需要改脚本吗，

**Comment by mchome** [comment]
pppoe拨号不通和本repo无关，自己解决。
