### ISSUE TITLE
用得好好的学校更新了客户端，但是版本还是5.2.1d 我看了下跟原来一样无变化

### ISSUE THREAD

**Issue by wtfitis1** [drcoms/drcom-generic#62]
就是连不上网了。。只能出现下载客户端的界面了 不知道是哪里改变了

![Uploading image.png…]()

**Comment by wtfitis1** [comment]
说是61440端口被占用。可我是windows系统

**Comment by ly0** [comment]
你是啥系统都有可能被占用，请检查是否开启了官方客户端

#25 #16

**Comment by wtfitis1** [comment]
谢谢了啦 我昨天看了 是drcom客户端占用了端口 但是我关了也上不了。

**Comment by wtfitis1** [comment]
后来我就去改了下drcom.conf的文件  把xd8改成了xd7..还有个x02改成了x03..就可以上网了。。
