### ISSUE TITLE
P版 v5.2.0 拨号成功，运行闪退timeout上不了网

### ISSUE THREAD

**Issue by SiWuXie64** [drcoms/drcom-generic#63]
https://github.com/drcoms/drcom-generic/wiki/%E5%85%B3%E4%BA%8EP%E7%89%88%E7%9A%84PPPoE%E6%8B%A8%E5%8F%B7%E9%97%AE%E9%A2%98
按照这个教程做的，但是到后来运行latest-pppoe.py闪退，用cmd运行显示timeout
>>>>>>>>>>
[*]  auth svr:120.203.160.10
pppoe_flag:26
keep_alive2_flag:dc
[*]  open local port:61440
[*]  DEBUG MODE:True
[*]  pppoe: send challenge request
        packet:0701080001000000
Traceback (most recent call last):
  File "latest-pppoe.py", line 288, in <module>
    main()
  File "latest-pppoe.py", line 284, in main
    pppoe.send(s)
  File "latest-pppoe.py", line 142, in send
    data, address = s.recv()
  File "latest-pppoe.py", line 77, in recv
    data, address = self.s.recvfrom(1024)
socket.timeout: timed out

**Comment by ly0** [comment]
说明这个服务器可能连不通 120.203.160.10

**Comment by SiWuXie64** [comment]
可是我抓包得到的就是这个ip啊

**Comment by mchome** [comment]
重新抓一遍
