### ISSUE TITLE
5.2.0(x)版没法提取配置文件

### ISSUE THREAD

**Issue by ZZzeal** [drcoms/drcom-generic#64]
产品版本:5.2.0.201404111.A.W.100267
主模块:5.2.0.201402130.A.W.100267
通讯模块:0.8(U29.R110908)(1x)Build(k31.20140409)
升级模块:5.2.0.201402130.A.W.100267
检测模块:5.2.0.201402130.A.W.100267
网际协议:IPV4
认证/封装方式:802.1X_Ext / 不封装防代理
内网认证:已禁用

查看日志发现需要持续发送心跳包，不知道取得配置文件了能不能通过验证

**Comment by ly0** [comment]
8021x通过了吗
？

**Comment by ZZzeal** [comment]
![1](https://cloud.githubusercontent.com/assets/19574652/15560428/f1e5c1ac-231d-11e6-88f0-f87e71cbbf70.PNG)

**Comment by ly0** [comment]
这个提示，802.1x应该是过了的

**Comment by ZZzeal** [comment]
x版配置文件不能用d版的，用了提取出来的信息是空的

**Comment by ZZzeal** [comment]
![1](https://cloud.githubusercontent.com/assets/19574652/15575933/edae266e-2387-11e6-8135-0e1938037b96.PNG)
用其他学校x版客户端，参照5.2.1（x）版修改，尝试登陆出现的

**Comment by ly0** [comment]
有一定可能是 
1. 通过802.1x认证
2. DHCP获得IP
3. 进行D版客户端认证

**Comment by mchome** [comment]
通过了802.1x认证后，有获取到ip吗?

**Comment by ZZzeal** [comment]
@ly0 
802.1x已经通过了呀，好像需要持续发送心跳包
main.py 是使用DHCP获取IP
D版客户端配置信息无法获取

**Comment by ZZzeal** [comment]
@mchome 
获取到了IP，WAN口有IP

**Comment by ly0** [comment]
理论上不应该会报 Network is unreachable 错误 除非网络没通。。
试试在8021x认证后  traceroute 一下 10.10.0.100

**Comment by ZZzeal** [comment]
![Uploading 3.png…]()

**Comment by ZZzeal** [comment]
![10](https://cloud.githubusercontent.com/assets/19574652/15626410/fa6b77d8-24f6-11e6-9a49-57feecc678c9.png)

**Comment by mchome** [comment]
路由器跑802.1x，电脑来发心跳包试过吗

**Comment by ZZzeal** [comment]
@mchome 请问电脑怎么发心跳包

**Comment by deckvig** [comment]
NetWork is Unreachable 这个问题在前天我校开通dhcp之后也遇到
经过检查 发现问题在于当802.1X认证通过后ip地址并不是瞬时返回的(DHCP存在三个过程),
解决办法 在eapauth.py 中 import time 并在第115行之后添加 time.sleep(10) 
😬

**Comment by ZZzeal** [comment]
@deckvig 
现在放假了，等开学我就试试，大神测试可用吗

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f62c.png)

**Comment by deckvig** [comment]
刚弄的 可以用 我校刚刚开始用dhcp

from Deckvig
On 周四, 7月 14, 2016 at 18:27, ZZzeal <notifications@github.com> wrote:
@deckvig [https://github.com/deckvig]
现在放假了，等开学我就试试，大神测试可用吗

[https://camo.githubusercontent.com/c14cdb4c2e68c3e878157cd3d03bf24afe2a2816/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663632632e706e67]

**Comment by blb2514235934** [comment]
512x版本的可以用路由器拨号吗？有成功的吗

**Comment by ZZzeal** [comment]
@blb2514235934 x版配置文件都获取不到

**Comment by ZZzeal** [comment]
@deckvig 请问为什么802.1x认证成功了后还是会有login failed
