### ISSUE TITLE
5.20x版802.1x正常，心跳包执行不到几次后802.1x收到下线报文

### ISSUE THREAD

**Issue by jujf1111** [drcoms/drcom-generic#69]
5.20x版802.1x正常，心跳包执行不到十几行，浏览一个网页的时间内802.1x收到下线报文，如果不登录心跳包或者web登录，则802.1x正常（802.1x之后也可以web登录类似cmcc）不知道是不是交换机可以检测我这边是不是路由器，电脑端802.1x认证之后心跳包发送偶尔也会导致下线（半小时左右），但是频率不高，已经试过路由器加web路由器加电脑心跳包，也一样会下线

**Comment by mchome** [comment]
有试过802.1x登陆后，再web登陆吗

**Comment by jujf1111** [comment]
有了，802.1x后web 802.1x还是会收到强制下线报文，在登录成功后10秒内，有时候会持续几分钟，但是用pc端的神州数码标准802.1x时，2小时内可能才下线一次，但是官网的drcom很稳定，我觉得是不是上边有上面检测的黑科技

**Comment by gatesyoung** [comment]
drcom协议没正常通过就会导致强制1x下线，并不是发现了你是路由器

**Comment by gatesyoung** [comment]
x版本的，始终还是没办法兼容吧，已经遇到不少不兼容的x版本案例了
