### ISSUE TITLE
吉大定制版，无限 被服务器拒绝 ([login] server return exception.retry)

### ISSUE THREAD

**Issue by Aeforever** [drcoms/drcom-generic#71]
在电脑上实验十几分钟了还是这样，能上部分网站，但网速极慢，多数网站打不开
[login] packet sent.
[login] server return exception.retry
[login] last packet server returned:
04000005003112000099402600ffffffffff00000000004472636f0a643d030fd2318ce5cc0110b00500030110
[DEBUG] challenge:
0202da9a2449070001000100f203e8f000000000318ce5ccf000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[login] packet sent.
[login] server return exception.retry
[login] last packet server returned:
04000005003312000099402600ffffffffff00000000004472636f0a643d0312d2318ce5cc0113b00500030110
[DEBUG] challenge:
0202b69a2449070001000100f203e8f000000000318ce5ccf000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[login] packet sent.
[login] server return exception.retry
就像这样循环

**Comment by ly0** [comment]
流程上好像出了问题，看上去是登陆成功了。

**Comment by Aeforever** [comment]
[drcom.txt](https://github.com/drcoms/drcom-generic/files/424546/drcom.txt)
这个是已经好长时间了也没连上，也不停止，手动关掉了
然后成功过两次，每次都是电脑关了很久再开，然后第一次打开可以连上（大概2分钟左右）。
一会如果能再连上再把连上的日志传上来~

**Comment by ly0** [comment]
发送的内容不大对，你用那个repo的客户端

**Comment by Aeforever** [comment]
抱歉啊。不是很明白。不是这个日志吗？那应该怎么获取日志呢

**Comment by Aeforever** [comment]
我试了下jlu-drcom-client / python-mini_client.py   ，发现可以了。应该是旧的问题吧。我用这个新的没问题。建议更新下wiki里吉大的教程
