### ISSUE TITLE
5.2.1p使用latest-pppoe脚本报错

### ISSUE THREAD

**Issue by xie3777** [drcoms/drcom-generic#72]
感谢贵项目的分享。我尝试进行了抓包后，修改latest-pppoe的设置并用pthon运行之，出现如下报错，请问要如何解决呢，不胜感谢：
D:\a>python latest-pppoe.py
[*]  auth svr:10.0.3.2
pppoe_flag:2a
keep_alive2_flag:dc
[*]  open local port:61440
[*]  DEBUG MODE:True
[*]  pppoe: send challenge request
        packet:0701080001000000
Traceback (most recent call last):
  File "latest-pppoe.py", line 288, in <module>
    main()
  File "latest-pppoe.py", line 284, in main
    pppoe.send(s)
  File "latest-pppoe.py", line 142, in send
    data, address = s.recv()
  File "latest-pppoe.py", line 77, in recv
    data, address = self.s.recvfrom(1024)
socket.timeout: timed out

**Comment by mchome** [comment]
拨号后能ping通10.0.3.2吗

**Comment by xie3777** [comment]
@mchome 您好，在windows下拨号后会出现错误629，使用教程上的pppoe-dialer拨号也会失败。在用户名前加了\r\n再拨号会出现错误691。非常感谢您的关注

**Comment by neophack** [comment]
要先拨号成功，再运行latest-pppoe才行，拨号失败就不用进入第二步了

**Comment by xie3777** [comment]
@neophack 好的，谢谢您
