### ISSUE TITLE
您好  如果portal IP有多个怎么办？

### ISSUE THREAD

**Issue by yanhuanzhi** [drcoms/drcom-generic#73]
# CONFIG
server = '123.138.74.242'
pppoe_flag = '\x1a'
keep_alive2_flag = '\xdc'
# CONFIG_END

# CONFIG
server = '123.138.72.146'
pppoe_flag = '\x1a'
keep_alive2_flag = '\xdc'
# CONFIG_END

已知目前学校好像有两个认证服务器（也许更多），这个应该怎么办？

**Comment by mchome** [comment]
随便一个，能上网就成
