### ISSUE TITLE
 关于D版5.2.0的成功配置后连接不稳定的情况

### ISSUE THREAD

**Issue by szy18** [drcoms/drcom-generic#74]
配置好了，也成功了。但是路由器不稳定，用不了多久就会断连。后来经过检测，电脑要重新联网，则需要重新运行drcom.py，所以觉得问题就出在dr.com。难道是用这种模拟认证的方法时，客户端认证有期限？还是其它什么原因？

**Comment by szy18** [comment]
现在是这样的，只要重新运行一次电脑里的drcom.py，不管是电脑，还是WI-FI就都可以用了。真不知道是什么回事！

**Comment by ly0** [comment]
路由器坏了吧 23333

**Comment by szy18** [comment]
新的

**Comment by szy18** [comment]
对了，请问可以连两台电脑吗？有线的

**Comment by ly0** [comment]
路由器上跑python很有可能出现各种情况，
连两台电脑，当然没有问题啦

**Comment by szy18** [comment]
@ly0 一个账号，可以连两台电脑？

**Comment by ly0** [comment]
哦你说这哥啊，不行。
你看看是不是路由里python跑挂了

**Comment by szy18** [comment]
@ly0 我用的是Lenovo Y1（Newifi mini），刷了PandoraBox r1024，安装了Python。是路由器的问题，还是PandoraBox不稳定？还有，我用putty给路由器安装python时，并没有什么反应，这正常吗？指令如下：
# opkg update
 # opkg install python-mini
 # opkg install python

**Comment by mchome** [comment]
就是说你网断了的时候，路由器还有没有python进程

**Comment by szy18** [comment]
现在在测试drcom.py在电脑上运行（没连路由），发现也会断网。难道是程序不太适合我们学校的验证？

**Comment by szy18** [comment]
@ly0 应该没有。我用putty运行一遍路由器里的drcom.py，就又连上了。可能真的是跑着跑着就挂了
