### ISSUE TITLE
dr.com v5.2.1 windows pppoe 登录失败

### ISSUE THREAD

**Issue by kkzzhizhou** [drcoms/drcom-generic#76]
第一次尝试拨号 629错误
第二次尝试拨号 691错误
server = '10.0.3.2'
pppoe_flag = '\x2a'
keep_alive2_flag = '\xdc'

**Comment by mchome** [comment]
拨号失败请继续努力 #72

**Comment by kkzzhizhou** [comment]
网上说dr.com不是采用pppoe协议，那直接用电脑的拨号能拨号成功吗？你们成功过吗？

**Comment by mchome** [comment]
是标准的pppoe，不信自己看抓的数据包
