### ISSUE TITLE
5.2.1(p) 配置成功后浏览网页经常断线，但百度云盘不会断线

### ISSUE THREAD

**Issue by JerryChaox** [drcoms/drcom-generic#79]
配置成功了 发现用百度网盘下载，可以一直保持下载状态。
但是浏览网页的时候发现经常断线，极路由提示无线信号太弱，或者时不时拨号会断开。
奇怪的是百度网盘的下载并不会断开，进度一直有跳动

请示各位技术大哥，我要提供什么材料才好分析这个状况

我发现我们校园网每一次**登陆IP**都是不同的， 但是**出口IP**每次都一样
有没有可能是这个原因造成经常断线需要重新连接

**Comment by JerryChaox** [comment]
配置成功了 下载时网络不会断。浏览网页会时不时断开。这是什么原因?

**Comment by JerryChaox** [comment]
更神奇的是我同时浏览网页和下载
网页弹出极路由后台诊断，
下载仍在高速进行

**Comment by blb2514235934** [comment]
不是固定ip地址的吗？？

**Comment by blb2514235934** [comment]
5.2.1（x）的表示连上网都不行

**Comment by JerryChaox** [comment]
估计是广东工业大学有加密 2分钟断一次
