### ISSUE TITLE
D版认证脚本运行报错

### ISSUE THREAD

**Issue by wszgrcy** [drcoms/drcom-generic#8]
最新的问题在最下楼层，此小问题根据5楼建议已经改正
用的是这个https://github.com/drcoms/drcom-generic/blob/master/latest-wired.py脚本，直接下载然后运行就报错，这里是报错内容
Traceback (most recent call last):
File "D:\test\latest-wired.py", line 350, in 
main()
File "D:\test\latest-wired.py", line 336, in main
daemon()
File "D:\test\latest-wired.py", line 331, in daemon
with open('/var/run/jludrcom.pid','w') as f:
IOError: [Errno 2] No such file or directory: '/var/run/jludrcom.pid'
电脑是WIN7 64位，32位，XP也试过了，都是报这个错，用的是python2.7.10版本，听说D版是最好搞的认证，我估计可能是我哪里设置出现问题了把，环境变量已经设置，直接python正常
D:>python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on wi
n32
Type "help", "copyright", "credits" or "license" for more information.
另外需要问什么问题补充也可以说，由于不抓包直接运行脚本也出错我就不把包贴出来影响大家的判断了，

**Comment by wszgrcy** [comment]
我是在CMD下 直接在目录下D:\>python latest-wired.py
同时也用IDLE打开后用F5运行过，都是上面的结果，
D:\>python latest-wired.py
Traceback (most recent call last):
  File "latest-wired.py", line 351, in <module>
    main()
  File "latest-wired.py", line 337, in main
    daemon()
  File "latest-wired.py", line 332, in daemon
    with open('/var/run/jludrcom.pid','w') as f:
IOError: [Errno 2] No such file or directory: '/var/run/jludrcom.pid'
我想问下是不是我运行的有问题还是在WIN系统上测试不出来必须要上路由上测试

**Comment by wszgrcy** [comment]
今天我把latest-wired的脚本的最后一处的
def main():
    if  IS_TEST:#这儿原来是if not IS_TEST:，我把NOT去掉了，可以运行了，但是并没有登录上，我把抓的包和运行出的日志的地址上传了链接: http://pan.baidu.com/s/1mgtJiOg 密码: vw2w
        daemon()
        execfile(CONF, globals())
    log("auth svr:"+server+"\nusername:"+username+"\npassword:"+password+"\nmac:"+str(hex(mac)))
    while True:
      try:
        package_tail = login(username, password, server)
      except LoginException:
        continue
      log('package_tail',package_tail.encode('hex'))
      #keep_alive1 is fucking bullshit!
      empty_socket_buffer()
      keep_alive1(SALT,package_tail,password,server)
      keep_alive2(SALT,package_tail,password,server)
链接: http://pan.baidu.com/s/1mgtJiOg 密码: vw2w

**Comment by wszgrcy** [comment]
产品版本:5.2.0.201205281.A.W.100142
主模块:5.2.0.201205230.A.W.100142
通讯模块:0.8(U56.R110908)Build(k10.20120326)
升级模块:5.2.0.201205230.A.W.100142
检测模块:5.2.0.201205230.A.W.100142
网际协议:IPV4
认证/封装方式:Dr.COM / 不封装防代理
内网认证:已禁用
客户端登录处版本显示ver5.2.0(D)
恩，其他没了，另外已经申请318495368群，望管理通过，

**Comment by ly0** [comment]
想要在windows上做测试,请将`IS_TEST = True`

**Comment by iceriverweng** [comment]
先按照上面那哥们说的测试一下。。看行不行。。还报错再反馈。。。

**Comment by iceriverweng** [comment]
此外，今天木有收到加群请求耶。。。少年要不要再试一下

**Comment by wszgrcy** [comment]
恩，改完后依旧报错，其他信息除日志外与网盘链接里的完全相同，希望再帮忙看看
Python 2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
auth svr:10.10.1.3
username:CCX37606
password:8888
mac:0x3018adff19L
[challenge] recv 02029ceee1a7ca0000000100f003e8f0000000000a51b68af00000a600002ae4119800000000d402000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02029ceee1a7ca0000000100f003e8f0000000000a51b68af00000a600002ae4119800000000d402000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001c48cbac6caa1bd78213aa0275dfca6dd7434358333736303600000000000000000000000000000000000000000000000000000000200148fbb4c1550255d2afefa30becaeed5107b4779bc5c2010a51b68a000000000000000000000000d6302f7b609b1e7901000000004452434f4d4655434b455200000000000000000000000000000000000000000008080808c0a80101000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00020cc03767bf00003018adff190000e913
[login] send 0301001c48cbac6caa1bd78213aa0275dfca6dd7434358333736303600000000000000000000000000000000000000000000000000000000200148fbb4c1550255d2afefa30becaeed5107b4779bc5c2010a51b68a000000000000000000000000d6302f7b609b1e7901000000004452434f4d4655434b455200000000000000000000000000000000000000000008080808c0a80101000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00020cc03767bf00003018adff190000e913
[login] recv 0400000500042a00009f016403ffffffffff00000000004472636f0a0a01039d250a51b68a0150b00501000100000000000000000000000110
[login] packet sent.
[login] loged in
[login] login sent
package_tail 4472636f0a0a01039d250a51b68a0150
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff48cbac6caa1bd78213aa0275dfca6dd70000004472636f0a0a01039d250a51b68a0150ee1d00000000
[keep-alive1] recv 070110000600ee1d27a5ff150a51b68a00a600002ae4119800000000d4020000040000000000000001000000042a00009f016403ffffffffffffffffffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv file, resending..
[keep-alive2] send1 070128000b010f272f12000000000000000000000000000000000000000000000000000000000000
--------------------------------------
很多行[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv file, resending..
-------------

Traceback (most recent call last):
  File "D:\latest-wired.py", line 351, in <module>
    main()
  File "D:\latest-wired.py", line 349, in main
    keep_alive2(SALT,package_tail,password,server)
  File "D:\latest-wired.py", line 153, in keep_alive2
    packet = keep_alive_package_builder(svr_num,dump(ran),'\x00'*4,1, False)
  File "D:\latest-wired.py", line 99, in keep_alive_package_builder
    data = '\x07'+ chr(number) + '\x28\x00\x0b' + chr(type)
ValueError: chr() arg not in range(256)
>>>

**Comment by iceriverweng** [comment]
send1和send2是正常的心跳过程，从日志看登录成功了，不能正常的上网吗？

**Comment by iceriverweng** [comment]
send1和send2是正常的心跳过程，从日志看登录成功了，不能正常的上网吗？

**Comment by iceriverweng** [comment]
send1和send2是正常的心跳过程，从日志看登录成功了，不能正常的上网吗？

**Comment by ly0** [comment]
有没有下错文件或者用了老版本的？  
因为从代码上分析
https://github.com/drcoms/drcom-generic/blob/master/latest-wired.py#L151

**Comment by wszgrcy** [comment]
@ly0 嗯，脚本确实用的最新的，我听从你的意见再试下，感谢大大忙里抽闲帮忙解决问题
@iceriverweng en，用了脚本后出现个很奇怪的现象，网页登录不上了（没登陆之前任意网页跳转到内网的一个认证须知网页）然后直接输入那个认证须知的网页提示连接上了，也有流量和时间，但是任何网页也登录不是，持续个1-2分钟把，就又恢复正常了，同时也感谢大大的帮助，今天我再根据作者的建议实事反馈给你们

**Comment by ly0** [comment]
再用配置脚本跑一下 XD

**Comment by wszgrcy** [comment]
成功了！！！！另求友情赞助地址，钱不多，表示下心意
