### ISSUE TITLE
请问下在pc端使用py登陆，还会对猎豹wifi分享进行检测吗？

### ISSUE THREAD

**Issue by bigfuji** [drcoms/drcom-generic#81]
rt，开启猎豹wifi后脚本界面上没有receive只有send。
又或者并不是猎豹wifi的问题？是因为配置错误不能维持连接？
因为不在现场没测试。

**Comment by ly0** [comment]
不会，这个检测是DrCOM客户端程序上的检测

**Comment by bigfuji** [comment]
thx
