### ISSUE TITLE
5.2.1(x)

### ISSUE THREAD

**Issue by blb2514235934** [drcoms/drcom-generic#83]
5.2.1（x）用5.2.0（x）的教失败了，在电脑上运行 latest-wired.py 登陆失败，每次抓包后的mac地址也不一样， 抓包用d版配置生成器，还是在线配置器好？？？

**Comment by blb2514235934** [comment]
求大神帮帮忙

**Comment by ly0** [comment]
日志贴上来

**Comment by blb2514235934** [comment]
链接：http://pan.baidu.com/s/1qXHqyGc 密码：o3gb 里面有拨号器和日志。

**Comment by blb2514235934** [comment]
@ly0 日志是在原版拨号器文件夹log里获取的是这个把

**Comment by blb2514235934** [comment]
@ly0 拨号时要先登录内网，外网才能拨号成功，请问要怎么修改登录脚本加上内网登陆，内网跟外网账号不一样

**Comment by mchome** [comment]
你看下内网是哪种协议，外网又是哪种。

**Comment by blb2514235934** [comment]
@mchome 要怎么看协议
