### ISSUE TITLE
吉林大学的openwrt脚本经常无故掉线

### ISSUE THREAD

**Issue by SatyrLee** [drcoms/drcom-generic#84]
RT，貌似每隔几个小时python脚本就会被kill掉，然后必须手动重启

**Comment by ly0** [comment]
路由器问题 建议用watchdog程序监控，比如supervisor

**Comment by zaidao2023** [comment]
校友 你怎么配置的 我怎么拨号失败啊？
![image](https://cloud.githubusercontent.com/assets/23253877/20270467/1c8bc880-aac2-11e6-9cfd-5b0cae52ff5f.png)

**Comment by ly0** [comment]
麻烦请先插上网线

**Comment by zaidao2023** [comment]
网线已插在wan口 路由也按照wiki中的d版设置的

**Comment by zaidao2023** [comment]
py文件在电脑上已经测试通过，路由器用的是k2,固件版本”PandoraBox-ralink-mt7620-xiaomi-mini-squashfs-sysupgrade-r1055-20150615_5.5M“，K2测试通过，安装了“1zlib_1.2.8-1_ralink.ipk” “2python-mini.ipk”，其余按照wiki中d版设置的

**Comment by ly0** [comment]
这显然是网络不通的错误啊，检查是否能上内网
