### ISSUE TITLE
CQU D版软件电脑调试登陆后一会儿后会掉线

### ISSUE THREAD

**Issue by wangkun321** [drcoms/drcom-generic#87]
0.0.0.0
[challenge] recv 02023abbef12170000000100f303e8f000000000ac18aab8f000a8a20000294d4d3f00000000d802000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02023abbef12170000000100f303e8f000000000ac18aab8f000a8a20000294d4d3f00000000d802000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 030100209989db5c0c5b7f038210bf48f5d91ee732303136313130323037367400000000000000000000000000000000000000000000000020049df4a0cb517aab637040fae71f07da2826c85ba367f401ac18aab8000000000000000000000000b987709891d5513c01000000004452434f4d4655434b4552000000000000000000000000000000000000000000caca0232caca0232000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00020ca03154830000047d7b975d210000e913
[login] send 030100209989db5c0c5b7f038210bf48f5d91ee732303136313130323037367400000000000000000000000000000000000000000000000020049df4a0cb517aab637040fae71f07da2826c85ba367f401ac18aab8000000000000000000000000b987709891d5513c01000000004452434f4d4655434b4552000000000000000000000000000000000000000000caca0232caca0232000000000000000000000000940000000500000001000000280a00000200000057494e4449414f530000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00020ca03154830000047d7b975d210000e913
[login] recv 04000005006816000007271401ffffffffff00000000004472636fcaca00a31664ac18aab80136b00500030110
[login] packet sent.
[login] loged in
[login] login sent
package_tail 4472636fcaca00a31664ac18aab80136
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff9989db5c0c5b7f038210bf48f5d91ee70000004472636fcaca00a31664ac18aab80136bab700000000
[keep-alive1] recv 070110000600bab701691002ac18aab8a8a20000294d4d3f00000000d80200000300000000000000000000006816000007271401ffffffffffffffffffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070010010b06d8022f12000000000000a8a20000294d4d3f00000000d80200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a2400000000000000be4ff959fa2e970afa2e970afa2e970aa30d840af82e970a81329b0afe2e970a7926ca0af02e970a7932990af82e970a95319c0afb2e970a95319d0aff2e970a9531930af82e970afa2e960a492e970acc08930af92e970acc089c0af22e970a3d28910afb2e970a050e930af92e970a
[keep-alive2] recv file, resending..
[keep-alive2] send1 070128000b01d8022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070128000b02d8022f12000000000000016910020000000000000000000000000000000000000000
[keep-alive2] send2 070128000b01d8022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2 070128000b02d8022f12000000000000016910020000000000000000000000000000000000000000
[keep-alive2] send3 070228000b03d8022f12000000000000016910020000000000000000ac18aab80000000000000000
[keep-alive2] recv3 070228000b04d8022f12000000000000016910020000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive2] send 3 070328000b01d8022f12000000000000016910020000000000000000000000000000000000000000
[keep_alive2] recv 070328000b02d8022f12000000000000026910020000000000000000000000000000000000000000
[keep_alive2] send 4 070428000b03d8022f12000000000000026910020000000000000000ac18aab80000000000000000
[keep_alive2] recv 070428000b04d8022f12000000000000026910020000000000000000000000000000000000000000
[keep_alive1] send ff9989db5c0c5b7f038210bf48f5d91ee70000004472636fcaca00a31664ac18aab80136bacb00000000
[keep-alive1] recv 070110000600bacbbc691002ac18aab8a8a20000294d4d3f00000000d80200001700000000000000b10300006816000007271401ffffffffffffffffffffffff
[keep_alive2] send 5 070528000b01d8022f12000000000000026910020000000000000000000000000000000000000000
[keep_alive2] recv 070528000b02d8022f12000000000000bc6910020000000000000000000000000000000000000000
[keep_alive2] send 6 070628000b03d8022f12000000000000bc6910020000000000000000ac18aab80000000000000000
[keep_alive2] recv 070628000b04d8022f12000000000000bc6910020000000000000000000000000000000000000000

**Comment by wangkun321** [comment]
登录大概1分钟之后就会掉线

**Comment by ly0** [comment]
可以试试把keeplive2不要发送看看
