### ISSUE TITLE
 issue 5.21p电脑端打开py拨号后上不了网 但是拨号成功

### ISSUE THREAD

**Issue by PuerLLK** [drcoms/drcom-generic#88]
qiu'da'shen'bang'zhu求大神帮助 

[dr.pcapng.zip](https://github.com/drcoms/drcom-generic/files/466702/dr.pcapng.zip)

**Comment by ly0** [comment]
发一下程序的log

**Comment by PuerLLK** [comment]
我参照了“关于P版的PPPoE拨号问题”获取到了账号和密码，并且利用里面的拨号软件成功上网，但是后半部分的我看不懂，能麻烦你讲解下吗？我想放到路由器里面

**Comment by PuerLLK** [comment]
接下来应该怎么放入路由器呢？

**Comment by ly0** [comment]
放入路由器的部分还是google一下吧，有很多教程。

**Comment by PuerLLK** [comment]
好的吧 谢谢

**Comment by PuerLLK** [comment]
好的吧 谢谢
