### ISSUE TITLE
实测重庆交通大学(5.2.1d)可用（PC20160912）

### ISSUE THREAD

**Issue by milkai** [drcoms/drcom-generic#90]
本日开始，学校部分用户网页登录时出现“本账号不允许Web方式登录”的提示，故尝试Wiki中的[latest-wired.py](https://github.com/drcoms/drcom-generic/blob/57bcd71b92ebc0cf656f07c0bb1ae8693605b70b/latest-wired.py)。经测试可用，配置文件可参考下面文件。希望有帮助！

[config_0912.txt](https://github.com/drcoms/drcom-generic/files/467619/config_0912.txt)

**Comment by Johnliang91** [comment]
这都能能碰到校友呀，太感动了，我也在测试，不知道你在哪个宿舍，能交流一下么，我的QQ是1651598873







在2016年09月12 23时10分, "WUU KAI"<notifications@github.com>写道:



本日开始，学校部分用户网页登录时出现“本账号不允许Web方式登录”的提示，故尝试Wiki中的latest-wired.py。经测试可用，配置文件可参考下面文件。希望有帮助！

config_0912.txt

**Comment by ly0** [comment]
https://github.com/drcoms/drcom-generic/issues/82
先试试这里的
