### ISSUE TITLE
广东工业大学5.2.1p心跳认证错误

### ISSUE THREAD

**Issue by JerryChaox** [drcoms/drcom-generic#91]
路由器版本:  PandoraBox 14.09 r865
正常客户端登陆的截包：
http://pan.baidu.com/s/1jHGNxAY   q664

**参考#82 心跳认证错误的原因可能是crc校验部分是八字节**
**#92 似乎是一个成功的例子**

**## 运行drcom.py得到以下结果**
pppoe: received challenge response
         packet:070110000202000092dd55010a1e84d8a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
         packet:0702600003000000000000000a1e84d80062006992dd550136d1af410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
         packet:0701080001000000
pppoe: received challenge response
         packet:0701100002030000afdd55010a1e84d8a8a80000e659f16700000000dc020000
pppoe: send heartbeat request      
   packet:0702600003000000000000000a1e84d800620069afdd5501d0fb6f320000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
         packet:0701080001000000
pppoe: received challenge response
         packet:0701100002010000cddd55010a1e84d8a8a80000e659f16700000000dc020000
pppoe: send heartbeat request    
     packet:0702600003000000000000000a1e84d800620069cddd55010ce264a50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
         packet:0701080001000000
pppoe: received challenge response
         packet:0701100002030000ebdd55010a1e84d8a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
         packet:0702600003000000000000000a1e84d800620069ebdd5501480934820000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
         packet:0701080001000000
pppoe: received challenge response
         packet:07011000020200000ade55010a1e84d8a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
         packet:0702600003000000000000000a1e84d8006200690ade5501061edf780000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
        packet:0701080001000000
pppoe: received challenge response
        packet:070110000203000027de55010a1e84d8a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
         packet:0702600003000000000000000a1e84d80062006927de5501e0d815440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
 pppoe: send challenge request
         packet:0701080001000000
pppoe: received challenge response
         packet:070110000201000045de55010a1e84d8a8a80000e659f16700000000dc020000
 pppoe: send heartbeat request
         packet:0702600003000000000000000a1e84d80062006945de55011cbf0ab70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
 pppoe: heartbeat response failed, retry
 pppoe: reset idx to 0x01
 pppoe: send challenge request
         packet:0701080001000000
 Traceback (most recent call last):
   File "/usr/bin/drcom.py", line 288, in <module>
     main()
   File "/usr/bin/drcom.py", line 284, in main
     pppoe.send(s)
   File "/usr/bin/drcom.py", line 141, in send
     s.send(data)
   File "/usr/bin/drcom.py", line 73, in send
     self.s.sendto(data, (self.server, self.port))
 socket.error: [Errno 128] Network is unreachable

**## 运行#82 的脚本得到以下结果：**
[drcom_client_log.txt](https://github.com/drcoms/drcom-generic/files/484528/drcom_client_log.txt)

auth svr:10.0.3.2
pppoe_flag:2a
keep_alive2_flag:dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
auth svr:10.0.3.2
pppoe_flag:2a
keep_alive2_flag:dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000234c63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a234c6301d8ea2cf90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020300003f4c63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a3f4c6301f06019eb0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020300005b4c63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a5b4c630128de66600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000774c63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a774c630180e4c92c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000934c63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a934c6301b8e3cb750000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000af4c63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002aaf4c6301d059b8670000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000cb4c63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002acb4c630108d705dd0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000e74c63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002ae74c630160dd68a90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000034d63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a034d630198dc6af20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000274d63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a274d6301e03e30c80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000434d63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a434d630118bc7d3d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020300005f4d63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a5f4d630130326a2f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020300007b4d63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a7b4d630168f0910e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000974d63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002a974d6301c037cf440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002030000b34d63010a1ecc7aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000000a1ecc7a0062002ab34d6301f8f5f6230000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**运行drcom.py时因为发送心跳后一直 response failed，所以没有执行 keep_alive_2 的代码**

**Comment by ly0** [comment]
#82 的脚本试过了吗

**Comment by JerryChaox** [comment]
试过了还是不行

**Comment by ly0** [comment]
@JerryChaox 反馈一下#82 的日志到这个issue里吧

**Comment by JerryChaox** [comment]
路由器版本:  PandoraBox 14.09 r865 
运行#82 中的脚本得到以下结果:
`[root@PandoraBox:/root]#python /usr/bin/drcom.py
[] auth svr:10.0.3.2
pppoe_flag:2a
keep_alive2_flag:dc
[] open local port:61440
[] DEBUG MODE:True
[] pppoe: send challenge request
packet:0701080001000000
[] pppoe: received challenge response
packet:0701100002020000be0863010a1ec5aea8a80000e659f16700000000dc020000
[] pppoe: send heartbeat request
packet:0702600003000000000000000a1ec5ae0062002abe0863016e755f3f000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000
[] pppoe: heartbeat response failed, retry
[] pppoe: reset idx to 0x01
[] pppoe: send challenge request
packet:0701080001000000
[] pppoe: received challenge response
packet:0701100002030000db0863010a1ec5aea8a80000e659f16700000000dc020000
[] pppoe: send heartbeat request
packet:0702600003000000000000000a1ec5ae0062002adb08630128a780b3000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000
[] pppoe: heartbeat response failed, retry
[] pppoe: reset idx to 0x01
[] pppoe: send challenge request
packet:0701080001000000
[] pppoe: received challenge response
packet:0701100002030000f70863010a1ec5aea8a80000e659f16700000000dc020000
[] pppoe: send heartbeat request
packet:0702600003000000000000000a1ec5ae0062002af708630180ade37f000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000
[] pppoe: heartbeat response failed, retry
[] pppoe: reset idx to 0x01
[] pppoe: send challenge request
packet:0701080001000000
[] pppoe: received challenge response
packet:0701100002030000130963010a1ec5aea8a80000e659f16700000000dc020000
[*] pppoe: send heartbeat request
packet:0702600003000000000000000a1ec5ae0062002a13096301b8ace5c8000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000`

**Comment by JerryChaox** [comment]
代码里面好像并没有运行到 _gen_crc 那一块呀

**Comment by mchome** [comment]
正常，因为修改的是keepalive部分23333333

**Comment by JerryChaox** [comment]
@mchome 啊哈哈哈哈那段代码是干啥用的。

**Comment by JerryChaox** [comment]
@mchome 表示我连发送心跳好像都没成功

**Comment by JerryChaox** [comment]
请问还需要提供什么信息

**Comment by aintnodawn** [comment]
同为广东工业大学，也是心跳包没发送成功

**Comment by JerryChaox** [comment]
上传一个Linux系统下(ubuntu 16.04LTS, 关闭了防火墙)广东工业大学5.2.1p可用的官方拨号客户端
root下运行privilege, 然后pppoe拨通之后(账户名前面要加\r\n), 运行DrClientLInux就可以拨通.
https://pan.baidu.com/s/1bo9Aecv  dtgz
贴上一个拨通后的日志,希望有用:
[dubug_log.txt](https://github.com/drcoms/drcom-generic/files/481679/dubug_log.txt)

**Comment by ly0** [comment]
发一下一个正常客户端登陆的截包

**Comment by liuminghao233** [comment]
目前只能用交换机+代理共享了

**Comment by ly0** [comment]
@liuminghao233 如果有时间看一下#82最后回复测试一下

**Comment by JerryChaox** [comment]
@ly0 我发了，在正文

**Comment by liuminghao233** [comment]
@ly0 已发

**Comment by JerryChaox** [comment]
参考#82最新脚步!!!

**Comment by Linjieqiang** [comment]
@JerryChaox 同广东工业大学 搞定了吗？

**Comment by ouyangyueying** [comment]
@JerryChaox 广工同胞，搞掂了？
