### ISSUE TITLE
重庆科技学院5.2.1p latest-pppoe反馈问题。

### ISSUE THREAD

**Issue by YouKnowMyEggs** [drcoms/drcom-generic#92]
链接：http://pan.baidu.com/s/1slmwLA1 密码：vchb  
脚本文件，日志输出，抓包，Windows客户端都在里面，求大神帮我看看。万分感谢！

**Comment by ly0** [comment]
https://github.com/drcoms/drcom-generic/issues/82
先试试这里的

**Comment by YouKnowMyEggs** [comment]
@ly0 试了#82，出现一下结果：
auth svr:10.0.1.222
pppoe_flag:2a
keep_alive2_flag:dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:070110000200000040ea4000ac1b302aa8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ac1b302a0062002a40ea4000de6649780000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000005eea4000ac1b25a4a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000ac1b25a40062002a5eea4000e2cf4af40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:0702300004002000f8b312bd000000004439d8eda00004bd93852b63522504edb0820060000000000000000000000000
[keep-alive2] send1
	packet:070028000b010f272f120000000000000000000000000000000000000000000000000000

**Comment by ly0** [comment]
看样子好像成功了？

**Comment by YouKnowMyEggs** [comment]
@ly0 感谢大神，已经成功。30分钟未断网！^ ^

**Comment by 771572632** [comment]
@YouKnowMyEggs 能把你配置这个文件发我行吗 同是科院的

**Comment by 771572632** [comment]
@YouKnowMyEggs 能把你配置好的文件发过来行吗  同是科院 谢谢啦

**Comment by liuminghao233** [comment]
不是有heartbeat response failed, retry吗。

**Comment by WillowLiu** [comment]
科院现在没开心跳
